Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-06, with the labels that each got.

#939 URI Data-objects.
  src/Data/Factory.php
  src/Data/URI.php
  tests/Data/URITest.php
Labels: improvement

#1048 Identical Scorting for LongMenuQuestion
  Modules/TestQuestionPool/classes/class.assLongMenu.php
  Modules/TestQuestionPool/classes/class.assLongMenuGUI.php
  Modules/TestQuestionPool/classes/export/qti12/class.assLongMenuExport.php
  Modules/TestQuestionPool/classes/import/qti12/class.assLongMenuImport.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  setup/sql/dbupdate_04.php
Labels: improvement

#1074 KS: Lead icon in list item
  src/UI/Component/Item/Factory.php
  src/UI/Component/Item/Item.php
Labels: kitchen sink

#1090 possible bug fix for mantis ticket 0023091
  lang/ilias_en.lang
Labels: bugfix

#1091 0023165 fixed typo in query builder
  Modules/OrgUnit/classes/Positions/UserAssignment/class.ilOrgUnitUserAssignmentQueries.php
Labels: bugfix

#1082 Fix stripped tags in XLS cloze texts exports
  Modules/TestQuestionPool/classes/class.assClozeTest.php
Labels: improvement

#1050 Add documentation for running shibboleth with nginx
  docs/configuration/nginx_shibboleth.md
Labels: improvement, jour fixe

#947 Assistance: Generic messages / Added logging / Removed global variables
  Services/Init/classes/class.ilPasswordAssistanceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#1092 Fix/0023166/trunk/iliasinifile and ilclientinifile are not available in setup via dic bug
  setup/include/inc.setup_header.php
Labels: bugfix

#1099 ilRPCServerSettings: Fatal Error because of null object ilError
  Services/WebServices/RPC/classes/class.ilRPCServerSettings.php
Labels: improvement

#872 modal replacement pull request
  libs/composer/vendor/composer/ClassLoader.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  src/UI/Component/Modal/Modal.php
  src/UI/Component/Modal/RoundTrip.php
  src/UI/Component/Popover/Popover.php
  src/UI/Component/Popover/ReplaceContentSignal.php
  src/UI/Component/ReplaceContentSignal.php
  src/UI/Component/ReplaceSignal.php
  src/UI/Implementation/Component/Modal/Modal.php
  src/UI/Implementation/Component/Modal/Renderer.php
  src/UI/Implementation/Component/Modal/RoundTrip.php
  src/UI/Implementation/Component/Popover/Popover.php
  src/UI/Implementation/Component/ReplaceContentSignal.php
  src/UI/Implementation/Component/ReplaceSignal.php
  src/UI/Implementation/Component/SignalGeneratorInterface.php
  src/UI/Implementation/Render/AbstractComponentRenderer.php
  src/UI/Implementation/Render/ilJavaScriptBinding.php
  src/UI/examples/Modal/Roundtrip/show_multi_step_modal.php
  src/UI/examples/Popover/Standard/show_popover_with_dynamic_changing_content.php
  src/UI/templates/default/Modal/tpl.roundtrip.html
  src/UI/templates/default/Popover/tpl.popover.html
  src/UI/templates/js/Core/ui.js
  src/UI/templates/js/Modal/modal.js
  src/UI/templates/js/Popover/popover.js
Labels: improvement, kitchen sink

#1101 Client Selection: Fixed #23212 / RuntimeException thrown with message "Cannot override frozen service "ilDB"."
  setup/classes/class.ilDbSetup.php
Labels: bugfix

#1102 Chat: Configurable client name
  Modules/Chatroom/chat/README.md
  Modules/Chatroom/classes/admingui/class.ilChatroomAdminViewGUI.php
  Modules/Chatroom/classes/class.ilChatroomAdmin.php
  Modules/Chatroom/classes/class.ilChatroomFormFactory.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1103 Dicto: Proposals for additional ignore statements
  dicto/config.yaml
Labels: improvement
