Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-11, with the labels that each got.

#1290 Mail: Removed unused variable declaration and assignment
  Services/Mail/classes/class.ilMail.php
Labels: improvement

#1291 Setup: Workaround for Mantis issue 23876
  Services/Cron/classes/class.ilCronManager.php
Labels: bugfix

#1294 [FIX] 0023877: Setup broken: Uncaught ilCtrlException: ERROR: Can't f…
  Services/Database/classes/class.ilDBUpdate.php
  setup/classes/class.ilSetupGUI.php
Labels: bugfix

#1295 [Certificates] Wrong default value for course certificate settings
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsCourseFormRepository.php
Labels: bugfix

#1288 Forum: Removed massive code duplication
  Modules/Forum/classes/Actions/class.ilForumAutoSaveAsyncDraftAction.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#1298 [Certificates] Reduce duplicated code in migration job
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: improvement

#1301 [Certificates] Use logger instance instead of method in ilCertificateMigrationJob
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: improvement

#1302 [Certificates] Remove invalid paramters in debugging method
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: improvement

#1275 UI: Roadmap for Cards and Items
  src/UI/ROADMAP.md
Labels: roadmap

#1303 [Certificates] Use Completion Datetime for Migrated Certificates instead file modified time
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
  Services/Certificate/classes/class.ilCertificateAdapter.php
Labels: bugfix

#1307 [Certificates] Redcuce code duplication in ilCertifcateMigrationJob
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: improvement

#1308 [Certificates] Change call-by-reference to call-by-value for certifcate parameter in ilCertificateMigrationJob
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: improvement

#1306 OnScreen Chat: Fixed conv. window state handling (across tabs, on pag…
  Services/OnScreenChat/js/chat.js
  Services/OnScreenChat/js/onscreenchat-menu.js
  Services/OnScreenChat/js/onscreenchat.js
Labels: bugfix

#1310 [Certificates] Add Migration Validator test
  Services/Certificate/classes/Migration/class.ilCertificateMigrationValidator.php
  Services/Certificate/test/ilCertificateMigrationValidatorTest.php
Labels: improvement

#1311 UI: Stateful buttons, aria-pressed and engageable-interface
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  src/UI/Component/Button/Bulky.php
  src/UI/Component/Button/Button.php
  src/UI/Component/Button/Close.php
  src/UI/Component/Button/Engageable.php
  src/UI/Component/Button/Factory.php
  src/UI/Component/Button/Primary.php
  src/UI/Component/Button/Standard.php
  src/UI/Component/Button/Toggle.php
  src/UI/Factory.php
  src/UI/Implementation/Component/Button/Bulky.php
  src/UI/Implementation/Component/Button/Button.php
  src/UI/Implementation/Component/Button/Close.php
  src/UI/Implementation/Component/Button/Engageable.php
  src/UI/Implementation/Component/Button/Primary.php
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/Implementation/Component/Button/Standard.php
  src/UI/Implementation/Component/Button/Toggle.php
  src/UI/Implementation/Component/ViewControl/Renderer.php
  src/UI/examples/Button/Standard/stateful.php
  src/UI/templates/default/Button/tpl.bulky.html
  src/UI/templates/default/Button/tpl.primary.html
  src/UI/templates/default/Button/tpl.standard.html
  tests/UI/Component/Button/BulkyButtonTest.php
  tests/UI/Component/Button/ButtonTest.php
  tests/UI/Component/Button/ToggleButtonTest.php
  tests/UI/Component/ViewControl/ViewControlTest.php
Labels: improvement, kitchen sink

#1314 UI: Bootstrap 4 on Roadmap
  src/UI/ROADMAP.md
Labels: roadmap

#1325 0024095: Failed test: Blog löschen
  Modules/LearningSequence/classes/class.ilLSEventHandler.php
Labels: bugfix

#1297 User: Fixed #23625
  Services/User/classes/class.ilUserProfile.php
Labels: bugfix

#1313 [Mail] Throws exception caused by strict types in method
  Services/Mail/classes/class.ilMail.php
Labels: bugfix

#1332 [Certificates] Fix download of course certificates
  Modules/Course/classes/class.ilObjCourseGUI.php
Labels: bugfix

#1305 UI Disabled Inputs
  src/UI/Component/Input/Field/Input.php
  src/UI/Implementation/Component/Input/Field/Checkbox.php
  src/UI/Implementation/Component/Input/Field/Group.php
  src/UI/Implementation/Component/Input/Field/Input.php
  src/UI/Implementation/Component/Input/Field/Radio.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Input/Field/Checkbox/disabled.php
  src/UI/examples/Input/Field/DependantGroup/disabled.php
  src/UI/examples/Input/Field/Group/disabled.php
  src/UI/examples/Input/Field/Radio/disabled.php
  src/UI/examples/Input/Field/Section/disabled.php
  src/UI/examples/Input/Field/Select/disabled.php
  src/UI/examples/Input/Field/Tag/disabled.php
  src/UI/examples/Input/Field/Text/disabled.php
  src/UI/examples/Input/Field/TextArea/disabled.php
  src/UI/templates/default/Input/tag.less
  src/UI/templates/default/Input/tpl.checkbox.html
  src/UI/templates/default/Input/tpl.multiselect.html
  src/UI/templates/default/Input/tpl.numeric.html
  src/UI/templates/default/Input/tpl.password.html
  src/UI/templates/default/Input/tpl.radio.html
  src/UI/templates/default/Input/tpl.select.html
  src/UI/templates/default/Input/tpl.tag_input.html
  src/UI/templates/default/Input/tpl.text.html
  src/UI/templates/default/Input/tpl.textarea.html
  src/UI/templates/js/Input/Field/tagInput.js
  templates/default/less/variables.less
  tests/UI/Component/Input/Field/CheckboxInputTest.php
  tests/UI/Component/Input/Field/InputTest.php
  tests/UI/Component/Input/Field/MultiSelectInputTest.php
  tests/UI/Component/Input/Field/NumericInputTest.php
  tests/UI/Component/Input/Field/PasswordInputTest.php
  tests/UI/Component/Input/Field/RadioInputTest.php
  tests/UI/Component/Input/Field/TagInputTest.php
  tests/UI/Component/Input/Field/TextInputTest.php
  tests/UI/Component/Input/Field/TextareaTest.php
Labels: kitchen sink

#1328 #0023927: Missing Lang Vars
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1273 0023859: New Test objects are online after creaction
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#1342 Fixed 0024192: Mail to members does not filter by position access
  Services/Contact/classes/class.ilMailMemberSearchDataProvider.php
  Services/Contact/classes/class.ilMailMemberSearchGUI.php
Labels: bugfix

#1340 fix 24189: LSO, do not try to get path of objects that are not in the tree
  Modules/LearningSequence/classes/class.ilLSEventHandler.php
Labels: bugfix

#1341 fix 0024189 - do not try to get path of objects that are not in the tree
  Modules/LearningSequence/classes/class.ilLSEventHandler.php
Labels: bugfix

#1344 [Certificate/Verification] Exception for no longer existing objects
  Modules/Course/classes/Verification/class.ilObjCourseVerification.php
  Modules/Course/classes/Verification/class.ilObjCourseVerificationGUI.php
  Modules/Exercise/classes/class.ilObjExerciseVerification.php
  Modules/Exercise/classes/class.ilObjExerciseVerificationGUI.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerification.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerificationGUI.php
  Modules/Test/classes/class.ilObjTestVerification.php
  Modules/Test/classes/class.ilObjTestVerificationGUI.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationClassMap.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationFileService.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationObject.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#1347 [Certificate/Verification] Exception for no longer existing objects
  Modules/Course/classes/Verification/class.ilObjCourseVerification.php
  Modules/Course/classes/Verification/class.ilObjCourseVerificationGUI.php
  Modules/Exercise/classes/class.ilObjExerciseVerification.php
  Modules/Exercise/classes/class.ilObjExerciseVerificationGUI.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerification.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerificationGUI.php
  Modules/Test/classes/class.ilObjTestVerification.php
  Modules/Test/classes/class.ilObjTestVerificationGUI.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationClassMap.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationFileService.php
  Services/Verification/classes/Certificate/class.ilCertificateVerificationObject.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#1343 [Mail] Create Value Object for mail body and purifier to ensure sanitized data
  Services/Mail/classes/Message/class.ilMailBody.php
  Services/Mail/classes/Message/class.ilMailBodyPurifier.php
  Services/Mail/classes/class.ilMailFormGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#1348 [Mail] Create Value Object for mail body and purifier to ensure sanitized data ILIAS 5.4
  Services/Mail/classes/Message/class.ilMailBody.php
  Services/Mail/classes/Message/class.ilMailBodyPurifier.php
  Services/Mail/classes/class.ilMailFormGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#1349 [Mail] Useful correct DI
  Services/Mail/classes/class.ilMailFormGUI.php
Labels: improvement
