Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-05, with the labels that each got.

#1044 ErrorHandling: DEVMODE may not be defined.
  Services/Init/classes/class.ilErrorHandling.php
Labels: improvement

#1047 Proposal/5 4/installation postgres
  docs/configuration/postgresql.md
Labels: jour fixe

#1032 Documentation: Extra Security for Setup
  docs/configuration/install.md
Labels: improvement

#1051 Preconditions: Fixed #23038
  Services/AccessControl/classes/class.ilConditionHandler.php
Labels: bugfix

#1055 User: Fixed #23066
  Services/Block/classes/class.ilBlockSetting.php
  Services/Block/classes/class.ilColumnGUI.php
  Services/PersonalDesktop/classes/class.ilObjPersonalDesktopSettingsGUI.php
  Services/PersonalDesktop/classes/class.ilUsersOnlineBlockGUI.php
  Services/User/classes/class.ilObjUser.php
  Services/Utilities/classes/class.ilUtil.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#1061 Setup: Bugfix #22723
  lang/setup_de.lang
  lang/setup_en.lang
  setup/classes/class.ilSetupGUI.php
  setup/templates/tpl.form_change_admin_password.html
  setup/templates/tpl.main.html
Labels: bugfix

#671 UI Pagination
  Services/Style/System/data/data.json
  src/UI/Component/ViewControl/Factory.php
  src/UI/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Factory.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Renderer.php
  src/UI/examples/ViewControl/Pagination/base.php
  src/UI/examples/ViewControl/Pagination/many_pages.php
  src/UI/examples/ViewControl/Pagination/many_pages_dropdown.php
  src/UI/examples/ViewControl/Pagination/no_pages.php
  src/UI/examples/ViewControl/Pagination/with_signal.php
  src/UI/templates/default/ViewControl/tpl.pagination.html
  src/UI/templates/default/ViewControl/viewcontrol.less
  src/UI/templates/js/ViewControl/pagination.js
  templates/default/delos.css
  tests/UI/Component/ViewControl/PaginationTest.php
Labels: kitchen sink

#1066 fixed #22966 in removing prompt, no idea why this was there in the first place
  Modules/TestQuestionPool/templates/default/cloze_gap_builder.js
Labels: bugfix

#1068 Ticket 23099 - replace raise error
  setup/classes/class.ilCtrlStructureReader.php
  setup/classes/class.ilSetup.php
  setup/classes/class.ilSetupGUI.php
Labels: bugfix
