Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-04, with the labels that each got.

#931 [fix 0022758] File-Upload failed in Postgres
  Modules/File/classes/class.ilObjFile.php
Labels: bugfix

#943 .gitignore: Added '/Customizing/clients'
  .gitignore
Labels: improvement

#949 Reduce code duplication in Forum Notification Mails
  Modules/Forum/classes/class.ilForumMailNotification.php
Labels: improvement

#956 Fix/5 4/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: bugfix

#948 Files: Added extensions to whitelist / Added mime types
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: improvement

#957 Fix/5 3/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: bugfix

#958 Fix/5 2/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: bugfix

#959 Fix/5 1/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: bugfix

#952 Files: Added *.md to whitelist / Added mime type for *.md
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: improvement

#966 [fix 0022829] creating new objects in repository home (PG-Error)
  Services/Tree/classes/class.ilNestedSetTree.php
Labels: bugfix

#975 Chatserver: Improve error message when files do not exist
  Modules/Chatroom/chat/Validation/Rules/FileExists.js
Labels: improvement

#968 Test: Fixed Mantis issue #22833
  Services/Repository/classes/class.ilTestQuestionPoolSelectorExplorer.php
Labels: bugfix

#935 proposal for new label technical-board
  docs/documentation/contributing.md
Labels: improvement, jour fixe

#976 Mail notification cache
  Modules/Forum/classes/class.ilForumCronNotification.php
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
  Modules/Forum/classes/class.ilForumNotificationCache.php
  libs/composer/vendor/composer/ClassLoader.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#983 Remove globals for ilChatroomeInviteUsersToPrivateRoomGUI
  Modules/Chatroom/classes/gui/class.ilChatroomInviteUsersToPrivateRoomGUI.php
Labels: bugfix

#987 Remove globals from ilChatroomPrivateRoomGUI
  Modules/Chatroom/classes/gui/class.ilChatroomPrivateRoomGUI.php
Labels: bugfix

#991 Remove class chatroom inital gui
  Modules/Chatroom/classes/gui/class.ilChatroomInitialGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#989 Remove globals from ilChatroomSmilies
  Modules/Chatroom/classes/class.ilChatroomSmilies.php
Labels: bugfix

#992 Remove globals from ilChatroomInfoGUI
  Modules/Chatroom/classes/gui/class.ilChatroomInfoGUI.php
Labels: bugfix

#986 Remove globals from ilChatroomViewGUI
  Modules/Chatroom/classes/class.ilChatroomGUIHandler.php
  Modules/Chatroom/classes/gui/class.ilChatroomHistoryGUI.php
  Modules/Chatroom/classes/gui/class.ilChatroomViewGUI.php
Labels: bugfix

#993 Remove unused class ilChatroomUploadFileGUI
  Modules/Chatroom/classes/gui/class.ilChatroomUploadFileGUI.php
  Modules/Chatroom/test/tasks/class.ilChatroomUploadFileTaskTest.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#995 Replace globals with DIC calls from ilCronManagerTableGUI
  Services/Cron/classes/class.ilCronManagerTableGUI.php
Labels: bugfix

#994 Replace global with DIC globals in ilCronManager
  Services/Cron/classes/class.ilCronManager.php
Labels: bugfix

#997 Use dependency injection instead of using $GLOBALS
  Modules/Chatroom/classes/gui/class.ilChatroomBanGUI.php
Labels: bugfix

#1000 Wrong variable declaration in cron manager
  Services/Cron/classes/class.ilCronManager.php
Labels: bugfix

#921 Upgrade openlayer map to 4.6.4
  Services/Maps/classes/class.ilOpenLayersMapGUI.php
  Services/Maps/css/service_openlayers.css
  Services/Maps/js/OpenLayers.js
  Services/Maps/js/ServiceOpenLayers.js
  Services/Maps/js/img/east-mini.png
  Services/Maps/js/img/north-mini.png
  Services/Maps/js/img/south-mini.png
  Services/Maps/js/img/west-mini.png
  Services/Maps/js/img/zoom-minus-mini.png
  Services/Maps/js/img/zoom-plus-mini.png
  Services/Maps/js/img/zoom-world-mini.png
  Services/Maps/js/theme/default/style.css
  Services/Maps/templates/default/tpl.openlayers_map.html
  libs/bower/bower.json
  libs/bower/bower_components/OpenLayers/.bower.json
  libs/bower/bower_components/OpenLayers/ol-debug.js
  libs/bower/bower_components/OpenLayers/ol.css
  libs/bower/bower_components/OpenLayers/ol.js
Labels: bugfix, improvement

#1001 Replace globals variable in cron start up
  Services/Cron/classes/class.ilCronStartUp.php
Labels: bugfix

#996 CoPage: Set attr. for ext. links
  Services/COPage/xsl/page.xsl
Labels: bugfix

#1007 Replace globals with DIC usages in ilNotificationGUI
  Services/Notifications/classes/class.ilNotificationGUI.php
Labels: bugfix

#973 Fix/5 1/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
  Services/WebDAV/classes/class.ilObjFileAccessSettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#971 Fix/5 2/whitelist additions
  Services/Utilities/classes/class.ilFileUtils.php
  Services/Utilities/classes/class.ilMimeTypeUtil.php
  Services/WebDAV/classes/class.ilObjFileAccessSettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1015 Replace globals with DIC usages in ilNotifcationSettingsTable
  Services/Notifications/classes/class.ilNotificationSettingsTable.php
Labels: bugfix

#1011 Removed unused global from unused method
  Services/Notifications/classes/class.ilObjNotificationAdmin.php
Labels: bugfix

#1010 Remove forgotten global
  Services/Notifications/classes/class.ilNotificationGUI.php
Labels: bugfix

#1016 Fix: constructor is private for ilObjNotifcationOSDHandler
  Services/Notifications/classes/class.ilNotificationOSDHandler.php
Labels: bugfix

#1013 Replace globals with DIC usages in ilObjNotificationAdminGUI
  Services/Notifications/classes/class.ilObjNotificationAdminGUI.php
Labels: bugfix

#974 [fix 0022839] adapt locate-method for PostgreSQL
  Services/Database/classes/MDB2/class.ilDBPostgreSQL.php
  Services/Database/classes/QueryUtils/class.ilPostgresQueryUtils.php
Labels: bugfix

#1003 Error handling PDO exception output
  error.php
Labels: bugfix

#1018 Replace globals with DIC methods from ilNotifcationSystem
  Services/Notifications/classes/class.ilNotificationSystem.php
Labels: bugfix

#1019 Fix/0022826/trunk/press enter p tag and br tag bug
  Modules/DataCollection/classes/Content/class.ilDclRecordListGUI.php
Labels: bugfix

#1020 Fix: Fatal error during reloading command structure
  setup/include/inc.setup_header.php
Labels: bugfix

#977 [fix 0022849] DataCollection-Fix (SQL) for PostgreSQL
  Modules/DataCollection/classes/Table/class.ilDclTable.php
Labels: bugfix

#927 Fix/0022298/5 2/postgres improvements
  Modules/DataCollection/classes/Fields/Reference/class.ilDclReferenceFieldModel.php
  Modules/DataCollection/classes/class.ilDataCollectionExporter.php
  Modules/OrgUnit/classes/PathStorage/class.ilOrgUnitPathStorage.php
  Modules/TestQuestionPool/classes/class.assClozeGapCombination.php
  Services/ActiveRecord/Connector/class.arConnectorDB.php
  Services/Database/classes/MDB2/class.ilDB.php
  Services/Database/classes/MDB2/class.ilDBMySQL.php
  Services/Database/classes/MDB2/class.ilDBPostgreSQL.php
  Services/Database/classes/PDO/Manager/class.ilDBPdoManagerPostgres.php
  Services/Database/classes/PDO/class.ilDBPdo.php
  Services/Database/classes/PDO/class.ilDBPdoPostgreSQL.php
  Services/Database/classes/QueryUtils/class.ilMySQLQueryUtils.php
  Services/Database/classes/QueryUtils/class.ilPostgresQueryUtils.php
  Services/Database/classes/QueryUtils/class.ilQueryUtils.php
  Services/Database/classes/class.ilDBGenerator.php
  Services/Database/interfaces/interface.ilDBInterface.php
  Services/Database/interfaces/interface.ilQueryUtils.php
  Services/Tree/classes/class.ilMaterializedPathTree.php
  Services/Tree/classes/class.ilTree.php
Labels: bugfix

#928 Fix/0022298/5 4/postgres improvements
  Modules/DataCollection/classes/Fields/Reference/class.ilDclReferenceFieldModel.php
  Modules/DataCollection/classes/class.ilDataCollectionExporter.php
  Modules/OrgUnit/classes/PathStorage/class.ilOrgUnitPathStorage.php
  Modules/TestQuestionPool/classes/class.assClozeGapCombination.php
  Services/ActiveRecord/Connector/class.arConnectorDB.php
  Services/Database/classes/MDB2/class.ilDB.php
  Services/Database/classes/MDB2/class.ilDBMySQL.php
  Services/Database/classes/MDB2/class.ilDBPostgreSQL.php
  Services/Database/classes/PDO/Manager/class.ilDBPdoManagerPostgres.php
  Services/Database/classes/PDO/class.ilDBPdo.php
  Services/Database/classes/PDO/class.ilDBPdoPostgreSQL.php
  Services/Database/classes/QueryUtils/class.ilMySQLQueryUtils.php
  Services/Database/classes/QueryUtils/class.ilPostgresQueryUtils.php
  Services/Database/classes/QueryUtils/class.ilQueryUtils.php
  Services/Database/classes/class.ilDBGenerator.php
  Services/Database/interfaces/interface.ilDBInterface.php
  Services/Database/interfaces/interface.ilQueryUtils.php
  Services/MyStaff/classes/ListUsers/class.ilMStListUsers.php
  Services/Tree/classes/class.ilMaterializedPathTree.php
  Services/Tree/classes/class.ilTree.php
  setup/sql/dbupdate_04.php
Labels: bugfix

#1024 Study Programme: Fixed #22577
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeTreeGUI.php
  Modules/StudyProgramme/test/mocks.php
Labels: bugfix

#1026 fixed 21945: Blocked users arent displayed
  Modules/LearningModule/classes/class.ilLMTracker.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionList.php
Labels: bugfix

#985 [fix 0022897] Test-Creation failed in PostgreSQL
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#917 Fix mantis 22320 - no access to uploaded file(s) during manual correction in "Scoring by Question"-mode
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
Labels: bugfix

#1004 Bookmarks: Set attr. for ext. links
  Services/Bookmarks/classes/class.ilBookmarkAdministrationTableGUI.php
  Services/Bookmarks/classes/class.ilBookmarkBlockGUI.php
  Services/Bookmarks/templates/default/tpl.bookmark_administration_row.html
  Services/Bookmarks/templates/default/tpl.bookmark_pd_list.html
  Services/UIComponent/Explorer2/classes/class.ilExplorerBaseGUI.php
Labels: bugfix

#1021 Feeds: Set attr. for ext. links
  Services/Feeds/classes/class.ilExternalFeedItem.php
  Services/Feeds/templates/default/tpl.show_feed_item.html
  Services/News/templates/default/tpl.show_feed_url.html
Labels: bugfix

#936 [fix 0022772] removing unnecessary distinct in sql (postgres-fix)
  Services/COPage/classes/class.ilPageObject.php
Labels: bugfix

#934 [fix 0022769] quoting reserved word for postgreSQL
  Modules/Wiki/classes/class.ilWikiStat.php
Labels: bugfix

#910 [Fix 22651] Exc. Cron job after grace period
  Modules/Exercise/classes/class.ilExAssignment.php
Labels: bugfix

#998 WebResource: Set attr. for ext. links
  Modules/WebResource/classes/class.ilWebResourceLinkTableGUI.php
  Modules/WebResource/templates/default/tpl.webr_link_row.html
Labels: bugfix

#929 Fix/22395/5 4/export import all file versions
  Modules/File/classes/class.ilFileXMLParser.php
  Modules/File/classes/class.ilFileXMLWriter.php
Labels: bugfix

#1039 Cookies: Respected flag
  Services/Http/classes/class.ilHTTPS.php
  Services/Init/classes/class.ilInitialisation.php
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix

#1043 Event: Logging
  Services/EventHandling/classes/class.ilAppEventHandler.php
  Services/EventHandling/service.xml
  setup/sql/dbupdate_04.php
Labels: improvement
