Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-07, with the labels that each got.

#1100 Add cpp header file types to default whitelist
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#687 Cloud Plugin vs. PHP 7.2: Replaced create_function (deprecated)
  Modules/Cloud/classes/class.ilCloudPluginConfig.php
Labels: bugfix, improvement

#688 Active Record vs. PHP 7.2: Replaced create_function (deprecated)
  Services/ActiveRecord/class.ActiveRecord.php
Labels: bugfix, improvement

#1106 Feature: 'Mail: Option to Hide Mail Settings Tab in Personal Settings'
  Services/Mail/classes/class.ilMailGUI.php
  Services/Mail/classes/class.ilMailOptionsGUI.php
  Services/Mail/classes/class.ilObjMailGUI.php
  Services/Mail/test/gui/ilMailOptionsGUITest.php
  Services/Mail/test/ilServicesMailSuite.php
  Services/User/classes/class.ilPersonalSettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  setup/sql/dbupdate_04.php
Labels: improvement

#1111 Move initalisation of ILIAS into constructor of CronStartUp
  Services/Cron/classes/class.ilCronStartUp.php
  cron/cron.php
Labels: bugfix, improvement

#1115 Fixes: Course Icons are blocked for a regular user (#23308)
  Services/Container/classes/class.ilContainerAccess.php
Labels: bugfix

#1116 Moved phantomjs to optional dependencies
  docs/configuration/install.md
Labels: improvement, jour fixe

#1095 UI Input Password, Constraints
  src/UI/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Password.php
  src/UI/examples/Input/Field/Password/with_contraints.php
  src/Validation/Constraints/Password/Factory.php
  src/Validation/Constraints/Password/HasLowerChars.php
  src/Validation/Constraints/Password/HasMinLength.php
  src/Validation/Constraints/Password/HasNumbers.php
  src/Validation/Constraints/Password/HasSpecialChars.php
  src/Validation/Constraints/Password/HasUpperChars.php
  src/Validation/Factory.php
  tests/Validation/Constraints/PasswordContraintsTest.php
Labels: jour fixe, kitchen sink
