Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-12, with the labels that each got.

#1353 [Mail] Create Value Object for mail body and purifier to ensure sanitized data for Release 5.3
  Services/Mail/classes/Message/class.ilMailBody.php
  Services/Mail/classes/Message/class.ilMailBodyPurifier.php
  Services/Mail/classes/class.ilMailFormGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#1334 Fixed 0024161: Static call in ilFileUtils
  Services/Utilities/classes/class.ilFileUtils.php
Labels: bugfix

#1317 Centralize block News configurations in a subtab
  Modules/Category/classes/class.ilObjCategoryGUI.php
  Modules/Course/classes/class.ilObjCourseGUI.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Services/Container/classes/class.ilContainerNewsSettingsGUI.php
  Services/News/classes/class.ilNewsForContextBlockGUI.php
Labels: bugfix, improvement

#1346 Enable lom meta data for iass
  Modules/IndividualAssessment/classes/class.ilObjIndividualAssessmentGUI.php
  Services/Object/classes/class.ilObjectMetaDataGUI.php
Labels: improvement

#1345 Enable lom meta data for iass
  Modules/IndividualAssessment/classes/class.ilObjIndividualAssessmentGUI.php
  Services/Object/classes/class.ilObjectMetaDataGUI.php
Labels: improvement

#1352 UI Guideline Update
  src/UI/README.md
  src/UI/docu/rules.md
Labels: improvement, jour fixe, kitchen sink

#1360 [Mail] Refactor file name according to class name
  Services/Mail/classes/class.ilMailFormAttachmentPropertyGUI.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: improvement

#1249 Moved DiskQuota classes from Services/WebDAV to existing Services/DiskQuota folder
  Modules/File/classes/class.ilObjFileAccessSettingsGUI.php
  Modules/Portfolio/classes/class.ilObjPortfolioGUI.php
  Services/AccessControl/classes/class.ilObjRoleGUI.php
  Services/DiskQuota/classes/class.ilDAVCronDiskQuota.php
  Services/DiskQuota/classes/class.ilDiskQuotaActivationChecker.php
  Services/DiskQuota/classes/class.ilDiskQuotaChecker.php
  Services/DiskQuota/classes/class.ilDiskQuotaHandler.php
  Services/DiskQuota/classes/class.ilObjDiskQuotaSettings.php
  Services/DiskQuota/service.xml
  Services/DiskQuota/templates/default/tpl.disk_quota_reminder_mail.html
  Services/DiskQuota/templates/default/tpl.disk_quota_report.html
  Services/Form/classes/class.ilFileInputGUI.php
  Services/InfoScreen/classes/class.ilInfoScreenGUI.php
  Services/Mail/classes/class.ilDiskQuotaReminderMail.php
  Services/Mail/classes/class.ilDiskQuotaSummaryNotification.php
  Services/PersonalDesktop/classes/class.ilObjPersonalDesktopSettingsGUI.php
  Services/User/classes/class.ilObjUserGUI.php
  Services/WebDAV/service.xml
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  setup/sql/dbupdate_04.php
Labels: improvement

#1327 UI: extend pagination-control with custom label for dropdown
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/ViewControl/Factory.php
  src/UI/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Renderer.php
  src/UI/examples/ViewControl/Pagination/many_pages_dropdown.php
  tests/UI/Component/ViewControl/PaginationTest.php
Labels: improvement, jour fixe, kitchen sink

#1188 Fix iltabs
  Services/UIComponent/Tabs/classes/class.ilTabsGUI.php
Labels: improvement

#1356 [Certificates] Remove not needed methods
  Services/Certificate/classes/class.ilCertificate.php
Labels: improvement

#1365 User: Fixed autocomplete query
  Services/User/classes/class.ilUserAutoComplete.php
Labels: bugfix

#1366 Test: String handling in cloze question
  Modules/TestQuestionPool/classes/class.assClozeTestGUI.php
Labels: bugfix

#1339 orgunit zip Bug #24218
  Modules/Exercise/classes/BackgroundTasks/class.ilDownloadSubmissionsBackgroundTask.php
  Modules/Exercise/classes/BackgroundTasks/class.ilExerciseManagementCollectFilesJob.php
  Modules/Exercise/classes/class.ilExSubmission.php
  Modules/Exercise/classes/class.ilExerciseManagementGUI.php
  Modules/Exercise/classes/class.ilExerciseMembersFilter.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#1351 0023964; set permission on LSO role-templates for admin and member
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#1350 0023964; set permission on LSO role-templates for admin and member
  setup/sql/dbupdate_04.php
Labels: bugfix

#1354 Remove redundant image actions
  src/UI/Component/Card/Card.php
  src/UI/Implementation/Component/Card/Card.php
  src/UI/Implementation/Component/Card/Renderer.php
  src/UI/examples/Card/RepositoryObject/with_image_action.php
  src/UI/examples/Card/Standard/with_image_action.php
  src/UI/templates/default/Card/tpl.card.html
  tests/UI/Component/Card/CardTest.php
Labels: kitchen sink

#1337 UI Signal as an action for Images
  src/UI/Component/Image/Image.php
  src/UI/Factory.php
  src/UI/Implementation/Component/Image/Image.php
  src/UI/Implementation/Component/Image/Renderer.php
  src/UI/examples/Image/Standard/with_signal_action.php
  src/UI/examples/Image/Standard/with_string_action.php
  src/UI/templates/default/Image/tpl.image.html
  tests/UI/Component/Image/ImageTest.php
Labels: kitchen sink

#1362 Client ID handling
  Services/Init/classes/class.ilInitialisation.php
  Services/Utilities/classes/class.ilUtil.php
  src/Data/ClientId.php
  src/Data/Factory.php
  tests/Data/ClientIdTest.php
Labels: bugfix

#1372 fixed #23766: [54] Default-Größe für Textfeld in Declaration of Autho…
  src/UI/templates/default/Input/input.less
  src/UI/templates/default/Input/textarea.less
  templates/default/delos.css
  templates/default/less/variables.less
Labels: bugfix, kitchen sink

#1355 UI: Roadmap-Entry for JS
  src/UI/ROADMAP.md
Labels: jour fixe, kitchen sink, roadmap

#1370 Abandon 'License' service (trunk)
  Modules/Course/classes/class.ilObjCourseGUI.php
  Modules/HTMLLearningModule/classes/class.ilObjFileBasedLMGUI.php
  Modules/LearningModule/classes/class.ilObjLearningResourcesSettingsGUI.php
  Modules/Scorm2004/classes/class.ilObjSCORM2004LearningModuleGUI.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleGUI.php
  Modules/ScormAicc/classes/class.ilObjSCORMLearningModuleGUI.php
  Modules/ScormAicc/classes/class.ilSAHSPresentationGUI.php
  Services/AccessControl/classes/class.ilAccess.php
  Services/AccessControl/classes/class.ilAccessInfo.php
  Services/AccessControl/interfaces/interface.ilRBACAccessHandler.php
  Services/License/classes/class.ilLicense.php
  Services/License/classes/class.ilLicenseAccess.php
  Services/License/classes/class.ilLicenseGUI.php
  Services/License/classes/class.ilLicenseOverviewGUI.php
  Services/License/classes/class.ilLicenseOverviewTableGUI.php
  Services/License/maintenance.json
  Services/License/templates/default/tpl.lic_show_licenses.html
  Services/Object/classes/class.ilObjectListGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  libs/composer/vendor/composer/ClassLoader.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  setup/sql/dbupdate_05.php
Labels: improvement, jour fixe, technical board

#1222 Make ilDBPdo.nextId() abstract.
  Services/Database/classes/PDO/class.ilDBPdo.php
Labels: improvement

#1245 User: Added new cron job task to delete user accounts never logged i…
  Services/User/classes/class.ilCronDeleteInactiveUserAccounts.php
  Services/User/classes/class.ilCronDeleteNeverLoggedInUserAccounts.php
  Services/User/classes/class.ilObjUser.php
  Services/User/service.xml
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#1127 Error Handling: Editor Support
  Services/Init/classes/class.ilErrorHandling.php
  Services/Init/classes/class.ilInitialisation.php
Labels: improvement

#1183 initial interface and database migration concept …
  Modules/Scorm2004/classes/class.ilQuestionExporter.php
  Services/AssessmentQuestion/classes/class.ilAsqFactory.php
  Services/AssessmentQuestion/classes/class.ilAsqQuestionResourcesCollector.php
  Services/AssessmentQuestion/classes/class.ilAsqQuestionResult.php
  Services/AssessmentQuestion/classes/class.ilAsqService.php
  Services/AssessmentQuestion/classes/class.ilAssessmentQuestionExporter.php
  Services/AssessmentQuestion/classes/class.ilAssessmentQuestionImporter.php
  Services/AssessmentQuestion/docs/readme.md
  Services/AssessmentQuestion/examples/class.exObjQuestionPoolGUI.php
  Services/AssessmentQuestion/examples/class.exPageContentQuestions.php
  Services/AssessmentQuestion/examples/class.exQuestionPoolExporter.php
  Services/AssessmentQuestion/examples/class.exQuestionPoolImporter.php
  Services/AssessmentQuestion/examples/class.exQuestionsTableGUI.php
  Services/AssessmentQuestion/examples/class.exTestPlayerGUI.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestion.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestionAuthoring.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestionNavigationAware.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestionOfflinePresentationExporter.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestionPresentation.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqQuestionSolution.php
  Services/AssessmentQuestion/interfaces/interface.ilAsqResultCalculator.php
  src/DI/Container.php
Labels: technical board

#1363 Mail: Changed delivery approach
  Services/Mail/classes/BackgroundTask/class.ilMailDeliveryJob.php
  Services/Mail/classes/class.ilMail.php
  webservice/soap/classes/class.ilNusoapUserAdministrationAdapter.php
  webservice/soap/classes/class.ilSoapUtils.php
  webservice/soap/include/inc.soap_functions.php
Labels: improvement

#1384 [Certificate] ObjectHelper::getInstanceByObjId can also return boolean
  Services/Certificate/classes/Helper/ilCertificateObjectHelper.php
  Services/Certificate/classes/class.ilCertificateCron.php
Labels: bugfix

#1385 Certificate: Added ping during iteration / Added proper result status…
  Services/Certificate/classes/class.ilCertificateCron.php
Labels: improvement

#1386 T&A: Fixed Unit Tests
  Modules/Test/test/ilModulesTestSuite.php
  Modules/Test/test/ilTestFinalMarkLangVarBuilderTest.php
  Modules/Test/test/ilassMarkSchemaTest.php
  Modules/Test/test/ilassMarkTest.php
  Modules/TestQuestionPool/test/assAnswerBinaryStateImageTest.php
  Modules/TestQuestionPool/test/assAnswerBinaryStateTest.php
  Modules/TestQuestionPool/test/assAnswerClozeTest.php
  Modules/TestQuestionPool/test/assAnswerErrorTextTest.php
  Modules/TestQuestionPool/test/assAnswerImagemapTest.php
  Modules/TestQuestionPool/test/assAnswerMatchingDefinitionTest.php
  Modules/TestQuestionPool/test/assAnswerMatchingPairTest.php
  Modules/TestQuestionPool/test/assAnswerMatchingTermTest.php
  Modules/TestQuestionPool/test/assAnswerMatchingTest.php
  Modules/TestQuestionPool/test/assAnswerMultipleResponseImageTest.php
  Modules/TestQuestionPool/test/assAnswerMultipleResponseTest.php
  Modules/TestQuestionPool/test/assAnswerOrderingTest.php
  Modules/TestQuestionPool/test/assAnswerSimpleTest.php
  Modules/TestQuestionPool/test/assAnswerTrueFalseTest.php
  Modules/TestQuestionPool/test/assBaseTestCase.php
  Modules/TestQuestionPool/test/assClozeSelectGapTest.php
  Modules/TestQuestionPool/test/assClozeTestGUITest.php
  Modules/TestQuestionPool/test/assFormulaQuestionTest.php
  Modules/TestQuestionPool/test/assKprimChoiceTest.php
  Modules/TestQuestionPool/test/assLongMenuTest.php
  Modules/TestQuestionPool/test/assMultipleChoiceTest.php
  Modules/TestQuestionPool/test/assNumericGUITest.php
  Modules/TestQuestionPool/test/assNumericRangeTest.php
  Modules/TestQuestionPool/test/assSingleChoiceTest.php
  Modules/TestQuestionPool/test/assSkeletonTest.php
  Modules/TestQuestionPool/test/ilAnswerWizardInputGUITest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintAbstractTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintGUITest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintListTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintRequestGUITest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintRequestStatisticDataTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintTrackingTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintsGUITest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintsOrderingClipboardTest.php
  Modules/TestQuestionPool/test/ilAssQuestionHintsTableGUITest.php
  Modules/TestQuestionPool/test/ilAssQuestionSkillAssignmentRegistryTest.php
  Modules/TestQuestionPool/test/ilModulesTestQuestionPoolSuite.php
Labels: bugfix
