Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-09, with the labels that each got.

#1133 UI, Radio Input
  Services/Style/System/data/data.json
  src/UI/Component/Input/Field/Factory.php
  src/UI/Component/Input/Field/Radio.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Radio.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Input/Field/Radio/base.php
  src/UI/templates/default/Input/input.less
  src/UI/templates/default/Input/radio.less
  src/UI/templates/default/Input/tpl.radio.html
  src/UI/templates/js/Input/Field/dependantGroup.js
  src/UI/templates/js/Input/Field/radioInput.js
  templates/default/delos.css
  tests/UI/Component/Input/Field/FieldFactoryTest.php
  tests/UI/Component/Input/Field/RadioInputTest.php
Labels: jour fixe, kitchen sink

#1174 Language: fixed DB-usage in ilLanguage::__destruct
  Services/Language/classes/class.ilLanguage.php
Labels: improvement

#1168 Fixed lineendings for ui component progressmeter
  src/UI/Component/Chart/ProgressMeter/Factory.php
  src/UI/Component/Chart/ProgressMeter/FixedSize.php
  src/UI/Component/Chart/ProgressMeter/Mini.php
  src/UI/Component/Chart/ProgressMeter/ProgressMeter.php
  src/UI/Component/Chart/ProgressMeter/Standard.php
  src/UI/Implementation/Component/Chart/ProgressMeter/Factory.php
  src/UI/Implementation/Component/Chart/ProgressMeter/FixedSize.php
  src/UI/Implementation/Component/Chart/ProgressMeter/Mini.php
  src/UI/Implementation/Component/Chart/ProgressMeter/ProgressMeter.php
  src/UI/Implementation/Component/Chart/ProgressMeter/Renderer.php
  src/UI/Implementation/Component/Chart/ProgressMeter/Standard.php
  src/UI/examples/Chart/ProgressMeter/FixedSize/base.php
  src/UI/examples/Chart/ProgressMeter/FixedSize/maximum_configuration.php
  src/UI/examples/Chart/ProgressMeter/FixedSize/only_comparison_value.php
  src/UI/examples/Chart/ProgressMeter/FixedSize/user_reached_required.php
  src/UI/examples/Chart/ProgressMeter/Mini/base.php
  src/UI/examples/Chart/ProgressMeter/Mini/maximum_configuration.php
  src/UI/examples/Chart/ProgressMeter/Mini/no_score_yet.php
  src/UI/examples/Chart/ProgressMeter/Mini/reached_100_percent.php
  src/UI/examples/Chart/ProgressMeter/Standard/base.php
  src/UI/examples/Chart/ProgressMeter/Standard/maximum_configuration.php
  src/UI/examples/Chart/ProgressMeter/Standard/only_comparison_value.php
  src/UI/examples/Chart/ProgressMeter/Standard/user_reached_required.php
  src/UI/templates/default/Chart/tpl.progressmeter_mini.html
  src/UI/templates/default/Chart/tpl.progressmeter_one_bar.html
  src/UI/templates/default/Chart/tpl.progressmeter_two_bar.html
  tests/UI/Component/Chart/ProgressMeter/ChartProgressMeterTest.php
Labels: improvement

#1136 UI - MultiSelect Input
  Services/Style/System/data/data.json
  src/UI/Component/Input/Field/Factory.php
  src/UI/Component/Input/Field/MultiSelect.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/MultiSelect.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Input/Field/MultiSelect/base.php
  src/UI/templates/default/Input/input.less
  src/UI/templates/default/Input/multiselect.less
  src/UI/templates/default/Input/tpl.multiselect.html
  templates/default/delos.css
  tests/UI/Component/Input/Field/FieldFactoryTest.php
  tests/UI/Component/Input/Field/MultiSelectInputTest.php
Labels: kitchen sink

#805 [Fix 22271] Marginal calendar add event
  Services/Calendar/classes/class.ilCalendarAppointmentGUI.php
  Services/Calendar/classes/class.ilCalendarBlockGUI.php
Labels: bugfix

#1040 Allow other php session cookie names for the session handling
  Modules/DataCollection/classes/Content/class.ilDclContentExporter.php
  Modules/Test/classes/toolbars/class.ilTestInfoScreenToolbarGUI.php
  Modules/TestQuestionPool/classes/class.assFlashQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assJavaAppletGUI.php
  Services/Container/classes/class.ilContainerGUI.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/Object/classes/class.ilObjectCopyGUI.php
  Services/RTE/classes/class.ilTinyMCE.php
  Services/WebServices/ECS/classes/class.ilECSTaskScheduler.php
  include/inc.pwassist_session_handler.php
  studip_referrer.php
  webservice/soap/classes/class.ilSoapAdministration.php
  webservice/soap/classes/class.ilSoapAuthentication.php
  webservice/soap/classes/class.ilSoapUserAdministration.php
Labels: improvement

#1178 Educated guess for (un)zip-path...
  Services/Style/System/test/ilSystemStyleSkinContainerTest.php
Labels: improvement

#1109 UI: better encapsulation, tests and some cleanup for Triggerer-trait
  src/UI/CHANGELOG.md
  src/UI/Component/Triggerer.php
  src/UI/Implementation/Component/Button/Button.php
  src/UI/Implementation/Component/Dropdown/Dropdown.php
  src/UI/Implementation/Component/Dropzone/File/File.php
  src/UI/Implementation/Component/Dropzone/File/Renderer.php
  src/UI/Implementation/Component/Glyph/Glyph.php
  src/UI/Implementation/Component/Input/Field/Checkbox.php
  src/UI/Implementation/Component/Input/Field/DependantGroupHelper.php
  src/UI/Implementation/Component/Modal/Modal.php
  src/UI/Implementation/Component/TriggeredSignal.php
  src/UI/Implementation/Component/TriggeredSignalInterface.php
  src/UI/Implementation/Component/Triggerer.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Sortation.php
  tests/UI/Component/TriggererTest.php
Labels: improvement

#1161 New UI Input Textarea (former #1028)
  Services/Style/System/data/data.json
  lang/ilias_en.lang
  src/UI/Component/Input/Field/Factory.php
  src/UI/Component/Input/Field/Textarea.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/Implementation/Component/Input/Field/Textarea.php
  src/UI/Implementation/Render/DefaultRendererFactory.php
  src/UI/examples/Input/Field/TextArea/base.php
  src/UI/examples/Input/Field/TextArea/with_limits.php
  src/UI/templates/default/Input/tpl.textarea.html
  src/UI/templates/js/Input/Field/textarea.js
  src/Validation/Constraints/HasMaxLength.php
  src/Validation/Factory.php
  tests/UI/Base.php
  tests/UI/Component/Input/Field/FieldFactoryTest.php
  tests/UI/Component/Input/Field/TextareaTest.php
Labels: improvement, kitchen sink

#1105 Proposal for an Interface for a General Kiosk Mode
  Services/KioskMode/README.md
  Services/KioskMode/classes/class.ilKioskModeService.php
  Services/KioskMode/classes/class.ilKioskModeView.php
  Services/KioskMode/maintenance.json
  Services/KioskMode/service.xml
  src/KioskMode/ControlBuilder.php
  src/KioskMode/LocatorBuilder.php
  src/KioskMode/README.md
  src/KioskMode/State.php
  src/KioskMode/TOCBuilder.php
  src/KioskMode/URLBuilder.php
  src/KioskMode/View.php
  src/KioskMode/maintenance.json
Labels: improvement

#1169 Docs: Coordinator Update
  docs/documentation/maintenance-coordinator.md
  docs/documentation/maintenance.md
Labels: improvement, jour fixe

#1185 Kiosk Mode: Fixed return type declarations / Fixed instanceof check
  Services/KioskMode/classes/class.ilKioskModeView.php
  src/KioskMode/View.php
Labels: bugfix

#1192 Fix ilDB handles Querys to null if no mb4 replacement founds
  Services/Database/classes/MDB2/class.ilDB.php
  Services/Database/classes/PDO/class.ilDBPdo.php
Labels: bugfix

#1077 Linkify: Special handling for '_blank' links
  Services/Link/js/ilExtLink.js
Labels: improvement

#1163 Chatroom: Node.js Chat Server Documentation
  Modules/Chatroom/README.md
  Modules/Chatroom/docu/images/view-clientsettings_de.PNG
  Modules/Chatroom/docu/images/view-clientsettings_en.PNG
  Modules/Chatroom/docu/images/view-clientsettings_enable_osd_de.PNG
  Modules/Chatroom/docu/images/view-clientsettings_enable_osd_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_adress_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_adress_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_client_proxy_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_client_proxy_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_deletion_mode_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_deletion_mode_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_ilias_proxy_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_ilias_proxy_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_log_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_log_en.PNG
  Modules/Chatroom/docu/images/view-serversettings_protocol_de.PNG
  Modules/Chatroom/docu/images/view-serversettings_protocol_en.PNG
Labels: improvement

#1195 Language: Fixed Mantis issue 23610 (Issue with 'w_height_info' langua…
  lang/ilias_en.lang
Labels: bugfix

#1147 [fix 0023451] fix query for postgres (field-aliasing)
  Services/Tracking/classes/class.ilTrQuery.php
Labels: bugfix

#1154 Allow tar upload
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#1155 Allow mdl upload
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#1166 23510 fixed orgu assignment removal
  Modules/OrgUnit/classes/class.ilObjOrgUnit.php
Labels: bugfix

#1186 Fix/0022951/trunk/download multiple objects fails error bug
  Modules/File/classes/class.ilObjFile.php
  Modules/Folder/classes/class.ilObjFolder.php
  Services/Container/classes/class.ilContainerGUI.php
Labels: bugfix
