Repository ILIAS-eLearning/ILIAS, pull requests merged in 2018-08, with the labels that each got.

#1118 [FIX] 0023096: Bug with cyrillic filename
  Modules/File/classes/class.ilObjFile.php
  Services/Calendar/classes/FileHandler/class.ilCalendarFileHandler.php
  Services/FileDelivery/classes/Delivery.php
  Services/FileDelivery/classes/class.ilPHPOutputDelivery.php
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix

#1130 ilUtil: Fix of DI call (#23398)
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix

#1093 UI Workflow
  Services/Style/System/data/data.json
  src/UI/Component/Listing/Factory.php
  src/UI/Component/Listing/Workflow/Factory.php
  src/UI/Component/Listing/Workflow/Linear.php
  src/UI/Component/Listing/Workflow/Step.php
  src/UI/Component/Listing/Workflow/Workflow.php
  src/UI/Implementation/Component/Listing/Factory.php
  src/UI/Implementation/Component/Listing/Workflow/Factory.php
  src/UI/Implementation/Component/Listing/Workflow/Linear.php
  src/UI/Implementation/Component/Listing/Workflow/Renderer.php
  src/UI/Implementation/Component/Listing/Workflow/Step.php
  src/UI/Implementation/Component/Listing/Workflow/Workflow.php
  src/UI/examples/Listing/Workflow/Linear/base.php
  src/UI/examples/Listing/Workflow/Linear/with_actions.php
  src/UI/templates/default/Listing/tpl.linear.html
  src/UI/templates/default/Listing/workflow.less
  templates/default/delos.css
  templates/default/delos.css.map
  templates/default/delos.less
  templates/default/less/variables.less
  tests/UI/Component/Listing/ListingFactoryTest.php
  tests/UI/Component/Listing/Workflow/LinearWorkflowTest.php
  tests/UI/Component/Listing/Workflow/WorkflowFactoryTest.php
  tests/UI/Component/Listing/Workflow/WorkflowStepTest.php
Labels: kitchen sink

#1119 UI Input, Password with Revelation
  Services/Style/System/data/data.json
  src/UI/Component/Glyph/Factory.php
  src/UI/Component/Glyph/Glyph.php
  src/UI/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Glyph/Factory.php
  src/UI/Implementation/Component/Glyph/Glyph.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Password.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Glyph/Eyeclosed/eyeclosed.php
  src/UI/examples/Glyph/Eyeopen/eyeopen.php
  src/UI/examples/Input/Field/Password/in_form.php
  src/UI/templates/default/Glyph/tpl.glyph.html
  src/UI/templates/default/Input/input.less
  src/UI/templates/default/Input/password.less
  src/UI/templates/default/Input/tpl.password.html
  templates/default/delos.css
  tests/UI/Component/Input/Field/PasswordInputTest.php
Labels: jour fixe, kitchen sink

#1126 Remove undefined $dir.
  Services/Utilities/classes/class.ilUtil.php
Labels: improvement

#1140 Presentation table should render only one element or nothing as action
  src/UI/Component/Table/PresentationRow.php
  src/UI/Implementation/Component/Table/PresentationRow.php
  src/UI/Implementation/Component/Table/Renderer.php
  src/UI/examples/Table/Presentation/base.php
  src/UI/examples/Table/Presentation/base1.php
Labels: improvement

#1141 Translate expander link label via language
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Table/Renderer.php
Labels: improvement

#1134 refactor checkbox with dependant-group trait
  src/UI/Component/Input/Field/Checkbox.php
  src/UI/Component/Input/Field/DependantGroupProviding.php
  src/UI/Implementation/Component/Input/Field/Checkbox.php
  src/UI/Implementation/Component/Input/Field/DependantGroupHelper.php
  src/UI/Implementation/Component/Input/Field/Group.php
  src/UI/Implementation/Component/Input/Field/GroupHelper.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
Labels: improvement

#1143 Additional OrgUnit Position Permissions (incl. Langvars)
  Modules/OrgUnit/classes/Positions/Operation/class.ilOrgUnitOperation.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#1054 UI: use dependency injection for factory hierarchy
  Services/Init/classes/class.ilInitialisation.php
  src/UI/Implementation/Component/Chart/Factory.php
  src/UI/Implementation/Component/Dropzone/Factory.php
  src/UI/Implementation/Component/Icon/Icon.php
  src/UI/Implementation/Component/Input/Container/Form/Form.php
  src/UI/Implementation/Component/Input/Factory.php
  src/UI/Implementation/Component/MessageBox/Factory.php
  src/UI/Implementation/Component/Panel/Factory.php
  src/UI/Implementation/Component/ViewControl/Renderer.php
  src/UI/Implementation/Factory.php
  src/UI/README.md
  tests/UI/Component/Breadcrumbs/BreadcrumbsTest.php
  tests/UI/Component/Button/BulkyButtonTest.php
  tests/UI/Component/Button/ButtonMonthTest.php
  tests/UI/Component/Card/CardTest.php
  tests/UI/Component/Chart/ChartScaleBarTest.php
  tests/UI/Component/Chart/ProgressMeter/ChartProgressMeterTest.php
  tests/UI/Component/Deck/DeckTest.php
  tests/UI/Component/Divider/DividerTest.php
  tests/UI/Component/Dropdown/DropdownTest.php
  tests/UI/Component/Dropzone/File/DropzoneRendererTest.php
  tests/UI/Component/Icon/IconTest.php
  tests/UI/Component/Input/Container/Form/FormTest.php
  tests/UI/Component/Item/ItemGroupTest.php
  tests/UI/Component/Item/ItemTest.php
  tests/UI/Component/Legacy/LegacyTest.php
  tests/UI/Component/MessageBox/MessageBoxTest.php
  tests/UI/Component/Modal/InterruptiveTest.php
  tests/UI/Component/Modal/LightboxTest.php
  tests/UI/Component/Modal/ModalBase.php
  tests/UI/Component/Panel/PanelListingTest.php
  tests/UI/Component/Panel/PanelTest.php
  tests/UI/Component/Popover/PopoverTest.php
  tests/UI/Component/Table/PresentationTest.php
  tests/UI/Component/ViewControl/PaginationTest.php
  tests/UI/Component/ViewControl/SortationTest.php
  tests/UI/Component/ViewControl/ViewControlTest.php
Labels: improvement

#1132 UI Framework: Introduced lightbox text page
  Services/Style/System/data/data.json
  src/UI/Component/Modal/Factory.php
  src/UI/Component/Modal/LightboxDescriptionEnabledPage.php
  src/UI/Component/Modal/LightboxPage.php
  src/UI/Implementation/Component/Modal/Factory.php
  src/UI/Implementation/Component/Modal/LightboxImagePage.php
  src/UI/Implementation/Component/Modal/LightboxTextPage.php
  src/UI/Implementation/Component/Modal/Renderer.php
  src/UI/examples/Modal/Lightbox/show_a_single_text.php
  src/UI/examples/Modal/Lightbox/show_different_page_types.php
  src/UI/examples/Modal/Lightbox/show_multiple_texts.php
  src/UI/templates/default/Modal/modal.less
  src/UI/templates/default/Modal/tpl.lightbox.html
  templates/default/delos.css
  templates/default/delos.less
  tests/UI/Component/Modal/LightboxTest.php
Labels: improvement, kitchen sink

#1128 Travis - add travis yml file for auto testing purposes
  .travis.yml
  run_tests.sh
Labels: improvement

#1151 Fixed 0023474: Invalid nic server name
  setup/classes/class.ilSetup.php
Labels: bugfix

#1123 UI: Reset Glyph
  src/UI/Component/Glyph/Factory.php
  src/UI/Component/Glyph/Glyph.php
  src/UI/Implementation/Component/Glyph/Factory.php
  src/UI/Implementation/Component/Glyph/Glyph.php
  src/UI/examples/Glyph/Reset/glyph_reset.php
  src/UI/examples/Glyph/Reset/glyph_reset_disabled.php
  src/UI/templates/default/Glyph/tpl.glyph.html
  tests/UI/Component/Glyph/GlyphFactoryTest.php
  tests/UI/Component/Glyph/GlyphTest.php
Labels: kitchen sink

#1148 UI: Roadmap-Proposal for "Smoke-Tests for Examples"
  src/UI/ROADMAP.md
Labels: improvement

#1150 SOAP: Fixed #23463
  Services/Style/System/classes/class.ilSystemStyleSettings.php
  webservice/soap/classes/class.ilSoapAdministration.php
Labels: bugfix

#1120 Mail Service Documentation
  Services/Mail/README.md
  Services/Mail/classes/class.ilMail.php
Labels: improvement

#1153 UI: Moved Backlog
  src/UI/ROADMAP.md
  src/UI/docu/BACKLOG.md
Labels: improvement, kitchen sink

#1152 UI Dropdown: Added description and rule for empty dropdowns
  src/UI/Factory.php
Labels: jour fixe, kitchen sink

#1156 Check session.save_handler in setup.php
  docs/configuration/install.md
  setup/setup.php
Labels: improvement

#1164 TermsOfService: Changes according to Mantis issue 23473
  Services/Init/classes/class.ilInitialisation.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/User/classes/class.ilObjUserGUI.php
  Services/User/classes/class.ilPersonalProfileGUI.php
Labels: bugfix, improvement
