Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-08, with the labels that each got.

#2013 Content Page: Added object type as possible start object in a course
  Services/Container/classes/class.ilContainerStartObjects.php
Labels: bugfix

#2012 Content Page: Added object type as possible start object in a course
  Services/Container/classes/class.ilContainerStartObjects.php
Labels: bugfix

#1897 Restructuring CI Folder && PHP CS Fixer
  .travis.yml
  CI/PHP-CS-Fixer/code-format.php_cs
  CI/PHP-CS-Fixer/example/PhpStorm/ILIAS_CodeStyle.xml
  CI/PHP-CS-Fixer/example/example_cleaned.php
  CI/PHP-CS-Fixer/example/example_raw.php
  CI/PHP-CS-Fixer/run_check.sh
  CI/PHPUnit/run_tests.sh
  CI/PHPUnit/run_tests_with_reporting.sh
  docs/documentation/git-hooks.md
  libs/composer/composer.json
  run_tests.sh
Labels: improvement, technical board

#1838 Introduce PSR-2 (+ some X)
  docs/documentation/coding-style.md
Labels: improvement, technical board

#1983 Feature 6.0: Placeholder for «Mail to Course Member»
  Modules/Course/classes/class.ilCourseMailTemplateMemberContext.php
  Modules/Course/classes/class.ilCourseMailTemplateTutorContext.php
  Modules/Course/classes/class.ilObjCourseAccess.php
  Modules/Exercise/classes/class.ilExcMailTemplateGradeReminderContext.php
  Modules/Exercise/classes/class.ilExcMailTemplatePeerReminderContext.php
  Modules/Exercise/classes/class.ilExcMailTemplateSubmitReminderContext.php
  Modules/ScormAicc/classes/class.ilScormMailTemplateLPContext.php
  Modules/Session/classes/class.ilSessionMailTemplateParticipantContext.php
  Modules/Survey/classes/class.ilSurveyMailTemplateReminderContext.php
  Services/Mail/classes/Form/class.ilMailTemplateSelectInputGUI.php
  Services/Mail/classes/Form/class.ilManualPlaceholderInputGUI.php
  Services/Mail/classes/Helper/class.ilMailEnvironmentHelper.php
  Services/Mail/classes/Helper/class.ilMailLanguageHelper.php
  Services/Mail/classes/Helper/class.ilMailUserHelper.php
  Services/Mail/classes/class.ilMailFormGUI.php
  Services/Mail/classes/class.ilMailTemplateContext.php
  Services/Mail/classes/class.ilMailTemplateGenericContext.php
  Services/Mail/classes/class.ilMailTemplateNameFormatter.php
  Services/Mail/classes/class.ilMailTemplatePlaceholderResolver.php
  Services/Mail/templates/default/tpl.prop_template_select_container.html
  Services/Mail/test/bootstrap.php
  Services/Mail/test/gui/ilMailOptionsGUITest.php
  Services/Mail/test/ilGroupNameAsMailValidatorTest.php
  Services/Mail/test/ilMailAddressListTest.php
  Services/Mail/test/ilMailAddressParserTest.php
  Services/Mail/test/ilMailAddressTest.php
  Services/Mail/test/ilMailAddressTypesTest.php
  Services/Mail/test/ilMailBaseTest.php
  Services/Mail/test/ilMailMimeTest.php
  Services/Mail/test/ilMailOptionsTest.php
  Services/Mail/test/ilMailTaskProcessorTest.php
  Services/Mail/test/ilMailTemplateContextTest.php
  Services/Mail/test/ilMailTemplateRepositoryTest.php
  Services/Mail/test/ilMailTemplateServiceTest.php
  Services/Mail/test/ilMailTest.php
  Services/Mail/test/ilMailTransportSettingsTest.php
  Services/Mail/test/ilServicesMailSuite.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2015 Question Pool: Fixed Mantis issue #25814
  Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php
Labels: bugfix

#2019 Refinery: Added 'EstimatedReadingTime' transformation
  src/Refinery/README.md
  src/Refinery/String/EstimatedReadingTime.php
  src/Refinery/String/Group.php
  src/Refinery/examples/String/01-estimated-reading-time.php
  tests/Refinery/String/Transformation/EstimatedReadingTimeTest.php
Labels: improvement

#2029 Refinery: Handled punctuation when counting words in a string
  src/Refinery/String/EstimatedReadingTime.php
  tests/Refinery/String/Transformation/EstimatedReadingTimeTest.php
Labels: bugfix

#2033 Use actual saved font size to be displayed in editor
  Services/Certificate/xml/fo2xhtml.xsl
Labels: bugfix, improvement

#2034 [Certificate] Use actual saved font size to be displayed in editor
  Services/Certificate/xml/fo2xhtml.xsl
Labels: bugfix, improvement

#2030 Bugfix 25831
  Modules/Forum/classes/class.ilForumPostsDeleted.php
  Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
Labels: bugfix

#2031 Bugfix 25831
  Modules/Forum/classes/class.ilForumPostsDeleted.php
  Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
Labels: bugfix

#2032 Bugfix 25831
  Modules/Forum/classes/class.ilForumPostsDeleted.php
  Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
Labels: bugfix

#2044 leaner wrapper for library ramsey UUID
  src/Data/UUID/Factory.php
  src/Data/UUID/RamseyUuidWrapper.php
  src/Data/UUID/Uuid.php
  src/Data/UUID/UuidInterface.php
Labels: improvement

#2038 KS typos & minor improvements
  src/UI/Component/Symbol/Factory.php
  src/UI/Component/Symbol/Glyph/Factory.php
Labels: improvement, kitchen sink

#2050 fixed timezone format for ISO_8601
  Services/Calendar/classes/class.ilDateTime.php
Labels: bugfix

#2047 SPRG: fix 0025679, tree order
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeTreeGUI.php
  Modules/StudyProgramme/templates/js/ilStudyProgramme.js
Labels: bugfix

#2045 SPRG: fix 0025679, tree order
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeTreeGUI.php
  Modules/StudyProgramme/templates/js/ilStudyProgramme.js
Labels: bugfix

#2041 LSO: fix 25812; truncate (ellipsis) text in workflow-listing
  src/UI/templates/default/Listing/workflow.less
  templates/default/delos.css
Labels: bugfix, kitchen sink

#2036 LSO: fix 0025496 - Routing problems
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
Labels: bugfix

#2054 [Certificate] Fix some static code related bugs
  Services/Certificate/classes/File/Background/class.ilCertificateBackgroundImageUpload.php
  Services/Certificate/classes/Portfolio/class.ilPortfolioCertificateFileService.php
  Services/Certificate/classes/Queue/class.ilCertificateQueueRepository.php
  Services/Certificate/classes/Template/class.ilCertificateTemplateRepository.php
  Services/Certificate/classes/User/class.ilUserCertificateRepository.php
  Services/Certificate/classes/User/class.ilUserCertificateTableProvider.php
  Services/Certificate/classes/class.ilCertificate.php
Labels: bugfix, improvement

#2055 File: Fixed Mantis issue 25882
  Modules/File/classes/class.ilObjFileGUI.php
Labels: bugfix

#2057 [Certificates] Remove usage of il certificate in certificate GUI elements
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsCourseFormRepository.php
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsExerciseRepository.php
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsScormFormRepository.php
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsTestFormRepository.php
  Services/Certificate/classes/Form/Repository/interface.ilCertificateFormRepository.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/test/ilCertificateSettingsCourseFormRepositoryTest.php
  Services/Certificate/test/ilCertificateSettingsExerciseRepositoryTest.php
  Services/Certificate/test/ilCertificateSettingsScormFormRepositoryTest.php
  Services/Certificate/test/ilCertificateSettingsTestFormRepositoryTest.php
Labels: improvement

#2059 [Certificates] Extract ZIP methods into separated class
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Services/Certificate/classes/User/Action/Zip/class.ilUserCertificateZip.php
  Services/Certificate/classes/class.ilCertificate.php
Labels: improvement

#2061 Move forum notification from Services/Mail to Modules/Forum
  Modules/Forum/classes/Notification/class.ilMailEventNotificationSender.php
Labels: improvement

#2046 News/Membership Notifications: Possible fix for 25370
  Services/Membership/classes/class.ilMembershipCronNotifications.php
Labels: bugfix

#2035 Fix 25848
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2062 Extract background image delete method to separated class
  Services/Certificate/classes/File/Background/classs.ilCertificateBackgroundImageDelete.php
  Services/Certificate/classes/class.ilCertificate.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: improvement

#2070 [Certificate] Create own directory for path related services
  Services/Certificate/classes/File/Template/Path/class.ilCertificatePathConstants.php
Labels: improvement

#2069 [Certificate] Create own directory for XLS related file services
  Services/Certificate/classes/File/Template/XLS/class.ilCertificateXlsFileLoader.php
  Services/Certificate/classes/File/Template/XLS/class.ilCertificateXlstProcess.php
  Services/Certificate/classes/File/Template/XLS/class.ilXlsFoParser.php
Labels: improvement

#2071 Group: Fixed Mantis issue 25908
  Modules/Group/classes/class.ilGroupXMLParser.php
Labels: bugfix

#2072 Create new path factory to avoid usage of constant in actual code
  Modules/Course/classes/class.ilObjCourse.php
  Modules/Exercise/classes/class.ilObjExercise.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Services/Certificate/classes/File/Template/Path/class.ilCertificatePathFactory.php
  Services/Certificate/classes/Gui/class.ilCertificateFactory.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/test/ilCertificateCloneActionTest.php
  Services/Certificate/test/ilCertificateFactoryTest.php
Labels: improvement

#2052 JS Interface for with loading animation
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/examples/Button/Standard/with_load_anim.php
  src/UI/templates/js/Button/button.js
Labels: improvement, kitchen sink

#2073 Extract check for thumbnail into clone service
  Modules/Course/classes/class.ilObjCourse.php
  Modules/Exercise/classes/class.ilObjExercise.php
  Modules/Test/classes/class.ilObjTest.php
  Services/Certificate/classes/Template/Action/Clone/class.ilCertificateCloneAction.php
  Services/Certificate/classes/class.ilCertificate.php
  Services/Certificate/test/ilCertificateCloneActionTest.php
Labels: improvement

#2067 [Refinery] Create URI to string transformation, to get the origin string to create e.g. a href element from the URI object
  src/Refinery/Factory.php
  src/Refinery/URI/Group.php
  src/Refinery/URI/StringTransformation.php
  tests/Refinery/FactoryTest.php
  tests/Refinery/URI/GroupTest.php
  tests/Refinery/URI/StringTransformationTest.php
Labels: improvement

#2017 Fix 25624
  Services/Container/classes/class.ilContainerContentGUI.php
  src/UI/Component/Card/Card.php
  src/UI/Component/Image/Image.php
  src/UI/Implementation/Component/Card/Card.php
  src/UI/Implementation/Component/Card/Renderer.php
  src/UI/Implementation/Component/Image/Image.php
  src/UI/Implementation/Component/Image/Renderer.php
  src/UI/examples/Image/Standard/with_signal_action.php
  src/UI/examples/Image/Standard/with_string_action.php
  src/UI/templates/default/Image/tpl.image.html
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/Services/Container/delos.less
  tests/UI/Component/Image/ImageTest.php
Labels: bugfix, kitchen sink

#2076 Use correct check for a achieved certificate of the user
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestEvaluationGUI.php
Labels: improvement

#1914 UserInterfaceHook in ILIAS 6.0
  Services/Component/classes/class.ilPlugin.php
  Services/Component/classes/class.ilPluginConfigGUI.php
  Services/Init/classes/class.ilInitialisation.php
  Services/UIComponent/README.md
  Services/UIComponent/classes/class.ilUIHookPluginGUI.php
Labels: improvement

#2086 fixed templates for thread print, posting print and thread export to html
  Modules/Forum/classes/class.ilForumExportGUI.php
Labels: bugfix

#2087 refactored ilForumExporrtGUI to PSR-2
  Modules/Forum/classes/class.ilForumExportGUI.php
Labels: improvement

#2088 [Certificate] Replace is active checks with validator variant
  Modules/Course/classes/class.ilCourseCertificateAdapter.php
  Modules/Course/classes/class.ilObjCourseGUI.php
  Modules/Exercise/classes/class.ilExerciseCertificateAdapter.php
  Modules/Exercise/classes/class.ilObjExerciseGUI.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleGUI.php
  Modules/Test/classes/class.ilTestTabsManager.php
  Services/COPage/classes/class.ilPCPlaceHolderGUI.php
  Services/PersonalDesktop/Achievements/classes/class.ilAchievements.php
Labels: improvement

#2089 [Certificates] Remove adapters
  Modules/Course/classes/class.ilCourseCertificateAdapter.php
  Modules/Exercise/classes/class.ilExerciseCertificateAdapter.php
  Modules/ScormAicc/classes/class.ilSCORMCertificateAdapter.php
  Modules/Test/classes/class.ilTestCertificateAdapter.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/classes/class.ilCertificateGUI.php
  Services/Skill/classes/class.ilSkillCertificateAdapter.php
Labels: improvement

#2090 [Certificate] Remove ilCertificate
  Services/Certificate/classes/Gui/class.ilCertificateFactory.php
  Services/Certificate/classes/class.ilCertificate.php
  Services/Certificate/classes/class.ilCertificateGUI.php
  Services/Certificate/test/ilCertificateFactoryTest.php
  Services/Certificate/test/ilCertificateSettingsExerciseRepositoryTest.php
Labels: improvement

#2096 Learning Sequence: Fix continue targeting switch (https://www.php.net…
  Modules/LearningSequence/classes/Members/class.ilLearningSequenceParticipants.php
Labels: bugfix

#2091 External Feed: Removed wrong include
  Services/Feeds/classes/class.ilPDExternalFeedBlock.php
Labels: bugfix

#2093 Exercise: Fix continue targeting switch (https://www.php.net/manual/e…
  Modules/Exercise/classes/class.ilExerciseSubmissionTableGUI.php
Labels: bugfix

#2097 Tracking: Fix continue targeting switch (https://www.php.net/manual/e…
  Services/Tracking/classes/repository_statistics/class.ilTrMatrixTableGUI.php
Labels: bugfix

#2095 Course/Objective Materials: Fix continue targeting switch (https://ww…
  Modules/Course/classes/class.ilCourseObjectiveMaterials.php
Labels: bugfix

#2092 Calendar: Fix continue targeting switch (https://www.php.net/manual/e…
  Services/Calendar/classes/iCal/class.ilICalParser.php
Labels: bugfix

#2098 Refinery: Load language module for 'constraint' transformations / Introduced new problem description for empty values in `IsNumeric` transformation
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Refinery/Factory.php
  src/Refinery/Numeric/IsNumeric.php
  tests/Refinery/Numeric/Validation/IsNumericConstraintTest.php
Labels: bugfix

#2094 Test: Fix continue targeting switch (https://www.php.net/manual/en/mi…
  Modules/Test/classes/confirmations/class.ilTestSettingsChangeConfirmationGUI.php
Labels: bugfix

#2082 Test/QTI: Fixed Mantis issue 25922
  Services/QTI/classes/class.ilQTIItem.php
Labels: bugfix

#2065 T&A/QTI: Fixed Mantis issue 25893
  Services/QTI/classes/class.ilQTIRenderFib.php
Labels: bugfix

#2100 [Certificate] Use general file service for image delete instead of custom method
  Services/Certificate/classes/File/Background/classs.ilCertificateBackgroundImageDelete.php
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: improvement

#2107 Travis CI: removed classmap spam, from composer process
  src/Setup/ImplementationOfInterfaceFinder.php
Labels: improvement

#2043 UI/Node: Introduction of new 'Bylined' node type
  src/UI/Component/Tree/Node/Bylined.php
  src/UI/Component/Tree/Node/Factory.php
  src/UI/Implementation/Component/Tree/Node/Bylined.php
  src/UI/Implementation/Component/Tree/Node/Factory.php
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  src/UI/examples/Tree/Node/Bylined/bylined.php
  src/UI/templates/default/Tree/tpl.node.html
  tests/UI/Component/Tree/Node/BylineNodeTest.php
Labels: improvement, jour fixe, kitchen sink

#2108 Replcaing boolean default value with empty string to avoid exception …
  Services/Mail/classes/class.ilMailOptions.php
Labels: bugfix

#2109 [UI/Tree] Fix Bylined Node Unittests
  tests/UI/Component/Tree/Node/BylineNodeTest.php
Labels: bugfix

#2084 53 fix 25852
  Modules/Forum/classes/class.ilForum.php
  Modules/Forum/classes/class.ilForumTopic.php
  Modules/Forum/classes/class.ilForumTopicTableGUI.php
Labels: bugfix

#2114 SOAP/Category: Fix new categories being created without title marked …
  webservice/soap/classes/class.ilSoapObjectAdministration.php
Labels: bugfix

#2113 User XML Parser: Fix handling of 'AuthMode' XML elements with 'local'…
  Services/User/classes/class.ilUserImportParser.php
Labels: bugfix

#2111 LDAP: Fixed Mantis issue 25959
  Services/LDAP/classes/class.ilLDAPCronSynchronization.php
Labels: bugfix

#2120 Refinery: Add rule regarding Pull Request title prefix / Remove code …
  src/Refinery/CONTRIBUTING.md
Labels: improvement

#2066 Hide ECS in roles and advanced meta data
  Services/AccessControl/classes/class.ilObjRole.php
  Services/AccessControl/classes/class.ilObjRoleGUI.php
  Services/AccessControl/classes/class.ilObjRoleTemplateGUI.php
  Services/AdvancedMetaData/classes/class.ilAdvancedMDRecord.php
  Services/WebServices/ECS/classes/class.ilECSEventQueueReader.php
  Services/WebServices/ECS/classes/class.ilECSSetting.php
Labels: bugfix

#2122 [Certificates] Move getBackgroundImageDirectory to dedicated file service
  Services/Certificate/classes/File/Background/classs.ilCertificateBackgroundImageDelete.php
  Services/Certificate/classes/File/Background/ilCertificateBackgroundImageFileService.php
  Services/Certificate/classes/Template/Action/Import/class.ilCertificateTemplateImportAction.php
  Services/Certificate/test/ilCertificateTemplateImportActionTest.php
Labels: improvement

#2124 UI Pagination: Fix PhpDoc arguments/return types and some typos
  src/UI/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
Labels: improvement

#2123 Build artifact for UI-documentation's structure
  Services/Style/System/classes/Documentation/class.ilSystemStyleDocumentationGUI.php
  Services/Style/System/classes/Setup/class.ilUIBuildDataStructureObjective.php
  Services/Style/System/classes/Setup/class.ilUIStructureSetupAgent.php
  Services/Style/System/data/data.json
  setup/cli.php
  src/Setup/ArrayArtifact.php
Labels: improvement

#2126 Move fetching temporary background image file name to dedicated service instead
  Services/Certificate/classes/File/Background/classs.ilCertificateBackgroundImageDelete.php
  Services/Certificate/classes/File/Background/ilCertificateBackgroundImageFileService.php
Labels: improvement

#2128 [Certificate] Replace method call with constants
  Services/Certificate/classes/File/Background/ilCertificateBackgroundImageFileService.php
  Services/Certificate/classes/class.ilObjCertificateSettings.php
Labels: improvement

#2131 lso fix wrong tpl type hints
  Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentGUI.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Modules/LearningSequence/classes/Settings/class.ilObjLearningSequenceSettingsGUI.php
Labels: bugfix

#2039 LSO: fix 0025714; prevents popup-blocking.
  Modules/LearningSequence/classes/Player/LSControlBuilder.php
  Modules/LearningSequence/classes/Player/class.ilKioskPageRenderer.php
  Modules/LearningSequence/classes/Player/class.ilLegacyKioskModeView.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Modules/LearningSequence/templates/default/tpl.kioskpage.html
Labels: bugfix

#2133 [Certificate] Move XML Checker to specific domain
  Services/Certificate/classes/File/Template/XLS/class.ilXmlChecker.php
Labels: improvement

#2104 Exercise Submission Table: Fixed continue in switch
  Modules/Exercise/classes/class.ilExerciseSubmissionTableGUI.php
Labels: bugfix

#2053 UI, Bulky Link
  Services/Certificate/test/ilCertificateLearningHistoryProviderTest.php
  src/UI/Component/Link/Bulky.php
  src/UI/Component/Link/Factory.php
  src/UI/Component/MainControls/MainBar.php
  src/UI/Implementation/Component/Button/Bulky.php
  src/UI/Implementation/Component/Link/Bulky.php
  src/UI/Implementation/Component/Link/Factory.php
  src/UI/Implementation/Component/Link/Renderer.php
  src/UI/Implementation/Component/MainControls/MainBar.php
  src/UI/Implementation/Component/MainControls/Slate/Combined.php
  src/UI/Implementation/Component/Menu/Menu.php
  src/UI/Implementation/Component/Symbol/Glyph/GlyphRendererFactory.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/examples/Link/Bulky/base.php
  src/UI/examples/Menu/Drilldown/drilldown.php
  src/UI/templates/default/Link/link.less
  src/UI/templates/default/Link/tpl.bulky.html
  src/UI/templates/default/MainControls/Slate/slate.less
  src/UI/templates/default/Menu/drilldown.less
  src/UI/templates/js/Menu/drilldown.js
  templates/default/delos.css
  templates/default/delos.less
  tests/UI/Component/Link/BulkyLinkTest.php
  tests/UI/Component/MainControls/MainBarTest.php
Labels: improvement, kitchen sink

#2099 GlobalScreen: Scope Notifications
  Services/BackgroundTasks/classes/Provider/BTNotificationProvider.php
  Services/GlobalScreen/artifacts/global_screen_providers.php
  Services/GlobalScreen/classes/Setup/class.ilGlobalScreenBuildProviderMapObjective.php
  Services/GlobalScreen/classes/class.ilGSProviderFactory.php
  src/GlobalScreen/Collector/CollectorFactory.php
  src/GlobalScreen/Provider/NullProviderFactory.php
  src/GlobalScreen/Provider/ProviderFactory.php
  src/GlobalScreen/README.md
  src/GlobalScreen/Scope/Layout/Collector/MainLayoutCollector.php
  src/GlobalScreen/Scope/MetaBar/Collector/Renderer/NotificationCenterRenderer.php
  src/GlobalScreen/Scope/MetaBar/Factory/MetaBarItemFactory.php
  src/GlobalScreen/Scope/MetaBar/Factory/NotificationCenter.php
  src/GlobalScreen/Scope/MetaBar/Provider/NotificationCenterProvider.php
  src/GlobalScreen/Scope/Notification/Collector/MainNotificationCollector.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/AbstractBaseNotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/NotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/StandardNotificationGroupRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/StandardNotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Factory/AbstractBaseNotification.php
  src/GlobalScreen/Scope/Notification/Factory/AbstractTitleNotification.php
  src/GlobalScreen/Scope/Notification/Factory/NotificationFactory.php
  src/GlobalScreen/Scope/Notification/Factory/StandardNotification.php
  src/GlobalScreen/Scope/Notification/Factory/StandardNotificationGroup.php
  src/GlobalScreen/Scope/Notification/Factory/canHaveSymbol.php
  src/GlobalScreen/Scope/Notification/Factory/hasActions.php
  src/GlobalScreen/Scope/Notification/Factory/hasTitle.php
  src/GlobalScreen/Scope/Notification/Factory/isItem.php
  src/GlobalScreen/Scope/Notification/NotificationServices.php
  src/GlobalScreen/Scope/Notification/Provider/AbstractNotificationProvider.php
  src/GlobalScreen/Scope/Notification/Provider/NotificationProvider.php
  src/GlobalScreen/Scope/Notification/README.md
  src/GlobalScreen/Services.php
Labels: improvement

#2042 UI/Node: Propose to add links to tree nodes so labels can be displayed as href link
  Modules/MediaPool/classes/class.ilMediaPoolExplorerGUI.php
  Services/UIComponent/Explorer2/classes/class.ilTreeExplorerGUI.php
  src/UI/Component/Tree/Node/Factory.php
  src/UI/Component/Tree/Node/Node.php
  src/UI/Implementation/Component/Tree/Node/Factory.php
  src/UI/Implementation/Component/Tree/Node/Node.php
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  src/UI/Implementation/Component/Tree/Node/Simple.php
  src/UI/examples/Tree/Node/Simple/simple-with-link.php
  src/UI/templates/default/Tree/tpl.node.html
  src/UI/templates/js/Tree/tree.js
  templates/default/delos.css
  tests/UI/Component/Tree/Node/NodeTest.php
Labels: improvement, kitchen sink

#2136 Global Screen: Fix an issue where the 'Basic.js' file is included aft…
  Services/JavaScript/js/Basic.js
Labels: bugfix

#2137 Fix behavior if il-variable is undefined
  Services/JavaScript/js/Basic.js
Labels: bugfix

#2139 UI/Node: Fix some rendering problems with bylined nodes and bylined linked nodes
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  src/UI/templates/default/Tree/tpl.node.html
Labels: bugfix

#2138 Forum: Tree in slate
  Modules/Forum/classes/class.ilForumExplorerGUI.php
  Modules/Forum/classes/class.ilForumGlobalScreenToolsProvider.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Modules/Forum/js/ilForumExplorer.js
  Modules/Forum/module.xml
  Services/GlobalScreen/artifacts/global_screen_providers.php
Labels: improvement

#2142 [Forum] Use root node instead of first thread responses for tree display
  Modules/Forum/classes/class.ilForumExplorerGUI.php
Labels: improvement

#2140 Mail: Tree in slate
  Services/GlobalScreen/artifacts/global_screen_providers.php
  Services/Mail/classes/class.ilMailExplorer.php
  Services/Mail/classes/class.ilMailGUI.php
  Services/Mail/classes/class.ilMailGlobalScreenToolProvider.php
Labels: improvement

#2144 Logging: removed unnecessary usage of DIC
  Services/Logging/classes/error/class.ilLoggingErrorFileStorage.php
Labels: improvement

#2146 Fix/54/25989
  Services/Calendar/js/calendar_appointment.js
  Services/OnScreenChat/js/onscreenchat.js
Labels: bugfix

#1515 SCORM: Fixed PHP 7.2 deprecations (http://php.net/manual/de/function.…
  Modules/ScormAicc/classes/SCORM/class.ilSCORMPackageParser.php
Labels: bugfix

#2147 [Certificate] Refactoring some Certificate settings code
  Services/Certificate/classes/class.ilObjCertificateSettings.php
Labels: improvement

#1444 0024494: Failed test: Kurs mit SCORM Lernmodul exportieren
  Modules/ScormAicc/classes/class.ilSAHSEditGUI.php
  Modules/ScormAicc/classes/class.ilScormAiccDataSet.php
  Modules/ScormAicc/classes/class.ilScormAiccExporter.php
Labels: bugfix

#2148 [Certificate] Remove absract adapter class
  Services/Certificate/classes/class.ilCertificateAdapter.php
Labels: improvement
