Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-09, with the labels that each got.

#1996 Fix new plugin entries
  Services/Component/classes/class.ilPluginSlot.php
Labels: bugfix

#2153 Fix new plugin entries (#1996)
  Services/Component/classes/class.ilPluginSlot.php
Labels: bugfix

#2152 [Certificate] Remove unused method
  Services/Certificate/classes/class.ilObjCertificateSettingsAccess.php
Labels: improvement

#2154 #22627 Making application date to the default order field.
  Services/Membership/classes/class.ilWaitingListTableGUI.php
Labels: bugfix

#2143 Tracking: Fixed Mantis issue 25990
  Services/Tracking/classes/class.ilTrQuery.php
Labels: bugfix

#1994 Fix org units paths are may doubled
  Modules/OrgUnit/classes/PathStorage/class.ilOrgUnitPathStorage.php
Labels: bugfix

#2155 Fix org units paths are may doubled (#1994)
  Modules/OrgUnit/classes/PathStorage/class.ilOrgUnitPathStorage.php
Labels: bugfix

#2156 Fix org units paths are may doubled (#1994) (#2155)
  Modules/OrgUnit/classes/PathStorage/class.ilOrgUnitPathStorage.php
Labels: bugfix

#2159 [Certificates] Static code fixes
  Services/Certificate/classes/Provider/CertificateMainBarProvider.php
  Services/Certificate/classes/User/Action/Zip/class.ilUserCertificateZip.php
  Services/Certificate/classes/User/class.ilUserCertificateGUI.php
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: improvement

#2160 [Composer] Remove duplicate package reference
  libs/composer/composer.json
Labels: bugfix, improvement

#1966 Update tcpdf library (For PHP 7.2 support)
  libs/composer/composer.json
  libs/composer/composer.lock
Labels: improvement

#2163 Bugfix 0026035
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#2164 Bugfix 0026035
  setup/sql/dbupdate_05.php
Labels: bugfix

#1933 UI Input: getUpdateOnLoadCode for all Inputs (and some more associated things)
  src/UI/Component/Input/Field/MultiSelect.php
  src/UI/Component/Input/Field/Numeric.php
  src/UI/Component/Input/Field/Tag.php
  src/UI/Implementation/Component/Input/Container/Form/Renderer.php
  src/UI/Implementation/Component/Input/Field/Checkbox.php
  src/UI/Implementation/Component/Input/Field/DateTime.php
  src/UI/Implementation/Component/Input/Field/Duration.php
  src/UI/Implementation/Component/Input/Field/FilterContextRenderer.php
  src/UI/Implementation/Component/Input/Field/Group.php
  src/UI/Implementation/Component/Input/Field/Input.php
  src/UI/Implementation/Component/Input/Field/MultiSelect.php
  src/UI/Implementation/Component/Input/Field/Numeric.php
  src/UI/Implementation/Component/Input/Field/Password.php
  src/UI/Implementation/Component/Input/Field/Radio.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/Implementation/Component/Input/Field/Select.php
  src/UI/Implementation/Component/Input/Field/Tag.php
  src/UI/Implementation/Component/Input/Field/Text.php
  src/UI/Implementation/Component/Input/Field/Textarea.php
  src/UI/templates/default/Input/tpl.multiselect.html
  src/UI/templates/default/Input/tpl.numeric.html
  src/UI/templates/default/Input/tpl.textarea.html
  tests/UI/Component/Input/Field/InputTest.php
  tests/UI/Component/Input/Field/TextareaTest.php
Labels: kitchen sink

#2157 Fix multiple inline css not works in ilTemplate
  Services/UICore/classes/class.ilTemplate.php
Labels: bugfix

#2125 [bugfix-25976]: added language module 'obj' to lng
  Modules/Portfolio/classes/class.ilObjPortfolioBaseGUI.php
Labels: bugfix

#2007 try catch onload code of modules, services, plugins, ...
  Modules/LearningModule/templates/default/tpl.glossary_term_output.html
  Modules/LearningModule/templates/default/tpl.page.html
  Modules/LearningModule/templates/default/tpl.page_new.html
  Modules/LearningModule/templates/default/tpl.ppt_fullscreen.html
  Modules/LearningSequence/templates/default/tpl.kioskpage.html
  Services/COPage/templates/default/tpl.fullscreen.html
  Services/JavaScript/js/Basic.js
  Services/LTI/templates/default/tpl.main.html
  src/UI/templates/default/Layout/tpl.standardpage.html
  templates/default/tpl.main.html
Labels: improvement

#1457 Update class.ilLTIRouterGUI
  Services/LTI/classes/class.ilLTIRouterGUI.php
Labels: improvement

#2105 Fix ternary expression violating: Unparenthesized `a ? b : c ? d : e`…
  Services/Repository/classes/class.ilRepositoryGUI.php
  Services/UIComponent/Glyph/classes/class.ilGlyphGUI.php
  Services/WebAccessChecker/classes/class.ilWACSignedPath.php
Labels: bugfix

#2166 fixed 25811: Import/Export Tiles and Custom Icons
  Services/Container/classes/class.ilContainerExporter.php
  Services/Object/CommonSettings/TileImage/classes/class.ilObjectTileImage.php
  Services/Object/Icon/classes/class.ilObjectCustomIconImpl.php
  Services/Object/classes/class.ilObjectDataSet.php
  Services/Object/classes/class.ilObjectExporter.php
  Services/Object/classes/class.ilObjectImporter.php
Labels: bugfix

#1969 Documentation for “Secure ILIAS”
  docs/configuration/install.md
  docs/configuration/secure.md
Labels: improvement, jour fixe, technical board

#2168 Fix for Mantis #24777 sequencing in Scorm
  Modules/Scorm2004/classes/ilSCORM13Player.php
Labels: bugfix

#2170 Survey: Fixed Mantis issue 26084
  Modules/SurveyQuestionPool/classes/class.SurveyMultipleChoiceQuestion.php
Labels: bugfix

#2172 fixed 25985: Panel: Listing → Standard: Example 3 With lead image in …
  src/UI/templates/default/Item/item.less
  templates/default/delos.css
Labels: bugfix, kitchen sink

#2135 Mail: Add implementation of notification provider
  Services/GlobalScreen/artifacts/global_screen_providers.php
  Services/Mail/classes/Provider/MailNotificationProvider.php
  Services/Mail/classes/class.ilMailGlobalServices.php
  Services/MainMenu/classes/class.ilMainMenuGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2141 UI Tree: Better handling for clicks on nodes with an action URI
  src/UI/templates/js/Tree/tree.js
Labels: bugfix, kitchen sink

#2134 Repository Chat: Moved public chat to 'Communication' main bar parent
  Modules/Chatroom/classes/Provider/ChatMainBarProvider.php
  Services/GlobalScreen/artifacts/global_screen_providers.php
  Services/OnScreenChat/classes/class.ilOnScreenChatMenuGUI.php
  Services/OnScreenChat/js/onscreenchat-menu.js
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2103 Fix strings being accessed with {} (PHP 7.4 deprecation: Array and st…
  Modules/TestQuestionPool/classes/class.assErrorText.php
  Modules/Wiki/mediawiki/Title.php
  Services/AuthApache/classes/class.ilWhiteListUrlValidator.php
  Services/Feeds/classes/class.ilExternalFeed.php
  Services/FileDelivery/classes/FileDeliveryTypes/PHPChunked.php
  Services/FileUpload/classes/class.ilFileUploadGUI.php
  Services/Mail/classes/Address/Type/class.ilRoleMailboxSearch.php
  Services/RTE/classes/class.ilTinyMCE.php
  Services/UICore/lib/html-it/IT.php
  Services/UICore/lib/html-it/ITX.php
  Services/Utilities/classes/Parser.php
  Services/XHTMLValidator/validator/Text_Diff/Renderer.php
  Services/XHTMLValidator/validator/validator.inc
  include/Unicode/UtfNormal.php
  include/Unicode/UtfNormalUtil.php
  tests/UI/Renderer/ilIndependentTemplate.php
  webservice/soap/classes/class.ilSoapAdministration.php
Labels: bugfix

#2051 UI, Footer
  src/UI/Component/Layout/Page/Factory.php
  src/UI/Component/Layout/Page/Standard.php
  src/UI/Component/MainControls/Factory.php
  src/UI/Component/MainControls/Footer.php
  src/UI/Implementation/Component/Layout/Page/Factory.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Component/Layout/Page/Standard.php
  src/UI/Implementation/Component/MainControls/Factory.php
  src/UI/Implementation/Component/MainControls/Footer.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/examples/MainControls/Footer/footer.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/default/MainControls/footer.less
  src/UI/templates/default/MainControls/maincontrols.less
  src/UI/templates/default/MainControls/tpl.footer.html
  tests/UI/Component/MainControls/FooterTest.php
Labels: improvement, kitchen sink

#2181 possible fix for 26013: Error when opening Achievement with my Admin-…
  Services/Object/Icon/classes/class.ilObjectCustomIconFactory.php
Labels: bugfix

#2180 Certificate: removed dislocated str_replace
  Services/Certificate/classes/Placeholder/Replacement/class.ilCertificateValueReplacement.php
Labels: improvement

#2189 fixed certificate template version type
  Services/Certificate/classes/Template/class.ilCertificateTemplateRepository.php
  Services/Certificate/classes/User/class.ilUserCertificateRepository.php
  Services/Certificate/test/ilCertificateTemplateRepositoryTest.php
  Services/Certificate/test/ilUserCertificateRepositoryTest.php
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#2182 fixed certificate template version type
  Services/Certificate/classes/Template/class.ilCertificateTemplateRepository.php
  Services/Certificate/classes/User/class.ilUserCertificateRepository.php
  Services/Certificate/test/ilCertificateTemplateRepositoryTest.php
  Services/Certificate/test/ilUserCertificateRepositoryTest.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#2191 refactored treenode styles
  src/UI/templates/default/Tree/tpl.node.html
  src/UI/templates/default/Tree/tree.less
  templates/default/delos.css
  tests/UI/Component/Tree/Node/BylineNodeTest.php
  tests/UI/Component/Tree/Node/SimpleNodeTest.php
Labels: improvement, kitchen sink

#2193 Init: Remove dead authentication code
  Services/Init/classes/class.ilInitialisation.php
Labels: bugfix, improvement

#2194 Startup GUI: Remove dead authentication code
  Services/Init/classes/class.ilStartUpGUI.php
  Services/Init/templates/default/tpl.user_mapping_selection.html
Labels: bugfix, improvement

#2195 Authentication: Removed dead code
  Services/Authentication/classes/class.ilAuthBase.php
  Services/Authentication/classes/class.ilAuthContainerBase.php
  Services/Authentication/classes/class.ilAuthFactory.php
  Services/Authentication/classes/class.ilAuthHTTP.php
  Services/Authentication/classes/class.ilAuthInactive.php
  Services/Authentication/classes/class.ilAuthLogObserver.php
  Services/Authentication/classes/class.ilAuthUtils.php
  Services/Authentication/classes/class.ilAuthWeb.php
  Services/CAS/classes/class.ilAuthCAS.php
  Services/CAS/classes/class.ilAuthContainerCAS.php
  Services/CAS/classes/class.ilCASAuth.php
  Services/Calendar/classes/class.ilAuthCalendar.php
  Services/Calendar/classes/class.ilAuthCalendarToken.php
  Services/SOAPAuth/classes/class.ilAuthContainerSOAP.php
  Services/WebServices/ECS/classes/class.ilAuthContainerECS.php
  Services/WebServices/ECS/classes/class.ilAuthECS.php
  Services/WebServices/SOAP/classes/class.ilAuthSOAP.php
  src/Setup/ImplementationOfInterfaceFinder.php
  webservice/soap/classes/class.ilSoapAuthentication.php
  webservice/soap/classes/class.ilSoapAuthenticationCAS.php
  webservice/soap/classes/class.ilSoapUserAdministration.php
Labels: bugfix, improvement

#2174 Course Grouping: Fix counting non array
  Modules/Course/classes/class.ilCourseGroupingTableGUI.php
Labels: bugfix

#2130 13359 - Hide ecs types in ADM > Presentation if ecs is not configured
  Services/AdvancedMetaData/classes/class.ilAdvancedMDRecord.php
Labels: bugfix

#2129 Bugfix for 6871
  Services/LDAP/classes/class.ilLDAPCronSynchronization.php
  Services/LDAP/classes/class.ilLDAPQuery.php
  Services/LDAP/classes/class.ilLDAPResult.php
  Services/LDAP/exceptions/class.ilLDAPPagingException.php
Labels: bugfix

#1842 Course Waiting List: Fixed #24736
  Services/Membership/classes/class.ilWaitingListTableGUI.php
  Services/User/classes/class.ilUserQuery.php
Labels: bugfix

#2167 Fixed Crash after recieving a contact request
  Services/MediaObjects/classes/class.ilObjMediaObject.php
  Services/Object/classes/class.ilObject.php
  Services/Object/classes/class.ilObject2.php
  Services/User/classes/class.ilUserUtil.php
Labels: bugfix

#2197 fixed type hinting for null return (empty SQL result)
  Services/Certificate/classes/Helper/ilCertificateParticipantsHelper.php
Labels: bugfix

#1910 CaseOfLabelIfPossible transform
  src/Refinery/String/CaseOfLabel.php
  src/Refinery/String/Group.php
  tests/Refinery/String/Transformation/CaseOfLabelTest.php
Labels: improvement

#1425 0024565: "No Permission Granted" for Learning Progress of objects out…
  Services/AccessControl/classes/class.ilAccess.php
Labels: bugfix

#2198 fixed type hinting for null return (empty SQL result)
  Services/Certificate/classes/Helper/ilCertificateParticipantsHelper.php
Labels: bugfix

#2132 [Certificate] Developer API to access user specific data
  Services/Certificate/README.md
  Services/Certificate/classes/API/Data/UserCertificateDto.php
  Services/Certificate/classes/API/Download/class.ilUserCertificateApiGUI.php
  Services/Certificate/classes/API/Filter/UserDataFilter.php
  Services/Certificate/classes/API/Repository/UserDataRepository.php
  Services/Certificate/classes/API/UserCertificateAPI.php
  Services/Certificate/test/UserCertificateAPITest.php
  Services/Certificate/test/ilApiUserCertificateRepositoryTest.php
  Services/Certificate/test/ilUserCertificateApiGUITest.php
Labels: improvement

#2206 Test Question Pool: Fixed Mantis issue 26062
  Modules/TestQuestionPool/classes/class.assFormulaQuestionGUI.php
Labels: bugfix
