Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-04, with the labels that each got.

#1725 Fix ilDBGenerator output script (use of globals accidentially removed)
  Services/Database/classes/class.ilDBGenerator.php
Labels: improvement

#1547 24902: Who is online tool does not show online status for Shibboleth Auth
  Services/Authentication/classes/class.ilSession.php
  Services/Context/classes/class.ilContext.php
  Services/Context/classes/class.ilContextApacheSSO.php
  Services/Context/classes/class.ilContextCron.php
  Services/Context/classes/class.ilContextIcal.php
  Services/Context/classes/class.ilContextLTIProvider.php
  Services/Context/classes/class.ilContextRest.php
  Services/Context/classes/class.ilContextRss.php
  Services/Context/classes/class.ilContextRssAuth.php
  Services/Context/classes/class.ilContextSaml.php
  Services/Context/classes/class.ilContextScorm.php
  Services/Context/classes/class.ilContextSessionReminder.php
  Services/Context/classes/class.ilContextShibboleth.php
  Services/Context/classes/class.ilContextSoap.php
  Services/Context/classes/class.ilContextSoapNoAuth.php
  Services/Context/classes/class.ilContextSoapWithoutClient.php
  Services/Context/classes/class.ilContextUnitTest.php
  Services/Context/classes/class.ilContextWAC.php
  Services/Context/classes/class.ilContextWeb.php
  Services/Context/classes/class.ilContextWebdav.php
  Services/Context/interfaces/interface.ilContextTemplate.php
Labels: bugfix

#1728 #25166 - Setup: fixed odd missing database error
  setup/classes/class.ilClient.php
Labels: bugfix

#1646 Proposal: Add UI Links to UI Dropdowns
  src/UI/Component/Dropdown/Dropdown.php
  src/UI/Component/Dropdown/Factory.php
  src/UI/Implementation/Component/Dropdown/Dropdown.php
  src/UI/examples/Dropdown/Standard/with_buttons_and_links.php
  tests/UI/Component/Dropdown/DropdownTest.php
Labels: jour fixe, kitchen sink

#1732 [fix-25210] several typos in: templates/Readme.md
  templates/Readme.md
Labels: bugfix

#1733 #25019: Fixed Position-Based Access to Members in Individual Assessment
  Modules/IndividualAssessment/classes/AccessControl/class.ilIndividualAssessmentAccessHandler.php
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMembersGUI.php
Labels: bugfix

#1730 ObjectCopyGUI: Fixed treating non array as array (e.g. for count())
  Services/Object/classes/class.ilObjectCopyGUI.php
Labels: bugfix

#1704 [Fix 25131] edit/delete events if read write permision in shared cale…
  Services/Calendar/classes/AppointmentPresentation/class.ilAppointmentPresentationGUI.php
Labels: bugfix

#1708 WebDAV: Added rewrite rule to .htaccess to prevent problems with windows clients
  .htaccess
Labels: bugfix

#1740 TinyMCE/SOAP: Fixed #25243 / Use of undefined constant (PHP 7.2)
  webservice/soap/classes/class.ilSoapAdministration.php
Labels: bugfix

#1718 Tracking: Fixed PHP warning in ilLPStatus when accessing illegal stri…
  Services/Tracking/classes/class.ilLPStatus.php
Labels: bugfix

#1744 Search: Fixed counting non array / Mantis Issue 25250 (PHP 7.2)
  Services/WebServices/RPC/classes/class.ilRpcClient.php
Labels: bugfix

#1743 Search: Fixed counting non array / Mantis Issue 25249 (PHP 7.2)
  Services/Search/classes/Lucene/class.ilLuceneSearchResult.php
Labels: bugfix

#1747 Container: Initialized empty arrays to prevent errors on count() call…
  Services/Container/classes/class.ilContainerGUI.php
Labels: bugfix

#1746 Container Lists/Preconditions: Fixed passing a non object to ilCtrl (…
  Services/Object/classes/class.ilObjectListGUI.php
Labels: bugfix

#1745 Notes (in container lists): Fixed usage of undefined constants (PHP 7.2)
  Services/Object/classes/class.ilObjectListGUI.php
Labels: bugfix

#1738 [Fix 25130] BP- avoid schedules with wrong hours.
  Modules/BookingManager/classes/class.ilScheduleInputGUI.php
Labels: bugfix

#1614 Documentation for Repository Pattern
  docs/code-examples/repository-pattern/00_base_classes/ilGeoLocation.php
  docs/code-examples/repository-pattern/00_base_classes/ilGeoLocationRepository.php
  docs/code-examples/repository-pattern/01_simple_example/ilGeoLocationDBRepository.php
  docs/code-examples/repository-pattern/02_mock_for_developement/ilGeoLocationFileMockRepository.php
  docs/code-examples/repository-pattern/02_mock_for_developement/mocked_geolocation_data.txt
  docs/code-examples/repository-pattern/03_use_for_unit_tests/ilGeoLocationCalculator.php
  docs/code-examples/repository-pattern/03_use_for_unit_tests/ilGeoLocationCalculatorTest.php
  docs/documentation/repository-pattern.md
Labels: improvement

#1752 Improved translation for certificates in portfolio
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#1753 Improved translation for certificats in portfolio
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#1739 fallback for button-tests otherwise considered risky
  src/UI/templates/default/Button/tpl.primary.html
  src/UI/templates/default/Button/tpl.shy.html
  src/UI/templates/default/Button/tpl.tag.html
  tests/UI/Component/Button/ButtonTest.php
  tests/UI/Component/Dropzone/File/DropzoneRendererTest.php
  tests/UI/Component/ViewControl/SortationTest.php
Labels: kitchen sink

#1727 bugfix: now using variable 'background-images-path' for tree icons
  templates/default/less/Services/Container/delos.less
Labels: bugfix

#1755 Fix default option, when nothing is ever saved
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: bugfix

#1756 Fix default option, when nothing is ever saved
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: bugfix

#1762 [Certificate/turnk] Fix SCORM certificate download
  Modules/ScormAicc/classes/SCORM/class.ilSCORMPresentationGUI.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleAccess.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleListGUI.php
  Services/Certificate/classes/User/Validator/class.ilCertificateDownloadValidator.php
  Services/Certificate/classes/User/Validator/class.ilCertificateUserCertificateAccessValidator.php
  Services/Certificate/test/ilCertificateDownloadValidatorTest.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  webservice/soap/classes/class.ilSoapSCORMAdministration.php
Labels: bugfix

#1761 [Certificate/Release 5-4] Fix SCORM certificate download
  Modules/ScormAicc/classes/SCORM/class.ilSCORMPresentationGUI.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleAccess.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleListGUI.php
  Services/Certificate/classes/User/Validator/class.ilCertificateDownloadValidator.php
  Services/Certificate/classes/User/Validator/class.ilCertificateUserCertificateAccessValidator.php
  Services/Certificate/test/ilCertificateDownloadValidatorTest.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
  webservice/soap/classes/class.ilSoapSCORMAdministration.php
Labels: bugfix

#1299 Allow stl upload
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#1300 Allow obj upload
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#1685 UI Tree
  Services/Init/classes/class.ilInitialisation.php
  Services/Style/System/data/data.json
  setup/include/inc.setup_header.php
  src/UI/Component/Tree/Expandable.php
  src/UI/Component/Tree/Factory.php
  src/UI/Component/Tree/Node/AsyncNode.php
  src/UI/Component/Tree/Node/Factory.php
  src/UI/Component/Tree/Node/Node.php
  src/UI/Component/Tree/Node/Simple.php
  src/UI/Component/Tree/Tree.php
  src/UI/Component/Tree/TreeRecursion.php
  src/UI/Factory.php
  src/UI/Implementation/Component/Tree/Expandable.php
  src/UI/Implementation/Component/Tree/Factory.php
  src/UI/Implementation/Component/Tree/Node/Factory.php
  src/UI/Implementation/Component/Tree/Node/Node.php
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  src/UI/Implementation/Component/Tree/Node/Simple.php
  src/UI/Implementation/Component/Tree/Renderer.php
  src/UI/Implementation/Component/Tree/Tree.php
  src/UI/Implementation/Factory.php
  src/UI/examples/Tree/Expandable/expandable.php
  src/UI/examples/Tree/Expandable/expandable2.php
  src/UI/examples/Tree/Expandable/expandable_async_repo.php
  src/UI/examples/Tree/Node/Simple/simple.php
  src/UI/templates/default/Tree/tpl.node.html
  src/UI/templates/default/Tree/tpl.tree.html
  src/UI/templates/default/Tree/tree.less
  src/UI/templates/js/Tree/tree.js
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/variables.less
  tests/UI/Base.php
  tests/UI/Component/Breadcrumbs/BreadcrumbsTest.php
  tests/UI/Component/Card/CardTest.php
  tests/UI/Component/Card/RepositoryObjectTest.php
  tests/UI/Component/Deck/DeckTest.php
  tests/UI/Component/Dropzone/File/DropzoneRendererTest.php
  tests/UI/Component/Tree/ExpandableTreeTest.php
  tests/UI/Component/Tree/Node/NodeTest.php
  tests/UI/Component/Tree/Node/SimpleNodeTest.php
  tests/UI/Component/Tree/TreeTest.php
Labels: kitchen sink

#1767 [Certificate] Default page format was never used on creation of new certificate templates
  Services/Certificate/classes/File/Template/class.ilPageFormats.php
  Services/Certificate/classes/Form/class.ilFormFieldParser.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#1768 [Certificate/Release-5-4] Default page format was never used on creation of new certificate templates
  Services/Certificate/classes/File/Template/class.ilPageFormats.php
  Services/Certificate/classes/Form/class.ilFormFieldParser.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#1771 [Certificate] SCORM certificate template GUI throws exception because an undefined variables is used in the constructor
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsScormFormRepository.php
Labels: bugfix

#1770 [Certificate/Release-5-4] Fix diappearing certificate button in tests if test results were deleted
  Modules/Test/classes/class.ilTestResultsGUI.php
Labels: bugfix

#1769 [Certificate] Fix diappearing certificate button in tests if test results were deleted
  Modules/Test/classes/class.ilTestResultsGUI.php
Labels: bugfix

#1778 UI: Fixed missing Signal usage
  src/UI/Implementation/Component/Input/Field/Select.php
  src/UI/Implementation/Component/Input/Field/Text.php
Labels: bugfix

#1780 UI: Fixed tests on windows machines ("\r" issue)
  tests/UI/Base.php
Labels: bugfix

#1783 UI: Fixed tests on windows machines
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
  tests/UI/Component/MainControls/Slate/CombinedSlateTest.php
  tests/UI/Component/Tree/ExpandableTreeTest.php
  tests/UI/Component/Tree/Node/SimpleNodeTest.php
Labels: bugfix

#1784 UI: Fixed text input test
  tests/UI/Component/Input/Field/TextInputTest.php
Labels: bugfix

#1781 UI: Fixed tests because of missing member variable in template engine…
  Services/UICore/lib/html-it/IT.php
Labels: bugfix

#1782 UI: Fixed PHP notices when accessing undefined index of array
  src/UI/Implementation/Component/Input/Field/DependantGroupHelper.php
Labels: bugfix

#1779 Setup: Fixed dependency orchestration
  setup/include/inc.setup_header.php
Labels: bugfix

#1788 Bugfix 25307
  Modules/Exercise/Tasks/classes/class.ilExerciseDerivedTaskProviderFactory.php
  Services/Tasks/README.md
Labels: bugfix

#1785 Validation (aka. part of the Refinery): Fixed unit test issue
  src/Validation/Constraints/LogicalOr.php
  tests/Validation/Constraints/CustomTest.php
Labels: bugfix

#1790 Bugfix 25317
  Services/Repository/classes/class.ilRepositoryObjectPlugin.php
Labels: bugfix

#1776 #25042, #25037: radio collects, but does not show errors of dependant fields.
  Services/MainMenu/classes/TypeHandler/class.ilMMTypeHandlerRepositoryLink.php
  src/UI/Implementation/Component/Input/Field/Radio.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
Labels: bugfix

#1789 (Derived)Tasks: Added optional URL for derived task items
  Services/Tasks/DerivedTasks/classes/class.ilDerivedTask.php
  Services/Tasks/DerivedTasks/classes/class.ilDerivedTasksGUI.php
  Services/Tasks/README.md
Labels: improvement

#1759 LSO - Mantis 25175 - Fix xml import for lso
  Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLParser.php
  Modules/LearningSequence/classes/class.ilLearningSequenceImporter.php
Labels: bugfix

#1764 UI Rule change for test cases
  src/UI/README.md
  src/UI/docu/rules.md
Labels: kitchen sink

#1792 [Certificates] Check if learning progress is activated/deactivated on course object for certificate template.
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsCourseFormRepository.php
  Services/Certificate/classes/LearningProgress/class.ilCertificateCourseLearningProgressEvaluation.php
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1795 Avoid duplicate database query during certificate event listening + Fixing failing unit tests
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsCourseFormRepository.php
  Services/Certificate/classes/LearningProgress/class.ilCertificateCourseLearningProgressEvaluation.php
  Services/Certificate/classes/Template/class.ilCertificateTemplateRepository.php
  Services/Certificate/classes/class.ilCertificate.php
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  Services/Certificate/test/ilCertificateCourseLearningProgressEvaluationTest.php
  Services/Certificate/test/ilCertificateSettingsCourseFormRepositoryTest.php
  Services/Certificate/test/ilCertificateTemplateRepositoryTest.php
Labels: bugfix

#1796 [Certificates] Check if learning progress is activated/deactivated on course object for certificate template.
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsCourseFormRepository.php
  Services/Certificate/classes/LearningProgress/class.ilCertificateCourseLearningProgressEvaluation.php
  Services/Certificate/classes/Template/class.ilCertificateTemplateRepository.php
  Services/Certificate/classes/class.ilCertificate.php
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  Services/Certificate/test/ilCertificateCourseLearningProgressEvaluationTest.php
  Services/Certificate/test/ilCertificateSettingsCourseFormRepositoryTest.php
  Services/Certificate/test/ilCertificateTemplateRepositoryTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1797 [Certificates/trunk] Add messagebox to show that the learning progress has been deactiviated for a certain object
  Services/Certificate/classes/class.ilCertificateGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#1798 [Certificates/release-5-4] Add messagebox to show that the learning progress has been deactiviated for a certain object
  Services/Certificate/classes/class.ilCertificateGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#1799 Utilities: Fixed 'undefined constant issue' and other crude things in…
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix

#1803 lso - mantis_25178 - add lng vars for news
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#1734 [FIX] 0025216: PHP7.3: "continue" targeting switch is equivalent to "…
  Services/Object/classes/class.ilObjectCopyGUI.php
Labels: bugfix

#1720 Fix/23298/trunk/save confirmation anonymous
  Modules/DataCollection/classes/Content/class.ilDclRecordEditGUI.php
  Modules/DataCollection/classes/Fields/Fileupload/class.ilDclFileuploadFieldRepresentation.php
  Modules/DataCollection/classes/Fields/Fileupload/class.ilDclFileuploadRecordFieldModel.php
  Modules/DataCollection/classes/Helpers/class.ilDclPropertyFormGUI.php
  Services/Form/classes/class.ilPropertyFormGUI.php
Labels: bugfix
