Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-10, with the labels that each got.

#2210 fix 26175: check for error_path before deleting
  Services/Logging/classes/error/class.ilLoggerCronCleanErrorFiles.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2213 Bugfix artifact builder path separator windows
  src/Setup/ImplementationOfInterfaceFinder.php
Labels: bugfix

#2209 Setup: store config in environment
  src/Setup/ArrayEnvironment.php
  src/Setup/CLI/InstallCommand.php
  src/Setup/Environment.php
  tests/Setup/ArrayEnvironmentTest.php
Labels: improvement

#2214 Improvment certificate api
  Services/Certificate/classes/API/Download/class.ilUserCertificateApiGUI.php
  Services/Certificate/classes/API/Repository/UserDataRepository.php
  Services/Certificate/test/ilUserCertificateApiGUITest.php
Labels: improvement

#2217 Improvment certificate api (multiple sort)
  Services/Certificate/classes/API/Filter/UserDataFilter.php
  Services/Certificate/classes/API/Repository/UserDataRepository.php
Labels: improvement

#2185 Improvements and fixes for secure.md
  docs/configuration/secure.md
Labels: improvement

#2215 fixed header overwritting
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix

#2223 Setup/Artifact Builder: Fix testing blacklisted folders against regex…
  src/Setup/ImplementationOfInterfaceFinder.php
Labels: bugfix

#2216 Improvment certificate api (limit)
  Services/Certificate/classes/API/Filter/UserDataFilter.php
  Services/Certificate/classes/API/Repository/UserDataRepository.php
  Services/Certificate/classes/API/UserCertificateAPI.php
Labels: improvement

#2225 UI, fix rendering of switchable group
  src/UI/Implementation/Component/Input/Field/Renderer.php
Labels: improvement

#2184 `getPageLength` is missing in `Pagination` interface
  src/UI/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
Labels: improvement, jour fixe, kitchen sink

#2222 UI, Close Glyph: use X to close an overlay or leave a view
  src/UI/Component/Symbol/Glyph/Factory.php
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
  src/UI/examples/Symbol/Glyph/Close/close.php
  src/UI/templates/default/Symbol/tpl.glyph.html
  tests/UI/Component/Symbol/Glyph/GlyphFactoryTest.php
Labels: kitchen sink

#2220 UI: add title to page
  src/UI/Component/Layout/Page/Factory.php
  src/UI/Component/Layout/Page/Standard.php
  src/UI/Implementation/Component/Layout/Page/Factory.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Component/Layout/Page/Standard.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  tests/UI/Component/Layout/Page/StandardPageTest.php
Labels: kitchen sink

#2118 KS: UI > Listing > CharacteristicValue
  src/UI/Component/Listing/CharacteristicValue/Factory.php
  src/UI/Component/Listing/CharacteristicValue/Text.php
  src/UI/Component/Listing/Factory.php
  src/UI/Implementation/Component/Listing/CharacteristicValue/Factory.php
  src/UI/Implementation/Component/Listing/CharacteristicValue/Renderer.php
  src/UI/Implementation/Component/Listing/CharacteristicValue/Text.php
  src/UI/Implementation/Component/Listing/Factory.php
  src/UI/examples/Listing/CharacteristicValue/Text/base.php
  src/UI/templates/default/Listing/characteristic_value.less
  src/UI/templates/default/Listing/tpl.characteristic_value.html
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/variables.less
  tests/UI/Component/Listing/CharacteristicValue/CharacteristicValueFactoryTest.php
  tests/UI/Component/Listing/CharacteristicValue/CharacteristicValueTest.php
  tests/UI/Component/Listing/CharacteristicValue/CharacteristicValueTextTest.php
  tests/UI/Component/Listing/ListingFactoryTest.php
  tests/UI/Component/Listing/ListingTest.php
Labels: improvement, kitchen sink

#2229 enable empty groups by returning empty content by default if no sub-i…
  src/UI/Implementation/Component/Input/Field/Group.php
  tests/UI/Component/Input/Field/GroupInputTest.php
Labels: improvement

#2080 Adding Guidelines for Screenshots in Docs
  docs/development/docs-guidelines.md
Labels: improvement, technical board

#2240 certificates_api_limit
  Services/Certificate/classes/API/Filter/UserDataFilter.php
  Services/Certificate/classes/API/Repository/UserDataRepository.php
Labels: improvement

#2244 Feature/tile image for chat and cp
  Modules/Chatroom/classes/class.ilChatroomGUIHandler.php
  Modules/Chatroom/classes/gui/class.ilChatroomSettingsGUI.php
  Modules/ContentPage/classes/class.ilObjContentPageGUI.php
  Services/Object/classes/class.ilObjectGUI.php
Labels: improvement

#2246 Minimal Set of Changes to Apply Code Style in release_5-4
  CI/PHP-CS-Fixer/code-format.php_cs
  libs/composer/composer.json
  libs/composer/composer.lock
  libs/composer/vendor/composer/ClassLoader.php
Labels: improvement

#2247 Minimal Set of Changes to Apply Code Style in release_5-3
  CI/PHP-CS-Fixer/code-format.php_cs
  libs/composer/composer.json
  libs/composer/composer.lock
  libs/composer/vendor/composer/ClassLoader.php
Labels: improvement

#2248 fix/6/certificates_no_sort
  Services/Certificate/classes/API/Repository/UserDataRepository.php
Labels: bugfix

#2245 fix broken plugins legacy menu
  Services/Component/classes/class.ilPlugin.php
Labels: improvement

#2207 WebDAV: Added versioning to 5.4. This adds a new 'modification date' as well
  Services/WebDAV/classes/dav/class.ilObjContainerDAV.php
  Services/WebDAV/classes/dav/class.ilObjFileDAV.php
Labels: bugfix

#2252 UI Tree/Node: Add new approach to centralize node state persistence by using ilTreeExplorerGUI (with 'Mail' being the first consumer)
  Services/Mail/classes/Provider/MailGlobalScreenToolProvider.php
  Services/Mail/classes/class.ilMailExplorer.php
  Services/Mail/classes/class.ilMailGUI.php
  Services/UIComponent/Explorer2/classes/class.ilExplorerBaseGUI.php
  Services/UIComponent/Explorer2/classes/class.ilTreeExplorerGUI.php
  src/UI/templates/js/Tree/tree.js
Labels: bugfix, improvement

#2227 Improvement forum tree node state
  Modules/Forum/classes/Provider/ForumGlobalScreenToolsProvider.php
  Modules/Forum/classes/class.ilForumExplorerGUI.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Services/Mail/classes/class.ilMailExplorer.php
  Services/UIComponent/Explorer2/classes/class.ilExplorerBaseGUI.php
  Services/UIComponent/Explorer2/classes/class.ilTreeExplorerGUI.php
Labels: bugfix, improvement

#2196 security.md file for security group
  docs/development/security.md
Labels: improvement

#2253 Media Pool: Add persistence for new UI Tree/Node
  Modules/MediaPool/classes/class.ilMediaPoolExplorerGUI.php
  Modules/MediaPool/classes/class.ilObjMediaPoolGUI.php
Labels: improvement

#2265 Fixed that certificate template background images are saved as directories
  Services/Certificate/classes/Template/Action/Clone/class.ilCertificateCloneAction.php
Labels: bugfix

#2264 Fixed that certificate template background images are saved as directories
  Services/Certificate/classes/Template/Action/Clone/class.ilCertificateCloneAction.php
Labels: bugfix

#2263 Initial LTI Provider ScreenContext with basic ModificationProvider
  Services/Init/classes/class.ilInitialisation.php
  Services/LTI/classes/Screen/LtiViewLayoutProvider.php
  Services/LTI/classes/class.ilLTIViewGUI.php
  src/GlobalScreen/ScreenContext/ContextRepository.php
  src/GlobalScreen/ScreenContext/Stack/ContextCollection.php
Labels: improvement

#2255 UI, Slate: rename ShowSignal to EngageSignal, implement ReplaceSignal
  src/UI/Component/MainControls/Slate/Slate.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/templates/js/MainControls/slate.js
  tests/UI/Component/MainControls/Slate/SlateTest.php
Labels: kitchen sink

#2250 Draft for the legacy component to return custom js code
  src/UI/Component/Legacy/Legacy.php
  src/UI/Implementation/Component/Legacy/Legacy.php
Labels: improvement, kitchen sink

#2270 Bugfix 26342
  Modules/Forum/classes/class.ilForumAuthorInformation.php
Labels: bugfix

#2269 Bugfix 26342
  Modules/Forum/classes/class.ilForumAuthorInformation.php
Labels: bugfix

#2271 Bugfix 26342
  Modules/Forum/classes/class.ilForumAuthorInformation.php
Labels: bugfix

#2267 fixed missing card thumb image copy on course copy
  Services/Certificate/classes/Template/Action/Clone/class.ilCertificateCloneAction.php
  Services/Certificate/test/ilCertificateCloneActionTest.php
Labels: bugfix

#2266 fixed missing card thumb image copy on course copy
  Services/Certificate/classes/Template/Action/Clone/class.ilCertificateCloneAction.php
  Services/Certificate/test/ilCertificateCloneActionTest.php
Labels: bugfix

#1939 fix xml_style in ilCtrl::getFormAction
  Services/UICore/classes/class.ilCtrl.php
Labels: bugfix, improvement

#2262 fix empty values on non required input field numeric
  src/UI/Implementation/Component/Input/Field/Numeric.php
Labels: bugfix, kitchen sink

#2237 fixed missing fallback on background image
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2236 Hotfix/certificate default background image fallback
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2278 Revert "added immutablity for default background images "
  Services/Certificate/classes/class.ilObjCertificateSettings.php
  Services/Certificate/classes/class.ilObjCertificateSettingsAccess.php
Labels: bugfix

#2279 fixed card thumbail erro handling
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2280 fixed card thumbnail error handling
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2277 fix breadcrump workflow engine
  Services/WorkflowEngine/classes/class.ilObjWorkflowEngineGUI.php
Labels: bugfix

#2283 WebDAV: Fixed a bug in the versioning of files over webdav
  Modules/File/classes/class.ilObjFileAccessSettings.php
  Modules/File/classes/class.ilObjFileAccessSettingsGUI.php
  Services/WebDAV/classes/dav/class.ilObjContainerDAV.php
  Services/WebDAV/classes/dav/class.ilObjFileDAV.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2242 Accessibility: Add possible fix for missing aria-labels for table fil…
  Services/Form/classes/class.ilCheckboxInputGUI.php
  Services/Form/classes/class.ilDateDurationInputGUI.php
  Services/Form/classes/class.ilSelectInputGUI.php
  Services/Form/classes/class.ilTextInputGUI.php
  Services/Form/templates/default/tpl.prop_checkbox.html
  Services/Form/templates/default/tpl.prop_datetime_duration.html
  Services/Form/templates/default/tpl.prop_select.html
  Services/Form/templates/default/tpl.prop_textinput.html
  Services/Mail/classes/Form/class.ilMailQuickFilterInputGUI.php
  Services/Mail/templates/default/tpl.prop_mail_quick_filter_input.html
Labels: bugfix
