Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-12, with the labels that each got.

#2366 Webdav mount instructions
  Modules/Category/classes/class.ilObjCategoryListGUI.php
  Modules/File/classes/class.ilObjFileAccessSettings.php
  Modules/File/classes/class.ilObjFileAccessSettingsGUI.php
  Modules/Folder/classes/class.ilObjFolderListGUI.php
  Modules/Group/classes/class.ilObjGroupListGUI.php
  Services/Object/classes/class.ilObjectListGUI.php
  Services/WebDAV/classes/class.ilWebDAVMountInstructionsGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVBaseMountInstructions.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMounInstructionsDocumentProcessorBase.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocument.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocumentContentValidator.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocumentFormGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocumentPurifier.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocumentTableGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsDocumentsContainsHtmlValidator.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsFactory.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsHtmlDocumentProcessor.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsModalGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsRepositoryImpl.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsTableDataProvider.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsTextDocumentProcessor.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVMountInstructionsUploadGUI.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVObjectMountInstructions.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVObjectlessMountInstructions.php
  Services/WebDAV/classes/mount_instructions/class.ilWebDAVUriBuilder.php
  Services/WebDAV/classes/mount_instructions/ilWebDAVMountInstructionsDocumentProcessor.php
  Services/WebDAV/classes/mount_instructions/ilWebDAVMountInstructionsRepository.php
  Services/WebDAV/templates/default/tpl.webdav_documents_row.html
  Services/WebDAV/test/mount_instructions/ilWebDAVMountInstructionsDocumentProcessorBaseTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  templates/default/tpl.page_content.html
  webdav.php
Labels: improvement

#2319 Test: Add fix for counting non countable values
  Modules/Test/classes/class.ilParticipantsTestResultsGUI.php
Labels: bugfix

#2365 Login/Logout Glyph
  src/UI/Component/Symbol/Glyph/Factory.php
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
  src/UI/examples/Symbol/Glyph/Login/login.php
  src/UI/examples/Symbol/Glyph/Logout/logout.php
  src/UI/templates/default/Symbol/glyph.less
  src/UI/templates/default/Symbol/tpl.glyph.html
  templates/default/delos.css
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: bugfix, kitchen sink

#2360 Fix for 26638, Introducing Language Glyph
  src/UI/Component/Symbol/Glyph/Factory.php
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
  src/UI/examples/Symbol/Glyph/Language/language.php
  src/UI/templates/default/Symbol/tpl.glyph.html
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: bugfix, kitchen sink

#2370 Certificate: Use default background image as fallback during 5.4.x up…
  setup/sql/dbupdate_04.php
Labels: bugfix

#2312 UI: Revision of Mainbar
  src/UI/Component/MainControls/MainBar.php
  src/UI/Component/MainControls/Slate/Slate.php
  src/UI/Implementation/Component/MainControls/MainBar.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Combined.php
  src/UI/Implementation/Component/MainControls/Slate/Legacy.php
  src/UI/Implementation/Component/MainControls/Slate/Notification.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/Implementation/Component/Signal.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/js/MainControls/mainbar.js
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/Slate/SlateTest.php
Labels: improvement, kitchen sink

#2367 UI, Footer: add label and input for perma-link
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/ROADMAP.md
  src/UI/templates/default/MainControls/tpl.footer.html
  tests/UI/Component/MainControls/FooterTest.php
Labels: bugfix, kitchen sink

#2368 OnScreenChat: Possible fix for Mantis issue 26676
  Services/OnScreenChat/classes/Provider/OnScreenChatNotificationProvider.php
  Services/OnScreenChat/classes/class.ilOnScreenChatGUI.php
  Services/OnScreenChat/js/onscreenchat.js
  src/UI/templates/js/Item/notification.js
Labels: bugfix

#2372 fixed ...Holder ...holder typo
  Services/Certificate/classes/Cron/class.ilCertificateTypeClassMap.php
  Services/Certificate/classes/Gui/class.ilCertificateFactory.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/classes/Placeholder/Values/class.ilCoursePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilExercisePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilScormPlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilTestPlaceholderValues.php
  Services/Certificate/test/ilCertificateTypeClassMapTest.php
  Services/Certificate/test/ilExercisePlaceHolderValuesTest.php
  Services/Certificate/test/ilTestPlaceHolderValuesTest.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#2369 6.0/ui/mainbar levels
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/templates/default/MainControls/Slate/tpl.slate.html
  tests/UI/Component/MainControls/MainBarTest.php
Labels: bugfix, kitchen sink

#2375 UI, Mainbar: engage tools, if there are any (visible)
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix, kitchen sink

#2378 Adding MIME-Type for seb-file
  Services/Utilities/classes/class.ilMimeTypeUtil.php
Labels: bugfix

#1524 Fixed language log to lang service
  Services/Language/classes/class.ilLanguage.php
  Services/Language/classes/class.ilLanguageDetection.php
  Services/Language/service.xml
Labels: improvement

#2381 fixed missing placeholder in certificate contents
  Services/Certificate/classes/Placeholder/Values/class.ilDefaultPlaceholderValues.php
  Services/Certificate/test/ilDefaultPlaceholderValuesTest.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#2382 stricten replacing and fixed typo
  setup/sql/dbupdate_05.php
Labels: bugfix

#2371 appended user certificate migration to default certificate generation progress
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: bugfix

#2380 fixed missing placeholder in certificate contents
  Services/Certificate/classes/Placeholder/Values/class.ilDefaultPlaceholderValues.php
  Services/Certificate/test/ilDefaultPlaceholderValuesTest.php
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#2388 fixed regex replacement for old mysqls
  setup/sql/dbupdate_05.php
Labels: bugfix

#2387 fixed regex replacement for old mysqls
  setup/sql/dbupdate_05.php
Labels: bugfix

#2386 fixed regex replacement for old mysqls
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#2340 fixed overwriting of startingpoints in rearrangement
  Services/AccessControl/classes/class.ilStartingPoint.php
Labels: bugfix

#2394 Mantis 26846
  libs/composer/README.md
Labels: bugfix, technical board

#2383 fix #26554: show installation-title in page header
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix

#2396 fix 26559,26554: Page-Titles
  Services/Init/classes/class.ilStartUpGUI.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix

#2402 fix 26748 - activate first tool, if tools are actually engaged, but …
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix, kitchen sink

#2403 fix 26748 - activate first tool, if tools are actually engaged, but …
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix, kitchen sink

#2405 fix #26312 - metabar closes on outside click
  src/UI/templates/js/MainControls/metabar.js
Labels: bugfix

#2406 fix #26312 - metabar closes on outside click
  src/UI/templates/js/MainControls/metabar.js
Labels: bugfix

#2407 NotificationCenter: Add API method to close the NotificationCenter co…
  src/UI/templates/js/Item/notification.js
Labels: improvement

#2408 fix 26459, 26462 - flickering of bar-buttons
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/default/MainControls/tpl.metabar.html
  src/UI/templates/js/MainControls/mainbar.js
  src/UI/templates/js/MainControls/metabar.js
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
Labels: bugfix, kitchen sink

#2409 fix 26459, 26462 - flickering of bar-buttons
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/default/MainControls/tpl.metabar.html
  src/UI/templates/js/MainControls/mainbar.js
  src/UI/templates/js/MainControls/metabar.js
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
Labels: jour fixe, kitchen sink

#2414 fix typo in saml login form info
  lang/ilias_de.lang
Labels: bugfix

#2415 Globa Screen/Main Menu: Show Repository Link and Seperator
  Services/MainMenu/classes/Provider/CustomMainBarProvider.php
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/RepositoryLinkItemRenderer.php
Labels: bugfix

#2397 Global Page: Fix installation title, see #26554
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix
