Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-06, with the labels that each got.

#1883 SCORM: Fixed #25372 and other undefined constants
  Modules/Scorm2004/classes/ilSCORM13Package.php
  Modules/Scorm2004/classes/ilSCORM13Player.php
Labels: bugfix

#1884 Search: Fixed #25430
  Services/Search/classes/Lucene/class.ilLuceneSearchResultParser.php
Labels: bugfix

#1551 File (PHP 7.2): Fixed counting non array
  Modules/File/classes/class.ilObjFileGUI.php
Labels: bugfix

#1885 StudyProgramme: Fixed #25524
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeTreeExplorerGUI.php
  Modules/StudyProgramme/templates/default/tpl.tree_node_content.html
  Modules/StudyProgramme/templates/js/ilStudyProgramme.js
Labels: bugfix

#1861 Fix of 25489
  Services/FileUpload/js/ilFileUpload.js
Labels: bugfix

#1890 Namespace for custom icon has changed
  Services/LearningHistory/classes/class.ilLearningHistoryTimelineItem.php
Labels: bugfix

#1896 UI: fixed #25510
  src/UI/templates/default/MainControls/metabar.less
  templates/default/delos.css
Labels: bugfix

#1905 [Certificates] Set default option to cron for certificates
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  Services/Certificate/classes/class.ilCertificateCron.php
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: bugfix

#1904 [Certificates] Set default option to cron for certificates
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  Services/Certificate/classes/class.ilCertificateCron.php
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: bugfix

#1907 [Certificates] Icon factory method moved to symbol instead of the base UI factory
  Services/Certificate/classes/User/class.ilUserCertificateGUI.php
Labels: bugfix

#1872 fixed cloze bug 25375
  Modules/TestQuestionPool/classes/class.assClozeTestGUI.php
Labels: bugfix

#1909 Fix for upcoming composer version
  libs/composer/composer.json
Labels: bugfix, improvement

#1894 #25480: withUnavailableAction for Pagination's Nav Controls
  src/UI/Implementation/Component/ViewControl/Renderer.php
  tests/UI/Component/ViewControl/PaginationTest.php
Labels: bugfix

#1898 Documentation Service/Excel
  Services/Excel/README.md
Labels: improvement

#1911 PHP error on creating new forum thread/post, when notifications are a…
  Modules/Forum/classes/class.ilForumMailNotification.php
Labels: bugfix

#1902 Excel: Added method to merge cells of the passed coordinates
  Services/Excel/classes/class.ilExcel.php
Labels: improvement

#1889 [Certicates] Remove certificate migration
  Services/Certificate/README.md
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationInteraction.php
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJobDefinitions.php
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationReducedInteraction.php
  Services/Certificate/classes/Migration/class.ilCertificateMigration.php
  Services/Certificate/classes/Migration/class.ilCertificateMigrationInformationObject.php
  Services/Certificate/classes/Migration/class.ilCertificateMigrationRepository.php
  Services/Certificate/classes/Migration/class.ilCertificateMigrationUIElements.php
  Services/Certificate/classes/Migration/class.ilCertificateMigrationValidator.php
  Services/Certificate/classes/User/class.ilUserCertificateGUI.php
  Services/Certificate/classes/class.ilCertificateAppEventListener.php
  Services/Certificate/classes/class.ilCertificateMigrationGUI.php
  Services/Certificate/test/ilCertificateMigrationInformationObjectTest.php
  Services/Certificate/test/ilCertificateMigrationRepositoryTest.php
  Services/Certificate/test/ilCertificateMigrationTest.php
  Services/Certificate/test/ilCertificateMigrationUIElementsTest.php
  Services/Certificate/test/ilCertificateMigrationValidatorTest.php
  Services/User/classes/class.ilPersonalProfileGUI.php
  setup/sql/dbupdate_05.php
Labels: improvement

#1919 [Certificates] Remove unused methods
  Services/Certificate/classes/class.ilCertificate.php
Labels: improvement

#1917 fixed login max length
  Services/Form/classes/class.ilUserLoginInputGUI.php
Labels: bugfix

#1918 fix 21583: View of Content-fields: Only 3 lines, then stop with ...
  src/UI/templates/default/Item/tpl.item_standard.html
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/multi-line-cap.less
  tests/UI/Component/Item/ItemTest.php
Labels: bugfix

#1923 Use ilDatePresentation for user birthday
  Services/Certificate/classes/Placeholder/Values/class.ilDefaultPlaceholderValues.php
  Services/Certificate/test/ilDefaultPlaceholderValuesTest.php
Labels: bugfix

#1922 Use ilDatePresentation for user birthday
  Services/Certificate/classes/Placeholder/Values/class.ilDefaultPlaceholderValues.php
  Services/Certificate/test/ilDefaultPlaceholderValuesTest.php
Labels: bugfix

#1925 Don't save default image path on certificate template save. To avoid empty exports and similiar issues
  Services/Certificate/classes/Template/Action/Export/class.ilCertificateTemplateExportAction.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#1926 Handle empty background images on template save 5.4
  Services/Certificate/classes/Template/Action/Export/class.ilCertificateTemplateExportAction.php
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#1927 SCORM: Fixed #25609 (PHP 7.2)
  Modules/Scorm2004/classes/class.ilSCORM2004DeleteData.php
Labels: bugfix

#1929 ilMembershipCronNotifications: Fixed counting non array (PHP 7.2)
  Services/Membership/classes/class.ilMembershipCronNotifications.php
Labels: bugfix

#1899 Proposal to Include "Draft-PRs" into our Guidelines
  docs/documentation/contributing.md
Labels: improvement

#1901 Introduce `info.php` for Composer-Dependencies
  docs/configuration/install.md
  libs/composer/info.php
Labels: improvement, jour fixe

#1928 Course: Fixed counting non array in class.ilLOTestAssignmentTableGUI.php (PHP 7.2)
  Modules/Course/classes/Objectives/class.ilLOTestAssignmentTableGUI.php
Labels: bugfix

#1932 Fix inconsistency in supported php versions
  docs/configuration/install.md
Labels: bugfix

#1912 Certificate: Fixed migration issue with SCORM objects (https://mantis…
  Services/Certificate/classes/BackgroundTasks/class.ilCertificateMigrationJob.php
Labels: bugfix

#1941 Bugfix: 25640 Forum moderators
  Modules/Forum/classes/class.ilForumModeratorsGUI.php
Labels: bugfix

#1915 fixed add inline css
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: improvement

#1945 [Setup] Message hint that composers autoloader is missing in the setup an needs to run 'composer install' first
  setup/setup.php
Labels: improvement

#1949 ilDB: Quote table name in insert/update
  Services/Database/classes/PDO/class.ilDBPdo.php
Labels: improvement

#1946 PR for Mantis #25663
  Services/Feeds/classes/class.ilObjectFeedWriter.php
Labels: bugfix

#1891 SCORM: Fixed #25534
  Modules/ScormAicc/classes/class.ilSAHSPresentationGUI.php
Labels: bugfix

#1231 0023728: Updating LP Settings does not refresh Learning Progress corr…
  Services/Tracking/classes/status/class.ilLPStatusSCORM.php
Labels: bugfix

#1235 Fix/0022964/release 5 3/scorm copy lp setting
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModule.php
  Services/Tracking/classes/collection/class.ilLPCollectionOfSCOs.php
Labels: bugfix
