Repository ILIAS-eLearning/ILIAS, pull requests merged in 2019-11, with the labels that each got.

#2102 Travis CI: Add PHP 7.4 snapshot to build matrix
  .travis.yml
  Modules/DataCollection/test/ilModulesDataCollectionSuite.php
  Modules/DataCollection/test/ilObjDataCollectionTest.php
  Modules/IndividualAssessment/test/ilIndividualAssessmentSettingsTest.php
  Modules/StudyProgramme/test/ilObjStudyProgrammeTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeEventsTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeLPTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeProgressCalculationTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeUserAssignmentTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeUserProgressTest.php
  Services/AccessControl/test/ilServicesAccessControlSuite.php
  Services/Context/test/ilContextTest.php
  Services/Init/test/ilInitialisationTest.php
  libs/composer/composer.json
  libs/composer/composer.lock
  tests/Filesystem/Finder/FinderTest.php
Labels: improvement

#2290 ArtifactBuilder/ExternalFeed: Fix usage of undefined constants
  Services/Feeds/classes/class.ilExternalFeed.php
Labels: bugfix

#2289 ArtifactBuilder/Unicode: Add existence check when defining constants
  Services/Utilities/classes/class.ilMWParserAdapter.php
  include/Unicode/UtfNormal.php
Labels: bugfix

#2288 ArtifactBuilder/ExternalFeed/CLI: Add existence check when defining c…
  Services/Feeds/classes/class.ilExternalFeed.php
  setup/cli.php
Labels: bugfix

#2282 Fix/0025526/6/image elements in main bar do not have alt attributes
  Modules/Chatroom/classes/Provider/ChatMainBarProvider.php
  Modules/Forum/classes/Provider/ForumGlobalScreenToolsProvider.php
  Modules/LearningModule/Editing/GlobalScreen/classes/class.ilLMEditGSToolProvider.php
  Modules/Portfolio/classes/Provider/PortfolioMainBarProvider.php
  Services/Badge/classes/Provider/BadgeMainBarProvider.php
  Services/COPage/GlobalScreen/classes/class.ilCOPageEditGSToolProvider.php
  Services/Calendar/classes/Provider/CalendarMainBarProvider.php
  Services/Certificate/classes/Provider/CertificateMainBarProvider.php
  Services/Contact/classes/Provider/ContactMainBarProvider.php
  Services/Help/GlobalScreen/classes/class.ilHelpGSToolProvider.php
  Services/Help/GlobalScreen/classes/class.ilHelpMetaBarProvider.php
  Services/LearningHistory/classes/Provider/LearningHistoryMainBarProvider.php
  Services/Mail/classes/Provider/MailGlobalScreenToolProvider.php
  Services/Mail/classes/Provider/MailMainBarProvider.php
  Services/MainMenu/classes/Provider/StandardTopItemsProvider.php
  Services/MyStaff/classes/Provider/StaffMainBarProvider.php
  Services/News/classes/Provider/NewsMainBarProvider.php
  Services/Notes/GlobalScreen/classes/NotesMainBarProvider.php
  Services/PersonalDesktop/classes/Provider/PDMainBarProvider.php
  Services/PersonalWorkspace/GlobalScreen/classes/class.ilWorkspaceGlobalScreenProvider.php
  Services/Repository/GlobalScreen/classes/RepositoryMainBarProvider.php
  Services/Skill/classes/Provider/SkillMainBarProvider.php
  Services/Tagging/GlobalScreen/classes/TaggingMainBarProvider.php
  Services/Tasks/DerivedTasks/classes/Provider/DerivedTaskMainBarProvider.php
  Services/Tracking/classes/Provider/LPMainBarProvider.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Complex.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Link.php
  src/GlobalScreen/Scope/MainMenu/Factory/TopItem/TopLinkItem.php
  src/GlobalScreen/Scope/MainMenu/Factory/TopItem/TopParentItem.php
  src/GlobalScreen/Scope/Tool/Factory/Tool.php
  src/GlobalScreen/Scope/Tool/Factory/TreeTool.php
Labels: bugfix

#2296 SAML: Replace continue; With break; In Switch Statement
  Services/Saml/classes/class.ilAuthProviderSaml.php
Labels: bugfix

#2261 UI: extended Mainbar Interface
  src/UI/Component/MainControls/MainBar.php
  src/UI/Implementation/Component/MainControls/MainBar.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/templates/default/MainControls/mainbar.less
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/js/MainControls/mainbar.js
Labels: kitchen sink

#2300 Setup: Add fix for ilCtrl structure reload (with plugins installed)
  setup/classes/class.ilCtrlStructureReader.php
Labels: bugfix

#2249 WIP: UI, StandardPage: add short- and view-title
  Services/UICore/classes/Screen/PageContentProvider.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  src/GlobalScreen/Scope/Layout/Builder/StandardPageBuilder.php
  src/GlobalScreen/Scope/Layout/Collector/MainLayoutCollector.php
  src/GlobalScreen/Scope/Layout/Factory/ModificationFactory.php
  src/GlobalScreen/Scope/Layout/Factory/ShortTitleModification.php
  src/GlobalScreen/Scope/Layout/Factory/TitleModification.php
  src/GlobalScreen/Scope/Layout/Factory/ViewTitleModification.php
  src/GlobalScreen/Scope/Layout/ModificationHandler.php
  src/GlobalScreen/Scope/Layout/Provider/AbstractModificationProvider.php
  src/GlobalScreen/Scope/Layout/Provider/ModificationProvider.php
  src/GlobalScreen/Scope/Layout/Provider/PagePart/DecoratedPagePartProvider.php
  src/GlobalScreen/Scope/Layout/Provider/PagePart/PagePartProvider.php
  src/GlobalScreen/Scope/Layout/Provider/PagePart/StandardPagePartProvider.php
  src/UI/Component/Layout/Page/Factory.php
  src/UI/Component/Layout/Page/Standard.php
  src/UI/Implementation/Component/Layout/Page/Factory.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Component/Layout/Page/Standard.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  tests/UI/Component/Layout/Page/StandardPageTest.php
Labels: kitchen sink

#2274 Implementation of KS legacy with custom signals
  Services/Init/classes/class.ilInitialisation.php
  setup/include/inc.setup_header.php
  src/GlobalScreen/Scope/Layout/Provider/PagePart/StandardPagePartProvider.php
  src/UI/Component/Legacy/Factory.php
  src/UI/Component/Legacy/Legacy.php
  src/UI/Implementation/Component/Legacy/Factory.php
  src/UI/Implementation/Component/Legacy/Legacy.php
  src/UI/Implementation/Component/Legacy/Renderer.php
  src/UI/Implementation/Component/Modal/LightboxTextPage.php
  src/UI/Implementation/Factory.php
  tests/UI/Component/Breadcrumbs/BreadcrumbsTest.php
  tests/UI/Component/Card/CardTest.php
  tests/UI/Component/Card/RepositoryObjectTest.php
  tests/UI/Component/Deck/DeckTest.php
  tests/UI/Component/Dropzone/File/DropzoneRendererTest.php
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
  tests/UI/Component/Layout/Page/StandardPageTest.php
  tests/UI/Component/Legacy/LegacyTest.php
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/Menu/Drilldown/DrilldownTest.php
  tests/UI/Component/Modal/ModalBase.php
  tests/UI/Component/Panel/PanelSecondaryLegacyTest.php
  tests/UI/Component/Popover/PopoverTest.php
Labels: improvement, kitchen sink

#2292 UI counter JS
  src/UI/Implementation/Component/Counter/Renderer.php
  src/UI/examples/Counter/Status/with_js.php
  src/UI/templates/default/Counter/tpl.counter.html
  src/UI/templates/js/Counter/counter.js
  src/UI/templates/js/MainControls/metabar.js
  tests/UI/Client/Counter/CounterTest.html
  tests/UI/Client/Counter/CounterTest.js
  tests/UI/Client/Readme.md
  tests/UI/Client/Runner.js
  tests/UI/Client/index.html
  tests/UI/Component/Counter/CounterTest.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: improvement, kitchen sink

#2299 UI Components: Implementation of Notification Slate and Notification …
  Services/Init/classes/class.ilInitialisation.php
  src/UI/Component/Item/Factory.php
  src/UI/Component/Item/Item.php
  src/UI/Component/Item/Notification.php
  src/UI/Component/Item/Standard.php
  src/UI/Component/MainControls/Notification.php
  src/UI/Component/MainControls/Slate/Factory.php
  src/UI/Component/MainControls/Slate/Notification.php
  src/UI/Component/MainControls/Slate/Slate.php
  src/UI/Implementation/Component/Item/Factory.php
  src/UI/Implementation/Component/Item/Item.php
  src/UI/Implementation/Component/Item/Notification.php
  src/UI/Implementation/Component/Item/Renderer.php
  src/UI/Implementation/Component/Item/Standard.php
  src/UI/Implementation/Component/MainControls/Slate/Factory.php
  src/UI/Implementation/Component/MainControls/Slate/Notification.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/examples/Item/Notification/base.php
  src/UI/examples/Item/Notification/closable.php
  src/UI/examples/Item/Notification/with_aggregates.php
  src/UI/examples/MainControls/Slate/Notification/standard.php
  src/UI/templates/default/Item/item.less
  src/UI/templates/default/Item/tpl.item_notification.html
  src/UI/templates/default/MainControls/Slate/slate.less
  src/UI/templates/default/MainControls/Slate/tpl.notification.html
  src/UI/templates/default/MainControls/metabar.less
  src/UI/templates/js/Item/notification.js
  templates/default/less/variables.less
  tests/UI/Base.php
  tests/UI/Component/Deck/DeckTest.php
  tests/UI/Component/Item/ItemNotificationTest.php
  tests/UI/Component/Item/ItemTest.php
  tests/UI/Component/MainControls/FooterTest.php
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
  tests/UI/Component/MainControls/Slate/NotificationSlateTest.php
  tests/UI/Component/Tree/Node/BylineNodeTest.php
Labels: kitchen sink

#2317 WebDAV Feature: Error info file
  Services/Object/classes/class.ilObjectListGUI.php
  Services/WebDAV/classes/class.ilWebDAVObjDAVHelper.php
  Services/WebDAV/classes/dav/class.ilClientNodeDAV.php
  Services/WebDAV/classes/dav/class.ilObjContainerDAV.php
  Services/WebDAV/classes/dav/class.ilProblemInfoFileDAV.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2316 Fix 26505: Settings/GS - pull short-title from settings
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix

#2321 fixed too early web dir replacement
  Services/Certificate/classes/File/Certificate/class.ilPdfGenerator.php
  Services/Certificate/classes/Placeholder/Replacement/class.ilCertificateValueReplacement.php
  Services/Certificate/classes/class.ilCertificateCron.php
  Services/Certificate/test/ilCertificateValueReplacementTest.php
  Services/Certificate/test/ilPdfGeneratorTest.php
Labels: bugfix

#2322 fixed too early web dir replacement (6.0)
  Services/Certificate/classes/File/Certificate/class.ilPdfGenerator.php
  Services/Certificate/classes/Placeholder/Replacement/class.ilCertificateValueReplacement.php
  Services/Certificate/classes/class.ilCertificateCron.php
  Services/Certificate/test/ilCertificateValueReplacementTest.php
  Services/Certificate/test/ilPdfGeneratorTest.php
Labels: bugfix

#2325 fixed bug mystaff missing action menu
  Services/MyStaff/classes/ShowUser/class.ilMStShowUserCoursesTableGUI.php
  Services/MyStaff/classes/ShowUser/class.ilMStShowUserGUI.php
  Services/MyStaff/templates/default/tpl.list_user_courses_row.html
Labels: bugfix

#2320 plr performance
  Modules/Blog/classes/class.ilBlogGlobalTemplate.php
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Modules/Exercise/GlobalScreen/classes/class.ilExerciseGSToolProvider.php
  Modules/Forum/classes/Provider/ForumGlobalScreenToolsProvider.php
  Modules/LearningModule/Editing/GlobalScreen/classes/class.ilLMEditGSToolProvider.php
  Modules/LearningModule/Presentation/GlobalScreen/classes/class.ilLMGSToolProvider.php
  Modules/LearningModule/classes/class.ilLMGlobalTemplate.php
  Modules/MediaPool/GlobalScreen/classes/class.ilMediaPoolGSToolProvider.php
  Modules/OrgUnit/classes/Provider/OrgUnitToolProvider.php
  Modules/Portfolio/classes/class.ilPortfolioGlobalTemplate.php
  Modules/ScormAicc/Editing/GlobalScreen/classes/class.ilSAHSEditToolProvider.php
  Services/Administration/GlobalScreen/classes/class.ilAdminGSToolProvider.php
  Services/COPage/classes/class.ilCOPageGlobalTemplate.php
  Services/Dashboard/GlobalScreen/classes/PDMainBarProvider.php
  Services/Help/GlobalScreen/classes/class.ilHelpGSToolProvider.php
  Services/Init/classes/class.ilInitGlobalTemplate.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/Mail/classes/Provider/MailGlobalScreenToolProvider.php
  Services/MainMenu/classes/Items/Facade/class.ilMMAbstractItemFacade.php
  Services/MainMenu/classes/Items/class.ilMMItemRepository.php
  Services/MainMenu/classes/Provider/StandardTopItemsProvider.php
  Services/PersonalWorkspace/GlobalScreen/classes/class.ilWorkspaceGSToolProvider.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/Skill/GlobalScreen/classes/class.ilSkillGSToolProvider.php
  Services/Tagging/GlobalScreen/classes/TaggingMainBarProvider.php
  Services/Taxonomy/GlobalScreen/classes/class.ilTaxonomyGSToolProvider.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  Services/UICore/interfaces/interface.ilGlobalTemplateInterface.php
  error.php
  setup/classes/class.ilTemplate.php
  src/GlobalScreen/Collector/Collector.php
  src/GlobalScreen/Scope/Layout/Provider/PagePart/StandardPagePartProvider.php
  src/GlobalScreen/Scope/MainMenu/Collector/MainMenuMainCollector.php
  src/GlobalScreen/Scope/MainMenu/Collector/Map/Filterable.php
  src/GlobalScreen/Scope/MainMenu/Collector/Map/Map.php
  src/GlobalScreen/Scope/MainMenu/Collector/Map/Walkable.php
  src/GlobalScreen/Scope/MainMenu/Factory/AbstractBaseItem.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Complex.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Lost.php
  src/GlobalScreen/Scope/MainMenu/Factory/hasContent.php
  src/GlobalScreen/Scope/MetaBar/Collector/MetaBarMainCollector.php
  src/GlobalScreen/Scope/MetaBar/Collector/Renderer/NotificationCenterRenderer.php
  src/GlobalScreen/Scope/MetaBar/Provider/NotificationCenterProvider.php
  src/GlobalScreen/Scope/Notification/Collector/MainNotificationCollector.php
  src/GlobalScreen/Scope/Tool/Collector/MainToolCollector.php
  src/GlobalScreen/Scope/Tool/Factory/Tool.php
Labels: improvement, jour fixe

#2291 UI, More Glyph
  src/UI/Component/Symbol/Glyph/Factory.php
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
  src/UI/examples/Symbol/Glyph/Disclosure/disclosure.php
  src/UI/examples/Symbol/Glyph/More/more.php
  src/UI/templates/default/Symbol/tpl.glyph.html
  templates/default/fonts/Iconfont/il-icons.svg
  tests/UI/Base.php
  tests/UI/Component/Input/Field/SwitchableGroupInputTest.php
  tests/UI/Component/MainControls/FooterTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: improvement, kitchen sink

#2331 fixed 26538: KS Filter: Pressing Enter
  src/UI/Implementation/Component/Input/Container/Filter/Renderer.php
Labels: bugfix

#2330 26535 - Column 'virtual' is a reserved word in mysql >=5.7
  Modules/Glossary/classes/class.ilObjGlossary.php
Labels: improvement

#2243 Forum: Added 'Sorting' viewcontrol
  Modules/Forum/classes/class.ilForumProperties.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#2305 Global Screen: Notifications with Tests
  Services/Contact/classes/Provider/ContactNotificationProvider.php
  Services/Mail/classes/Provider/MailNotificationProvider.php
  src/GlobalScreen/Client/Notifications.php
  src/GlobalScreen/Client/notify.php
  src/GlobalScreen/Scope/MetaBar/Collector/Renderer/NotificationCenterRenderer.php
  src/GlobalScreen/Scope/MetaBar/Factory/NotificationCenter.php
  src/GlobalScreen/Scope/MetaBar/Provider/NotificationCenterProvider.php
  src/GlobalScreen/Scope/Notification/Collector/MainNotificationCollector.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/AbstractBaseNotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/NotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/StandardNotificationGroupRenderer.php
  src/GlobalScreen/Scope/Notification/Collector/Renderer/StandardNotificationRenderer.php
  src/GlobalScreen/Scope/Notification/Factory/AbstractBaseNotification.php
  src/GlobalScreen/Scope/Notification/Factory/AbstractTitleNotification.php
  src/GlobalScreen/Scope/Notification/Factory/StandardNotification.php
  src/GlobalScreen/Scope/Notification/Factory/StandardNotificationGroup.php
  src/GlobalScreen/Scope/Notification/Factory/hasActions.php
  src/GlobalScreen/Scope/Notification/Factory/hasAmount.php
  src/GlobalScreen/Scope/Notification/Factory/isItem.php
  src/GlobalScreen/Scope/Notification/README.md
  tests/GlobalScreen/Notification/BaseNotificationSetUp.php
  tests/GlobalScreen/Notification/Collector/MainNotificationCollectorTest.php
  tests/GlobalScreen/Notification/Collector/Renderer/StandardNotificationGroupRendererTest.php
  tests/GlobalScreen/Notification/Collector/Renderer/StandardNotificationRendererTest.php
  tests/GlobalScreen/Notification/Factory/GroupNotificationTest.php
  tests/GlobalScreen/Notification/Factory/NotificationFactoryTest.php
  tests/GlobalScreen/Notification/Factory/StandardNotificationTest.php
  tests/GlobalScreen/Notification/NotificationServicesTest.php
  tests/GlobalScreen/Notification/Provider/DummyProviderTest.php
Labels: improvement

#2329 UI Components: Async Notifications
  src/UI/Implementation/Component/Item/Renderer.php
  src/UI/ROADMAP.md
  src/UI/examples/Item/Notification/async.php
  src/UI/examples/MainControls/MetaBar/extended_notifications.php
  src/UI/examples/MainControls/Slate/Notification/standard.php
  src/UI/templates/default/Item/tpl.item_notification.html
  src/UI/templates/js/Item/notification.js
  tests/UI/Client/NotificationItem/NotificationItem.html
  tests/UI/Client/NotificationItem/NotificationItem.js
  tests/UI/Client/Runner.js
  tests/UI/Client/index.html
  tests/UI/Component/Item/ItemNotificationTest.php
  tests/UI/Component/MainControls/Slate/NotificationSlateTest.php
Labels: improvement, kitchen sink

#2335 Mail/NotificationCenter: Prepare persistence to accept left interval …
  Services/Mail/classes/class.ilMailGlobalServices.php
Labels: improvement

#2336 BuddySystem/NotificationCenter: Prepared notification provider for ha…
  Services/Contact/classes/Provider/ContactNotificationProvider.php
Labels: improvement

#2343 fixed invalid path controlls due loose type declaration
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
  Services/Certificate/classes/Template/Action/Export/class.ilCertificateTemplateExportAction.php
  Services/Certificate/classes/Template/class.ilCertificateTemplate.php
Labels: bugfix

#2345 fixed invalid path controlls due loose type declaration
  Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
  Services/Certificate/classes/Template/Action/Export/class.ilCertificateTemplateExportAction.php
  Services/Certificate/classes/Template/class.ilCertificateTemplate.php
Labels: bugfix

#2342 OnScreenChat: NotificationCenter Integration
  Services/GlobalScreen/artifacts/global_screen_providers.php
  Services/OnScreenChat/classes/DTO/ConversationDto.php
  Services/OnScreenChat/classes/DTO/MessageDto.php
  Services/OnScreenChat/classes/Provider/OnScreenChatNotificationProvider.php
  Services/OnScreenChat/classes/Repository/Conversation.php
  Services/OnScreenChat/classes/Repository/Subscriber.php
  Services/OnScreenChat/classes/class.ilOnScreenChatAppEventListener.php
  Services/OnScreenChat/classes/class.ilOnScreenChatGUI.php
  Services/OnScreenChat/classes/class.ilOnScreenChatMenuGUI.php
  Services/OnScreenChat/classes/class.ilOnScreenChatUserDataProvider.php
  Services/OnScreenChat/classes/class.ilOnScreenChatUserUserAutoComplete.php
  Services/OnScreenChat/js/onscreenchat-menu.js
  Services/OnScreenChat/js/onscreenchat.js
  Services/OnScreenChat/templates/default/tpl.chat-menu-item-info.html
  Services/OnScreenChat/templates/default/tpl.chat-menu-item-room.html
  Services/OnScreenChat/templates/default/tpl.chat-menu-item.html
  Services/OnScreenChat/templates/default/tpl.chat-menu.html
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/templates/js/Item/notification.js
Labels: improvement

#2351 fixed empty background images on initial save with fallback
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2352 fixed empty background images on initial save with fallback
  Services/Certificate/classes/class.ilCertificateGUI.php
Labels: bugfix

#2353 Fix 26605: add reset to meta
  src/GlobalScreen/Scope/Layout/MetaContent/MetaContent.php
Labels: bugfix

#2230 UI: View Controls in Standard Panels
  src/UI/Component/Panel/Factory.php
  src/UI/Component/Panel/Secondary/Secondary.php
  src/UI/Component/Panel/Standard.php
  src/UI/Component/Table/Presentation.php
  src/UI/Component/ViewControl/HasViewControls.php
  src/UI/Implementation/Component/Panel/Renderer.php
  src/UI/Implementation/Component/Panel/Secondary/Secondary.php
  src/UI/Implementation/Component/Panel/Standard.php
  src/UI/Implementation/Component/Table/Presentation.php
  src/UI/Implementation/Component/ViewControl/HasViewControls.php
  src/UI/examples/Panel/Standard/with_view_controls.php
  src/UI/templates/default/Panel/panel.less
  src/UI/templates/default/Panel/tpl.secondary.html
  src/UI/templates/default/Panel/tpl.standard.html
  templates/default/delos.css
  tests/UI/Component/Panel/PanelSecondaryLegacyTest.php
  tests/UI/Component/Panel/PanelSecondaryListingTest.php
  tests/UI/Component/Panel/PanelTest.php
Labels: kitchen sink

#2355 #26625 / PrivacySecurity: be humble with missing export implementations for specific types
  Services/PrivacySecurity/classes/class.ilExportFieldsInfo.php
Labels: bugfix

#2314 Security Fix
  Services/Init/classes/class.ilStartUpGUI.php
Labels: improvement

#2315 Security Fix
  Services/Init/classes/class.ilPasswordAssistanceGUI.php
Labels: improvement

#2361 Global Screen, Links in Combined Slate of User
  src/GlobalScreen/Scope/MetaBar/Collector/Renderer/LinkItemRenderer.php
  src/GlobalScreen/Scope/MetaBar/Collector/Renderer/TopParentItemRenderer.php
Labels: bugfix

#2357 Help Provider: Use Glyph instead of Icon in Meta Bar
  Services/Help/GlobalScreen/classes/class.ilHelpMetaBarProvider.php
Labels: bugfix

#2359 Feature/6/ui mode info implementation
  Services/Container/classes/Screen/MemberViewLayoutProvider.php
  src/UI/Component/Layout/Page/Standard.php
  src/UI/Component/MainControls/Factory.php
  src/UI/Component/MainControls/ModeInfo.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Component/Layout/Page/Standard.php
  src/UI/Implementation/Component/MainControls/Factory.php
  src/UI/Implementation/Component/MainControls/ModeInfo.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/ROADMAP.md
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/examples/MainControls/ModeInfo/modeinfo.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/default/MainControls/maincontrols.less
  src/UI/templates/default/MainControls/mode_info.less
  src/UI/templates/default/MainControls/tpl.mode_info.html
  templates/default/delos.css
  templates/default/less/variables.less
  tests/UI/Component/MainControls/ModeInfoTest.php
Labels: kitchen sink
