Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-08, with the labels that each got.

#2815 UI/Layout/Footer: Remove z-index from footer
  src/UI/templates/default/Layout/standardpage.less
  templates/default/delos.css
Labels: bugfix, kitchen sink

#2824 UI/Dropzone: Add fix for type check of 'lastRedirect' property
  src/UI/templates/js/Dropzone/File/uploader.js
Labels: bugfix

#2823 WAC/Random: Fix Mantis issue 28719
  Services/Randomization/classes/class.ilRandom.php
Labels: bugfix

#2816 28566 -LearningSequence: Fixed bug regarding changes on position if more objects exist than hits/page is set
  Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentTableGUI.php
Labels: bugfix

#2825 [Mantis 28727] Remove reference to deleted block_top.png
  templates/default/delos.css
  templates/default/less/Services/Table/delos.less
Labels: bugfix

#2804 Update pt language file
  lang/ilias_pt.lang
Labels: improvement

#2776 Fixed wrong precision in formulaQuestions
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
  Modules/TestQuestionPool/test/assFormulaQuestionTest.php
Labels: bugfix

#2775 Fixed wrong precision in formulaQuestions
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
  Modules/TestQuestionPool/test/assFormulaQuestionTest.php
Labels: bugfix

#2774 Fixed wrong precision in formulaQuestions
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
  Modules/TestQuestionPool/test/assFormulaQuestionTest.php
Labels: bugfix

#2773 Fixed wrong precision in formulaQuestions
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
  Modules/TestQuestionPool/test/assFormulaQuestionTest.php
Labels: bugfix

#2813 BT-28641: Removed updateTranslation for cat type in ilSoapObjectAdministration, because it was outdated
  webservice/soap/classes/class.ilSoapObjectAdministration.php
Labels: bugfix

#2796 src: #28595 set callback cmd to show search, because there is no func…
  Services/Search/classes/class.ilRepositorySearchGUI.php
Labels: bugfix

#2777 Init/Auth: Add fix for failed routing of some goto URLs
  Services/Init/classes/class.ilInitialisation.php
Labels: bugfix

#2756 Trim each entry of valid email domains
  Services/Registration/classes/class.ilRegistrationSettings.php
Labels: improvement

#2831 Feature: User Agreement by Country
  Services/Init/classes/class.ilInitialisation.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceCriterionTypeFactory.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceHistorizedCriterion.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceLogicalAndDocumentCriteriaEvaluation.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceUserHasCountryCriterion.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceUserHasCountryCriterionGUI.php
  Services/TermsOfService/classes/Criteria/class.ilTermsOfServiceUserHasLanguageCriterion.php
  Services/TermsOfService/classes/Document/class.ilTermsOfServiceHistorizedDocument.php
  Services/TermsOfService/classes/Document/class.ilTermsOfServiceSequentialDocumentEvaluation.php
  Services/TermsOfService/classes/class.ilObjTermsOfService.php
  Services/TermsOfService/classes/class.ilTermsOfServiceHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceRequestTargetAdjustmentCase.php
  Services/TermsOfService/classes/class.ilTermsOfServiceSettingsFormGUI.php
  Services/TermsOfService/interfaces/interface.ilTermsOfServiceDocumentCriteriaEvaluation.php
  Services/TermsOfService/interfaces/interface.ilTermsOfServiceDocumentEvaluation.php
  Services/TermsOfService/test/acceptance/ilTermsOfServiceRequestTargetAdjustmentCaseTest.php
  Services/TermsOfService/test/criteria/ilTermsOfServiceCriterionBaseTest.php
  Services/TermsOfService/test/criteria/ilTermsOfServiceUserHasCountryCriterionTest.php
  Services/TermsOfService/test/evaluation/ilTermsOfServiceDocumentEvaluationTest.php
  Services/TermsOfService/test/events/ilTermsOfServiceAppEventListenerTest.php
  Services/TermsOfService/test/factories/ilTermsOfServiceCriterionTypeFactoryTest.php
  Services/TermsOfService/test/gui/ilTermsOfServiceSettingsFormGUITest.php
  Services/TermsOfService/test/helper/ilTermsOfServiceHelperTest.php
  Services/TermsOfService/test/ilServicesTermsOfServiceSuite.php
  Services/User/Profile/classes/class.ilPersonalProfileGUI.php
  Services/User/ProfilePrompt/classes/class.ilUserProfileIncompleteRequestTargetAdjustmentCase.php
  Services/User/classes/class.ilObjUser.php
  Services/User/classes/class.ilUserPasswordResetRequestTargetAdjustmentCase.php
  Services/User/classes/class.ilUserRequestTargetAdjustment.php
  Services/User/classes/class.ilUserRequestTargetAdjustmentCase.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2832 Feature: Multilingualism for Content Pages
  Modules/ContentPage/classes/class.ilContentPageDataSet.php
  Modules/ContentPage/classes/class.ilContentPageExporter.php
  Modules/ContentPage/classes/class.ilContentPageImporter.php
  Modules/ContentPage/classes/class.ilContentPageKioskModeView.php
  Modules/ContentPage/classes/class.ilContentPageLP.php
  Modules/ContentPage/classes/class.ilContentPagePage.php
  Modules/ContentPage/classes/class.ilContentPagePageCollector.php
  Modules/ContentPage/classes/class.ilContentPagePageCommandForwarder.php
  Modules/ContentPage/classes/class.ilContentPagePageConfig.php
  Modules/ContentPage/classes/class.ilContentPagePageGUI.php
  Modules/ContentPage/classes/class.ilObjContentPage.php
  Modules/ContentPage/classes/class.ilObjContentPageAccess.php
  Modules/ContentPage/classes/class.ilObjContentPageGUI.php
  Modules/ContentPage/classes/class.ilObjContentPageListGUI.php
  Modules/ContentPage/interfaces/interface.ilContentPageObjectConstants.php
  Modules/ContentPage/module.xml
Labels: improvement

#2828 fix_28737: use il-footer-bg-color in default layout
  src/UI/templates/default/Layout/standardpage.less
Labels: bugfix

#2829 Modules - StudyProgramme: set permissions for auto content references
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
Labels: bugfix

#2837 Forum: Hotfix for Mantis issue 28765
  setup/sql/6_hotfixes.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#2840 Forum: Don't fix frm trees if regular db step was executed after fix …
  setup/sql/6_hotfixes.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#2753 UI Components: Roadmap entry for missing high priority components
  src/UI/ROADMAP.md
Labels: kitchen sink, roadmap

#2821 LegacyForm/TagInput: Fix typeahead issue
  Services/Form/templates/default/tpl.prop_tag_typeahead.html
Labels: bugfix

#2836 #28744: highlight (current) nodes in ToC
  Modules/LearningSequence/classes/Player/LSTOCBuilder.php
  Modules/LearningSequence/classes/Player/class.ilLSTOCGUI.php
  Modules/LearningSequence/test/LSTOCBuilderTest.php
  src/KioskMode/TOCBuilder.php
Labels: bugfix, improvement

#2584 Refinery: add interface to kindlyTo-transformation
  src/Refinery/Factory.php
  src/Refinery/KindlyTo/Group.php
  src/Refinery/KindlyTo/Transformation/BooleanTransformation.php
  src/Refinery/KindlyTo/Transformation/DateTimeTransformation.php
  src/Refinery/KindlyTo/Transformation/DictionaryTransformation.php
  src/Refinery/KindlyTo/Transformation/FloatTransformation.php
  src/Refinery/KindlyTo/Transformation/IntegerTransformation.php
  src/Refinery/KindlyTo/Transformation/ListTransformation.php
  src/Refinery/KindlyTo/Transformation/RecordTransformation.php
  src/Refinery/KindlyTo/Transformation/StringTransformation.php
  src/Refinery/KindlyTo/Transformation/TupleTransformation.php
  tests/Refinery/KindlyTo/GroupTest.php
  tests/Refinery/KindlyTo/Transformation/BooleanTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/DateTimeTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/DictionaryTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/FloatTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/IntegerTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/ListTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/RecordTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/StringTransformationTest.php
  tests/Refinery/KindlyTo/Transformation/TupleTransformationTest.php
Labels: improvement

#2848 BT-28801: Added tile image functionality to sessions
  Modules/Session/classes/class.ilObjSessionGUI.php
  Modules/Session/classes/class.ilSessionExporter.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2855 Making maps more robust for async requests
  Services/Maps/js/ServiceGoogleMaps.js
  Services/Maps/js/ServiceOpenLayers.js
Labels: improvement

#2854 Fix typo in tpl.standard.html
  src/UI/templates/default/Input/tpl.standard.html
  tests/UI/Component/Input/Container/Form/StandardFormTest.php
Labels: improvement

#2851 UICore: improve handling of paths in reader
  Services/UICore/classes/Setup/class.ilCtrlStructureReader.php
  Services/UICore/classes/Setup/class.ilCtrlStructureStoredObjective.php
Labels: bugfix
