Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-04, with the labels that each got.

#2567 fix #27922 - set header-title for login
  Services/Init/classes/class.ilStartUpGUI.php
Labels: bugfix

#2615 IASS: Add subtab for addition feature settings
  Modules/IndividualAssessment/classes/Settings/class.ilIndividualAssessmentCommonSettingsGUI.php
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentDIC.php
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentSettingsGUI.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#2613 Survey: Change sender for system mail in survey (codes)
  Modules/Survey/classes/class.ilObjSurvey.php
Labels: bugfix

#2619 LS, Player: fix item-availability
  Modules/LearningSequence/classes/LearnerProgress/class.ilLearnerProgressDB.php
  Modules/LearningSequence/classes/Player/class.ilLSItemsQueries.php
  Modules/LearningSequence/classes/Player/class.ilLSPlayer.php
  Modules/LearningSequence/classes/class.ilLearningSequenceConditionController.php
Labels: bugfix

#2618 PRG: 28020 show additional settings for prg
  Modules/StudyProgramme/ROADMAP.md
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeGUI.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeSettingsGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeCommonSettingsGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
Labels: bugfix

#2010 Language: Increased 'identifier' database field length
  Services/Language/classes/class.ilLanguageExtTableGUI.php
  setup/sql/5_3_hotfixes.php
Labels: bugfix, improvement

#2617 [Mantis:28038]: Fix Calendar-Zip
  Services/Calendar/classes/BackgroundTasks/class.ilDownloadFilesBackgroundTask.php
Labels: bugfix

#2626 UI, Overlays: substract right-col from max_width (#28001)
  src/UI/templates/js/Page/stdpage.js
Labels: bugfix

#2622 prg - mantis_28035 - fix accredeting in edit individual plan; fix lng
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoMembershipsGUI.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeIndividualPlanGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserProgress.php
  Modules/StudyProgramme/classes/model/Progress/class.ilStudyProgrammeProgressDBRepository.php
  lang/ilias_ar.lang
  lang/ilias_bg.lang
  lang/ilias_cs.lang
  lang/ilias_da.lang
  lang/ilias_de.lang
  lang/ilias_el.lang
  lang/ilias_en.lang
  lang/ilias_es.lang
  lang/ilias_et.lang
  lang/ilias_fa.lang
  lang/ilias_fr.lang
  lang/ilias_hu.lang
  lang/ilias_it.lang
  lang/ilias_ka.lang
  lang/ilias_lt.lang
  lang/ilias_nl.lang
  lang/ilias_pl.lang
  lang/ilias_pt.lang
  lang/ilias_ro.lang
  lang/ilias_ru.lang
  lang/ilias_sk.lang
  lang/ilias_sq.lang
  lang/ilias_sr.lang
  lang/ilias_tr.lang
  lang/ilias_uk.lang
  lang/ilias_vi.lang
  lang/ilias_zh.lang
Labels: bugfix

#2624 LS, Tracking: calculate status for object (fixes 27620)
  Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipMailNotification.php
  Services/Tracking/classes/status/class.ilLPStatusCollection.php
Labels: bugfix

#2623 27976 change labels for mail context radio boxes to be more meaningful
  lang/ilias_de.lang
Labels: bugfix

#2606 Fixed strange grep message in special char checker
  CI/Special-Char-Checker/special-char-checker.sh
Labels: bugfix

#2628 prg - mantis_28047 - remove additional settings from settings tab
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeSettingsGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAdditionalSettings.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
  Modules/StudyProgramme/classes/model/Settings/class.ilStudyProgrammeSettings.php
  Modules/StudyProgramme/classes/model/Settings/class.ilStudyProgrammeSettingsDBRepository.php
  Modules/StudyProgramme/test/ilModulesStudyProgrammeSuite.php
  Modules/StudyProgramme/test/ilStudyProgrammeAdditionalSettingsTest.php
Labels: bugfix

#2621 System Styles: Revised fix for #27946
  Services/Calendar/classes/class.ilCalendarPresentationGUI.php
  Services/Dashboard/classes/class.ilDashboardGUI.php
  Services/Init/classes/class.ilInitialisation.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/CssCollection.php
Labels: bugfix, improvement

#2625 LS, delete contents and update states (fixes 28046)
  Modules/LearningSequence/classes/Player/class.ilLSStateDB.php
Labels: bugfix

#2632 UI, #28066 Fix: Remove faulty Sort Glyph
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
Labels: bugfix, kitchen sink

#2566 cat_repo - mantis_27938 - add prg to type whitelist in showTargetSelectionTree
  Services/Object/classes/class.ilObjectCopyGUI.php
Labels: bugfix

#2634 prg - mantis_28047 - ajust accessment handling
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAccess.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#2638 prg - mantis_28028 - add confirmation for deleting categories
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoCategoriesGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAutoCategoriesTableGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
Labels: bugfix

#2642 ContentPage: Fix Mantis 27762
  Modules/ContentPage/classes/class.ilContentPagePageCollector.php
  libs/composer/vendor/composer/autoload_classmap.php
  libs/composer/vendor/composer/autoload_static.php
Labels: bugfix

#2643 ContentPage: Fix Mantis issue 27762 (Wrong Reference for Internal Lin…
  Modules/ContentPage/classes/class.ilContentPagePageCollector.php
Labels: bugfix

#2644 ContentPage: Fix Mantis issue 27762 (Wrong Reference for Internal Lin…
  Modules/ContentPage/classes/class.ilContentPagePageCollector.php
Labels: bugfix

#2645 Added msender to index
  Services/Mail/LuceneDataSource.xml
Labels: bugfix

#2640 SP, fix member filter expiry-to (27698)
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#2636 prg_28029 - check for public profile for creating a static link
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoCategoriesGUI.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoMembershipsGUI.php
Labels: bugfix

#2637 UI, #28077: Fix rivals in Avatar description
  src/UI/Component/Symbol/Avatar/Factory.php
Labels: bugfix, kitchen sink

#2648 LS, fix permission-check on subtabs (#26321)
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
Labels: bugfix

#2646 prg - mantis_28068 - use newest progress and check for type at comple…
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMailTemplateContext.php
Labels: bugfix

#2641 prg - mantis_27750 - fix reminder mails
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilPrgUserNotRestartedCronJob.php
  Modules/StudyProgramme/classes/class.ilPrgUserRiskyToFailCronJob.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAppEventListener.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserAssignment.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserProgress.php
  Modules/StudyProgramme/classes/model/Assignments/class.ilStudyProgrammeAssignmentDBRepository.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2649 Mail/Lucene: Use 'ilias' as sender string for Lucene index if user id…
  Services/Mail/LuceneDataSource.xml
Labels: improvement

#2527 Proposed DBMS Versions in ILIAS 7
  docs/configuration/install.md
Labels: technical board

#2650 Added WebDAV configuration to install.md
  docs/configuration/install.md
Labels: improvement

#2651 fix classname changes
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#2653 Hotfix/certificate class case
  setup/sql/dbupdate_05.php
Labels: bugfix

#2652 Hotfix/certificate class case
  setup/sql/6_0_hotfixes.php
Labels: bugfix

#2658 Fixed: 0028110: Forum: Wrong subject after merging threads
  Modules/Forum/classes/class.ilForum.php
Labels: bugfix

#2657 Fixed: 0028110: Forum: Wrong subject after merging threads
  Modules/Forum/classes/class.ilForum.php
Labels: bugfix

#2659 Fixed: 0028110: Forum: Wrong subject after merging threads
  Modules/Forum/classes/class.ilForum.php
Labels: bugfix

#2662 Fixed 0028121: Forum Settings (Default View) not saved
  Modules/Forum/classes/class.ilForumSettingsGUI.php
Labels: bugfix

#2663 Fixed: 0028121: Forum Settings (Default View) not saved
  Modules/Forum/classes/class.ilForumSettingsGUI.php
Labels: bugfix

#2664 Fixed 0028119: Forum: Notifications not correctly merge
  Modules/Forum/classes/class.ilForumNotification.php
Labels: bugfix

#2665 Fixed 0028119: Forum: Notifications not correctly merge
  Modules/Forum/classes/class.ilForumNotification.php
Labels: bugfix

#2666 Fixed 0028119: Forum: Notifications not correctly merge
  Modules/Forum/classes/class.ilForumNotification.php
Labels: bugfix

#2630 UI, #28062 - Fix missing and existing aria labels for Glyphs
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/Symbol/Glyph/Factory.php
  src/UI/Implementation/Component/Symbol/Glyph/Factory.php
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: bugfix, kitchen sink

#2668 Fixed: 0028115: Forum: Changing title of thread is not reflected in r…
  Modules/Forum/classes/class.ilForumTopic.php
Labels: bugfix

#2670 Fixed: 0028115: Forum: Changing title of thread is not reflected in r…
  Modules/Forum/classes/class.ilForumTopic.php
Labels: bugfix

#2669 Fixed: 0028115: Forum: Changing title of thread is not reflected in r…
  Modules/Forum/classes/class.ilForumTopic.php
Labels: bugfix

#2661 Forum: Delete orphaned source thread root node when mering threads
  Modules/Forum/classes/class.ilForum.php
  Modules/Forum/classes/class.ilForumPost.php
Labels: bugfix

#2660 IASS: 27368 fix deletion of record file
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
  Modules/IndividualAssessment/classes/ilIndividualAssessmentUserGrading.php
Labels: bugfix

#2673 UI: make focus on `main` work in chrome (#27270)
  src/UI/templates/js/Page/stdpage.js
Labels: bugfix, kitchen sink

#2511 Docs: Change supported Node.js versions for ILIAS 7
  Modules/Chatroom/README.md
  docs/configuration/install.md
Labels: improvement

#2675 Completely reworked the user import form and import process to use new form builder and filesystem functionality
  Services/User/classes/class.ilObjUserFolderGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2647 Container: Fix broken cleanup of internal page editor links
  Services/Container/classes/class.ilContainer.php
Labels: bugfix

#2540 UI, Viewcontrols as Inputs
  Services/Init/classes/class.ilInitialisation.php
  setup/cli.php
  src/UI/Component/Input/Container/Factory.php
  src/UI/Component/Input/Container/ViewControl/Factory.php
  src/UI/Component/Input/Container/ViewControl/Standard.php
  src/UI/Component/Input/Container/ViewControl/ViewControl.php
  src/UI/Component/Input/Factory.php
  src/UI/Component/Input/ViewControl/Factory.php
  src/UI/Component/Input/ViewControl/FieldSelection.php
  src/UI/Component/Input/ViewControl/ViewControl.php
  src/UI/Implementation/Component/Input/Container/Factory.php
  src/UI/Implementation/Component/Input/Container/Filter/Filter.php
  src/UI/Implementation/Component/Input/Container/QueryParamsFromServerRequest.php
  src/UI/Implementation/Component/Input/Container/ViewControl/Factory.php
  src/UI/Implementation/Component/Input/Factory.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/ViewControl/Factory.php
  src/UI/ROADMAP.md
Labels: improvement, kitchen sink

#2656 new Datatype: Order
  src/Data/Factory.php
  src/Data/Order.php
  tests/Data/OrderTest.php
Labels: improvement

#2635 ilObjectFactory: Missing Class include for Plugins, see: #27073
  Services/Object/classes/class.ilObjectFactory.php
Labels: bugfix

#2678 0028148: settings form: privacy header
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumXMLParser.php
Labels: bugfix

#2677 0028148: settings form: privacy header
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumXMLParser.php
Labels: bugfix

#2676 0028148: settings form: privacy header
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumXMLParser.php
Labels: bugfix

#2074 Fixed public space redirect to login on insufficient permissions
  Modules/RootFolder/classes/class.ilObjRootFolderGUI.php
Labels: bugfix
