Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-06, with the labels that each got.

#2736 LSO - check for availability of last_item, fixes 28275
  Modules/LearningSequence/classes/Player/class.ilLSPlayer.php
Labels: bugfix

#2500 Aria (Landmark) Roles + some more accessibility fixes
  Modules/LearningSequence/test/LSLocatorBuilderTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/Layout/Page/Factory.php
  src/UI/Component/MainControls/Factory.php
  src/UI/Component/Tree/Factory.php
  src/UI/Factory.php
  src/UI/Implementation/Component/Breadcrumbs/Renderer.php
  src/UI/Implementation/Component/Button/Bulky.php
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  src/UI/ROADMAP.md
  src/UI/templates/default/Breadcrumbs/tpl.breadcrumbs.html
  src/UI/templates/default/Button/tpl.bulky.html
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/default/MainControls/Slate/tpl.notification.html
  src/UI/templates/default/MainControls/Slate/tpl.slate.html
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/default/MainControls/tpl.metabar.html
  src/UI/templates/default/Tree/tpl.node.html
  src/UI/templates/default/Tree/tpl.tree.html
  src/UI/templates/js/Tree/tree.js
  templates/default/tpl.page_content.html
  tests/UI/Component/Breadcrumbs/BreadcrumbsTest.php
  tests/UI/Component/Button/BulkyButtonTest.php
  tests/UI/Component/MainControls/MainBarTest.php
  tests/UI/Component/MainControls/MetaBarTest.php
  tests/UI/Component/MainControls/Slate/CombinedSlateTest.php
  tests/UI/Component/MainControls/Slate/SlateTest.php
  tests/UI/Component/Tree/ExpandableTreeTest.php
  tests/UI/Component/Tree/Node/BylineNodeTest.php
  tests/UI/Component/Tree/Node/SimpleNodeTest.php
Labels: improvement, kitchen sink

#2747 CSS Doc: Updating guideline on compiling by using lessc
  templates/Readme.md
Labels: improvement

#2741 orgu: #28432 remove typo in usr_id variable to show confirmation gui …
  Modules/OrgUnit/classes/Positions/UserAssignment/class.ilOrgUnitRecursiveUserAssignmentTableGUI.php
Labels: bugfix

#2749 Add missing property to remove notice
  Services/Component/classes/class.ilPluginSlot.php
Labels: improvement

#2725 Docs: Add PHP 7.4 as supported version
  docs/configuration/install.md
Labels: improvement

#2728 Docs: Add PHP 7.4 as supported version for ILIAS 6
  docs/configuration/install.md
Labels: improvement

#2732 Docs: Change DBMS support for ILIAS 6
  docs/configuration/install.md
Labels: improvement

#2731 Docs: Change DBMS support for ILIAS 6
  docs/configuration/install.md
Labels: improvement

#2761 BT-0028182: Removed delete button in registration code list if write-rights are missing
  Services/Registration/classes/class.ilRegistrationCodesTableGUI.php
  Services/Registration/classes/class.ilRegistrationSettingsGUI.php
Labels: bugfix

#2755 Docs: Change reference system for ILIAS 7
  docs/configuration/install.md
Labels: improvement, jour fixe

#2746 Javascript Modules and Bundling Guideline
  docs/development/js/bundling-example/bundling-example.html
  docs/development/js/bundling-example/component1/dist/component1.js
  docs/development/js/bundling-example/component1/dist/component1.min.js
  docs/development/js/bundling-example/component1/rollup.config.js
  docs/development/js/bundling-example/component1/src/component-submodule1.js
  docs/development/js/bundling-example/component1/src/component-submodule2.js
  docs/development/js/bundling-example/component1/src/component1.js
  docs/development/js/bundling-example/component2/component2.js
  docs/development/js/bundling-example/component3/component3.js
  docs/development/js/bundling-example/core/il.js
  docs/development/js/js-bundling.md
  docs/development/js/js-modules.md
  package-lock.json
  package.json
Labels: improvement

#2752 JS Unit Testing
  docs/development/js/js-unit-test-example/src/component.js
  docs/development/js/js-unit-test-example/src/math.js
  docs/development/js/js-unit-test-example/test/component.test.js
  docs/development/js/js-unit-test.md
Labels: improvement

#2764 fix #28501 - do not position DDs for negative width-values
  src/UI/templates/js/Page/stdpage.js
Labels: bugfix, kitchen sink

#2766 RTE/TinyMCE: Possible fix for Firefox 77 issue (Mantis 28514)
  Services/RTE/tiny_mce_3_5_11/tiny_mce.js
Labels: bugfix

#2284 Introduce CaptainHook as development dependency
  captainhook.json
  composer.json
  composer.lock
  docs/development/git-hooks.md
Labels: improvement

#2768 fix #28526 - number input for offset-days in cron log-clean
  Services/Logging/classes/error/class.ilLoggerCronCleanErrorFiles.php
Labels: bugfix

#2760 BT 0027895: Fixed individual assessment always having 0 accesses in usage intensity statistics
  Modules/IndividualAssessment/classes/class.ilObjIndividualAssessmentGUI.php
Labels: bugfix

#2765 BT-27897: Added learning sequence type to usage statistics filter dropdown. Also added tracking of usage to Learning Sequences
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  Services/Tracking/classes/class.ilLPTableBaseGUI.php
Labels: bugfix

#2738 JavaScript Dependencies: Migrate 'nestable2' from bower to npm
  Services/Form/classes/class.ilMultipleNestedOrderingElementsInputGUI.php
  libs/bower/bower.json
  libs/bower/bower_components/nestable2/.bower.json
  libs/bower/bower_components/nestable2/.eslintrc
  libs/bower/bower_components/nestable2/.github/issue_template.md
  libs/bower/bower_components/nestable2/.gitignore
  libs/bower/bower_components/nestable2/.travis.yml
  libs/bower/bower_components/nestable2/LICENSE
  libs/bower/bower_components/nestable2/README.md
  libs/bower/bower_components/nestable2/bower.json
  libs/bower/bower_components/nestable2/dist/jquery.nestable.min.css
  libs/bower/bower_components/nestable2/dist/jquery.nestable.min.js
  libs/bower/bower_components/nestable2/gulpfile.js
  libs/bower/bower_components/nestable2/jquery.nestable.css
  libs/bower/bower_components/nestable2/jquery.nestable.js
  libs/bower/bower_components/nestable2/jquery.nestable.scss
  libs/bower/bower_components/nestable2/package-lock.json
  libs/bower/bower_components/nestable2/package.json
Labels: improvement

#2772 Database/Setup: trigger custom updates in db update
  Services/Database/classes/Setup/class.ilDatabaseUpdatedObjective.php
Labels: improvement

#2727 Test Additional Time, fix for: 28403
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestParticipantsTimeExtensionGUI.php
Labels: bugfix, improvement

#2762 MathJax: Fix Mantis issue #28505
  Services/RTE/tiny_mce_3_5_11/plugins/latex/latex.php
  Services/RTE/tiny_mce_3_5_11/plugins/latex/tpl.latex.html
Labels: bugfix

#2748 23908: Refine auto save fail message
  Modules/Test/js/ilTestPlayerQuestionEditControl.js
Labels: bugfix
