Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-01, with the labels that each got.

#2333 Typo: Temparatur > Temperatur
  lang/ilias_de.lang
Labels: bugfix, improvement

#2421 MyStaff: Fix Mantis issue 26855
  Services/MyStaff/classes/ShowUser/Courses/class.ilMStShowUserCourses.php
Labels: bugfix

#2426 Missing commit "moved class"
  Services/Component/classes/class.ilPlugin.php
Labels: bugfix

#2423 DateTime: Remove manipulations of global default timezone (except in …
  Services/WorkflowEngine/test/parser/002_StartEvent/StartEvent_MultiStart.bpmn2
  Services/WorkflowEngine/test/parser/002_StartEvent/StartEvent_MultiStart_goldsample.php
  Services/WorkflowEngine/test/parser/002_StartEvent/StartEvent_Timer_Date.bpmn2
  Services/WorkflowEngine/test/parser/002_StartEvent/StartEvent_Timer_Date_goldsample.php
  Services/WorkflowEngine/test/parser/002_StartEvent/class.test_002_StartEvent.php
  Services/WorkflowEngine/test/parser/007_IntermediateCatchEvent/IntermediateCatchEvent_Timer_Simple.bpmn2
  Services/WorkflowEngine/test/parser/007_IntermediateCatchEvent/IntermediateCatchEvent_Timer_Simple_goldsample.php
  src/BackgroundTasks/Implementation/Bucket/BasicBucket.php
  tests/Filesystem/Finder/FinderTest.php
  tests/Filesystem/Provider/FlySystem/FlySystemFileAccessTest.php
Labels: bugfix, jour fixe

#2416 Docs/Maintainer: Update maintenance files and introduce 'rschenk' as …
  Modules/CmiXapi/maintenance.json
  Modules/LTIConsumer/maintenance.json
  Services/VirusScanner/maintenance.json
  docs/development/maintenance.md
  src/HTTP/maintenance.json
Labels: improvement

#2391 UI: cleaned up rules
  src/UI/docu/rules.md
Labels: improvement

#2427 UI, Mainbar: add safety - tools are generally active, but none provided
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix

#2412 fixed creation mode dependence on ansynchronous repository tree calls
  Services/Container/classes/class.ilContainerGUI.php
Labels: bugfix

#2438 [FIX] 0026720: Tooltips in Online Help not working
  Services/Help/GlobalScreen/classes/class.ilHelpViewLayoutProvider.php
  Services/UIComponent/Tooltip/js/ilTooltip.js
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/BaseTypeRenderer.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Complex.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Link.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/LinkList.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Lost.php
  src/GlobalScreen/Scope/MainMenu/Factory/Item/RepositoryLink.php
  src/GlobalScreen/Scope/MainMenu/Factory/SymbolDecoratorTrait.php
  src/GlobalScreen/Scope/MainMenu/Factory/TopItem/TopLinkItem.php
  src/GlobalScreen/Scope/MainMenu/Factory/TopItem/TopParentItem.php
  src/GlobalScreen/Scope/MainMenu/Factory/hasSymbol.php
  src/GlobalScreen/Scope/MainMenu/Factory/hasSymbolTrait.php
  src/GlobalScreen/Scope/Tool/Factory/AbstractBaseTool.php
  src/GlobalScreen/Scope/Tool/Factory/TreeTool.php
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Component/Symbol/Symbol.php
  src/UI/Implementation/Component/Symbol/Icon/Icon.php
  src/UI/Implementation/Component/Symbol/Icon/Renderer.php
  src/UI/ROADMAP.md
  src/UI/templates/default/Symbol/tpl.icon.html
Labels: bugfix

#2444 add function to remove all active states from cookie
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix, kitchen sink

#2434 Fix 0026108: Some Mail settings can not be saved
  Services/Mail/classes/Form/class.ilIncomingMailInputGUI.php
Labels: bugfix

#2432 Updated process security.md
  docs/development/security.md
Labels: jour fixe

#2435 MAPS 26775 - add build folder for openlayer maps
  libs/bower/bower_components/openlayers/build/info.json
  libs/bower/bower_components/openlayers/build/ol-debug.js
  libs/bower/bower_components/openlayers/build/ol.css
  libs/bower/bower_components/openlayers/build/ol.ext/pbf.js
  libs/bower/bower_components/openlayers/build/ol.ext/pixelworks.js
  libs/bower/bower_components/openlayers/build/ol.ext/rbush.js
  libs/bower/bower_components/openlayers/build/ol.js
  libs/bower/bower_components/openlayers/build/ol.js.map
  libs/bower/bower_components/openlayers/build/timestamps/node-modules-timestamp
Labels: bugfix

#2400 UI Avatar: Initial Interfaces and Descriptions
  src/UI/Component/Symbol/Avatar/Avatar.php
  src/UI/Component/Symbol/Avatar/Factory.php
  src/UI/Component/Symbol/Avatar/Letter.php
  src/UI/Component/Symbol/Avatar/Picture.php
  src/UI/Component/Symbol/Factory.php
  src/UI/Implementation/Component/Symbol/Factory.php
Labels: kitchen sink

#1607 VirusScanner: Temporary changed file permissions of files to enable c…
  Services/VirusScanner/classes/class.ilVirusScannerClamAV.php
Labels: bugfix

#2443 fix 27116 - reload is not needed anymore on change of orientation/scr…
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  src/UI/templates/js/Page/stdpage.js
Labels: bugfix, kitchen sink

#2456 Fix missing Trash Command in LSO
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
Labels: bugfix

#2460 0027007: Failed test: Portfolio-Freigabe ist in einem Kurs und einer …
  Services/Contact/classes/class.ilMailSearchGroupsGUI.php
Labels: bugfix

#2424 SPRG: fix for 26964 - acknowledge LP, change dates
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeChangeDeadlineGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeChangeExpireDateGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserProgress.php
Labels: bugfix

#2440 fixed deprecated implode parameter order
  Services/Database/classes/PDO/class.ilDBPdo.php
Labels: bugfix

#2431 PRG 25896 - change prg_renewal_required from Erneuerung der Qualifika…
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMailTemplateContext.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  lang/ilias_hu.lang
Labels: bugfix

#2439 Fix/24855/recommend php 7 0 in documentation
  docs/configuration/install.md
Labels: bugfix

#2467 UI/Mainbar: add function to externally remove a tool
  src/UI/templates/js/MainControls/mainbar.js
Labels: improvement, kitchen sink

#2390 Course: Fixed Mantis issue 26799
  Services/Membership/classes/class.ilMembershipGUI.php
Labels: bugfix

#2471 Removed all the include/require from webdav
  Services/WebDAV/classes/auth/class.ilWebDAVAuthentication.php
  Services/WebDAV/classes/class.ilWebDAVObjDAVHelper.php
  Services/WebDAV/classes/class.ilWebDAVRepositoryHelper.php
  Services/WebDAV/classes/class.ilWebDAVRequestHandler.php
  Services/WebDAV/classes/class.ilWebDAVUtil.php
  Services/WebDAV/classes/dav/class.ilObjCategoryDAV.php
  Services/WebDAV/classes/dav/class.ilObjCourseDAV.php
  Services/WebDAV/classes/dav/class.ilObjFileDAV.php
  Services/WebDAV/classes/dav/class.ilObjFolderDAV.php
  Services/WebDAV/classes/dav/class.ilObjGroupDAV.php
  Services/WebDAV/classes/dav/class.ilObjRepositoryRootDAV.php
  Services/WebDAV/classes/lock/class.ilWebDAVLockBackend.php
  Services/WebDAV/classes/lock/class.ilWebDAVLockObject.php
  Services/WebDAV/test/dav/ilObjContainerDAVTest.php
  Services/WebDAV/test/dav/ilObjectDAVTest.php
  Services/WebDAV/test/tree/ilWebDAVUriPathResolverTest.php
  webdav.php
Labels: improvement
