Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-05, with the labels that each got.

#2689 StudyProgramme: adjust position-permissions (#28173)
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#2691 LSO: use static lookup-methods from ilObject
  Modules/LearningSequence/classes/LSItems/LSItemOnlineStatus.php
Labels: bugfix

#2693 SPRG, LP: check previous status for "failed after deadline"
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserProgress.php
  Services/Tracking/classes/status/class.ilLPStatusStudyProgramme.php
Labels: bugfix

#2692 Failed test: Globale Rolle mit "Visible und Read auf die Administration" anlegen und testen
  Services/LDAP/classes/class.ilLDAPSettingsGUI.php
  Services/Registration/classes/class.ilRegistrationSettingsGUI.php
  Services/User/classes/class.ilObjUserFolderGUI.php
Labels: bugfix

#2684 Table: Fix of scrolling in responsive view, see #27833
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/Services/Table/delos.less
Labels: bugfix

#2458 ilPluginAdmin: Change include_once to include for multiple method calls
  Services/Component/classes/class.ilPluginAdmin.php
Labels: bugfix

#2686 UI/Footer (#28159): copy permalink by click on label
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/templates/default/MainControls/tpl.footer.html
  src/UI/templates/js/MainControls/footer.js
  tests/UI/Component/MainControls/FooterTest.php
Labels: bugfix, kitchen sink

#2697 StudyProgramme: check for authority over user...
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#2559 Docs: Change PHP versions for ILIAS 7
  README.md
  composer.json
  docs/configuration/install.md
Labels: improvement, technical board

#2564 WorkflowEngine/PHPUnit: Get rid of deprecated MockBuilder::setMethods()
  Services/WorkflowEngine/test/activities/ilStopWorkflowActivityTest.php
  Services/WorkflowEngine/test/ilWorkflowEngineBaseTest.php
Labels: improvement

#2560 CI/PHPUnit: Upgrade to PHPUnit 9 and remove Travis CI 7.2 build
  .travis.yml
  composer.json
  composer.lock
Labels: improvement

#2563 TermsOfService/PHPUnit: Get rid of deprecated MockBuilder::setMethods()
  Services/TermsOfService/test/acceptance/ilTermsOfServiceRequestTargetAdjustmentCaseTest.php
  Services/TermsOfService/test/criteria/ilTermsOfServiceCriterionBaseTest.php
  Services/TermsOfService/test/criteria/ilTermsOfServiceDocumentCriterionAssignmentConstraintTest.php
  Services/TermsOfService/test/criteria/ilTermsOfServiceNullCriterionTest.php
  Services/TermsOfService/test/document/ilTermsOfServiceDocumentTest.php
  Services/TermsOfService/test/evaluation/ilTermsOfServiceEvaluationBaseTest.php
  Services/TermsOfService/test/factories/ilTermsOfServiceCriterionTypeFactoryTest.php
  Services/TermsOfService/test/gui/ilTermsOfServiceCriterionFormGUITest.php
  Services/TermsOfService/test/gui/ilTermsOfServiceDocumentFormGUITest.php
  Services/TermsOfService/test/gui/ilTermsOfServiceSettingsFormGUITest.php
  Services/TermsOfService/test/helper/ilTermsOfServiceHelperTest.php
  Services/TermsOfService/test/ilTermsOfServiceBaseTest.php
Labels: improvement

#2699 UI: Fix warnings in tests
  tests/UI/AbstractFactoryTest.php
Labels: bugfix, improvement

#2681 Plugin Slots: Fix of #28179
  Services/Component/classes/class.ilPlugin.php
Labels: bugfix, improvement

#2682 Content Provider: Fix Language Link, see #28053
  Services/UICore/classes/Screen/PageContentProvider.php
Labels: bugfix

#2696 UI/Page - set viewport to max-scale=1
  src/UI/templates/default/Layout/tpl.standardpage.html
Labels: bugfix

#2687 Performance Participant: Only count total amount if necessary
  Services/Membership/classes/class.ilParticipant.php
Labels: improvement

#2192 allowed '.' everywere in the local part of a mail
  Services/Mail/classes/Address/Parser/RFC822.php
  Services/Mail/test/ilMailAddressParserTest.php
Labels: bugfix, improvement

#2713 allowed '.' everywere in the local part of a mail
  Services/Mail/classes/Address/Parser/RFC822.php
  Services/Mail/test/ilMailAddressParserTest.php
Labels: bugfix

#2715 fixed patch doc typo
  Services/Mail/classes/Address/Parser/RFC822.php
Labels: bugfix

#2714 allowed '.' everywere in the local part of a mail
  Services/Mail/classes/Address/Parser/RFC822.php
  Services/Mail/test/ilMailAddressParserTest.php
Labels: bugfix

#2683 [ILIAS core 0028122]: Builds are failing in report-results.sh
  CI/Import/Variables.sh
Labels: bugfix

#2717 fixed bug #25903: Displaying the properties of an object causes the t…
  Modules/Forum/classes/class.ilObjForumListGUI.php
Labels: bugfix

#2694 UI, Breadcrumbs: left-side ellipsis (#26424)
  Modules/LearningSequence/test/LSLocatorBuilderTest.php
  src/UI/templates/default/Breadcrumbs/breadcrumbs.less
  src/UI/templates/default/Breadcrumbs/tpl.breadcrumbs.html
  tests/UI/Component/Breadcrumbs/BreadcrumbsTest.php
Labels: bugfix

#2695 ui-ks - add withAction method to ui element glyph
  src/UI/Component/Symbol/Glyph/Glyph.php
  src/UI/Implementation/Component/Symbol/Glyph/Glyph.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: improvement, kitchen sink

#2718 UI: mark error in group in i18n (#28352)
  Modules/IndividualAssessment/test/ilIndividualAssessmentSettingsTest.php
  Modules/IndividualAssessment/test/ilIndividualAssessmentUserGradingTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeAssessmentSettingsTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeAutoMailSettingsTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeDeadlineSettingsTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeTypeSettingsTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeValidityOfAchievedQualificationSettingsTest.php
  Modules/StudyProgramme/test/types/ilStudyProgrammeTypeInfoTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Input/Field/Duration.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Group.php
  src/UI/Implementation/Component/Input/Field/SwitchableGroup.php
  tests/UI/Component/Input/Container/Filter/FilterFactoryTest.php
  tests/UI/Component/Input/Container/Filter/FilterTest.php
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
  tests/UI/Component/Input/Container/Form/FormFactoryTest.php
  tests/UI/Component/Input/Container/Form/FormTest.php
  tests/UI/Component/Input/Container/Form/StandardFormTest.php
  tests/UI/Component/Input/Field/CheckboxInputTest.php
  tests/UI/Component/Input/Field/DateTimeInputTest.php
  tests/UI/Component/Input/Field/DurationInputTest.php
  tests/UI/Component/Input/Field/FieldFactoryTest.php
  tests/UI/Component/Input/Field/FileInputTest.php
  tests/UI/Component/Input/Field/GroupInputTest.php
  tests/UI/Component/Input/Field/MultiSelectInputTest.php
  tests/UI/Component/Input/Field/NumericInputTest.php
  tests/UI/Component/Input/Field/OptionalGroupInputTest.php
  tests/UI/Component/Input/Field/PasswordInputTest.php
  tests/UI/Component/Input/Field/RadioInputTest.php
  tests/UI/Component/Input/Field/SwitchableGroupInputTest.php
  tests/UI/Component/Input/Field/TagInputTest.php
  tests/UI/Component/Input/Field/TextInputTest.php
  tests/UI/Component/Input/Field/TextareaTest.php
Labels: bugfix

#2446 CoPage: Fix Mantis issue 27120
  Services/COPage/classes/class.ilPageLinker.php
Labels: bugfix

#2711 Optimize filtering of test participants info
  Modules/Test/classes/class.ilObjTest.php
Labels: improvement

#2721 Fix syntax error in class.ilObjTest.php
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#2722 Setup: Fix usage of undefined variable in exception message
  Services/UICore/classes/Setup/class.ilCtrlStructureReader.php
Labels: bugfix

#2701 UI, Mainbar: Support Bulky Links (fixes #28247)
  src/UI/Component/Link/Bulky.php
  src/UI/Implementation/Component/Link/Bulky.php
  src/UI/Implementation/Component/Link/Renderer.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/templates/default/Link/tpl.bulky.html
  src/UI/templates/js/MainControls/mainbar.js
  tests/UI/Component/Link/BulkyLinkTest.php
Labels: bugfix

#2712 Introducing language.md
  docs/development/language.md
Labels: improvement

#2729 Membership: Performance on Notification Settings
  Services/Membership/classes/class.ilMembershipNotifications.php
Labels: bugfix, improvement

#2702 0025820: falsified values of textfields in export when content is syn…
  Modules/DataCollection/classes/Fields/Text/class.ilDclTextRecordFieldModel.php
  Services/Excel/classes/class.ilExcel.php
Labels: bugfix

#2006 Possible fix delete lost plugin main menu items
  Services/MainMenu/classes/Administration/class.ilMMSubItemGUI.php
  Services/MainMenu/classes/Administration/class.ilMMSubItemTableGUI.php
Labels: bugfix
