Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-11, with the labels that each got.

#2966 UI Components, Close Button: Fixing #28950
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/templates/default/Button/tpl.close.html
  tests/UI/Component/Button/ButtonTest.php
  tests/UI/Component/Dropzone/File/DropzoneRendererTest.php
  tests/UI/Component/Item/ItemNotificationTest.php
Labels: bugfix, improvement, kitchen sink

#2570 Zahlendreher korrigiert
  Services/COPage/css/content.less
Labels: bugfix

#2971 UI Components, Improving Glyph Tests
  tests/UI/Component/Symbol/Glyph/GlyphFactoryTest.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
Labels: improvement

#2964 Composer/libris: Use lowercase package to support Composer 2
  libs/composer/composer.json
  libs/composer/composer.lock
Labels: improvement

#2965 ILIAS 7 Course/Group: Add new setting (additional feature) to define a subjec…
  Modules/Course/classes/class.ilObjCourseGUI.php
  Modules/Group/classes/class.ilObjGroupGUI.php
  Services/Object/classes/class.ilObjectServiceSettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2976 ILIAS 7: Group and Course Mail Prefix (Mail)
  Services/Mail/classes/Mime/Subject/class.ilMailMimeSubjectBuilder.php
  Services/Mail/classes/class.ilMail.php
  Services/Mail/classes/class.ilMimeMail.php
  Services/Mail/test/ilMailMimeSubjectBuilderTest.php
Labels: improvement

#2977 ILIAS 7 Course/Group: Mail Prefix (Part III)
  Modules/Course/classes/class.ilCourseMembershipGUI.php
  Modules/Course/classes/class.ilCourseMembershipMailNotification.php
  Modules/Forum/classes/Notification/class.ilForumMailEventNotificationSender.php
  Modules/Forum/classes/class.ilForumMailNotification.php
  Modules/Group/classes/class.ilGroupMembershipGUI.php
  Modules/Group/classes/class.ilGroupMembershipMailNotification.php
  Modules/Session/classes/class.ilSessionMembershipGUI.php
  Services/Contact/classes/class.ilMailMemberSearchGUI.php
  Services/Mail/classes/class.ilMailNotification.php
  Services/Membership/classes/class.ilMembershipGUI.php
Labels: improvement

#2941 ILIAS 7: Withdrawal of Consent provokes deleting User Account
  Services/Administration/classes/class.ilAdministrationSettingsFormHandler.php
  Services/Init/classes/StartupSequence/StartUpSequenceDispatcher.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/Init/templates/default/tpl.view_terms_of_service.html
  Services/TermsOfService/classes/Events/class.ilTermsOfServiceEventWithdrawn.php
  Services/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  Services/TermsOfService/classes/class.ilTermsOfServiceAcceptanceStartUpStep.php
  Services/TermsOfService/classes/class.ilTermsOfServiceHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalGUIHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalStartUpStep.php
  Services/TermsOfService/service.xml
  Services/TermsOfService/templates/default/tpl.tos_withdrawal_section.html
  Services/TermsOfService/templates/default/tpl.withdraw_terms_of_service.html
  Services/UICore/classes/Screen/PageContentProvider.php
  Services/User/Profile/classes/class.ilPersonalProfileGUI.php
  Services/User/classes/class.ilObjUserFolderGUI.php
  Services/User/classes/class.ilUserAppEventListener.php
  Services/User/service.xml
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2982 ILIAS 7: Include Chat-Settings in Workflow for Personal Profiles
  Modules/Chatroom/classes/class.ilPersonalChatSettingsFormGUI.php
  Modules/Chatroom/templates/default/tpl.personal_chat_settings_form.html
  Services/OnScreenChat/classes/Provider/OnScreenChatNotificationProvider.php
  Services/User/Profile/classes/ilProfileChecklistStatus.php
  Services/User/Settings/classes/class.ilPersonalSettingsGUI.php
  Services/User/Settings/classes/class.ilUserPrivacySettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2985 Various ToS Withdrawal Refactorings
  Services/Init/classes/class.ilStartUpGUI.php
  Services/TermsOfService/classes/class.ilTermsOfServiceHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalGUIHelper.php
  Services/User/Profile/classes/class.ilPersonalProfileGUI.php
Labels: improvement

#2986 ILIAS 7: Remove PhantomJS
  Services/PDFGeneration/classes/renderer/phantomjs/class.ilPhantomJSRenderer.php
  Services/PDFGeneration/js/rasterize.js
  Services/PDFGeneration/test/ilPhantomJSRendererTest.php
  Services/PDFGeneration/test/ilPhantomJSRendererUiTest.php
  Services/PDFGeneration/test/ilServicesPDFGenerationSuite.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  lang/setup_de.lang
  lang/setup_en.lang
  setup/sql/dbupdate_05.php
Labels: improvement

#2984 Migrate WebDAV Settings to DB for ILIAS7
  Services/WebDAV/classes/class.ilObjWebDAV.php
  Services/WebDAV/classes/class.ilObjWebDAVGUI.php
  Services/WebDAV/classes/dav/class.ilObjFileDAV.php
  Services/WebDAV/test/mount_instructions/ilWebDAVMountInstructionsDocumentProcessorBaseTest.php
  setup/sql/dbupdate_05.php
Labels: improvement

#2990 ILIAS 7: Virusscanner ICAP
  Modules/File/classes/class.ilObjFileGUI.php
  Services/COPage/classes/class.ilPCInteractiveImageGUI.php
  Services/Init/classes/class.ilInitialisation.php
  Services/Utilities/classes/class.ilUtil.php
  Services/VirusScanner/classes/Setup/class.ilVirusScannerConfigStoredObjective.php
  Services/VirusScanner/classes/Setup/class.ilVirusScannerSetupAgent.php
  Services/VirusScanner/classes/Setup/class.ilVirusScannerSetupConfig.php
  Services/VirusScanner/classes/class.ilVirusScannerAntiVir.php
  Services/VirusScanner/classes/class.ilVirusScannerClamAV.php
  Services/VirusScanner/classes/class.ilVirusScannerFactory.php
  Services/VirusScanner/classes/class.ilVirusScannerICapClient.php
  Services/VirusScanner/classes/class.ilVirusScannerICapRemote.php
  Services/VirusScanner/classes/class.ilVirusScannerICapRemoteAvClient.php
  setup/README.md
Labels: improvement

#2989 TermsOfService: Withdrawal fine-tuning
  Services/Init/classes/class.ilStartUpGUI.php
  Services/TermsOfService/classes/Events/class.ilTermsOfServiceEventWithdrawn.php
  Services/TermsOfService/classes/Mail/class.ilTermsOfServiceWithdrawnMimeMail.php
  Services/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  Services/TermsOfService/classes/class.ilTermsOfServiceHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalGUIHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalStartUpStep.php
  Services/TermsOfService/templates/default/tpl.withdraw_terms_of_service.html
  Services/UICore/classes/Screen/PageContentProvider.php
  Services/User/Profile/classes/class.ilPersonalProfileGUI.php
  Services/User/classes/class.ilUserAppEventListener.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#2995 Http/Setup: collect proxy config from settings (not ini) (#29177)
  Services/Http/classes/Setup/class.ilHttpMetricsCollectedObjective.php
Labels: bugfix

#2997 Bugfix: 29185
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#2998 Bugfix: 29185
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#2999 Bugfix: 29185
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3000 Fixed changeable pseudonym in forum drafts
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3001 Booking Pool: Add deletion of reservations
  Modules/BookingManager/classes/class.ilBookingReservationsTableGUI.php
  Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
  Modules/BookingManager/templates/default/tpl.booking_reservation_row.html
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2996 TermsOfService: Fix Mantis issue 29166
  Services/Init/classes/class.ilStartUpGUI.php
  Services/TermsOfService/classes/class.ilTermsOfServiceAcceptanceStartUpStep.php
  Services/TermsOfService/classes/class.ilTermsOfServiceHelper.php
  Services/TermsOfService/classes/class.ilTermsOfServiceWithdrawalGUIHelper.php
  Services/UICore/classes/Screen/PageContentProvider.php
  Services/User/Profile/classes/class.ilPersonalProfileGUI.php
Labels: bugfix

#3011 Chatroom/Setup: make config object more robust for update
  Modules/Chatroom/classes/Setup/class.ilChatroomServerConfigStoredObjective.php
Labels: improvement

#3012 fixed 28148: imported Forum eats some settings
  Modules/Forum/classes/class.ilForumExporter.php
  Services/Container/classes/class.ilContainerExporter.php
  Services/Container/classes/class.ilContainerNewsSettingsGUI.php
  Services/News/classes/class.ilNewsDataSet.php
  Services/News/classes/class.ilNewsExporter.php
  Services/News/classes/class.ilNewsForContextBlockGUI.php
  Services/Object/classes/class.ilObjectDataSet.php
  xml/il_news_5_4.xsd
Labels: bugfix

#3013 Improve Chatroom/Setup (#29218)
  Modules/Chatroom/classes/Setup/class.ilChatroomSetupAgent.php
Labels: bugfix, improvement

#2785 Imprint: get rid of template in method renderFullScreen (#28716)
  Services/Imprint/classes/class.ilImprintGUI.php
  Services/Imprint/templates/default/tpl.imprint.html
Labels: bugfix

#2834 [Mantis 15366] Test: Reliably calc. time remaining
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
  Modules/Test/templates/default/tpl.workingtime.js
Labels: bugfix, improvement

#3014 Setup: Add README fixes
  setup/README.md
Labels: bugfix

#3019 Setup/Chatroom: use null-object for config instead (#29226)
  Modules/Chatroom/classes/Setup/class.ilChatroomSetupAgent.php
  src/Setup/NullConfig.php
Labels: bugfix

#3026 Bugfix 28971 Sorting of forum drafts
  Modules/Forum/classes/GUI/class.ilForumThreadFormGUI.php
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3025 Bugfix 28971 Sorting of forum drafts
  Modules/Forum/classes/GUI/class.ilForumThreadFormGUI.php
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#2983 Bugfix 28971 Sorting of forum drafts
  Modules/Forum/classes/GUI/class.ilForumThreadFormGUI.php
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3007 add geogebra suffix to file whitelist
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#3004 add geogebra suffix to file whitelist
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#3005 add geogebra suffix to file whitelist
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#3006 add geogebra suffix to file whitelist
  Services/Utilities/classes/class.ilFileUtils.php
Labels: improvement

#3027 Use boolean value for a boolean parameter
  Modules/Test/classes/class.ilTestLP.php
Labels: bugfix

#3028 Use boolean value for a boolean parameter
  Modules/Test/classes/class.ilTestLP.php
Labels: bugfix

#3029 Use boolean value for a boolean parameter
  Modules/Test/classes/class.ilTestLP.php
Labels: bugfix

#3030 Use boolean value for a boolean parameter
  Modules/Test/classes/class.ilTestLP.php
Labels: bugfix

#3031 Test/Export: Make ref_id injectable to avoid dependency to global …
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilObjTestGUI.php
Labels: improvement

#3021 Certificate: Fix warnings in unit tests
  Services/Certificate/classes/Placeholder/Description/class.ilCoursePlaceholderDescription.php
  Services/Certificate/classes/Placeholder/Description/interface.ilCertificatePlaceholderDescription.php
  Services/Certificate/test/ilCoursePlaceholderDescriptionTest.php
  Services/Certificate/test/ilDefaultPlaceholderDescriptionTest.php
  Services/Certificate/test/ilExercisePlaceholderDescriptionTest.php
  Services/Certificate/test/ilScormPlaceholderDescriptionTest.php
Labels: improvement
