Repository ILIAS-eLearning/ILIAS, pull requests merged in 2020-09, with the labels that each got.

#2857 (fix #28834) - some typos fixed in 'docs/configuration/secure.md'
  docs/configuration/secure.md
Labels: improvement

#2856 Error handling: Modify strings
  Services/Exceptions/classes/class.ilPlainTextHandler.php
Labels: bugfix, technical board

#2863 Modules/Chatroom/classes/gui/class.ilChatroomHistoryGUI.php: Typo fix…
  Modules/Chatroom/classes/gui/class.ilChatroomHistoryGUI.php
Labels: bugfix

#2866 BackgroundTasks/TupleValue: Fix wrong string concatenation
  src/BackgroundTasks/Implementation/Values/AggregationValues/TupleValue.php
Labels: bugfix

#2850 Database/Setup: password in config is optional
  Services/Database/classes/Setup/class.ilDatabaseServerIsConnectableObjective.php
  Services/Database/classes/Setup/class.ilDatabaseSetupConfig.php
Labels: improvement

#2861 Remove POST from SESSION
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Services/COPage/classes/class.ilCOPageGlobalTemplate.php
  Services/Init/classes/class.ilInitialisation.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  setup/classes/class.ilTemplate.php
Labels: bugfix

#2758 setup: add folder Customizing/global/plugins to classmap to include p…
  Customizing/global/plugins/.gitkeep
  composer.json
Labels: improvement

#2849 fixed 0028471: removed grid in print-styles
  src/UI/templates/default/Layout/standardpage.less
  templates/default/delos.css
Labels: bugfix

#2881 https://mantis.ilias.de/view.php?id=28874
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#2883 Forum Bugfix 28874
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#2882 Forum Bugfix 28874
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#2872 Auth. Administration: Fix captcha settings not being displayed
  Services/Authentication/classes/class.ilObjAuthSettingsGUI.php
Labels: bugfix

#2878 Changes linked script to https://
  Services/WebServices/FileManager/templates/default/tpl.fm_launch_ws.html
Labels: bugfix

#2877 BT-28776: Added missing language variables for session title
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2875 BT-25530: Added labels to calendar selection
  Services/Calendar/templates/default/tpl.cal_selection_block_content.html
Labels: bugfix

#2852 Fixed 0028807: Different login-behaviour from 5.4 and 6.0: a) Not log…
  Services/Init/classes/Provider/StartUpMetaBarProvider.php
Labels: bugfix

#2874 BT-18611: Added missing Screen-IDs for consultation hour GUIs
  Services/Calendar/classes/ConsultationHours/class.ilConsultationHoursGUI.php
Labels: bugfix

#2873 BT-28825: Fixed missing screen IDs for calendar views
  Services/Calendar/classes/class.ilCalendarPresentationGUI.php
Labels: bugfix

#2889 Update install.md
  docs/configuration/install.md
Labels: improvement, technical board

#2892 UI/Input/Radio - numeric values, fix #28862
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Input/Field/Radio/base.php
Labels: bugfix

#2895 Auth: Fix Mantis issue 28226
  Services/Authentication/classes/Frontend/class.ilAuthFrontend.php
Labels: bugfix

#2893 SOAP: Fix Mantis issue 28866
  webservice/soap/lib/nusoap.php
Labels: bugfix

#2891 fix #28855 - typecast title
  Services/Init/classes/class.ilStartUpGUI.php
Labels: bugfix

#2894 Feeds: Update snoopy HTTP client
  Services/Feeds/magpierss/extlib/Snoopy.class.inc
Labels: bugfix

#2835 Object Activation: Add constraint for start/end datetime
  Services/Object/classes/class.ilObjectActivationGUI.php
Labels: bugfix

#2794 Administration: show more git information (origin-url and branch added)
  Services/Administration/classes/class.ilGitInformation.php
Labels: improvement

#2888 UI/Input/Field/Numeric - allow empty strings in optional numeric inputs
  src/UI/Implementation/Component/Input/Field/Numeric.php
  src/UI/examples/Input/Field/Numeric/numeric_inputs.php
  tests/UI/Component/Input/Field/NumericInputTest.php
Labels: bugfix

#2887 UI/Input/Field/Numeric - allow empty strings in optional numeric inputs
  src/UI/Implementation/Component/Input/Field/Numeric.php
  src/UI/examples/Input/Field/Numeric/numeric_inputs.php
  tests/UI/Component/Input/Field/NumericInputTest.php
Labels: bugfix

#2868 Fix usage of $php_errormsg
  Modules/TestQuestionPool/classes/class.assFlashQuestion.php
Labels: bugfix

#2869 Test/Assessment: Fix Syntax error, unexpected '}' on line 38
  Services/AssessmentQuestion/classes/class.ilAsqQuestionResult.php
Labels: bugfix

#2876 LSO, AdminGUI (see #28840)
  Modules/LearningSequence/classes/GlobalSettings/LSGlobalSettings.php
  Modules/LearningSequence/classes/GlobalSettings/LSGlobalSettingsDB.php
  Modules/LearningSequence/classes/GlobalSettings/ilLSGlobalSettingsDB.php
  Modules/LearningSequence/classes/Player/LSControlBuilder.php
  Modules/LearningSequence/classes/class.ilObjLearningSequence.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdmin.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdminAccess.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdminGUI.php
  Modules/LearningSequence/module.xml
  Modules/LearningSequence/test/GlobalSettings/GlobalSettingsTest.php
  Modules/LearningSequence/test/LSControlBuilderTest.php
  Modules/LearningSequence/test/LSItems/LSItemTest.php
  Modules/LearningSequence/test/LearnerProgress/LSLearnerItemTest.php
  Modules/LearningSequence/test/ilModulesLearningSequenceSuite.php
  Services/Administration/classes/class.ilAdministrationGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  setup/sql/5_4_hotfixes.php
  templates/default/images/icon_lsos.svg
Labels: bugfix

#2885 LSO, AdminGUI - add Admin-Section, set interval for legacy LP polling
  Modules/LearningSequence/classes/GlobalSettings/LSGlobalSettings.php
  Modules/LearningSequence/classes/GlobalSettings/LSGlobalSettingsDB.php
  Modules/LearningSequence/classes/GlobalSettings/ilLSGlobalSettingsDB.php
  Modules/LearningSequence/classes/Player/LSControlBuilder.php
  Modules/LearningSequence/classes/Settings/class.ilObjLearningSequenceAdminGUI.php
  Modules/LearningSequence/classes/Settings/ilObjLearningSequenceAdminAccess.php
  Modules/LearningSequence/classes/class.ilLSLocalDI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdmin.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdminAccess.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceAdminGUI.php
  Modules/LearningSequence/test/GlobalSettings/GlobalSettingsTest.php
  Modules/LearningSequence/test/LSControlBuilderTest.php
  Modules/LearningSequence/test/ilModulesLearningSequenceSuite.php
  Services/Administration/GlobalScreen/classes/AdministrationMainBarProvider.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2780 UI/mainbar.js - split and roll up
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/templates/js/MainControls/dist/mainbar.js
  src/UI/templates/js/MainControls/mainbar.js
  src/UI/templates/js/MainControls/rollup.config.js
  src/UI/templates/js/MainControls/src/mainbar.js
  src/UI/templates/js/MainControls/src/mainbar.main.js
  src/UI/templates/js/MainControls/src/mainbar.model.js
  src/UI/templates/js/MainControls/src/mainbar.persistence.js
  src/UI/templates/js/MainControls/src/mainbar.renderer.js
  src/UI/templates/js/MainControls/test/mainbar.test.js
  test/mainbar.test.js
Labels: improvement

#2898 Fixed "target" evaluation for #28807
  Services/Init/classes/Provider/StartUpMetaBarProvider.php
Labels: bugfix

#2865 Hotfix/trunk/join implode
  Modules/Exercise/classes/class.ilExSubmission.php
  Modules/Scorm2004/classes/class.ilObjSCORM2004LearningModuleGUI.php
  Modules/Survey/Evaluation/class.ilSurveyEvaluationGUI.php
  Modules/Survey/Mail/FormMailCodesGUI.php
  Modules/Survey/Participants/class.ilSurveyParticipantsGUI.php
  Modules/Survey/classes/class.SurveySearch.php
  Modules/Survey/classes/class.ilObjSurvey.php
  Modules/SurveyQuestionPool/Phrases/class.ilSurveyPhrasesGUI.php
  Modules/SurveyQuestionPool/Questions/class.SurveyQuestionGUI.php
  Modules/Test/classes/class.assMarkSchema.php
  Modules/Test/classes/class.ilObjAssessmentFolder.php
  Modules/Test/classes/class.ilObjAssessmentFolderGUI.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestExport.php
  Modules/TestQuestionPool/classes/class.assErrorText.php
  Modules/TestQuestionPool/classes/class.assFlashQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assImagemapQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assJavaApplet.php
  Modules/TestQuestionPool/classes/class.assOrderingHorizontal.php
  Modules/TestQuestionPool/classes/class.assOrderingHorizontalGUI.php
  Modules/TestQuestionPool/classes/class.assQuestion.php
  Modules/TestQuestionPool/classes/class.ilMatchingPairWizardInputGUI.php
  Modules/TestQuestionPool/classes/export/qti12/class.assMatchingQuestionExport.php
  Modules/TestQuestionPool/classes/forms/class.ilAssMatchingPairCorrectionsInputGUI.php
  Services/Container/classes/class.ilContainerGUI.php
  Services/Database/classes/PDO/class.ilDBPdo.php
  Services/Database/classes/PDO/class.ilDBPdoPostgreSQL.php
  Services/Database/classes/class.ilDBGenerator.php
  Services/FileSystem/classes/class.ilFileSystemTableGUI.php
  Services/Form/classes/class.ilFlashFileInputGUI.php
  Services/Init/classes/class.ilPasswordAssistanceGUI.php
  Services/MetaData/classes/class.ilMDEditorGUI.php
  Services/Tracking/classes/class.ilLPXmlWriter.php
  webservice/soap/classes/class.ilSoapLearningProgressAdministration.php
Labels: bugfix

#2897 QuestionPool: Add possible fix for taxonomy selection
  Modules/TestQuestionPool/classes/class.assQuestionGUI.php
Labels: bugfix

#2906 `ilObjDefReader`: Quote `system` which a keyword in MySQL 8
  Services/Component/classes/Setup/class.ilObjDefReader.php
Labels: bugfix

#2846 UI: rules to fence direct Modal usage
  src/UI/Factory.php
Labels: kitchen sink

#2879 allow uuid creation from strings
  src/Data/UUID/Factory.php
  tests/Data/UuidTest.php
Labels: improvement

#2901 0028831: Learning Progress Performance -> SCORM
  Modules/ScormAicc/classes/class.ilScormLP.php
Labels: bugfix

#2750 Setup - FileSystem - call parent constructor in ilFileSystemComponent…
  Services/FileSystem/classes/Setup/class.ilFileSystemComponentDataDirectoryCreatedObjective.php
  src/Setup/DirectoryCreatedObjective.php
Labels: bugfix

#2916 Fix #28873, SPRG, Dash-overview does not count crss on root level
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDashboardViewGUI.php
  Modules/StudyProgramme/test/ilModulesStudyProgrammeSuite.php
  Modules/StudyProgramme/test/ilObjStudyProgrammeTest.php
  Modules/StudyProgramme/test/ilStudyProgrammeDashGUITest.php
Labels: bugfix

#2913 FIX #28876: SPRG, role-based Permissions
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#2911 Fix: #28888 - decouple focussing of main-container
  src/UI/templates/js/Page/stdpage.js
Labels: bugfix

#2917 fix 28814 - no language selector, if only one language is available
  Services/Init/classes/Provider/StartUpMetaBarProvider.php
Labels: bugfix

#2539 Init/Contexts: Extract special cases to concrete contexts when buildi…
  Services/Context/classes/class.ilContext.php
  Services/Context/classes/class.ilContextApacheSSO.php
  Services/Context/classes/class.ilContextCron.php
  Services/Context/classes/class.ilContextIcal.php
  Services/Context/classes/class.ilContextLTIProvider.php
  Services/Context/classes/class.ilContextRest.php
  Services/Context/classes/class.ilContextRss.php
  Services/Context/classes/class.ilContextRssAuth.php
  Services/Context/classes/class.ilContextSaml.php
  Services/Context/classes/class.ilContextScorm.php
  Services/Context/classes/class.ilContextSessionReminder.php
  Services/Context/classes/class.ilContextShibboleth.php
  Services/Context/classes/class.ilContextSoap.php
  Services/Context/classes/class.ilContextSoapNoAuth.php
  Services/Context/classes/class.ilContextSoapWithoutClient.php
  Services/Context/classes/class.ilContextUnitTest.php
  Services/Context/classes/class.ilContextWAC.php
  Services/Context/classes/class.ilContextWeb.php
  Services/Context/classes/class.ilContextWebdav.php
  Services/Context/interfaces/interface.ilContextTemplate.php
  Services/Init/classes/class.ilInitialisation.php
Labels: improvement
