Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-01, with the labels that each got.

#3053 NotificationCenter: Fix Mantis issue 29500
  Services/Notifications/classes/Provider/NotificationCenterProvider.php
Labels: bugfix

#3055 SCORM: normalize classname of ilSCORM13PlayerGUI
  Modules/Scorm2004/classes/class.ilSCORM13PlayerGUI.php
  Modules/ScormAicc/classes/class.ilSAHSPresentationGUI.php
  Modules/ScormAicc/classes/class.ilSCORMOfflineMode.php
  Modules/ScormAicc/classes/class.ilSCORMOfflineModeGUI.php
  Services/Style/Content/classes/class.ilObjStyleSheetGUI.php
  Services/UICore/classes/Setup/class.ilCtrlStructureReader.php
  Services/UICore/test/ilCtrlStructureReaderTest.php
Labels: bugfix, improvement

#3058 Increase user login field to 255 characters
  Services/User/classes/class.ilUserProfile.php
  setup/sql/5_4_hotfixes.php
Labels: bugfix

#3062 fixed 0029641: Consultation Hours Error: colon vs ctrl regex
  Services/Calendar/classes/ConsultationHours/class.ilConsultationHoursGUI.php
  Services/Certificate/classes/class.ilCertificateGUI.php
  setup/sql/7_hotfixes.php
Labels: bugfix

#3054 Add Documentation for Expert Groups
  docs/development/expert-groups.md
Labels: improvement, technical board

#3072 BT-28951: Added aria label for main menu search form input
  Services/Search/classes/class.ilMainMenuSearchGUI.php
  Services/Search/templates/default/tpl.main_menu_search.html
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3073 UI/MainBar: give tool-button a more striking color
  src/UI/templates/default/MainControls/mainbar.less
  templates/default/less/variables.less
Labels: improvement

#3071 BT-28948: Replaced 'Go' in Searchbar with language variable
  Services/Search/classes/class.ilMainMenuSearchGUI.php
  Services/Search/templates/default/tpl.main_menu_search.html
Labels: bugfix

#3078 BT-13407: Added Aria Label to search dropdown
  Services/Search/classes/class.ilMainMenuSearchGUI.php
  Services/Search/templates/default/tpl.main_menu_search.html
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#2994 Setup: Fix proxy port in HttpMetricsObjective
  Services/Http/classes/Setup/class.ilHttpMetricsCollectedObjective.php
Labels: bugfix

#3090 BT-25583: Added clearer wording and links to accessibility administration
  Services/Authentication/classes/class.ilObjAuthSettingsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3077 fixed 0029713: Exercise Import fails
  Modules/Exercise/classes/class.ilObjExerciseGUI.php
Labels: bugfix

#2993 Component/Setup: use generalized objectives for plugin updates (#29169)
  Services/Component/classes/Setup/class.ilComponentActivatePluginsObjective.php
  Services/Component/classes/Setup/class.ilComponentPluginAdminInitObjective.php
  Services/Component/classes/Setup/class.ilComponentUpdatePluginObjective.php
Labels: bugfix

#3085 6/sprg/fixes
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeIndividualPlanGUI.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserAssignment.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserAssignmentDB.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserProgress.php
  Modules/StudyProgramme/classes/model/Assignments/class.ilStudyProgrammeAssignment.php
  Modules/StudyProgramme/classes/model/Progress/class.ilStudyProgrammeProgress.php
  Modules/StudyProgramme/test/model/Progress/ilStudyProgrammeProgressTest.php
Labels: bugfix

#3083 Add Composer 2 Support for ILIAS 7 (with rebuilt composer.lock)
  .travis.yml
  composer.lock
Labels: improvement

#3084 Add Composer 2 Support for trunk (with rebuilt composer.lock)
  .travis.yml
  composer.lock
Labels: improvement

#3087 UI Component Item, Listing Panel: Fixing Title, see #29616
  src/UI/templates/default/Item/item.less
  src/UI/templates/default/Item/tpl.item_standard.html
  templates/default/delos.css
  tests/UI/Component/Item/ItemGroupTest.php
  tests/UI/Component/Item/ItemTest.php
  tests/UI/Component/Panel/PanelListingTest.php
  tests/UI/Component/Panel/PanelSecondaryListingTest.php
Labels: bugfix, improvement, kitchen sink

#3114 fixed https://mantis.ilias.de/view.php?id=29757
  src/GlobalScreen/Scope/MainMenu/Factory/Item/RepositoryLink.php
Labels: bugfix

#3061 fixed required php-soap
  docs/configuration/install.md
Labels: bugfix, improvement

#3102 Setup: 29723 implement access to execute method from php side
  composer.json
  src/Setup/CLI/StatusCommand.php
  tests/Setup/CLI/StatusCommandTest.php
Labels: improvement

#3126 fixed #27776: Missing Form Label in Permalink in Footer
  src/UI/templates/default/MainControls/tpl.footer.html
  tests/UI/Component/MainControls/FooterTest.php
Labels: bugfix
