Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-09, with the labels that each got.

#3591 Bugfix: Missing direct notification for new posts
  Modules/Forum/classes/Notification/class.ilForumNotificationEvents.php
  Modules/Forum/classes/Notification/interface.ilForumNotificationEvents.php
  Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
Labels: bugfix

#3597 Test: Remove unused methods (certificate related)
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilObjTestAccess.php
Labels: improvement

#3598 Use bool false instead of empty string
  Services/Cron/classes/class.ilCronManager.php
Labels: bugfix

#3580 UI/Input: 31271, render duration group before generic group
  src/UI/Implementation/Component/Input/Field/Renderer.php
Labels: bugfix

#3601 rename ...PlaceHolder... to ...Placeholder...
  Modules/CmiXapi/classes/Certificate/class.ilCmiXapiPlaceholderValues.php
  Modules/LTIConsumer/classes/Certificate/class.ilLTIConsumerPlaceholderValues.php
  Services/Certificate/classes/Cron/class.ilCertificateTypeClassMap.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/classes/Placeholder/Values/class.ilCoursePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilExercisePlaceHolderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilScormPlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilStudyProgrammePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilTestPlaceHolderValues.php
  Services/Certificate/test/ilCertificateTypeClassMapTest.php
  Services/Certificate/test/ilExercisePlaceHolderValuesTest.php
  Services/Certificate/test/ilTestPlaceHolderValuesTest.php
  Services/Mail/classes/Error/class.ilMailError.php
  Services/Mail/classes/Error/class.ilMailErrorFormatter.php
  setup/sql/7_hotfixes.php
Labels: bugfix

#3602 rename ...PlaceHolder... to ...Placeholder...
  Modules/CmiXapi/classes/Certificate/class.ilCmiXapiPlaceholderValues.php
  Modules/LTIConsumer/classes/Certificate/class.ilLTIConsumerPlaceholderValues.php
  Services/Certificate/classes/Cron/class.ilCertificateTypeClassMap.php
  Services/Certificate/classes/Gui/class.ilCertificateGUIFactory.php
  Services/Certificate/classes/Placeholder/Values/class.ilCoursePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilExercisePlaceHolderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilScormPlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilStudyProgrammePlaceholderValues.php
  Services/Certificate/classes/Placeholder/Values/class.ilTestPlaceHolderValues.php
  Services/Certificate/test/ilCertificateTypeClassMapTest.php
  Services/Certificate/test/ilExercisePlaceHolderValuesTest.php
  Services/Certificate/test/ilTestPlaceHolderValuesTest.php
  Services/Mail/classes/Error/class.ilMailError.php
  Services/Mail/classes/Error/class.ilMailErrorFormatter.php
  setup/sql/6_hotfixes.php
Labels: bugfix

#3594 Bugfix 31290: regression in AreaInput introduced with tinymce5
  Services/Form/classes/class.ilTextAreaInputGUI.php
Labels: bugfix

#3605 PRG: hotfix 3132 Dashboard, not relevant for 7
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDashboardViewGUI.php
Labels: bugfix

#3608 Throw exception if file does not exist instead of returning null
  Services/WebServices/RPC/lib/src/de/ilias/services/lucene/index/file/path/FileObjectPathCreator7.java
Labels: improvement

#3604 PRG: 31316, do not add members automatically to inactive programmes
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
Labels: bugfix

#3611 SETUP: fix 31311, increase field size for updatesteps start/finished
  Services/Database/classes/Setup/ilDatabaseSetupStepsUpdateSteps.php
  Services/Database/classes/Setup/ilDatabaseUpdateAgent.php
Labels: bugfix

#3570 LearningSequence: Fix LP determination for unsupported objects
  Modules/LearningSequence/classes/LearnerProgress/class.ilLearnerProgressDB.php
  Modules/LearningSequence/classes/class.ilLSLocalDI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequence.php
Labels: bugfix

#3619 GlobalScreen: Fix symbol decorator trait (Mantis issue 31313)
  src/GlobalScreen/Scope/MainMenu/Factory/SymbolDecoratorTrait.php
Labels: bugfix

#3599 GlobalCache/Setup: Expose status of global cache service
  Services/GlobalCache/classes/Setup/class.ilGlobalCacheMetricsCollectedObjective.php
Labels: improvement

#3624 PHP 8 Fix: Undefined variable $ref_ids in ilUtil
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix

#3572 BT-31095: Added legend and css rules for it to search fieldset
  Services/Search/templates/default/tpl.main_menu_search.html
  templates/default/delos.css
  templates/default/less/Services/Search/delos.less
Labels: bugfix

#3628 Chatroom: cast settings['log'] to string
  Modules/Chatroom/classes/Setup/class.ilChatroomMetricsCollectedObjective.php
Labels: improvement

#3627 Database: 31311 increase field size in correct script
  Modules/Test/test/ilTestPlayerFixedQuestionSetGUITest.php
  Modules/Test/test/toolbars/ilTestSkillEvaluationToolbarGUITest.php
  Services/Database/classes/Setup/ilDatabaseSetupStepsUpdateSteps.php
  Services/Database/classes/Setup/ilDatabaseUpdateAgent.php
  setup/sql/dbupdate_05.php
Labels: bugfix

#3632 Search, Duplicate attribute type in Search Form Button
  Services/Search/templates/default/tpl.main_menu_search.html
Labels: bugfix

#3635 Fixes: 0031373: Pseudonymous forum reveals user in mail notifications…
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#3634 Fixes: 0031373: Pseudonymous forum reveals user in mail notifications…
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#3636 Fixes: 0031373: Pseudonymous forum reveals user in mail notifications…
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
Labels: bugfix

#3639 Fixes: 0031377: Verständlichkeit der 'Top-Thema-Sortierung'
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#3638 Fixes: 0031377: Verständlichkeit der 'Top-Thema-Sortierung'
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#3637 RTE: PHP 8
  Services/AdvancedEditing/classes/class.ilObjAdvancedEditing.php
  Services/RTE/classes/class.ilRTE.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/RTE/classes/class.ilTinyMCE.php
  Services/RTE/test/ilRTEBaseTest.php
  Services/RTE/test/ilTinyMCETest.php
Labels: improvement

#3629 UI Components, Metabar, Fix for 31366 and 31367
  src/UI/templates/js/Item/notification.js
  src/UI/templates/js/MainControls/metabar.js
Labels: bugfix, kitchen sink

#3631 UI Components, fix for Invalid href in Close Button Glyph, see #31369
  src/UI/Implementation/Component/Symbol/Glyph/ButtonContextRenderer.php
  src/UI/Implementation/Component/Symbol/Glyph/Renderer.php
  src/UI/templates/default/Symbol/tpl.glyph.context_btn.html
  tests/UI/Component/MainControls/MainBarTest.php
Labels: bugfix, kitchen sink

#3583 Fix TinyMCE active controll
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
  Modules/Test/templates/default/tpl.il_as_tst_correct_solution_output.html
Labels: bugfix

#3584 Fix TinyMCE active controll and TinyMCE5 styling
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
  Modules/Test/templates/default/tpl.il_as_tst_correct_solution_output.html
Labels: bugfix

#3643 Learning Progress Performance -> SCORM
  Modules/ScormAicc/classes/class.ilScormLP.php
Labels: bugfix

#3645 just some small corrections to ilias_de.lang ...
  lang/ilias_de.lang
Labels: improvement

#3612 WebAccessChecker Fix login page detection (Mantis 31338)
  Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
Labels: bugfix

#3642 WAC: Fix issue with denied requests for resources when requesting log…
  Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
Labels: bugfix

#3649 VirusScanner: Remove expensive file_exists(), is_readable() is suffic…
  Services/VirusScanner/classes/class.ilVirusScannerICapClient.php
  Services/VirusScanner/classes/class.ilVirusScannerICapRemoteAvClient.php
Labels: improvement

#3654 Setup/ConfigReader: Remove obsolete file_exists() and apply PSR-2
  src/Setup/CLI/ConfigReader.php
Labels: improvement

#3652 Tests/PHPUnit: Use XML config (instead of arguments) / Be more strict
  .gitignore
  CI/PHPUnit/phpunit.xml
  CI/PHPUnit/run_tests.sh
Labels: improvement

#3653 Test&Assessment: Fix risky tests
  Modules/Test/test/confirmations/ilTestSettingsChangeConfirmationGUITest.php
  Modules/Test/test/ilTestBaseTestCase.php
Labels: bugfix

#3650 WorkflowEngine: Remove expensive file_exists()
  Services/WorkflowEngine/classes/administration/class.ilWorkflowEngineDefinitionsGUI.php
  Services/WorkflowEngine/classes/class.ilWorkflowEngine.php
  Services/WorkflowEngine/classes/extractors/class.ilExtractorFactory.php
  Services/WorkflowEngine/classes/utils/class.ilWorkflowDbHelper.php
  Services/WorkflowEngine/classes/workflows/class.ilBaseWorkflow.php
Labels: improvement

#3657 Database/PDO Auth: Remove unused PDO authentication interface impleme…
  Services/Authentication/classes/PDO/class.ilPDOAuthentication.php
  Services/Authentication/classes/PDO/interface.ilAuthPDOInterface.php
Labels: improvement
