Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-12, with the labels that each got.

#3491 SystemFolder: id can only be used once
  Services/Administration/service.xml
Labels: improvement

#3776 UI/Mainbar: trigger in_view for fully engaged path only, store loaded…
  src/UI/templates/js/MainControls/dist/mainbar.js
  src/UI/templates/js/MainControls/src/mainbar.model.js
  src/UI/templates/js/MainControls/src/mainbar.renderer.js
  src/UI/templates/js/MainControls/test/mainbar.test.js
Labels: bugfix

#3808 FileUpload/JS: load JS and template parts separatedly (fixes 0031568)
  Services/FileUpload/classes/class.ilFileUploadGUI.php
  Services/FileUpload/templates/default/tpl.fileupload_shared.html
  Services/FileUpload/templates/default/tpl.fileupload_shared.js
Labels: bugfix

#3799 ILIAS 8: Mail: Add filter to exclude system notifications
  Services/Mail/classes/class.ilMailBoxQuery.php
  Services/Mail/classes/class.ilMailFolderTableGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#3801 BUGFIX [31661]: Contrast Issues: Who-is-online text-color on background
  templates/default/delos.css
  templates/default/less/Services/Awareness/delos.less
Labels: bugfix

#3797 Refinery: include GreaterThanOrEqual to Refinery -> Integer. Add test…
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAssessmentSettings.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Refinery/Integer/GreaterThanOrEqual.php
  src/Refinery/Integer/Group.php
  tests/Refinery/Integer/Constraints/GreaterThanOrEqualConstraintTest.php
  tests/Refinery/Integer/GroupTest.php
Labels: improvement

#3810 [PHP8] ilTree: Add type casts to match return type
  Services/Tree/classes/class.ilTree.php
Labels: bugfix

#3780 Setup: add composer dependency Seld\JsonLint and use it in ConfigReader
  composer.json
  composer.lock
  setup/cli.php
  src/Setup/CLI/ConfigReader.php
  tests/Setup/CLI/ConfigReaderTest.php
Labels: improvement

#3811 Update ilias_hu.lang
  lang/ilias_hu.lang
Labels: improvement

#3765 Refinery Randomization - Approach with Side Effects
  Modules/Test/classes/class.ilObjTestGUI.php
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
  Modules/Test/test/ilTestBaseTestCase.php
  Modules/Test/test/ilTestPlayerDynamicQuestionSetGUITest.php
  Modules/Test/test/ilTestPlayerFactoryTest.php
  Modules/Test/test/ilTestPlayerFixedQuestionSetGUITest.php
  Modules/Test/test/ilTestPlayerRandomQuestionSetGUITest.php
  Modules/TestQuestionPool/classes/class.assClozeGap.php
  Modules/TestQuestionPool/classes/class.assClozeTest.php
  Modules/TestQuestionPool/classes/class.assClozeTestGUI.php
  Modules/TestQuestionPool/classes/class.assKprimChoiceGUI.php
  Modules/TestQuestionPool/classes/class.assMatchingQuestion.php
  Modules/TestQuestionPool/classes/class.assMatchingQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assMultipleChoiceGUI.php
  Modules/TestQuestionPool/classes/class.assOrderingHorizontal.php
  Modules/TestQuestionPool/classes/class.assOrderingQuestion.php
  Modules/TestQuestionPool/classes/class.assQuestion.php
  Modules/TestQuestionPool/classes/class.assSingleChoiceGUI.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionPreviewGUI.php
  Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php
  Modules/TestQuestionPool/classes/export/qti12/class.assClozeTestExport.php
  Modules/TestQuestionPool/classes/feedback/class.ilAssClozeTestFeedback.php
  Modules/TestQuestionPool/classes/questions/LogicalAnswerCompare/ilAssLacCompositeValidator.php
  Modules/TestQuestionPool/test/assBaseTestCase.php
  Modules/TestQuestionPool/test/assClozeGapTest.php
  Modules/TestQuestionPool/test/assClozeSelectGapTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Refinery/DeriveApplyToFromTransform.php
  src/Refinery/Factory.php
  src/Refinery/IdentityTransformation.php
  src/Refinery/Random/Group.php
  src/Refinery/Random/Seed/GivenSeed.php
  src/Refinery/Random/Seed/RandomSeed.php
  src/Refinery/Random/Seed/Seed.php
  src/Refinery/Random/Transformation/ShuffleTransformation.php
  tests/Refinery/IdentityTransformationTest.php
  tests/Refinery/Random/GroupTest.php
  tests/Refinery/Random/Transformation/ShuffleTransformationTest.php
Labels: improvement, technical board

#3742 fixed #31401: Special Charactors in Tests don`t work
  Services/UIComponent/CharSelector/js/ilCharSelector.js
Labels: bugfix

#3805 Release 5.4 Bug Fixes Formula Question
  Modules/TestQuestionPool/classes/class.assFormulaQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
Labels: bugfix

#3814 Fix for mantis #31695
  Modules/TestQuestionPool/classes/class.assFileUpload.php
Labels: bugfix

#3813 fixed bug #31511: Detail level of block News is not the highest as de…
  Services/News/classes/class.ilNewsForContextBlockGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/templates/default/Item/item.less
  templates/default/delos.css
Labels: bugfix, kitchen sink

#3777 UI-Framework: use request- and post-wrapper where possible
  src/UI/examples/Dropzone/File/Standard/base.php
  src/UI/examples/Dropzone/File/Standard/server_side_error.php
  src/UI/examples/Dropzone/File/Standard/with_custom_file_metadata.php
  src/UI/examples/Dropzone/File/Standard/with_restricted_file_types_and_custom_message.php
  src/UI/examples/Dropzone/File/Standard/with_usage_in_legacy_form.php
  src/UI/examples/Dropzone/File/Wrapper/base.php
  src/UI/examples/Dropzone/File/Wrapper/restrict_max_files_and_file_size.php
  src/UI/examples/Item/Notification/closable.php
  src/UI/examples/Item/Notification/include_aggregates.php
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/examples/Layout/Page/Standard/ui_mainbar.php
  src/UI/examples/MainControls/Footer/footer.php
  src/UI/examples/MainControls/Footer/footer_with_modals.php
  src/UI/examples/MainControls/MetaBar/base_metabar.php
  src/UI/examples/MainControls/MetaBar/extended_example_for_developers.php
  src/UI/examples/MainControls/Slate/Notification/standard.php
  src/UI/examples/Modal/Interruptive/show_modal_on_button_click.php
  src/UI/examples/Modal/Interruptive/show_modal_on_button_click_async_rendered.php
  src/UI/examples/Modal/RoundTrip/show_form_in_modal.php
  src/UI/examples/Modal/RoundTrip/show_multi_step_modal.php
  src/UI/examples/Panel/Secondary/Legacy/with_viewcontrollers.php
  src/UI/examples/Panel/Secondary/Listing/with_viewcontrollers.php
  src/UI/examples/Panel/Standard/with_view_controls.php
  src/UI/examples/Popover/Standard/show_popover_with_async_loaded_content.php
  src/UI/examples/Popover/Standard/show_popover_with_dynamic_changing_content.php
  src/UI/examples/Tree/Expandable/expandable_async_repo.php
  src/UI/examples/ViewControl/Mode/base.php
  src/UI/examples/ViewControl/Pagination/base.php
  src/UI/examples/ViewControl/Pagination/many_pages.php
  src/UI/examples/ViewControl/Pagination/many_pages_dropdown.php
  src/UI/examples/ViewControl/Section/base.php
  src/UI/examples/ViewControl/Sortation/_Base.php
  src/UI/examples/ViewControl/Sortation/async.php
Labels: improvement

#3820 File: Fix missing 'use' statements
  Modules/File/classes/class.ilFileXMLParser.php
Labels: bugfix

#3783 ILIAS 8: Centralizing Online/Offline status - Step 2 (frm, copa)
  Modules/ContentPage/classes/Setup/class.ilContentPageSetupAgent.php
  Modules/ContentPage/classes/Setup/class.ilContentPageUpdateSteps.php
  Modules/ContentPage/classes/class.ilObjContentPage.php
  Modules/ContentPage/classes/class.ilObjContentPageGUI.php
  Modules/ContentPage/classes/class.ilObjContentPageListGUI.php
  Modules/ContentPage/module.xml
  Modules/Forum/classes/Setup/class.ilForumDatabaseUpdateSteps.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumListGUI.php
  Modules/Forum/module.xml
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#3819 BT-31500: merged missing "deleted_by".
  Services/Object/classes/class.ilObject.php
  Services/Object/classes/class.ilObject2.php
  Services/Object/test/ilObjectTest.php
  Services/Repository/classes/class.ilRepUtil.php
  Services/Tree/classes/class.ilTree.php
  webservice/soap/classes/class.ilSoapCourseAdministration.php
  webservice/soap/classes/class.ilSoapObjectAdministration.php
Labels: bugfix

#3821 BUGFIX [31661]: Insufficient Contrast in Star Ratings
  templates/default/images/icon_rate_0.svg
  templates/default/images/icon_rate_1.svg
  templates/default/images/icon_rate_10.svg
  templates/default/images/icon_rate_2.svg
  templates/default/images/icon_rate_3.svg
  templates/default/images/icon_rate_4.svg
  templates/default/images/icon_rate_5.svg
  templates/default/images/icon_rate_6.svg
  templates/default/images/icon_rate_7.svg
  templates/default/images/icon_rate_8.svg
  templates/default/images/icon_rate_9.svg
  templates/default/images/icon_rate_off.svg
  templates/default/images/icon_rate_on.svg
  templates/default/images/icon_rate_on_user.svg
Labels: bugfix

#3824 KioskMode: improvements to PHP8
  Services/KioskMode/classes/class.ilKioskModeService.php
  Services/KioskMode/classes/class.ilKioskModeView.php
  Services/KioskMode/test/class.ilDummyKioskModeView.php
  Services/KioskMode/test/ilKioskModeServiceTest.php
  Services/KioskMode/test/ilServicesKioskModeSuite.php
Labels: improvement

#3748 Proposal/8/headers in files
  CI/Rector/ChangeLicenseHeader.php
  CI/Rector/rector.php
Labels: improvement

#3826 Defining additional competences
  docs/development/maintenance.md
Labels: improvement, technical board

#3310 BT-29591: Fixed permissions for administration auth / self registrations
  Services/AuthShibboleth/classes/class.ilAuthShibbolethSettingsGUI.php
  Services/Authentication/classes/class.ilObjAuthSettingsGUI.php
Labels: bugfix

#3823 Refinery: add new method for 'less than or equal' integer inputs. Add…
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Refinery/Integer/Group.php
  src/Refinery/Integer/LessThanOrEqual.php
  tests/Refinery/Integer/Constraints/LessThanOrEqualConstraintTest.php
  tests/Refinery/Integer/GroupTest.php
Labels: improvement

#3833 Refinery: add typehints to functions for integer constraints.
  src/Refinery/Integer/GreaterThan.php
  src/Refinery/Integer/GreaterThanOrEqual.php
  src/Refinery/Integer/LessThan.php
Labels: improvement

#3834 StudyProgamme: harmonize the usage of the integer constraints in settings
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAutoMailSettings.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDeadlineSettings.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeValidityOfAchievedQualificationSettings.php
Labels: improvement

#3846 fixed #31747: ILIAS Install/Update broken Identifier ilAppEventHandle…
  Services/Tree/classes/class.ilMaterializedPathTree.php
  Services/Tree/classes/class.ilTree.php
Labels: bugfix

#3787 UI Components: Interface for Item/Shy
  src/UI/Component/Item/Factory.php
  src/UI/Component/Item/Item.php
  src/UI/Component/Item/Notification.php
  src/UI/Component/Item/Shy.php
  src/UI/Component/Item/Standard.php
  src/UI/Implementation/Component/Item/Factory.php
  src/UI/Implementation/Component/Item/Notification.php
  src/UI/Implementation/Component/Item/Standard.php
  src/UI/examples/Item/Shy/base.php
  src/UI/examples/Item/Shy/with_close.php
  src/UI/examples/Item/Shy/with_description.php
  src/UI/examples/Item/Shy/with_lead_icon.php
  src/UI/examples/Item/Shy/with_long_description.php
  src/UI/examples/Item/Shy/with_properties.php
Labels: kitchen sink, improvement

#3788 LSO: constant LP polling, bypass player GUIs
  Modules/LearningSequence/classes/Player/LSControlBuilder.php
  Modules/LearningSequence/classes/Player/class.ilLegacyKioskModeView.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLPPollingGUI.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Modules/LearningSequence/classes/class.ilLSLocalDI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  Modules/LearningSequence/test/LSControlBuilderTest.php
Labels: improvement

#3789 Setup: adjust init environment in ilComponentUpdatePluginObjective
  Services/Component/classes/Setup/class.ilComponentUpdatePluginObjective.php
Labels: improvement

#3818 UI Form: 31701, display error-message in form
  src/UI/Component/Input/Container/Form/Form.php
  src/UI/Implementation/Component/Input/Container/Form/Form.php
  src/UI/Implementation/Component/Input/Container/Form/Renderer.php
  src/UI/templates/default/Input/tpl.standard.html
  tests/UI/Component/Input/Container/Form/StandardFormTest.php
Labels: bugfix

#3840 Improve error propagation in ilServer (release_5-4)
  Services/WebServices/RPC/lib/src/de/ilias/ilServer.java
Labels: improvement

#3853 Bux fix php8
  Services/Language/classes/Setup/class.ilSetupLanguage.php
  Services/Language/classes/class.ilLanguage.php
  Services/Language/classes/class.ilLanguageExtTableGUI.php
  Services/Language/classes/class.ilLanguageTableGUI.php
  Services/Language/classes/class.ilObjLanguageExtGUI.php
  Services/Language/classes/class.ilObjLanguageFolderGUI.php
  tests/Refinery/TestCase.php
  tests/UI/Base.php
  tests/UI/Component/Input/Field/LinkInputTest.php
Labels: bugfix

#3831 Maps: improvements to PHP8
  Services/Maps/classes/class.ilGoogleMapGUI.php
  Services/Maps/classes/class.ilMapGUI.php
  Services/Maps/classes/class.ilMapUtil.php
  Services/Maps/classes/class.ilOpenLayersMapGUI.php
  Services/Maps/js/ServiceGoogleMaps.js
  Services/Maps/js/dist/ServiceOpenLayers.js
  Services/Maps/js/src/ilOl.js
  Services/Maps/templates/default/tpl.google_map.html
  Services/Maps/templates/default/tpl.google_map.js
  Services/Maps/templates/default/tpl.openlayers_map.html
  Services/Maps/templates/default/tpl.openlayers_map.js
Labels: bugfix

#3726 UI: Mainbar/Drilldown - use DD for Mainmenu Administration
  Services/MainMenu/classes/Provider/StandardTopItemsProvider.php
  src/GlobalScreen/README.md
  src/GlobalScreen/Scope/MainMenu/Collector/MainMenuMainCollector.php
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/BaseTypeRenderer.php
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/TopParentItemDrilldownRenderer.php
  src/GlobalScreen/Scope/MainMenu/Factory/AbstractBaseItem.php
  src/GlobalScreen/Scope/MainMenu/Factory/isItem.php
  src/UI/Component/MainControls/Slate/Drilldown.php
  src/UI/Component/MainControls/Slate/Factory.php
  src/UI/Component/Menu/Factory.php
  src/UI/Implementation/Component/MainControls/Slate/Drilldown.php
  src/UI/Implementation/Component/MainControls/Slate/Factory.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/Implementation/Component/Menu/Drilldown.php
  src/UI/Implementation/Component/Menu/Renderer.php
  src/UI/examples/MainControls/Slate/Drilldown/drilldownslate.php
  src/UI/templates/js/Menu/dist/drilldown.js
  src/UI/templates/js/Menu/src/drilldown.instances.js
  src/UI/templates/js/Menu/src/drilldown.js
  src/UI/templates/js/Menu/src/drilldown.main.js
  src/UI/templates/js/Menu/src/drilldown.mapping.js
  src/UI/templates/js/Menu/src/drilldown.model.js
  src/UI/templates/js/Menu/src/drilldown.persistence.js
  tests/UI/Client/Menu/Drilldown/drilldown.test.js
  tests/UI/Component/MainControls/Slate/DrilldownSlateTest.php
  tests/UI/Component/Menu/Drilldown/DrilldownTest.php
  tests/UI/Component/Menu/Drilldown/drilldown_test.html
Labels: improvement

#3640 Enabled Strict Mode per Default and fixed field order_nr of copg_pc_def
  Services/COPage/classes/Setup/class.ilCOPageDBUpdateSteps.php
  Services/Component/classes/Setup/class.ilComponentDefinitionsStoredObjective.php
  Services/Database/classes/PDO/class.ilDBPdoMySQL.php
Labels: bugfix

#3827 Authentication/Login Page/SAML: Add placeholder support for SAML logi…
  Services/COPage/classes/class.ilPCLoginPageElement.php
  Services/Init/classes/class.ilStartUpGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3837 Update Dependencies after Release v7.5
  composer.lock
Labels: technical board, dependencies

#3825 Update Dependencies after Release v6.13
  composer.lock
Labels: technical board, dependencies

#3847 Setup/Component: add objective to ensure plugin language refresh on cli update command
  Services/Component/classes/Setup/class.ilComponentPluginLanguageUpdatedObjective.php
  Services/Component/classes/Setup/class.ilPluginDefaultAgent.php
Labels: bugfix

#3860 UI Components, Unit Tests, add some helper Class for Dependency Injection
  tests/UI/UITestHelper.php
  tests/UI/UITestHelperTest.php
Labels: improvement

#3858 Set return-type to what was mentioned in the original comment.
  Services/Language/classes/Setup/class.ilSetupLanguage.php
Labels: improvement

#3863 Services/Cron: refresh job data for plugin jobs as well (#18411)
  Services/Cron/classes/class.ilCronManager.php
Labels: bugfix

#3866 UI Components Text Input, render "0"
  src/UI/Implementation/Component/Input/Field/Renderer.php
  tests/UI/Component/Input/Field/TextInputTest.php
Labels: bugfix
