Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-04, with the labels that each got.

#3283 TestQuestionPool: Fix formula question (54x)
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
Labels: bugfix

#3282 TestQuestionPool: Fix formula question (6x)
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
Labels: bugfix

#3281 TestQuestionPool: Fix formula question (7x)
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
Labels: bugfix

#3280 TestQuestionPool: Fix formula question (trunk)
  Modules/TestQuestionPool/classes/class.assFormulaQuestionResult.php
Labels: bugfix

#3264 Container/GlobalScreen: Fix Mantis issue 30438
  Modules/SystemFolder/classes/class.ilObjSystemFolder.php
  Services/Container/classes/class.ilContainerGUI.php
Labels: bugfix

#3269 LearningModule: Fix undefined constant (Mantis issue 28377)
  Modules/LearningModule/classes/class.ilLMPresentationGUI.php
Labels: bugfix

#3272 Legacy Forms, UI Components Forms: Fix of #28696
  Services/Form/templates/default/tpl.property_form.html
  src/UI/templates/default/Input/input.less
  src/UI/templates/default/Input/tpl.context_form.html
  templates/default/delos.css
  templates/default/less/Services/Form/delos.less
  tests/UI/Component/Input/Field/CheckboxInputTest.php
  tests/UI/Component/Input/Field/FileInputTest.php
  tests/UI/Component/Input/Field/NumericInputTest.php
  tests/UI/Component/Input/Field/PasswordInputTest.php
  tests/UI/Component/Input/Field/TagInputTest.php
  tests/UI/Component/Input/Field/TextInputTest.php
  tests/UI/Component/Input/Field/TextareaTest.php
Labels: bugfix, kitchen sink

#3255 LSO 29944: encode data from tiny to prevent lost text areas
  Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLParser.php
  Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLWriter.php
Labels: bugfix

#3289 Fix 30513: Fatal error because of access level
  Services/Certificate/classes/class.ilObjCertificateSettingsGUI.php
Labels: bugfix

#3284 Fix Scrolling in TinyMCE
  Services/RTE/classes/class.ilTinyMCE.php
  Services/RTE/css/tiny.css
  templates/default/delos.css
  templates/default/delos.less
Labels: bugfix

#3290 0030439: Option 'Page translation enabled' can't be disabled
  Services/Language/classes/class.ilObjLanguageAccess.php
Labels: bugfix

#3288 Search: Fix A11Y issue (for wiki and forum)
  Services/Search/classes/class.ilRepositoryObjectSearchBlockGUI.php
  Services/Search/templates/default/tpl.search_search_block.html
Labels: bugfix

#3217 fix typo
  Services/Search/classes/Provider/SearchMetaBarProvider.php
Labels: improvement

#3293 Standard Layout, Introduce Text Direction and Rendering Tests, see: #30532 and #29426
  src/UI/Component/Layout/Page/Standard.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Component/Layout/Page/Standard.php
  src/UI/templates/default/Layout/tpl.standardpage.html
  tests/UI/Base.php
  tests/UI/Component/Input/Field/FileInputTest.php
  tests/UI/Component/Layout/Page/StandardPageTest.php
  tests/UI/Component/MainControls/SystemInfoTest.php
Labels: bugfix, improvement, kitchen sink

#3300 CI: Implemented tests on push, changed badge on readme
  .github/workflows/checks.yml
  README.md
Labels: improvement

#3305 CI: Updated badge for README.md
  README.md
Labels: bugfix

#3307 CI: Updated badge for README.md
  README.md
Labels: bugfix

#3306 CI: Updated badge for README.md
  README.md
Labels: bugfix

#3316 BT-29587: Added permission check to actions in system check
  Services/SystemCheck/classes/class.ilSCTaskTableGUI.php
Labels: bugfix

#3304 BT-29427: Changed language variable in mobile view of meta bar to refer to user instead of avatar
  Services/User/classes/Provider/UserMetaBarProvider.php
Labels: bugfix

#2957 Auth/Session: Fix Mantis issue 28305
  Services/Authentication/classes/class.ilSessionDBHandler.php
Labels: bugfix

#3317 Declare DIC for autocomplete in IDEs
  ilias.php
Labels: improvement, php

#3294 Global Screen, Text Direction Fix: see #29426
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Services/COPage/classes/class.ilCOPageGlobalTemplate.php
  Services/Language/classes/class.ilLanguage.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  src/GlobalScreen/Scope/Layout/Builder/StandardPageBuilder.php
  src/GlobalScreen/Scope/Layout/MetaContent/MetaContent.php
Labels: bugfix

#2980 Fixes Use of undefined constant TIMING_NEVER error.
  Modules/Scorm2004/classes/adlparser/SeqActivity.php
Labels: bugfix

#2548 Move files from Services/Transformation to its only user
  Modules/Scorm2004/classes/class.ilContentObject2FO.php
  Modules/Scorm2004/classes/class.ilXML2FO.php
  Modules/Scorm2004/content_object2fo.xsl
  Services/Transformation/maintenance.json
Labels: improvement

#3230 #28561 fix improvement
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
  Modules/Test/classes/class.ilTestScoringGUI.php
  Modules/Test/classes/class.ilTestServiceGUI.php
  Modules/Test/templates/default/tpl.il_as_tst_answers_compare.html
  Modules/Test/templates/default/tpl.il_as_tst_correct_solution_output.html
  Modules/TestQuestionPool/classes/class.assClozeTestGUI.php
  Modules/TestQuestionPool/classes/class.assQuestionGUI.php
  Modules/TestQuestionPool/classes/class.assTextQuestion.php
  Modules/TestQuestionPool/classes/class.assTextQuestionGUI.php
  Modules/TestQuestionPool/templates/default/tpl.il_as_qpl_question_printview.html
Labels: bugfix, improvement

#3002 Learning Progress: Fix Mantis issue 29189
  Services/Tracking/classes/repository_statistics/class.ilTrMatrixTableGUI.php
Labels: bugfix

#3314 Marked ilUtil as deprecated
  Services/Utilities/classes/class.ilUtil.php
Labels: improvement, technical board

#3299 fixed 30538: Undefined array key (PHP 8)
  src/GlobalScreen/Scope/MainMenu/Collector/Map/Map.php
Labels: bugfix

#3190 Docs: Accessibility Process
  docs/development/README.md
  docs/development/accessibility-process.md
Labels: improvement

#3278 UI/CombinedSlate: Add optional entry id for menu sub entries (ILIAS 6)
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/TopParentItemRenderer.php
  src/UI/Component/MainControls/Slate/Combined.php
  src/UI/Implementation/Component/MainControls/Slate/Combined.php
  tests/UI/Component/MainControls/Slate/CombinedSlateTest.php
Labels: improvement, kitchen sink

#3320 CI: Implemented the possibility to run all checks locally
  .github/workflows/checks.yml
  CI/PHP-CS-Fixer/run_check.sh
  CI/Special-Char-Checker/special-char-checker.sh
Labels: improvement

#3249 Init/ErrorReporting: Use -1 in DEVMODE if PHP 8 or SHOWNOTICES = true
  Services/Init/classes/class.ilInitialisation.php
Labels: improvement

#3329 Add whitespaces instead of line brakes for latest article view in forum
  Modules/Forum/classes/class.ilObjForumAccess.php
Labels: improvement

#3296 Switching repository chat message field to textarea and also switched…
  Modules/Chatroom/js/iliaschat.jquery.js
  Modules/Chatroom/templates/default/style.css
  Modules/Chatroom/templates/default/tpl.chatroom.html
Labels: improvement

#3231 Remove dead function (follow-up to T&A #28561)
  Modules/TestQuestionPool/classes/class.assTextQuestion.php
Labels: improvement

#3266 Refactored random element provider and fixed unit test.
  Modules/TestQuestionPool/classes/class.assClozeGap.php
  Modules/TestQuestionPool/classes/class.assClozeTest.php
  Modules/TestQuestionPool/classes/class.assClozeTestGUI.php
  Modules/TestQuestionPool/classes/class.assQuestion.php
  Modules/TestQuestionPool/classes/export/qti12/class.assClozeTestExport.php
  Modules/TestQuestionPool/classes/feedback/class.ilAssClozeTestFeedback.php
  Modules/TestQuestionPool/classes/questions/LogicalAnswerCompare/ilAssLacCompositeValidator.php
  Modules/TestQuestionPool/test/assClozeSelectGapTest.php
  Services/Randomization/classes/class.ilArrayElementOrderKeeper.php
  Services/Randomization/classes/class.ilArrayElementShuffler.php
  Services/Randomization/classes/class.ilBaseRandomElementProvider.php
  Services/Randomization/classes/class.ilDeterministicArrayElementProvider.php
  Services/Randomization/interfaces/interface.ilRandomArrayElementProvider.php
Labels: improvement

#3163 Show tests in Assigned Objects tab of competences
  Modules/TestQuestionPool/classes/class.assQuestion.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionSkillAssignment.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionSkillAssignmentsGUI.php
  Modules/TestQuestionPool/classes/questions/class.ilAssQuestionSkillAssignmentImporter.php
Labels: bugfix

#3326 Fix for missing seetings when cloning test (Mantis: 30442)
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#3338 Add Icon for WebDAV
  src/UI/Component/Symbol/Icon/Standard.php
  src/UI/Implementation/Component/Symbol/Icon/Standard.php
  templates/default/images/icon_wbdv.svg
  templates/default/images/outlined/icon_wbdv.svg
Labels: improvement

#3341 Container References, Fixing build errors, see #30667
  Services/ContainerReference/classes/class.ilContainerReference.php
  Services/Object/classes/class.ilObject.php
  Services/Object/test/ilObjectDefinitionTest.php
Labels: bugfix

#3286 Repository: Fix ternary operator
  Services/Repository/classes/class.ilRepositoryGUI.php
Labels: bugfix

#3287 UIComponent/GlyphGUI: Fix ternary operator
  Services/UIComponent/Glyph/classes/class.ilGlyphGUI.php
Labels: bugfix

#3308 fixed #30563: mediaobject fixed height
  Services/COPage/xsl/page.xsl
Labels: bugfix

#3295 Fix paths to learning module and mob upload direcotries
  Services/Export/README.md
Labels: bugfix

#3328 PhpSpreadsheet: Fix color application on cell
  Services/Excel/classes/class.ilExcel.php
Labels: bugfix

#3324 #0030243: Failed test: TeX im PDF-Export anzeigen
  Modules/Survey/xml/question2fo.xsl
Labels: bugfix

#3339 BT-30503: Added label to 'mail to members' form
  Services/Contact/classes/class.ilMailMemberSearchGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3285 PublicArea: Add redirect if not enabled
  Services/Repository/classes/class.ilRepositoryGUI.php
Labels: bugfix

#2795 usr/src: #28594 filter assignes of orgunits by position permission i…
  Services/Search/classes/class.ilRepositorySearchGUI.php
  Services/User/classes/class.ilObjUserFolderGUI.php
Labels: bugfix

#3344 Object: Fix return types
  Services/Object/classes/class.ilObject.php
Labels: bugfix

#3343 Object: Fix return type and incorrect value when requesting long desc…
  Services/Object/classes/class.ilObject.php
Labels: bugfix

#3016 Mantis 28534
  lang/ilias_de.lang
Labels: bugfix

#3330 UI Components, Meta Bar Dom Structure, see #29717 and #28735
  Services/LTI/templates/default/lti.css
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/templates/default/Layout/standardpage.less
  src/UI/templates/default/MainControls/metabar.less
  src/UI/templates/default/MainControls/tpl.metabar.html
  src/UI/templates/js/Item/notification.js
  src/UI/templates/js/MainControls/metabar.js
  templates/default/delos.css
  tests/UI/Component/MainControls/MetaBarTest.php
Labels: bugfix, kitchen sink, php

#3337 BT-27027: Changed wording of course favourite info text to better describe its function
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#3346 UI Component, Update Roadmap, removed Bootstrap Entry
  src/UI/ROADMAP.md
Labels: roadmap
