Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-06, with the labels that each got.

#3417 Update Dependencies after Release v7.1
  composer.lock
Labels: technical board

#3245 Database: Fix implode()
  Services/Database/classes/PDO/class.ilDBPdo.php
Labels: bugfix

#3392 UI: On/Off Label for Toggle Button
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/Button/Factory.php
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/templates/default/Button/toggle.less
  src/UI/templates/default/Button/tpl.toggle.html
  src/UI/templates/js/Button/button.js
  templates/default/delos.css
  templates/default/less/variables.less
  tests/UI/Component/Button/ToggleButtonTest.php
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
Labels: kitchen sink

#3426 Bugfix Forum: 30821
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3424 Bugfix Forum 30821
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3423 Bugfix Forum 30821
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3425 Bugfix Forum 30821
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3434 ILIAS 7 forum html export overflow added to template
  Modules/Forum/templates/default/tpl.forums_export_html.html
  templates/default/delos.css
  templates/default/less/Modules/Forum/delos.less
Labels: bugfix

#3433 ILIAS 6 forum html export overflow added to template
  Modules/Forum/templates/default/tpl.forums_export_html.html
  templates/default/delos.css
  templates/default/less/Modules/Forum/delos.less
Labels: bugfix

#3435 ILIAS trunk forum html export overflow added to template
  Modules/Forum/templates/default/tpl.forums_export_html.html
  templates/default/delos.css
  templates/default/less/Modules/Forum/delos.less
Labels: bugfix

#3430 BT-29650: After registration user can now click on a link to get to the Login page instead of landing on another registration form
  Services/Registration/classes/class.ilAccountRegistrationGUI.php
  Services/Registration/templates/default/tpl.usr_registered.html
Labels: bugfix

#3427 Make reset administrative notification work from table (trunk)
  Services/AdministrativeNotification/classes/class.ilADNNotificationTableGUI.php
Labels: improvement

#3437 Update ilias_en.lang (T&A related)
  lang/ilias_en.lang
Labels: improvement

#3439 Update ilias_en.lang (T&A related)
  lang/ilias_en.lang
Labels: improvement

#3440 Update ilias_en.lang (T&A related)
  lang/ilias_en.lang
Labels: improvement

#3438 Update ilias_en.lang (T&A related)
  lang/ilias_en.lang
Labels: improvement

#3422 Rule for new files in root
  README.md
Labels: technical board

#3420 Add tests to ensure only expected files/folders in root folder
  tests/App/RootFolderTest.php
Labels: improvement, technical board

#3412 Fixed warnings in poll module that were found by php 8 inspection
  Modules/Poll/classes/class.ilObjPoll.php
  Modules/Poll/classes/class.ilObjPollAccess.php
  Modules/Poll/classes/class.ilObjPollGUI.php
  Modules/Poll/classes/class.ilObjPollListGUI.php
  Modules/Poll/classes/class.ilPollAnswerTableGUI.php
  Modules/Poll/classes/class.ilPollBlock.php
  Modules/Poll/classes/class.ilPollBlockGUI.php
  Modules/Poll/classes/class.ilPollDataSet.php
  Modules/Poll/classes/class.ilPollImporter.php
  Modules/Poll/classes/class.ilPollUserTableGUI.php
Labels: improvement

#3429 Module interaction fixes for php 8 compatibility
  Services/Object/classes/class.ilObject2GUI.php
Labels: bugfix

#3454 Fixed missing new_type when creating an object that extends ilObject2GUI
  Services/Object/classes/class.ilObject2GUI.php
Labels: bugfix

#3453 usability fix: https://mantis.ilias.de/view.php?id=30136
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Modules/Test/templates/default/tpl.il_as_tst_pass_details_overview_participants.html
Labels: improvement, jour fixe

#3445 Test: remove JavaAppletQuestion
  Modules/Test/classes/class.ilObjTestGUI.php
  Modules/Test/classes/class.ilTestExpressPageObjectGUI.php
  Modules/TestQuestionPool/classes/class.assJavaApplet.php
  Modules/TestQuestionPool/classes/class.assJavaAppletGUI.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionTypeOrderer.php
  Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php
  Modules/TestQuestionPool/classes/class.ilQuestionEditGUI.php
  Modules/TestQuestionPool/classes/export/qti12/class.assJavaAppletExport.php
  Modules/TestQuestionPool/classes/feedback/class.ilAssJavaAppletFeedback.php
  Modules/TestQuestionPool/classes/import/qti12/class.assJavaAppletImport.php
  Modules/TestQuestionPool/test/assJavaAppletGUITest.php
  Modules/TestQuestionPool/test/assJavaAppletTest.php
  Modules/TestQuestionPool/test/ilModulesTestQuestionPoolSuite.php
  Services/QTI/classes/class.ilQTIItem.php
  lang/ilias_ar.lang
  lang/ilias_bg.lang
  lang/ilias_cs.lang
  lang/ilias_da.lang
  lang/ilias_de.lang
  lang/ilias_el.lang
  lang/ilias_en.lang
  lang/ilias_es.lang
  lang/ilias_et.lang
  lang/ilias_fa.lang
  lang/ilias_fr.lang
  lang/ilias_hr.lang
  lang/ilias_hu.lang
  lang/ilias_it.lang
  lang/ilias_ja.lang
  lang/ilias_ka.lang
  lang/ilias_lt.lang
  lang/ilias_nl.lang
  lang/ilias_pl.lang
  lang/ilias_pt.lang
  lang/ilias_ro.lang
  lang/ilias_ru.lang
  lang/ilias_sk.lang
  lang/ilias_sq.lang
  lang/ilias_sr.lang
  lang/ilias_tr.lang
  lang/ilias_uk.lang
  lang/ilias_vi.lang
  lang/ilias_zh.lang
Labels: improvement

#3468 Webservices: update config in setup
  Services/WebServices/classes/Setup/class.ilWebServicesSetupAgent.php
Labels: bugfix

#3402 LearningSequence: #30445 - always show start-button
  Modules/LearningSequence/classes/Player/class.ilLSPlayer.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Modules/LearningSequence/classes/class.ilLSLocalDI.php
Labels: bugfix

#3476 Setup: Process possible NIC registration error to build exception mes…
  setup/classes/class.ilNICKeyRegisteredObjective.php
Labels: improvement

#3226 Setup Http: 30366 use correct ini file
  Services/Http/classes/Setup/class.ilHttpMetricsCollectedObjective.php
Labels: bugfix

#3484 setup: add declare strict types and use type hints
  setup/classes/class.ilIniFilesLoadedObjective.php
  setup/classes/class.ilIniFilesPopulatedObjective.php
  setup/classes/class.ilInstIdDefaultStoredObjective.php
  setup/classes/class.ilMakeInstallationAccessibleObjective.php
  setup/classes/class.ilNICKeyRegisteredObjective.php
  setup/classes/class.ilNICKeyStoredObjective.php
  setup/classes/class.ilOverwritesExistingInstallationConfirmed.php
  setup/classes/class.ilOwnRiskConfirmedObjective.php
  setup/classes/class.ilSetupAgent.php
  setup/classes/class.ilSetupConfig.php
  setup/classes/class.ilSetupConfigStoredObjective.php
  setup/classes/class.ilSetupMetricsCollectedObjective.php
  setup/classes/class.ilSetupObjective.php
  setup/classes/class.ilUseRootConfirmed.php
  setup/cli.php
Labels: improvement

#3485 src/KioskMode: add declare strict types and use type hints
  Modules/LearningSequence/classes/Player/LSTOCBuilder.php
  src/KioskMode/ControlBuilder.php
  src/KioskMode/LocatorBuilder.php
  src/KioskMode/State.php
  src/KioskMode/TOCBuilder.php
  src/KioskMode/URLBuilder.php
  src/KioskMode/View.php
Labels: improvement

#3471 Update Dependencies after Release v6.10
  composer.lock
Labels: technical board

#3472 Update Dependencies after Release v7.2
  composer.lock
Labels: technical board
