Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-10, with the labels that each got.

#3676 Setup: Fix 'setMethods' deprecation in tests and fix unsupported meth…
  tests/Setup/Artifact/BuildArtifactObjectiveTest.php
  tests/Setup/Helper.php
  tests/Setup/Objective/ClientIdReadObjectiveTest.php
  tests/Setup/ObjectiveIteratorTest.php
Labels: improvement

#3610 UI: Mainbar, check for state before gs-reloading contents; fixes 30610
  src/UI/templates/js/MainControls/dist/mainbar.js
  src/UI/templates/js/MainControls/src/mainbar.renderer.js
Labels: bugfix

#3609 UI: Mainbar, 30610 fix gs-call on resize
  src/GlobalScreen/Scope/MainMenu/Collector/Renderer/MakeSlateAsync.php
  src/UI/Implementation/Component/MainControls/Slate/Slate.php
  src/UI/templates/js/MainControls/mainbar.js
Labels: bugfix

#3411 UI Components: Interface for Toasts
  src/UI/Component/Toast/Factory.php
  src/UI/Component/Toast/Toast.php
  src/UI/Factory.php
  src/UI/Implementation/Factory.php
  src/UI/examples/Toast/Standard/base.php
  src/UI/examples/Toast/Standard/with_action.php
  src/UI/examples/Toast/Standard/with_additional_links.php
  src/UI/examples/Toast/Standard/with_description.php
  src/UI/examples/Toast/Standard/with_link_title.php
  src/UI/examples/Toast/Standard/with_long_description.php
  tests/UI/Base.php
Labels: kitchen sink

#3648 Update Dependencies after Release v6.11
  composer.lock
Labels: technical board, dependencies

#3647 Update Dependencies after Release v7.3
  composer.lock
Labels: technical board, dependencies

#3677 HTTP: Fix 'setMethods' deprecation in tests
  tests/DI/HTTPServicesTest.php
Labels: improvement

#3679 Database: Fix 'setMethods' deprecation in tests
  Services/Database/test/Setup/ilDBStepExecutionDBTest.php
Labels: improvement

#3644 UI Components: Interface for Button/Minimize
  src/UI/Component/Button/Factory.php
  src/UI/Component/Button/Minimize.php
  src/UI/Implementation/Component/Button/Factory.php
  src/UI/examples/Button/Minimize/base.php
  tests/UI/Component/Button/ButtonFactoryTest.php
Labels: kitchen sink, improvement

#3668 Cleanup .gitignore by introducing new comment groups
  .gitignore
Labels: improvement

#3675 DI: Remove unused exceptions
  src/DI/Exceptions/InvalidClassException.php
  src/DI/Exceptions/NoSuchServiceException.php
Labels: improvement

#3680 RTE: Fix 'setMethods' deprecation in tests
  Services/RTE/test/ilRTEBaseTest.php
Labels: improvement

#3682 LSO: Fix 'setMethods' deprecation in tests
  Modules/LearningSequence/test/IliasMocks.php
Labels: improvement

#3681 StudyProgramme: Fix 'setMethods' deprecation in tests
  Modules/StudyProgramme/test/ilStudyProgrammeDashGUITest.php
Labels: improvement

#3670 Remove class.ilXML2DOM.php and Migration\DBUpdate_439\classes
  Services/Migration/DBUpdate_439/classes/class.ilNestedSetXML.php
  Services/Xml/classes/class.ilXML2DOM.php
Labels: improvement

#3686 UI: add on-first-view trigger to slate (#31434)
  src/UI/templates/js/MainControls/slate.js
Labels: bugfix
