Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-11, with the labels that each got.

#3714 Update Dependencies after Release v6.12
  composer.lock
Labels: technical board, dependencies

#3663 UI/ViewControl: add possibility of return value null to Pagination::getRange
  src/UI/Component/ViewControl/Pagination.php
  src/UI/Implementation/Component/ViewControl/Pagination.php
  tests/UI/Component/ViewControl/PaginationTest.php
Labels: improvement

#3727 Mantis 31346: Add missing $
  Services/Language/classes/class.ilObjLanguageExtGUI.php
Labels: bugfix

#3729 Update Dependencies after Release v7.4
  composer.lock
Labels: technical board, dependencies

#3722 update repository pattern: ilGeoLocationDBRepository.php
  docs/development/code-examples/repository-pattern/01_simple_example/ilGeoLocationDBRepository.php
Labels: improvement, technical board

#3614 Modifies forum for PHP 8
  Modules/Forum/classes/Actions/class.ilForumAutoSaveAsyncDraftAction.php
  Modules/Forum/classes/Dto/class.ForumDto.php
  Modules/Forum/classes/GUI/class.ilForumThreadFormGUI.php
  Modules/Forum/classes/Notification/class.ilForumMailEventNotificationSender.php
  Modules/Forum/classes/Notification/class.ilForumNotificationEventsFormGUI.php
  Modules/Forum/classes/Notification/interface.ilForumNotificationEvents.php
  Modules/Forum/classes/Provider/ForumGlobalScreenToolsProvider.php
  Modules/Forum/classes/Setup/class.ilForumSetupAgent.php
  Modules/Forum/classes/Tasks/class.ilForumDerivedTaskProviderFactory.php
  Modules/Forum/classes/Tasks/class.ilForumDraftsDerivedTaskProvider.php
  Modules/Forum/classes/class.ilFileDataForum.php
  Modules/Forum/classes/class.ilFileDataForumDrafts.php
  Modules/Forum/classes/class.ilForum.php
  Modules/Forum/classes/class.ilForumAppEventListener.php
  Modules/Forum/classes/class.ilForumAuthorInformation.php
  Modules/Forum/classes/class.ilForumAuthorInformationCache.php
  Modules/Forum/classes/class.ilForumCronNotification.php
  Modules/Forum/classes/class.ilForumCronNotificationDataProvider.php
  Modules/Forum/classes/class.ilForumDraftsHistory.php
  Modules/Forum/classes/class.ilForumDraftsTableGUI.php
  Modules/Forum/classes/class.ilForumExplorerGUI.php
  Modules/Forum/classes/class.ilForumExportGUI.php
  Modules/Forum/classes/class.ilForumExporter.php
  Modules/Forum/classes/class.ilForumImporter.php
  Modules/Forum/classes/class.ilForumLP.php
  Modules/Forum/classes/class.ilForumMailNotification.php
  Modules/Forum/classes/class.ilForumModerators.php
  Modules/Forum/classes/class.ilForumModeratorsGUI.php
  Modules/Forum/classes/class.ilForumModeratorsTableGUI.php
  Modules/Forum/classes/class.ilForumMoveTopicsExplorer.php
  Modules/Forum/classes/class.ilForumNewsRendererGUI.php
  Modules/Forum/classes/class.ilForumNotification.php
  Modules/Forum/classes/class.ilForumNotificationCache.php
  Modules/Forum/classes/class.ilForumNotificationTableGUI.php
  Modules/Forum/classes/class.ilForumPost.php
  Modules/Forum/classes/class.ilForumPostDraft.php
  Modules/Forum/classes/class.ilForumPostsDeleted.php
  Modules/Forum/classes/class.ilForumPostsTree.php
  Modules/Forum/classes/class.ilForumProperties.php
  Modules/Forum/classes/class.ilForumSessionStorage.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumStatisticsTableGUI.php
  Modules/Forum/classes/class.ilForumThreadSettinsSessionStorage.php
  Modules/Forum/classes/class.ilForumTopic.php
  Modules/Forum/classes/class.ilForumTopicTableGUI.php
  Modules/Forum/classes/class.ilForumUtil.php
  Modules/Forum/classes/class.ilForumXMLParser.php
  Modules/Forum/classes/class.ilForumXMLWriter.php
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumAccess.php
  Modules/Forum/classes/class.ilObjForumAdministration.php
  Modules/Forum/classes/class.ilObjForumAdministrationAccess.php
  Modules/Forum/classes/class.ilObjForumAdministrationGUI.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Modules/Forum/classes/class.ilObjForumListGUI.php
  Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
  Modules/Forum/classes/class.ilObjForumSearchResultTableGUI.php
  Modules/Forum/classes/class.ilObjForumSubItemListGUI.php
  Modules/Forum/interfaces/interface.ilForumNotificationMailData.php
  goto.php
Labels: improvement

#3731 Fix duplicate il_head_action id
  Services/COPage/classes/class.ilCOPageGlobalTemplate.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/UICore/classes/MetaTemplate/PageContentGUI.php
  Services/UICore/classes/class.ilGlobalTemplate.php
Labels: bugfix

#3725 UI, Mainbar: 30644 render menuitems as list, focus contents
  src/UI/examples/Layout/Page/Standard/ui.php
  src/UI/examples/Layout/Page/Standard/ui_mainbar.php
  src/UI/templates/default/MainControls/mainbar.less
  src/UI/templates/default/MainControls/tpl.mainbar.html
  src/UI/templates/js/MainControls/dist/mainbar.js
  src/UI/templates/js/MainControls/src/mainbar.main.js
  src/UI/templates/js/MainControls/src/mainbar.renderer.js
  templates/default/delos.css
  tests/UI/Component/MainControls/MainBarTest.php
Labels: bugfix, kitchen sink

#3730 Fix aria labels in action menu
  Services/UIComponent/AdvancedSelectionList/templates/default/tpl.adv_selection_list.html
Labels: bugfix

#3737 This changes the role-attribute in BulkyLinks for Menu-Items
  src/UI/templates/default/Link/tpl.bulky.html
  tests/UI/Component/Link/BulkyLinkTest.php
Labels: bugfix

#3664 Feature/button/minimize implementation
  lang/ilias_en.lang
  src/UI/Implementation/Component/Button/Factory.php
  src/UI/Implementation/Component/Button/Minimize.php
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/templates/default/Button/button.less
  src/UI/templates/default/Button/tpl.minimize.html
  templates/default/delos.css
  templates/default/delos.less
  tests/UI/Component/Button/ButtonTest.php
  tests/UI/Component/Button/MinimizeButtonTest.php
Labels: kitchen sink, improvement

#3665 Feature/osc minimize button
  Services/OnScreenChat/classes/class.ilOnScreenChatGUI.php
  Services/OnScreenChat/js/onscreenchat.js
  Services/OnScreenChat/templates/default/tpl.chat-window.html
  templates/default/delos.css
  templates/default/less/Services/OnScreenChat/delos.less
Labels: improvement

#3746 ILIAS 8 / Forum: Customize Page
  Modules/Forum/LuceneObjectDefinition.xml
  Modules/Forum/classes/CoPage/class.ilForumPage.php
  Modules/Forum/classes/CoPage/class.ilForumPageCollector.php
  Modules/Forum/classes/CoPage/class.ilForumPageCommandForwarder.php
  Modules/Forum/classes/CoPage/class.ilForumPageConfig.php
  Modules/Forum/classes/CoPage/class.ilForumPageGUI.php
  Modules/Forum/classes/Setup/class.ilForumDatabaseUpdateSteps.php
  Modules/Forum/classes/Setup/class.ilForumSetupAgent.php
  Modules/Forum/classes/class.ilForumExporter.php
  Modules/Forum/classes/class.ilForumImporter.php
  Modules/Forum/classes/class.ilForumProperties.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumXMLParser.php
  Modules/Forum/classes/class.ilForumXMLWriter.php
  Modules/Forum/classes/class.ilObjForum.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Modules/Forum/interfaces/ilForumObjectConstants.php
  Modules/Forum/module.xml
  Services/COPage/classes/class.ilPageEditorSettings.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  xml/ilias_frm_7.xsd
Labels: improvement

#3747 DidacticTemplate: Refactored DIC calls
  Services/DidacticTemplate/classes/Action/class.ilDidacticTemplateLocalPolicyAction.php
  Services/DidacticTemplate/classes/Pattern/class.ilDidacticTemplateFilterPatternFactory.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateObjSettings.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSetting.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsGUI.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsTableGUI.php
Labels: improvement

#3739 UICore, Fix of: #31573
  Services/UICore/classes/class.ilGlobalPageTemplate.php
Labels: bugfix

#3755 JS, Forms: move JS to global template
  Services/Form/classes/class.ilFormPropertyGUI.php
  Services/Form/classes/class.ilPropertyFormGUI.php
  Services/Form/classes/class.ilRadioGroupInputGUI.php
  Services/Form/templates/default/tpl.prop_radio.html
  Services/Form/templates/default/tpl.property_form.html
Labels: bugfix

#3756 UIComponent: Fix 'Access key function ids are integers not strings'
  Services/UIComponent/Button/classes/class.ilButtonBase.php
  Services/UIComponent/Toolbar/classes/class.ilToolbarGUI.php
Labels: bugfix

#3753 JS, AdvancedSelectionList: #31382 add initialization later
  Services/UIComponent/AdvancedSelectionList/classes/class.ilAdvancedSelectionListGUI.php
  Services/UIComponent/AdvancedSelectionList/templates/default/tpl.adv_selection_list.html
  Services/UIComponent/AdvancedSelectionList/templates/default/tpl.adv_selection_list_js_init.js
Labels: bugfix

#3667 Remove unused debug file with debug functions
  Services/Init/classes/class.ilInitialisation.php
  include/inc.debug.php
Labels: improvement

#3656 Session Handler: Implement interface / Remove PHP version conditional…
  Services/Authentication/classes/class.ilSession.php
  Services/Authentication/classes/class.ilSessionDBHandler.php
  Services/Init/classes/class.ilInitialisation.php
Labels: improvement

#3763 Implement a way for components to listen for user field attribute cha…
  Services/Mail/classes/class.ilMailAppEventListener.php
  Services/Mail/classes/class.ilMailGlobalAddressSettingsChangedCommand.php
  Services/Mail/classes/class.ilMailUserFieldChangeListener.php
  Services/Mail/service.xml
  Services/User/classes/ChangedUserFieldAttribute.php
  Services/User/classes/InterestedUserFieldAttribute.php
  Services/User/classes/InterestedUserFieldChangeListener.php
  Services/User/classes/InterestedUserFieldComponent.php
  Services/User/classes/UserFieldAttributesChangeListener.php
  Services/User/classes/class.ilObjUserFolderGUI.php
  Services/User/classes/class.ilUserFieldSettingsTableGUI.php
  Services/User/classes/class.ilUserProfile.php
  Services/User/service.xml
  Services/User/templates/default/tpl.std_fields_settings_row.html
  Services/User/templates/default/tpl.usr_field_change_listener_confirm.html
  Services/User/test/ChangedUserFieldAttributeTest.php
  Services/User/test/InterestedUserFieldAttributeTest.php
  Services/User/test/InterestedUserFieldChangeListenerTest.php
  Services/User/test/InterestedUserFieldComponentTest.php
  Services/User/test/ilServicesUserSuite.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3761 Tree: Fix wrong tree root id fallback in constructor
  Services/Tree/classes/class.ilTree.php
Labels: bugfix

#3767 BT-31484: Fixed activation of subtabs in group settings
  Modules/Group/classes/class.ilObjGroupGUI.php
Labels: bugfix

#3773 ilDBUpdate:: values for [settings] MUST be strictly of type 'string'
  Services/Database/classes/class.ilDBUpdate.php
Labels: improvement

#3623 just some small typos
  docs/development/database-updates.md
Labels: bugfix

#3752 PHP8: some fixes
  Modules/Group/classes/class.ilGroupParticipantsTableGUI.php
  Modules/Group/classes/class.ilObjGroup.php
  Services/Membership/classes/class.ilMembershipGUI.php
  Services/MetaData/classes/class.ilMDCreator.php
  Services/MetaData/classes/class.ilMDGeneral.php
  Services/Search/classes/class.ilRepositorySearchGUI.php
  Services/Table/classes/class.ilTable2GUI.php
  Services/Tree/classes/class.ilTree.php
Labels: bugfix

#3757 APC: Fix PHP type when retrieving memory setting (and apply PSR-2 + X)
  Services/GlobalCache/classes/Apc/class.ilApc.php
  Services/GlobalCache/classes/class.ilGlobalCacheService.php
Labels: bugfix

#3713 ErrorHandling: only show error message once #31213
  error.php
  templates/default/tpl.error.html
Labels: bugfix

#3784 Sort icons and remove unnecessary full path from Edit icons
  Services/Style/System/classes/Icons/class.ilSystemStyleIconFolder.php
  Services/Style/System/classes/Icons/class.ilSystemStyleIconsGUI.php
Labels: improvement

#3790 UI: Fix signature of presentation table factory method
  src/UI/Implementation/Component/Table/Factory.php
Labels: bugfix

#3782 Refinery: MakeClickable Transformation
  Services/Utilities/classes/class.ilUtil.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Refinery/ROADMAP.md
  src/Refinery/String/Group.php
  src/Refinery/String/MakeClickable.php
  tests/Refinery/String/GroupTest.php
  tests/Refinery/String/MakeClickableTest.php
Labels: improvement

#3779 E-Mail: clickable mixed content type
  Services/Mail/classes/class.ilMimeMail.php
  Services/Mail/test/ilMailMimeTest.php
  Services/Mail/test/ilMailTest.php
Labels: bugfix

#3795 log: avoid static call
  src/DI/LoggingServices.php
Labels: improvement

#3574 Fix import of data collections if certain values are not set
  Modules/DataCollection/classes/class.ilDataCollectionDataSet.php
Labels: bugfix

#3796 BUGFIX [31661]: Contrast Issues: Who-is-online text-color on background
  templates/default/delos.css
  templates/default/delos.less
  templates/default/less/Services/Awareness/delos.less
Labels: bugfix, improvement

#3717 deleted composer lib zendframework/zend-httphandlerrunner and patch
  composer.json
  composer.lock
  libs/composer/patches/zend-httphandlerrunner.patch
Labels: improvement

#3716 deleted composer lib zendframework/zend-httphandlerrunner and patch
  composer.json
  composer.lock
  libs/composer/patches/zend-httphandlerrunner.patch
Labels: improvement

#3551 LTI/XAPI: Fix permanent links to learning progress (Mantis issues 30837 and 30838)
  Modules/CmiXapi/classes/class.ilObjCmiXapiGUI.php
  Modules/LTIConsumer/classes/class.ilObjLTIConsumerGUI.php
Labels: bugfix

#3490 LTI: id can only be used once
  Services/LTI/service.xml
Labels: improvement

#3197 (bugfix#30156): delete the temporary html file after creation of PDF (PhantomJS and wkHTMLToPDF)
  Services/PDFGeneration/classes/renderer/phantomjs/class.ilPhantomJSRenderer.php
  Services/PDFGeneration/classes/renderer/wkhtmltopdf/class.ilWkhtmlToPdfRenderer.php
Labels: bugfix

#3775 Dashboard Performance: Switch approach to SQL
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemBlockMembershipsDTO.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockMembershipsObjectDatabaseRepository.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockMembershipsProvider.php
  Services/Dashboard/ItemsBlock/interfaces/interface.ilPDSelectedItemsBlockMembershipsObjectRepository.php
Labels: bugfix, improvement

#3802 Setup: Fix error when duplicate setup agent is detected
  src/Setup/AgentCollection.php
Labels: bugfix

#3798 Updated italian language
  lang/ilias_it.lang
Labels: improvement
