Repository ILIAS-eLearning/ILIAS, pull requests merged in 2021-08, with the labels that each got.

#3519 fixed #31123: Permanent Link to Content Page fails if only visible pe…
  Modules/ContentPage/classes/class.ilObjContentPageGUI.php
Labels: bugfix

#3469 Object: move cache from component to object
  Services/Object/classes/class.ilCachedObjectDefinition.php
  Services/Object/classes/class.ilObjectDefinition.php
Labels: improvement

#3532 Added additional check if style doesn't exist for the user which will then revert to the default style.
  Services/User/classes/class.ilObjUser.php
Labels: bugfix

#3455 Setup: trunk7_30865 implement command achieve
  Services/UICore/classes/Setup/class.ilUICoreSetupAgent.php
  setup/README.md
  setup/cli.php
  src/Setup/AgentCollection.php
  src/Setup/AgentFinder.php
  src/Setup/CLI/AchieveCommand.php
  src/Setup/CLI/HasAgent.php
  src/Setup/CLI/ReloadControlStructureCommand.php
  src/Setup/ImplementationOfAgentFinder.php
  tests/Setup/CLI/AchieveCommandTest.php
Labels: improvement

#3536 User/Style: Fix accessing undefined array key
  Services/User/classes/class.ilObjUser.php
Labels: bugfix

#3533 [FIX] recursion in KeyValueAcess
  src/Refinery/KeyValueAccess.php
  tests/Refinery/KeyValueAccessTest.php
Labels: bugfix

#3540 LDAP: Fix missing return value
  Services/LDAP/classes/class.ilLDAPUserSynchronisation.php
Labels: bugfix

#3539 Fixed #31168
  Modules/TestQuestionPool/classes/tables/class.ilKprimChoiceAnswerFreqStatTableGUI.php
Labels: bugfix

#3390 UI: Filter Revision - Implementation
  Services/UI/classes/class.ilUIFilterRequestAdapter.php
  Services/UI/classes/class.ilUIFilterService.php
  Services/UI/classes/class.ilUIFilterServiceSessionGateway.php
  Services/UI/classes/class.ilUIService.php
  Services/UI/classes/class.ilUIServiceDependencies.php
  src/UI/Component/Input/README.md
  src/UI/Implementation/Component/Input/Container/Filter/Filter.php
  src/UI/Implementation/Component/Input/Container/Filter/Renderer.php
  src/UI/Implementation/Component/Input/Field/FilterContextRenderer.php
  src/UI/Implementation/Component/Input/Field/MultiSelect.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/examples/Input/Container/Filter/Standard/base.php
  src/UI/templates/default/Input/filter.less
  src/UI/templates/default/Input/tpl.context_filter.html
  src/UI/templates/default/Input/tpl.select.html
  src/UI/templates/default/Input/tpl.standard_filter.html
  src/UI/templates/js/Input/Container/dist/filter.js
  src/UI/templates/js/Input/Container/filter.js
  src/UI/templates/js/Input/Container/rollup.config.js
  src/UI/templates/js/Input/Container/src/filter.js
  src/UI/templates/js/Input/Container/src/filter.main.js
  src/UI/templates/js/Input/Container/test/filter.test.js
  templates/default/delos.css
  templates/default/less/variables.less
  test/filter.test.js
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
  tests/UI/Component/Input/Field/SelectTest.php
Labels: kitchen sink, improvement

#3544 Setup: Remove PHPUnit deprecations in setup test case (incl. boyscout…
  Services/Database/test/Setup/ilDatabaseUpdateStepTest.php
Labels: improvement

#3545 Certificate: Change properties in object list for crs and sahs object…
  Modules/Course/classes/class.ilObjCourseListGUI.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleListGUI.php
Labels: bugfix

#3477 usability fix: addition to https://mantis.ilias.de/view.php?id=30136
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Modules/Test/templates/default/tpl.il_as_tst_results_participant.html
Labels: improvement

#3514 Feature/php8 compatibility/modules test verification
  Modules/Test/classes/class.ilObjTestVerification.php
  Modules/Test/classes/class.ilObjTestVerificationAccess.php
  Modules/Test/classes/class.ilObjTestVerificationGUI.php
  Modules/Test/classes/class.ilObjTestVerificationListGUI.php
  Modules/Test/classes/tables/class.ilTestVerificationTableGUI.php
Labels: improvement

#3516 Feature/php8 compatibility/modules scorm verification
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerification.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerificationAccess.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerificationGUI.php
  Modules/ScormAicc/classes/Verification/class.ilObjSCORMVerificationListGUI.php
  Modules/ScormAicc/classes/Verification/class.ilSCORMVerificationTableGUI.php
Labels: improvement

#3510 Feature/php8 compatibility/modules course verification
  Modules/Course/classes/Verification/class.ilCourseVerificationTableGUI.php
  Modules/Course/classes/Verification/class.ilObjCourseVerification.php
  Modules/Course/classes/Verification/class.ilObjCourseVerificationAccess.php
  Modules/Course/classes/Verification/class.ilObjCourseVerificationGUI.php
  Modules/Course/classes/Verification/class.ilObjCourseVerificationListGUI.php
Labels: improvement

#3511 Feature/php8 compatibility/modules exercise verification
  Modules/Exercise/classes/class.ilExerciseVerificationTableGUI.php
  Modules/Exercise/classes/class.ilObjExerciseVerification.php
  Modules/Exercise/classes/class.ilObjExerciseVerificationAccess.php
  Modules/Exercise/classes/class.ilObjExerciseVerificationGUI.php
  Modules/Exercise/classes/class.ilObjExerciseVerificationListGUI.php
Labels: improvement

#3529 [FIX] 0031033: Update fails from ILIAS 5.3 to 5.4
  Modules/OrgUnit/classes/Positions/UserAssignment/class.ilOrgUnitUserAssignment.php
  setup/sql/dbupdate_04.php
Labels: bugfix

#3513 Feature/php8 compatibility/services copage verification
  Services/COPage/classes/class.ilPCVerification.php
  Services/COPage/classes/class.ilPCVerificationGUI.php
Labels: improvement

#3549 Setup/NICRegistration: Ensure correct types when building NIC registr…
  setup/classes/class.ilNICKeyRegisteredObjective.php
Labels: bugfix, improvement

#3564 ILIAS 8: Learning Progress for Forum
  Modules/Forum/classes/class.ilForum.php
  Modules/Forum/classes/class.ilForumAppEventListener.php
  Modules/Forum/classes/class.ilForumPost.php
  Modules/Forum/classes/class.ilForumProperties.php
  Modules/Forum/classes/class.ilForumStatisticsTableGUI.php
  Modules/Forum/classes/class.ilForumXMLParser.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Modules/Forum/classes/classilForumLP.php
  Modules/Forum/module.xml
  Modules/Forum/templates/default/tpl.statistics_table_row.html
  Services/Object/classes/class.ilObjectLP.php
  Services/Tracking/classes/class.ilLPObjSettings.php
  Services/Tracking/classes/class.ilLPTableBaseGUI.php
  Services/Tracking/classes/class.ilLearningProgressBaseGUI.php
  Services/Tracking/classes/collection/class.ilLPCollectionOfRepositoryObjects.php
  Services/Tracking/classes/status/class.ilLPStatusContributionToDiscussion.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  setup/sql/dbupdate_05.php
Labels: improvement

#3563 (bugfix#31255) iass: link fixed from cmd 'downloadAttachment' to 'downloadFile'
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMembersTableGUI.php
Labels: bugfix

#3556 UI: Filter Revision - Merge down to release 7
  Services/Container/Filter/classes/class.ilContainerFilterService.php
  Services/Container/Filter/classes/class.ilContainerUserFilter.php
  Services/Container/classes/class.ilContainerGUI.php
  Services/Cron/classes/class.ilCronManagerGUI.php
  Services/Cron/classes/class.ilCronManagerTableFilterMediator.php
  Services/UI/classes/class.ilUIFilterRequestAdapter.php
  Services/UI/classes/class.ilUIFilterService.php
  Services/UI/classes/class.ilUIFilterServiceSessionGateway.php
  Services/UI/classes/class.ilUIService.php
  Services/UI/classes/class.ilUIServiceDependencies.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/Button/Factory.php
  src/UI/Component/Input/Container/Factory.php
  src/UI/Component/Input/Field/FilterInput.php
  src/UI/Component/Input/Field/Tag.php
  src/UI/Component/Input/README.md
  src/UI/Implementation/Component/Button/Renderer.php
  src/UI/Implementation/Component/Input/Container/Filter/Filter.php
  src/UI/Implementation/Component/Input/Container/Filter/Renderer.php
  src/UI/Implementation/Component/Input/Field/FilterContextRenderer.php
  src/UI/Implementation/Component/Input/Field/MultiSelect.php
  src/UI/Implementation/Component/Input/Field/Numeric.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/Implementation/Component/Input/Field/Select.php
  src/UI/Implementation/Component/Input/Field/Text.php
  src/UI/examples/Input/Container/Filter/Standard/base.php
  src/UI/templates/default/Button/toggle.less
  src/UI/templates/default/Button/tpl.toggle.html
  src/UI/templates/default/Input/filter.less
  src/UI/templates/default/Input/tpl.context_filter.html
  src/UI/templates/default/Input/tpl.select.html
  src/UI/templates/default/Input/tpl.standard_filter.html
  src/UI/templates/js/Button/button.js
  src/UI/templates/js/Input/Container/dist/filter.js
  src/UI/templates/js/Input/Container/filter.js
  src/UI/templates/js/Input/Container/rollup.config.js
  src/UI/templates/js/Input/Container/src/filter.js
  src/UI/templates/js/Input/Container/src/filter.main.js
  src/UI/templates/js/Input/Container/test/filter.test.js
  templates/default/delos.css
  templates/default/less/variables.less
  test/filter.test.js
  tests/UI/Component/Button/ToggleButtonTest.php
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
  tests/UI/Component/Input/Field/SelectTest.php
Labels: kitchen sink, improvement

#3530 UI Components, Letter Avatars, Contrast too low, see #31102 and #0031153
  Services/User/Avatar/classes/class.ilUserAvatarLetter.php
  src/UI/Implementation/Component/Symbol/Avatar/Letter.php
  templates/default/delos.css
  templates/default/less/variables.less
  tests/UI/Component/Symbol/Avatar/AvatarTest.php
Labels: bugfix, kitchen sink

#3555 Less, Preview Images misplaced, see: 31234
  Modules/DataCollection/classes/Fields/Fileupload/class.ilDclFileuploadRecordRepresentation.php
  Services/Object/classes/class.ilObjectListGUI.php
  Services/Preview/templates/default/images/preview.psd
  Services/Preview/templates/default/images/preview_arrows.psd
  Services/Preview/templates/default/images/preview_close.psd
  templates/default/delos.css
  templates/default/images/preview.png
  templates/default/images/preview_arrows.png
  templates/default/images/preview_close.png
  templates/default/less/Services/Preview/delos.less
Labels: bugfix

#3503 T&A: explain inavailability of corrections (trunk)
  Modules/Test/classes/class.ilTestCorrectionsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3502 T&A: explain inavailability of corrections (release_7)
  Modules/Test/classes/class.ilTestCorrectionsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3501 T&A: explain inavailability of corrections (release_6)
  Modules/Test/classes/class.ilTestCorrectionsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3500 T&A: explain inavailability of corrections (release_5-4)
  Modules/Test/classes/class.ilTestCorrectionsGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3542 [FIX] 0031174: Lucene Suche indiziert keine PDF Dateien
  Modules/File/LuceneObjectDefinition.xml
  Services/WebServices/RPC/lib/src/de/ilias/services/lucene/index/file/path/FileObjectPathCreator7.java
Labels: bugfix

#3566 LearningSequence: 30836 refactor _goto function based on hotfix from mjansen
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
Labels: bugfix

#3567 Refinery: refactor the to()->Transformations into Constraints
  src/Refinery/To/Group.php
  src/Refinery/To/Transformation/BooleanTransformation.php
  src/Refinery/To/Transformation/DateTimeTransformation.php
  src/Refinery/To/Transformation/DictionaryTransformation.php
  src/Refinery/To/Transformation/FloatTransformation.php
  src/Refinery/To/Transformation/IntegerTransformation.php
  src/Refinery/To/Transformation/ListTransformation.php
  src/Refinery/To/Transformation/RecordTransformation.php
  src/Refinery/To/Transformation/StringTransformation.php
  src/Refinery/To/Transformation/TupleTransformation.php
  tests/Refinery/In/Transformation/ParallelTest.php
  tests/Refinery/In/Transformation/SeriesTest.php
  tests/Refinery/KindlyTo/Transformation/ListTransformationTest.php
  tests/Refinery/To/Transformation/BooleanTransformationTest.php
  tests/Refinery/To/Transformation/DateTimeTransformationTest.php
  tests/Refinery/To/Transformation/DictionaryTransformationTest.php
  tests/Refinery/To/Transformation/FloatTransformationTest.php
  tests/Refinery/To/Transformation/IntegerTransformationTest.php
  tests/Refinery/To/Transformation/ListTransformationTest.php
  tests/Refinery/To/Transformation/RecordTransformationTest.php
  tests/Refinery/To/Transformation/StringTransformationTest.php
  tests/Refinery/To/Transformation/TupleTransformationTest.php
Labels: improvement

#3571 Refinery: change implemented interface from Transformation to Constraint
  src/Refinery/To/Transformation/BooleanTransformation.php
  src/Refinery/To/Transformation/ListTransformation.php
Labels: improvement

#3457 UI: new Inputs URL and Link
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Data/Factory.php
  src/Data/Link.php
  src/UI/Component/Input/Field/Factory.php
  src/UI/Component/Input/Field/Link.php
  src/UI/Component/Input/Field/Url.php
  src/UI/Implementation/Component/Input/Field/Factory.php
  src/UI/Implementation/Component/Input/Field/Link.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/Implementation/Component/Input/Field/Url.php
  src/UI/examples/Input/Field/Link/base.php
  src/UI/examples/Input/Field/Url/base.php
  src/UI/examples/Input/Field/Url/disabled.php
  src/UI/examples/Input/Field/Url/with_error.php
  src/UI/examples/Input/Field/Url/with_value.php
  src/UI/templates/default/Input/tpl.url.html
  tests/Data/LinkTest.php
  tests/UI/Component/Input/Field/LinkInputTest.php
  tests/UI/Component/Input/Field/UrlInputTest.php
Labels: kitchen sink

#3535 UI, Drilldown: refactor drilldown menu
  Services/Init/classes/Dependencies/InitUIFramework.php
  src/UI/Component/Menu/Drilldown.php
  src/UI/Component/Menu/Factory.php
  src/UI/Component/Menu/LabeledMenu.php
  src/UI/Component/Menu/Menu.php
  src/UI/Component/Menu/Sub.php
  src/UI/Implementation/Component/Menu/Drilldown.php
  src/UI/Implementation/Component/Menu/Factory.php
  src/UI/Implementation/Component/Menu/LabeledMenu.php
  src/UI/Implementation/Component/Menu/Menu.php
  src/UI/Implementation/Component/Menu/Renderer.php
  src/UI/Implementation/Component/Menu/Sub.php
  src/UI/examples/Menu/Drilldown/drilldown.php
  src/UI/examples/Menu/Sub/sub.php
  src/UI/templates/default/Menu/drilldown.less
  src/UI/templates/default/Menu/tpl.drilldown.html
  src/UI/templates/default/Menu/tpl.menu.html
  src/UI/templates/default/Menu/tpl.menuitem.html
  src/UI/templates/js/Menu/dist/drilldown.js
  src/UI/templates/js/Menu/drilldown.js
  src/UI/templates/js/Menu/rollup.config.js
  src/UI/templates/js/Menu/src/drilldown.js
  src/UI/templates/js/Menu/src/drilldown.main.js
  src/UI/templates/js/Menu/src/drilldown.mapping.js
  src/UI/templates/js/Menu/src/drilldown.model.js
  src/UI/templates/js/Menu/test/drilldown.test.js
  templates/default/delos.css
  test/drilldown.test.js
  tests/UI/Component/Menu/Drilldown/DrilldownTest.php
Labels: kitchen sink, improvement

#3581 UI/Input: 31269, add problembuilder to required-validation
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Input/Field/DateTime.php
Labels: bugfix
