Repository ILIAS-eLearning/ILIAS, pull requests merged in 2022-01, with the labels that each got.

#3871 Fix type of maxlength from bool to int
  Services/Form/classes/class.ilPasswordInputGUI.php
Labels: bugfix

#3772 JS, CoPa: move JS to page/onload (fixes 31569)
  Services/COPage/classes/class.ilPCMediaObject.php
Labels: bugfix

#3774 JS, IntLink: move JS to page/onload (fixes 31570)
  Services/Link/classes/class.ilInternalLinkGUI.php
  Services/Link/templates/default/tpl.int_link_panel.html
Labels: bugfix

#3791 Composer: `composer update` + Upgrade simplesamlphp and symfony/yaml
  Services/Saml/lib/metadata.php
  composer.json
  composer.lock
Labels: improvement

#3872 Composer: Upgrade ezyang/htmlpurifier for PHP 8 support
  composer.json
  composer.lock
Labels: improvement, dependencies, php

#3875 Fix wrong namespace in Refinery Tests
  tests/Refinery/IdentityTransformationTest.php
  tests/Refinery/Random/Transformation/ShuffleTransformationTest.php
Labels: improvement

#3874 Fixed 31806: New bylines needed for admin settings file upload
  Modules/Forum/classes/class.ilObjForumAdministrationGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3877 Bibliografic db step improvement
  Modules/Bibliographic/classes/Setup/class.ilBibliograficDB80.php
Labels: improvement

#3884 UI Tree/Node: Add horizontal space between node line elements (arrow,…
  src/UI/templates/default/Tree/tree.less
  templates/default/delos.css
  templates/default/less/variables.less
Labels: bugfix, kitchen sink

#3882 Block: Escape special characters when adopting block title to aria la…
  Services/Block/classes/class.ilBlockGUI.php
Labels: bugfix

#3883 BT-31110: Fix show filesize in filelist
  Services/COPage/classes/class.ilPageObject.php
Labels: bugfix

#3812 PR as bugfix for mantis #26367
  Modules/BookingManager/Participants/classes/class.ilBookingParticipantGUI.php
Labels: bugfix

#3885 GlobalCache/APC: Fix iterating over invalid iterator state
  Services/GlobalCache/classes/Apc/class.ilApc.php
Labels: bugfix

#3886 GlobalCache/APC: Fix iterating over invalid iterator state (trunk)
  Services/GlobalCache/classes/Apc/class.ilApc.php
Labels: bugfix

#3887 fix mantis bug #29165: Tests in lso not shown in testoverview
  Services/Object/classes/class.ilPasteIntoMultipleItemsExplorer.php
Labels: bugfix

#3870 Improvement/8/language
  Services/Language/classes/class.ilCachedLanguage.php
  Services/Language/classes/class.ilLanguage.php
  Services/Language/classes/class.ilObjLanguage.php
Labels: improvement

#3829 Docu: new logic for supported versions
  docs/development/README.md
  docs/development/supported-versions.md
Labels: improvement

#3892 Implemented PHP 8.1 in check matrix
  .github/workflows/checks.yml
  composer.json
Labels: improvement

#3897 This allows for correct naming of files from php://input streams.
  src/ResourceStorage/Resource/InfoResolver/StreamInfoResolver.php
Labels: improvement

#3898 TermsOfService: wrong lang var name ('...no_consent_yet')
  lang/ilias_ar.lang
  lang/ilias_bg.lang
  lang/ilias_cs.lang
  lang/ilias_da.lang
  lang/ilias_de.lang
  lang/ilias_el.lang
  lang/ilias_en.lang
  lang/ilias_es.lang
  lang/ilias_et.lang
  lang/ilias_fa.lang
  lang/ilias_fr.lang
  lang/ilias_hr.lang
  lang/ilias_hu.lang
  lang/ilias_it.lang
  lang/ilias_ja.lang
  lang/ilias_ka.lang
  lang/ilias_lt.lang
  lang/ilias_nl.lang
  lang/ilias_pl.lang
  lang/ilias_pt.lang
  lang/ilias_ro.lang
  lang/ilias_ru.lang
  lang/ilias_sk.lang
  lang/ilias_sq.lang
  lang/ilias_sr.lang
  lang/ilias_tr.lang
  lang/ilias_uk.lang
  lang/ilias_vi.lang
  lang/ilias_zh.lang
Labels: bugfix

#3838 WIP: [FIX] 0031532: Regression in browser cache handling since the UI rework
  Services/Init/classes/class.ilInitialisation.php
  src/GlobalScreen/Scope/Layout/LayoutServices.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/AbstractCollection.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/AbstractMedia.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/AbstractMediaWithPath.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/Css.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/InlineCss.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/Js.php
  src/GlobalScreen/Scope/Layout/MetaContent/Media/OnLoadCode.php
  src/GlobalScreen/Scope/Layout/MetaContent/MetaContent.php
  src/GlobalScreen/Services.php
Labels: bugfix

#3902 Update PHP-CS-Fixer
  CI/PHP-CS-Fixer/code-format.php_cs
  composer.json
  composer.lock
  src/Setup/CLI/AchieveCommand.php
  src/Setup/CLI/BuildArtifactsCommand.php
  src/Setup/CLI/InstallCommand.php
  src/Setup/CLI/UpdateCommand.php
Labels: improvement

#3904 Add Unit Tests for Modules/Forum
  Modules/Forum/classes/class.ilForumNotification.php
  Modules/Forum/classes/class.ilForumTopic.php
  Modules/Forum/test/ilForumNotificationTest.php
  Modules/Forum/test/ilForumTopicTest.php
  Modules/Forum/test/ilObjForumAdministrationTest.php
Labels: improvement

#3909 Changed usage '' to ilSession
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix

#3903 Add Unit Tests for Services/Mail
  Services/Mail/classes/class.ilMail.php
  Services/Mail/classes/class.ilMailFormGUI.php
  Services/Mail/test/ilMailTest.php
Labels: improvement

#3910 Services/LDAP: fix ilLDAPRoleAssignmentRules::getAdditionalPluginAttributes
  Services/LDAP/classes/class.ilLDAPRoleAssignmentRules.php
Labels: bugfix

#3911 Refinery: Adding the newly introduced identity transformation to the factory
  src/Refinery/Factory.php
  tests/Refinery/FactoryTest.php
Labels: improvement

#3908 Scorm/CmiXapi: Fix PHP types / Apply PSR-2 + X Code Style
  Modules/CmiXapi/classes/class.ilObjCmiXapiGUI.php
  Modules/Scorm2004/classes/class.ilSCORM2004TrackingItems.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleAccess.php
  Modules/ScormAicc/classes/class.ilObjSAHSLearningModuleListGUI.php
  Modules/ScormAicc/classes/class.ilSCORMTrackingItems.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiCompleted.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiCompletedOrPassed.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiCompletedOrPassedWithFailed.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiCompletedWithFailed.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiPassed.php
  Services/Tracking/classes/status/class.ilLPStatusCmiXapiPassedWithFailed.php
Labels: bugfix

#3917 Remove unused random files
  Services/Randomization/classes/class.ilArrayElementShuffler.php
  Services/Randomization/classes/class.ilBaseRandomElementProvider.php
  Services/Randomization/classes/class.ilDeterministicArrayElementProvider.php
  Services/Randomization/interfaces/interface.ilRandomArrayElementProvider.php
  Services/Randomization/test/RandomizationStrategiesTest.php
Labels: improvement

#3918 PHP8: UICore
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Services/LTI/classes/class.ilGlobalTemplate.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/UICore/classes/MetaTemplate/PageContentGUI.php
  Services/UICore/classes/Screen/PageContentProvider.php
  Services/UICore/classes/class.ilCtrl.php
  Services/UICore/classes/class.ilFrameTargetInfo.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  Services/UICore/classes/class.ilTemplate.php
  Services/UICore/classes/class.ilUIFramework.php
  Services/UICore/exceptions/class.ilTemplateException.php
  Services/UICore/interfaces/interface.ilGlobalTemplateInterface.php
  Services/UICore/lib/html-it/IT.php
  Services/UICore/lib/html-it/ITX.php
  Services/UICore/lib/html-it/exceptions/class.ilTemplateException.php
  Services/UICore/lib/html-it/ilias-patches.php
  Services/UICore/maintenance.json
  Services/UICore/test/ilServicesUICoreSuite.php
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/Implementation/Render/Template.php
  src/UI/Implementation/Render/ilTemplateWrapper.php
  tests/UI/Renderer/AbstractRendererTest.php
  tests/UI/Renderer/ilIndependentTemplate.php
Labels: php

#3914 UI/Tree: Fix PSR-4 issue is expandable2 example
  src/UI/examples/Tree/Expandable/expandable2.php
Labels: kitchen sink, improvement

#3916 Data URI Support
  src/GlobalScreen/Scope/Layout/MetaContent/Media/AbstractMediaWithPath.php
Labels: bugfix, improvement

#3921 Add unit tests for Services/Contact/BuddySystem.
  Services/Contact/BuddySystem/classes/class.ilBuddySystemArrayCollection.php
  Services/Contact/BuddySystem/test/ilAwarenessUserProviderApprovedContactsTest.php
  Services/Contact/BuddySystem/test/ilAwarenessUserProviderContactRequestsTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateFilterRuleFactoryTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateInitiatorShouldNotBeAbleToApproveIgnoredRequestRuleTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateInitiatorShouldOnlyBeAbleToCancelRequestRuleTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateNullFilterRuleTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateReceiverShouldNotBeAbleToCancelRequestRuleTest.php
  Services/Contact/BuddySystem/test/states/ilBuddySystemRelationStateReceiverShouldOnlyBeAbleToApproveIgnoredRequestRuleTest.php
Labels: improvement

#3922 [FIX] 0031817: ilCtrl: PHP Warning when building artifacts - preg_match_all()
  Services/UICore/classes/Structure/class.ilCtrlStructureReader.php
Labels: bugfix

#3793 Feature/shy implementation
  src/UI/Implementation/Component/Item/Factory.php
  src/UI/Implementation/Component/Item/Renderer.php
  src/UI/Implementation/Component/Item/Shy.php
  src/UI/templates/default/Item/item.less
  src/UI/templates/default/Item/tpl.item_shy.html
  templates/default/delos.css
  templates/default/less/variables.less
  tests/UI/Component/Item/ItemShyTest.php
Labels: kitchen sink, improvement

#3926 #31897: adjusted calls to ilCtrl::getCmd()
  Modules/LearningModule/Presentation/class.ilLMPresentationGUI.php
Labels: bugfix

#3672 Fix removal of files with no rid
  Modules/File/classes/class.ilObjFile.php
Labels: bugfix

#3836 fixing 'comma in filenames' issue: #31730
  Modules/File/classes/Implementation/class.ilObjFileImplementationLegacy.php
Labels: bugfix

#3928 ilCtrl: Don't use PHP 8.0 functions
  Services/UICore/classes/Structure/class.ilCtrlStructureCidGenerator.php
  Services/UICore/classes/class.ilCtrl.php
Labels: bugfix, php

#3933 GlobalScreen: Initialize variables with null do prevent issues when a…
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Complex.php
Labels: bugfix

#3934 GlobalScreen: Initialize variables with null do prevent issues when a…
  src/GlobalScreen/Scope/MainMenu/Factory/Item/Complex.php
Labels: bugfix

#3927 Language: Don't use PHP 8.0 functions
  Services/Language/classes/Setup/class.ilSetupLanguage.php
  Services/Language/classes/class.ilLanguage.php
  Services/Language/classes/class.ilLanguageFile.php
  Services/Language/classes/class.ilLanguageTableGUI.php
  Services/Language/classes/class.ilObjLanguage.php
Labels: bugfix, php

#3830 UI/Input/Duration - customize labels for start/end
  src/UI/Component/Input/Field/Duration.php
  src/UI/Implementation/Component/Input/Field/Duration.php
  src/UI/examples/Input/Field/Duration/base.php
  tests/UI/Component/Input/Field/DurationInputTest.php
Labels: improvement

#3891 UI/Input/Tag: update tagify-version
  node_modules/.package-lock.json
  node_modules/@yaireo/tagify/README.md
  node_modules/@yaireo/tagify/dist/jQuery.tagify.min.js
  node_modules/@yaireo/tagify/dist/react.tagify.js
  node_modules/@yaireo/tagify/dist/tagify.css
  node_modules/@yaireo/tagify/dist/tagify.esm.js
  node_modules/@yaireo/tagify/dist/tagify.js
  node_modules/@yaireo/tagify/dist/tagify.min.js
  node_modules/@yaireo/tagify/dist/tagify.polyfills.min.js
  node_modules/@yaireo/tagify/package.json
  node_modules/@yaireo/tagify/src/tagify.scss
  package-lock.json
  package.json
Labels: improvement

#3896 A11Y/UI/Tree: Fix duplicate role attribute for tree node list items (Manti…
  src/UI/Implementation/Component/Tree/Node/Renderer.php
Labels: bugfix, kitchen sink

#3893 DataCollection: Fix file upload for new entry with enabled confirmati…
  Modules/DataCollection/classes/Fields/Fileupload/class.ilDclFileuploadRecordFieldModel.php
Labels: bugfix, php

#3923 #31796: Consideration of ilTable commands.
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Services/Table/classes/trait.ilTableCommandHelper.php
  Services/UICore/classes/class.ilCtrl.php
  Services/User/classes/class.ilObjUserFolderGUI.php
Labels: bugfix

#3937 Docs/NPM: Add example to install dependency from GitHub branch
  docs/development/js/third-party-libs-npm.md
Labels: improvement

#3951 FileSystem/Finder: PHP 8 / PSR-2 + x
  src/Filesystem/Finder/Comparator/BaseComparator.php
  src/Filesystem/Finder/Comparator/DateComparator.php
  src/Filesystem/Finder/Comparator/NumberComparator.php
  src/Filesystem/Finder/Finder.php
  src/Filesystem/Finder/Iterator/DateRangeFilterIterator.php
  src/Filesystem/Finder/Iterator/DepthRangeFilterIterator.php
  src/Filesystem/Finder/Iterator/ExcludeDirectoryFilterIterator.php
  src/Filesystem/Finder/Iterator/FileTypeFilterIterator.php
  src/Filesystem/Finder/Iterator/RecursiveDirectoryIterator.php
  src/Filesystem/Finder/Iterator/SizeRangeFilterIterator.php
  src/Filesystem/Finder/Iterator/SortableIterator.php
  tests/Filesystem/Finder/FinderTest.php
Labels: improvement

#3953 Move TinyMCE to Repo in ILIAS-eLearning
  node_modules/.package-lock.json
  node_modules/jquery-dragster/package.json
  node_modules/owl.carousel/package.json
  node_modules/tinymce/package.json
  node_modules/tinymce/plugins/ilimgupload/imgupload.php
  package-lock.json
  package.json
Labels: improvement

#3945 Move TinyMCE NPM dependency to repo in ILIAS-eLearning-Organization
  node_modules/.package-lock.json
  node_modules/tinymce/plugins/ilfrmquote/plugin.js
  node_modules/tinymce/plugins/ilfrmquote/plugin.min.js
  node_modules/tinymce/plugins/ilimgupload/imgupload.php
  node_modules/tinymce/plugins/latex/plugin.js
  package-lock.json
  package.json
Labels: technical board

#3666 Feature/notification chat seperation
  Modules/Chatroom/classes/Provider/ChatMainBarProvider.php
  Services/Notes/GlobalScreen/classes/NotesMainBarProvider.php
  Services/OnScreenChat/classes/Provider/OnScreenChatNotificationProvider.php
  Services/OnScreenChat/classes/Provider/OnScreenChatProvider.php
  Services/OnScreenChat/classes/class.ilOnScreenChatGUI.php
  Services/OnScreenChat/js/onscreenchat.js
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Item/Renderer.php
  src/UI/templates/default/Item/item.less
  src/UI/templates/default/MainControls/Slate/slate.less
  src/UI/templates/default/MainControls/mainbar.less
  templates/default/delos.css
  templates/default/less/variables.less
Labels: improvement

#3961 Fix #31947 Added version parameter to all JS files breaks MathJax in the Browser
  src/GlobalScreen/Scope/Layout/MetaContent/Media/AbstractMediaWithPath.php
Labels: bugfix

#3958 Forum: Bugfixes of PHP 8 Regressions
  Modules/Forum/classes/class.ilForumAuthorInformation.php
  Modules/Forum/classes/class.ilForumExplorerGUI.php
  Modules/Forum/classes/class.ilForumSettingsGUI.php
  Modules/Forum/classes/class.ilForumTopic.php
  Modules/Forum/classes/class.ilForumTopicTableGUI.php
Labels: bugfix, php

#3965 UI: allow Bulky Links in Meta Bar
  src/UI/Implementation/Component/MainControls/MetaBar.php
  src/UI/Implementation/Component/MainControls/Renderer.php
  tests/UI/Component/MainControls/MetaBarTest.php
Labels: bugfix, kitchen sink, php

#3967 Logging/Setup: Make objective more robust
  Services/Logging/classes/Setup/class.ilLoggingConfigStoredObjective.php
Labels: bugfix, php

#3971 fixed DynamicInputDataIterator::current().
  src/UI/Implementation/Component/Input/DynamicInputDataIterator.php
  tests/UI/Component/Input/DynamicInputDataIteratorTest.php
Labels: bugfix, kitchen sink

#3880 Refactor8 mathjax v3
  Services/Administration/classes/class.ilObjExternalToolsSettingsGUI.php
  Services/MathJax/README.md
  Services/MathJax/classes/Setup/class.ilMathJaxConfigStoredObjective.php
  Services/MathJax/classes/Setup/class.ilMathJaxMetricsCollectedObjective.php
  Services/MathJax/classes/Setup/class.ilMathJaxSetupAgent.php
  Services/MathJax/classes/Setup/class.ilMathJaxSetupConfig.php
  Services/MathJax/classes/class.ilMathJax.php
  Services/MathJax/classes/class.ilMathJaxConfig.php
  Services/MathJax/classes/class.ilMathJaxConfigSettingsRepository.php
  Services/MathJax/classes/class.ilMathJaxException.php
  Services/MathJax/classes/class.ilMathJaxFactory.php
  Services/MathJax/classes/class.ilMathJaxImage.php
  Services/MathJax/classes/class.ilMathJaxServer.php
  Services/MathJax/classes/class.ilMathJaxSettingsGUI.php
  Services/MathJax/docs/install-server.md
  Services/MathJax/interfaces/interface.ilMathJaxConfigRespository.php
  Services/MathJax/phpunit.xml
  Services/MathJax/test/bootstrap.php
  Services/MathJax/test/class.ilMathJaxTest.php
  Services/MathJax/test/example.png
  Services/MathJax/test/example.svg
  Services/MathJax/test/ilMathJaxBaseTest.php
  Services/MathJax/test/ilServicesMathJaxSuite.php
  Services/Utilities/classes/class.ilUtil.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  setup/README.md
Labels: improvement

#3949 UI: Add new Icons for Chat Conversations and Group Conversations
  Services/OnScreenChat/classes/Provider/OnScreenChatProvider.php
  src/UI/Component/Symbol/Icon/Standard.php
  src/UI/Implementation/Component/Symbol/Icon/Standard.php
  templates/default/images/icon_con.svg
  templates/default/images/icon_gcon.svg
  templates/default/images/outlined/icon_con.svg
  templates/default/images/outlined/icon_gcon.svg
Labels: kitchen sink, improvement, php

#3952 UI/Input/Duration - translate default labels for start/end
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Input/Field/Duration.php
  tests/UI/Component/Input/Field/DurationInputTest.php
Labels: kitchen sink, improvement, php

#3879 BT-30508: added aria label to comments/notes
  Services/Notes/classes/class.ilNoteGUI.php
  Services/Notes/templates/default/tpl.notes_edit.html
Labels: bugfix

#3881 BT-30506: Added aria label to tag input
  Services/Tagging/classes/class.ilTaggingGUI.php
  Services/Tagging/templates/default/tpl.tags_input.html
Labels: bugfix

#3900 BT-30502/BT-30498: Assignments: Added alt text to magnifier image, made image focusable and interactable by tabbing
  Modules/Exercise/classes/class.ilExAssignmentGUI.php
  Modules/Exercise/templates/default/tpl.image_file.html
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#3976 #31976: ilGlobalTemplate issues
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Services/LTI/classes/class.ilGlobalTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  Services/UICore/classes/class.ilTemplate.php
Labels: bugfix

#3980 #31912: Dropped 'gotolp' mechanism
  Modules/CmiXapi/classes/class.ilObjCmiXapiGUI.php
  Modules/ContentPage/classes/class.ilObjContentPageGUI.php
  Modules/LTIConsumer/classes/class.ilObjLTIConsumerGUI.php
  Services/Tracking/classes/repository_statistics/class.ilLPCollectionSettingsTableGUI.php
Labels: bugfix
