Repository ILIAS-eLearning/ILIAS, pull requests merged in 2022-12, with the labels that each got.

#5104 Fix Question Edit Links not Adding to Locator
  Modules/Test/classes/tables/class.ilTestQuestionsTableGUI.php
Labels: bugfix, php

#5268 [FIX] CI: copyright-checker now ignores UI examples.
  CI/Copyright-Checker/copyright-checker.sh
Labels: improvement

#5285 T&A #0035463 (trunk): Same name in Test export
  Modules/Test/classes/class.ilTestExport.php
Labels: bugfix

#5282 BT 32886: show correct copyright default in info tab
  Services/InfoScreen/classes/class.ilInfoScreenGUI.php
  Services/MetaData/classes/class.ilMDUtils.php
Labels: bugfix

#5295 Fixed type of ids from request ILIAS 8
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockGUI.php
Labels: bugfix, php

#5294 Fixed type of ids from request
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockGUI.php
Labels: bugfix, php

#5296 Fixed type of ids from request ILIAS TRUNK
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockGUI.php
Labels: bugfix, php

#5254 HUN - 20221124
  lang/ilias_hu.lang
Labels: improvement

#5291 Remove duplicates in language files
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#5292 release_8 remove newline at the end of lng file which causes an error in lang sort script
  lang/ilias_hu.lang
Labels: bugfix

#5260 Update Dependencies after Release v7.16
  composer.lock
Labels: technical board, dependencies

#5259 Update Dependencies after Release v6.20
  composer.lock
Labels: technical board, dependencies

#4969 GitHub Workflows security hardening
  .github/workflows/checks.yml
Labels: improvement

#5299 Registration: Fix issue with user email address being NULL (Mantis 35…
  Services/Registration/classes/class.ilAccountRegistrationMail.php
Labels: bugfix, php

#5290 Added info on ECS Interface
  docs/development/maintenance.md
Labels: improvement

#5236 Fix localization with multiple correct answers in Long Menu question as Page content (Mantis #35064) (release_6)
  Modules/Scorm2004/scripts/questions/question_handling.js
  Services/COPage/classes/class.ilPCQuestion.php
Labels: bugfix

#5302 T&A Bugfix #0035679: No tab-bar when switching from "Dashboard" or "Result" to "Statistics"
  Modules/Test/classes/class.ilTestTabsManager.php
Labels: bugfix, php

#5305 [FIX] 0034710: Failed test: Abbruch des Hochladens (in SCSS)
  src/UI/Component/Input/Field/UploadHandler.php
  src/UI/Implementation/Component/Dropzone/File/File.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/templates/default/Input/tpl.file.html
  src/UI/templates/js/Input/Field/file.js
  templates/default/010-settings/legacy-settings/_legacy-settings_ui-input-file.scss
  templates/default/070-components/UI-framework/Input/_ui-component_file.scss
  templates/default/delos.css
  templates/default/delos.css.map
  tests/UI/Component/Dropzone/File/FileTestBase.php
  tests/UI/Component/Input/Field/FileInputTest.php
Labels: bugfix

#4995 TA: Repo for ScoreSettings, UI Form
  Modules/Test/classes/ScoreReporting/ScoreSettingsRepository.php
  Modules/Test/classes/ScoreReporting/TestSettings.php
  Modules/Test/classes/ScoreReporting/class.ilObjTestScoreSettings.php
  Modules/Test/classes/ScoreReporting/class.ilObjTestScoreSettingsDatabaseRepository.php
  Modules/Test/classes/ScoreReporting/ilObjTestSettingsGamification.php
  Modules/Test/classes/ScoreReporting/ilObjTestSettingsResultDetails.php
  Modules/Test/classes/ScoreReporting/ilObjTestSettingsResultSummary.php
  Modules/Test/classes/ScoreReporting/ilObjTestSettingsScoring.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilObjTestGUI.php
  Modules/Test/classes/class.ilObjTestSettingsScoringResultsGUI.php
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Modules/Test/classes/class.ilTestRandomQuestionSetStagingPoolBuilder.php
  Modules/Test/classes/class.ilTestScoring.php
  Modules/Test/classes/class.ilTestServiceGUI.php
  Modules/Test/classes/class.ilTestToplistGUI.php
  Modules/Test/test/ScoreSettingsTest.php
  Modules/Test/test/ilObjTestSettingsScoringResultsGUITest.php
  Modules/Test/test/ilTestEvaluationGUITest.php
  Modules/TestQuestionPool/classes/class.ilQuestionPoolTaxonomiesDuplicator.php
  lang/ilias_de.lang
Labels: bugfix, php

#5218 removed the query_cache_size hint from install docu
  docs/configuration/install.md
Labels: improvement

#5158 Deprecation/Removal in ILIAS 10: Services/FileSystem
  Services/FileSystem/classes/class.ilFile.php
  Services/FileSystem/classes/class.ilFileData.php
  Services/FileSystem/classes/class.ilFileDataImport.php
  Services/FileSystem/classes/class.ilFileSystemAbstractionStorage.php
  Services/FileSystem/classes/class.ilFileSystemGUI.php
  Services/FileSystem/classes/class.ilFileSystemTableGUI.php
  Services/FileSystem/classes/class.ilUploadFiles.php
Labels: improvement

#5179 HTTP: Fix cookie expiration handling (partly)
  Services/Utilities/classes/class.ilUtil.php
Labels: bugfix, php

#5308 Bugfix Statistics and Learning Progress (3)
  Services/Form/classes/class.ilCombinationInputGUI.php
  Services/Form/classes/class.ilDurationInputGUI.php
  Services/Table/classes/class.ilTable2GUI.php
  Services/Table/js/ServiceTable.js
  Services/Tracking/classes/class.ilLPTableBaseGUI.php
Labels: bugfix

#5310 Various LSO Bugfixes
  Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentGUI.php
  Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipGUI.php
  Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceListGUI.php
Labels: bugfix

#5321 TA: 35945 call to undefined function
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#5319 T&A Bugfix 0035859: ECTS Evalutaion Error after finishing test
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix

#5328 Mail Bugfix #0035964: Failed test: Ort- und Zeitangabe bei individueller Bewertung
  Services/Mail/classes/class.ilMailNotification.php
Labels: bugfix, php

#5172 Replace some dependencies with PHP extensions
  docs/configuration/install.md
Labels: improvement

#5337 fixed bug #35978: Language: Trying to access array offset on value of type null
  Services/Language/classes/class.ilObjLanguageDBAccess.php
  Services/Language/classes/class.ilObjLanguageExt.php
Labels: bugfix

#5340 Dear @ILIAS-eLearning/technical-board, This PR updates all dependencies after release v7.17.
  composer.lock
Labels: technical board, dependencies

#5339 Update Dependencies after Release v6.21
  composer.lock
Labels: technical board, dependencies

#5342 User: Fix wrong argument type for system notification
  Services/User/Settings/classes/class.ilPersonalSettingsGUI.php
Labels: bugfix, php

#5327 File: Fix Doubleencoding in List-View
  src/ResourceStorage/Preloader/SecureString.php
Labels: bugfix
