Repository ILIAS-eLearning/ILIAS, pull requests merged in 2023-10, with the labels that each got.

#6322 9/composer/update psr7 and getallheaders
  composer.json
  composer.lock
Labels: improvement

#6025 Database Bugfix #0037504: Return value of ilDBAnalyzer::getPrimaryKeyInformation() must be of the type array, bool returned
  Services/Database/classes/class.ilDBAnalyzer.php
  Services/Database/classes/class.ilDBGenerator.php
Labels: bugfix, php

#6378 Fix: 0038109: Wenn es obligatorische Fragen in einem Test gibt, wird …
  Modules/Test/classes/tables/class.ilListOfQuestionsTableGUI.php
  Modules/Test/test/tables/ilListOfQuestionsTableGUITest.php
Labels: bugfix

#6348 refactor didactic-template-settings-table
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsGUI.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsTableDataRetrieval.php
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsTableGUI.php
Labels: improvement

#6353 Introduces calendar appointment export limit (1mb)
  Services/Calendar/classes/Export/class.ilCalendarExport.php
  Services/Calendar/classes/class.ilCalendarMailNotification.php
  Services/Calendar/classes/class.ilCalendarRemoteAccessHandler.php
  Services/Calendar/classes/class.ilCalendarSubscriptionGUI.php
  Services/Calendar/classes/iCal/class.ilICalWriter.php
  Services/Calendar/templates/default/tpl.subscription_dialog.html
  lang/ilias_de.lang
Labels: bugfix, php

#6296 [#37876] Add type cast to match argument type
  Services/WebServices/SOAP/classes/class.ilSoapClient.php
Labels: bugfix

#6387 Bugfix ILIAS 7 PDF Service
  Services/PDFGeneration/classes/class.ilPDFGenerationConstants.php
  Services/PDFGeneration/classes/renderer/wkhtmltopdf/class.ilWkhtmlToPdfConfigFormGUI.php
Labels: bugfix

#6386 0038146: iCal URL problems
  Services/Calendar/classes/Export/class.ilCalendarExport.php
Labels: bugfix

#6381 Fix: Return value must be of type bool, string returned
  Services/Authentication/classes/class.ilAuthUtils.php
Labels: bugfix

#5561 Setup: Implement an Import/Export Mechanism
  Services/Database/classes/Setup/MysqlDumper.php
  Services/Database/classes/Setup/MysqlIfsnopDumper.php
  Services/Database/classes/Setup/class.ilDatabaseDumpedToDirectoryObjective.php
  Services/Database/classes/Setup/class.ilDatabasePopulatedObjective.php
  Services/FileSystem/classes/Setup/class.ilFileSystemClientDirectoryRenamedObjective.php
  Services/FileSystem/classes/Setup/class.ilFileSystemDirectoriesCreatedObjective.php
  Services/FileSystem/classes/Setup/class.ilFileSystemDirectoryCopiedRecursivelyObjective.php
  composer.json
  composer.lock
  setup/README.md
  setup/classes/class.ilExportMetadataGatheredObjective.php
  setup/classes/class.ilExportZipBuiltObjective.php
  setup/classes/class.ilSetupAgent.php
  setup/classes/class.ilSetupConfig.php
  src/Setup/CLI/AchieveCommand.php
  src/Setup/CLI/ImportFileUnzippedFileObjective.php
  src/Setup/CLI/InstallCommand.php
Labels: improvement

#6390 fix: Undefined array key "frac_helper"
  Modules/TestQuestionPool/classes/class.assFormulaQuestion.php
Labels: bugfix, php

#6344 (ILIAS 8) T&A Bugfix #0029216: Test Import Results are being skipped
  Modules/Test/classes/class.ilObjTestGUI.php
  Modules/Test/classes/class.ilTestPassesSelector.php
  Modules/Test/classes/class.ilTestResultsImportParser.php
  Modules/Test/classes/class.ilTestResultsToXML.php
Labels: bugfix

#6402 AccessControl: Fix return value of ilRbacAdmin::assignUserLimited() (#37627)
  Services/AccessControl/classes/class.ilRbacAdmin.php
Labels: bugfix

#6406 [FIX] 0038223: Undeletable filter in Trash
  Services/Tree/classes/class.ilTreeTrashQueries.php
Labels: bugfix

#6404 MetaData: introduce lom api to dic
  Services/MetaData/docs/api.md
  src/DI/Container.php
Labels: improvement, php

#6411 IndividualAssessment: 36471 if mapping was succesfull cast new id to int
  Modules/IndividualAssessment/classes/class.ilIndividualAssessmentDataSet.php
Labels: bugfix

#6151 Allow Different Sources for Images Depending on Actual Size on Screen
  src/UI/Component/Image/Image.php
  src/UI/Factory.php
  src/UI/Implementation/Component/Image/Image.php
  src/UI/Implementation/Component/Image/Renderer.php
  src/UI/examples/Image/Responsive/with_additional_high_resolution_source.php
  src/UI/examples/Image/mountains-144w.jpg
  src/UI/examples/Image/mountains-301w.jpg
  src/UI/examples/Image/mountains-602w.jpg
  src/UI/templates/js/Image/dist/image.min.js
  src/UI/templates/js/Image/rollup.config.js
  src/UI/templates/js/Image/src/getImageElement.js
  src/UI/templates/js/Image/src/image.js
  src/UI/templates/js/Image/src/loadHighResolutionSource.js
  tests/UI/Client/Image/getImageElement.js
  tests/UI/Client/Image/loadHighResolutionSource.js
  tests/UI/Component/Image/ImageTest.php
Labels: kitchen sink, php, javascript

#6412 TA: 37233, use internal wrapper instead of POST
  Modules/TestQuestionPool/classes/forms/class.ilTagInputGUI.php
Labels: bugfix

#6285 Fix redirect loop when session expires
  Services/Authentication/classes/class.ilSession.php
  Services/Init/classes/class.ilInitialisation.php
  Services/Init/classes/class.ilStartUpGUI.php
Labels: bugfix, php

#6417 T&A Bugfix #0038107: Import Test Export File from a Random Test leads to Error
  Modules/Test/classes/class.ilObjTestGUI.php
Labels: bugfix

#6422 SCORM: #38025, check for empty result when checking (Tracking)Permissions
  Modules/Scorm2004/classes/class.ilSCORM2004StoreData.php
  Modules/ScormAicc/classes/SCORM/class.ilObjSCORMTracking.php
Labels: bugfix

#6214 Docu: Added Development Process How-To
  docs/development/development-process.md
Labels: documentation

#6009 Added Development How-Tos
  docs/development/use-developer-mode.md
  docs/development/use-exceptions.md
  docs/development/write-unit-tests.md
Labels: documentation

#6432 fixed mantis bugs 38115, 38116
  Services/Language/classes/class.ilObjLanguageDBAccess.php
  Services/Language/classes/class.ilObjLanguageExt.php
Labels: bugfix

#6438 9 remove pdf service
  Services/Administration/GlobalScreen/classes/AdministrationMainBarProvider.php
  Services/Administration/classes/class.ilAdministrationGUI.php
  Services/Component/classes/Setup/class.ilComponentDefinitionsStoredObjective.php
  Services/PDFGeneration/README.md
  Services/PDFGeneration/Setup/class.ilPDFGenerationDB90.php
  Services/PDFGeneration/Setup/class.ilPDFGenerationSetupAgent.php
  Services/PDFGeneration/classes/Setup/class.ilPDFGenerationDefinitionProcessor.php
  Services/PDFGeneration/classes/class.ilObjPDFGeneration.php
  Services/PDFGeneration/classes/class.ilObjPDFGenerationAccess.php
  Services/PDFGeneration/classes/class.ilObjPDFGenerationGUI.php
  Services/PDFGeneration/classes/class.ilPDFCompInstaller.php
  Services/PDFGeneration/classes/class.ilPDFGenerationConstants.php
  Services/PDFGeneration/classes/class.ilPDFGenerationJob.php
  Services/PDFGeneration/classes/class.ilPDFGenerationRequest.php
  Services/PDFGeneration/classes/class.ilPDFGeneratorUtils.php
  Services/PDFGeneration/classes/class.ilPDFRendererPlugin.php
  Services/PDFGeneration/classes/factory/class.ilHtmlToPdfTransformerFactory.php
  Services/PDFGeneration/classes/renderer/tcpdf/class.ilTCPDFRenderer.php
  Services/PDFGeneration/classes/renderer/wkhtmltopdf/class.ilWkhtmlToPdfConfig.php
  Services/PDFGeneration/classes/renderer/wkhtmltopdf/class.ilWkhtmlToPdfConfigFormGUI.php
  Services/PDFGeneration/classes/renderer/wkhtmltopdf/class.ilWkhtmlToPdfRenderer.php
  Services/PDFGeneration/interfaces/interface.ilPDFRenderer.php
  Services/PDFGeneration/interfaces/interface.ilRendererConfig.php
  Services/PDFGeneration/phpunit.xml
  Services/PDFGeneration/test/bootstrap.php
  Services/PDFGeneration/test/ilPdfGeneratorConstantsTest.php
  Services/PDFGeneration/test/ilServicesPDFGenerationSuite.php
  Services/PDFGeneration/test/ilWkhtmlToPdfConfigTest.php
  composer.json
  composer.lock
  lang/ilias_de.lang
  lang/ilias_en.lang
  libs/composer/patches/tcpdf.patch
Labels: improvement, php

#6413 UI: Fix Race Condition When Loading Image
  src/UI/Implementation/Component/Image/Renderer.php
Labels: kitchen sink, improvement

#6355 UI/Launcher: Modal button label customization
  src/UI/Component/Launcher/Launcher.php
  src/UI/Implementation/Component/Launcher/Inline.php
  src/UI/Implementation/Component/Launcher/Renderer.php
  src/UI/examples/Launcher/Inline/with_fields.php
  tests/UI/Component/Launcher/LauncherInlineTest.php
Labels: kitchen sink, improvement

#6257 PRG: 37678, sort before offset/limit on entire memberlist
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserTable.php
Labels: bugfix

#6419 Feature/9/dcl date fomulas
  Modules/DataCollection/ROADMAP.md
  Modules/DataCollection/classes/Fields/Datetime/class.ilDclDatetimeRecordFieldModel.php
  Modules/DataCollection/classes/Fields/Datetime/class.ilDclDatetimeRecordRepresentation.php
  Modules/DataCollection/classes/Fields/Datetime/trait.ilDclDatetimeRecordDateFormatter.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/ExpressionParser.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Math/Functions.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Math/Operators.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/DateResult.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/IntegerResult.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/MathResultResolver.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/Result.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/ResultFormatter.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/ResultResolver.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/StringResult.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Result/SubstitutionResultResolver.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Stack.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Substitution/FieldSubstitution.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Token/MathToken.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Token/Token.php
  Modules/DataCollection/classes/Fields/Formula/FormulaParser/Token/Tokenizer.php
  Modules/DataCollection/classes/Fields/Formula/class.ilDclExpressionParser.php
  Modules/DataCollection/classes/Fields/Formula/class.ilDclFormulaFieldRepresentation.php
  Modules/DataCollection/classes/Fields/Formula/class.ilDclFormulaRecordFieldModel.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6271 UI, Docu: allow docu-entries for array-returns and outside of UI/Component
  src/UI/Implementation/Crawler/EntriesYamlParser.php
  src/UI/Implementation/Crawler/Entry/ComponentEntry.php
  src/UI/examples/Help/Topic/HelpTopics/base.php
  tests/UI/Crawler/Entry/ComponentEntryTest.php
Labels: bugfix, kitchen sink

#6356 LSO: add error message if "Download Multiple Objects" is used. (#…
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#6365 Docs: use npm clean-install instead of install
  docs/configuration/install.md
Labels: improvement

#6437 Show Only Points
  Modules/Test/classes/MainSettings/ilObjTestSettingsQuestionBehaviour.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestQuestionHeaderBlockBuilder.php
  Modules/Test/classes/class.ilTestService.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6357 9/UI/buttons no press transform on active state
  templates/default/030-tools/_tool_buttons.scss
  templates/default/070-components/UI-framework/Button/_ui-component_button.scss
  templates/default/delos.css
Labels: improvement

#6395 9/UI/symbol/icon width on mobile 38166
  templates/default/070-components/UI-framework/Symbol/_ui-component_icon.scss
  templates/default/delos.css
Labels: bugfix

#6397 9/UI/image responsive max width fix 37743
  templates/default/050-layout/_layout_responsive-img.scss
  templates/default/delos.css
Labels: bugfix

#6400 9/UI/item drodown pull 38054
  templates/default/030-tools/_tool_clearfix.scss
  templates/default/050-layout/_layout_pull-float.scss
  templates/default/070-components/UI-framework/Item/_ui-component_item.scss
  templates/default/080-hacks/_index.scss
  templates/default/delos.css
Labels: bugfix

#6382 [FEATURE] UI: add chunked-upload for file-inputs.
  Services/Init/classes/Dependencies/InitUIFramework.php
  src/UI/Component/Input/Field/FileUpload.php
  src/UI/Implementation/Component/Input/Field/FieldRendererFactory.php
  src/UI/Implementation/Component/Input/Field/File.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/Implementation/Component/Input/UploadLimitResolver.php
  src/UI/Implementation/Component/Symbol/Glyph/GlyphRendererFactory.php
  src/UI/Implementation/Component/Symbol/Icon/IconRendererFactory.php
  src/UI/Implementation/Render/AbstractComponentRenderer.php
  src/UI/Implementation/Render/DefaultRendererFactory.php
  src/UI/ROADMAP.md
  src/UI/templates/js/Input/Field/file.js
  tests/UI/Base.php
  tests/UI/Component/Input/UploadLimitResolverTest.php
  tests/UI/Component/Input/ViewControl/ViewControlPaginationTest.php
  tests/UI/Component/Symbol/Glyph/GlyphTest.php
  tests/UI/Component/Table/DataRendererTest.php
  tests/UI/Renderer/AbstractRendererTest.php
  tests/UI/Renderer/ComponentRendererFSLoaderTest.php
Labels: kitchen sink, improvement

#6445 Improvements for DateTime/Duration Input
  Modules/Test/test/ScoreSettingsTest.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  src/UI/templates/default/Input/tpl.date.html
  tests/UI/Component/Input/Field/DurationInputTest.php
Labels: bugfix, kitchen sink, improvement

#6427 0038259: Typed property ilFileDataMail::$ilias must not be accessed before initialization
  Services/Mail/classes/class.ilFileDataMail.php
Labels: bugfix

#6374 filter: fixed 38103: Deleting a Comment throws error
  Services/UI/classes/class.ilUIFilterService.php
Labels: bugfix, kitchen sink

#6446 UI: Fix withValue with DateTimeImmutable
  Modules/IndividualAssessment/classes/ilIndividualAssessmentUserGrading.php
  src/UI/Implementation/Component/Input/Field/DateTime.php
  src/UI/Implementation/Component/Input/Field/Renderer.php
  tests/UI/Component/Input/Field/DateTimeInputTest.php
Labels: bugfix

#6453 Update Dependencies after Release v7.26
  composer.lock
Labels: technical board, dependencies

#6452 Update Dependencies after Release v8.6
  composer.lock
Labels: technical board, dependencies

#6405 ContainerReference: fix saving of title when switching from custom to reused (38221)
  Services/ContainerReference/classes/class.ilContainerReferenceGUI.php
Labels: bugfix, php

#6408 SVY: adjust english language variable for deleting...
  lang/ilias_en.lang
Labels: bugfix

#6409 Navigation: 37409 check if type of item is a known plugin id
  Services/Navigation/classes/class.ilNavigationHistory.php
Labels: bugfix

#6448 UICore: Remove Lightbox Related Functions
  Modules/DataCollection/classes/class.ilDataCollectionGlobalTemplate.php
  Services/RTE/classes/class.ilRTEGlobalTemplate.php
  Services/UICore/classes/MetaTemplate/PageContentGUI.php
  Services/UICore/classes/class.ilGlobalPageTemplate.php
  Services/UICore/classes/class.ilGlobalTemplate.php
  Services/UICore/interfaces/interface.ilGlobalTemplateInterface.php
  templates/default/tpl.page_content.html
Labels: improvement, php

#6454 9/UI/fix submit button on wrong side
  src/UI/templates/default/Modal/tpl.roundtrip.html
  tests/UI/Component/Dropzone/File/StandardTest.php
  tests/UI/Component/Dropzone/File/WrapperTest.php
  tests/UI/Component/Launcher/LauncherInlineTest.php
Labels: bugfix, kitchen sink

#6450 UI Components, Select Input: Display null if value set and required
  src/UI/Implementation/Component/Input/Field/Renderer.php
  tests/UI/Component/Input/Field/SelectTest.php
Labels: bugfix, kitchen sink, improvement

#6457 UI Feature: New Symbol Imprint
  src/UI/Component/Symbol/Icon/Standard.php
  src/UI/Implementation/Component/Symbol/Icon/Standard.php
  templates/default/images/standard/icon_impr.svg
Labels: kitchen sink, improvement, php

#6298 Trunk: Test: Use Launcher to Start the ILIAS Test
  Modules/Test/classes/MainSettings/class.ilObjTestSettingsMainGUI.php
  Modules/Test/classes/MainSettings/ilObjTestMainSettings.php
  Modules/Test/classes/MainSettings/ilObjTestMainSettingsDatabaseRepository.php
  Modules/Test/classes/MainSettings/ilObjTestSettingsAdditional.php
  Modules/Test/classes/MainSettings/ilObjTestSettingsIntroduction.php
  Modules/Test/classes/Setup/class.ilTest9DBUpdateSteps.php
  Modules/Test/classes/TestScreen/class.ilTestScreenGUI.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilObjTestAccess.php
  Modules/Test/classes/class.ilObjTestGUI.php
  Modules/Test/classes/class.ilTestOutputGUI.php
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
  Modules/Test/classes/class.ilTestSession.php
  Modules/Test/classes/class.ilTestTabsManager.php
  Modules/Test/classes/toolbars/class.ilTestInfoScreenToolbarGUI.php
  Services/Object/classes/class.ilObjectListGUI.php
  Services/Repository/GlobalScreen/classes/RepositoryMainBarProvider.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6471 Services/Notifications: Fix incomplete class in unserialize
  Services/Notifications/classes/Repository/ilNotificationOSDRepository.php
Labels: bugfix, php

#6464 User: Fix `Mustache` migration for welcome mail
  Services/User/classes/Setup/Migration/class.ilUpdateNewAccountMailTemplatesForMustache.php
Labels: bugfix, php

#6473 Test: Change Bylines to adapt new Features
  lang/ilias_de.lang
Labels: improvement

#6468 Services/Badge: Clean up the Badges area in Achievements
  Services/Badge/GlobalScreen/BadgeMainBarProvider.php
  Services/Badge/classes/BadgeParent.php
  Services/Badge/classes/Modal.php
  Services/Badge/classes/ModalContent.php
  Services/Badge/classes/PresentationHeader.php
  Services/Badge/classes/Sorting.php
  Services/Badge/classes/Tile.php
  Services/Badge/classes/TileView.php
  Services/Badge/classes/class.ilBadgePersonalTableGUI.php
  Services/Badge/classes/class.ilBadgeProfileGUI.php
  Services/Badge/classes/class.ilBadgeRenderer.php
  Services/Badge/classes/class.ilBadgeTableGUI.php
  Services/Badge/classes/class.ilObjectBadgeTableGUI.php
  Services/Badge/templates/default/tpl.badge_row.html
  Services/Badge/templates/default/tpl.object_badge_row.html
  Services/Badge/templates/default/tpl.personal_row.html
  Services/Badge/test/BadgeManagementSessionRepositoryTest.php
  Services/Badge/test/BadgeParentTest.php
  Services/Badge/test/ModalTest.php
  Services/Badge/test/PresentationHeaderTest.php
  Services/Badge/test/SortingTest.php
  Services/Badge/test/TileTest.php
  Services/Badge/test/TileViewTest.php
  Services/Badge/test/ilServicesBadgeSuite.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6414 AccessControl: Make items with preconditions clickable in Tree View (#28292)
  Services/Repository/classes/class.ilRepositoryExplorerGUI.php
Labels: bugfix

#6459 UI, DataTable: add a LinkColumn
  src/UI/Component/Table/Column/Factory.php
  src/UI/Component/Table/Column/Link.php
  src/UI/Component/Table/DataRow.php
  src/UI/Implementation/Component/Table/Column/Column.php
  src/UI/Implementation/Component/Table/Column/Factory.php
  src/UI/Implementation/Component/Table/Column/Link.php
  src/UI/Implementation/Component/Table/DataRow.php
  src/UI/Implementation/Component/Table/Renderer.php
  src/UI/ROADMAP.md
  src/UI/examples/Table/Column/Link/base.php
  tests/UI/Component/Table/Column/ColumnFactoryTest.php
  tests/UI/Component/Table/Column/ColumnTest.php
Labels: kitchen sink

#6479 Test: Remove Settings Result Filter
  Modules/Test/classes/ScoreReporting/class.ilObjTestScoreSettingsDatabaseRepository.php
  Modules/Test/classes/ScoreReporting/ilObjTestSettingsResultDetails.php
  Modules/Test/classes/Setup/class.ilTest9DBUpdateSteps.php
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestEvalObjectiveOrientedGUI.php
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Modules/Test/classes/class.ilTestFixedQuestionSetConfig.php
  Modules/Test/classes/class.ilTestQuestionSetConfig.php
  Modules/Test/classes/class.ilTestRandomQuestionSetConfig.php
  Modules/Test/classes/class.ilTestServiceGUI.php
  Modules/Test/classes/tables/class.ilTestPassDetailsOverviewTableGUI.php
  Modules/Test/test/ScoreSettingsTest.php
  lang/ilias_ar.lang
  lang/ilias_bg.lang
  lang/ilias_cs.lang
  lang/ilias_da.lang
  lang/ilias_de.lang
  lang/ilias_el.lang
  lang/ilias_en.lang
  lang/ilias_es.lang
  lang/ilias_et.lang
  lang/ilias_fa.lang
  lang/ilias_fr.lang
  lang/ilias_hr.lang
  lang/ilias_hu.lang
  lang/ilias_it.lang
  lang/ilias_ja.lang
  lang/ilias_ka.lang
  lang/ilias_lt.lang
  lang/ilias_nl.lang
  lang/ilias_pl.lang
  lang/ilias_pt.lang
  lang/ilias_ro.lang
  lang/ilias_ru.lang
  lang/ilias_sk.lang
  lang/ilias_sl.lang
  lang/ilias_sq.lang
  lang/ilias_sr.lang
  lang/ilias_tr.lang
  lang/ilias_uk.lang
  lang/ilias_vi.lang
  lang/ilias_zh.lang
Labels: improvement

#6481 UI, Table: fix example of LinkColumn
  src/UI/examples/Table/Column/Link/base.php
Labels: improvement

#6480 UI/Table: move Column::withIsInitiallyVisible to ::withIsOptional (#38070)
  src/UI/Component/Table/Column/Column.php
  src/UI/Implementation/Component/Table/Column/Column.php
  src/UI/examples/Table/Data/base.php
  src/UI/examples/Table/Data/repo_implementation.php
  tests/UI/Component/Table/Column/ColumnTest.php
  tests/UI/Component/Table/DataTest.php
Labels: jour fixe, improvement

#6078 Registration: Fix date for absolute date access limitations
  Services/Registration/classes/class.ilRegistrationSettingsGUI.php
Labels: bugfix, php

#6476 [9] Revamp Thread-Tab of Forum
  Modules/Forum/classes/class.ilForumDraftsTableGUI.php
  Modules/Forum/classes/class.ilForumExportGUI.php
  Modules/Forum/classes/class.ilForumProperties.php
  Modules/Forum/classes/class.ilForumThreadObjectTableGUI.php
  Modules/Forum/classes/class.ilForumTopicTableGUI.php
  Modules/Forum/classes/class.ilObjForumGUI.php
  Modules/Forum/templates/default/tpl.forums_threads_move.html
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6483 T&A Bugfix #0038244: Title of test changes with export/import
  Modules/Test/classes/class.ilQuestionPageParser.php
Labels: bugfix

#6478 PRG: add action 'Update Certificate' for Members Tab
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/helpers/ilPRGUpdateCertificateHelper.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6477 FR PRG: Separate Training Acknowledgement (vs "Update from Current Plan")
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAcknowledgeCompletedCoursesTableGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/helpers/ilPRGMessageCollection.php
  Modules/StudyProgramme/classes/model/Assignments/Node.php
  Modules/StudyProgramme/classes/model/Assignments/PRGAssignmentRepository.php
  Modules/StudyProgramme/classes/model/Assignments/PRGProgressId.php
  Modules/StudyProgramme/classes/model/Assignments/Zipper.php
  Modules/StudyProgramme/classes/model/Assignments/class.ilPRGAssignment.php
  Modules/StudyProgramme/classes/model/Assignments/class.ilPRGProgress.php
  Modules/StudyProgramme/classes/model/Assignments/ilPRGAssignmentActions.php
  Modules/StudyProgramme/classes/model/Assignments/ilPRGUserInformation.php
  Modules/StudyProgramme/templates/default/tpl.acknowledge_completed_courses.html
  Modules/StudyProgramme/templates/default/tpl.acknowledge_completed_courses_row.html
  Services/Tracking/classes/status/class.ilLPStatusStudyProgramme.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#5791 Administration (ILIAS 9): Feature: common administrative node »Legal Regulations«
  Modules/SystemFolder/classes/class.ilObjSystemFolderGUI.php
  Services/Administration/GlobalScreen/classes/AdministrationMainBarProvider.php
  Services/Imprint/classes/Setup/ImprintUpdateAgent.php
  Services/Imprint/classes/class.ilImprintGUI.php
  Services/Imprint/classes/class.ilObjLegalNotice.php
  Services/Imprint/classes/class.ilObjLegalNoticeAccess.php
  Services/Imprint/classes/class.ilObjLegalNoticeGUI.php
  Services/Imprint/service.xml
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6489 Services/LegalDocuments: Add missing property
  Services/LegalDocuments/classes/ConsumerToolbox/Blocks.php
Labels: bugfix, php

#6488 Services/Init, Services/COPage: Split DataProtection and ToS into separate placeholders (ILIAS 9)
  Services/COPage/classes/class.ilPCLoginPageElement.php
  Services/Init/classes/class.ilStartUpGUI.php
  Services/Init/templates/default/tpl.login.html
  Services/LegalDocuments/classes/Conductor.php
  Services/LegalDocuments/classes/Wiring.php
  Services/LegalDocuments/test/ConductorTest.php
  Services/LegalDocuments/test/WiringTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6490 Services/LegalDocuments add missing prop in Administration
  Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
  Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
  Services/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
Labels: bugfix, php

#6434 Calendar: Change length of title field to match length of object title (#31368)
  Services/Calendar/classes/Setup/class.ilCalendarDBUpdateSteps8.php
Labels: bugfix

#6431 Course: Handle autofill after changing course member settings (#29388)
  Modules/Course/classes/class.ilObjCourseGUI.php
Labels: bugfix

#6420 fix #37833 Ls as precondition for a subsequent object
  Services/Tracking/classes/status/class.ilLPStatusCollection.php
Labels: bugfix

#6384 Search: Fix User Search
  Services/Search/classes/class.ilRepositorySearchGUI.php
Labels: bugfix, php

#6492 Services/LegalDocuments: Add missing file upload property
  Services/LegalDocuments/classes/HTMLPurifier.php
  Services/LegalDocuments/test/Legacy/ConfirmationTest.php
Labels: bugfix, php

#6491 Services/Mail: Add missing namespace
  Services/Mail/classes/Recipient.php
  Services/Mail/classes/class.ilMail.php
  Services/Mail/test/RecipientTest.php
Labels: bugfix, php

#6321 Fix 37898: Use ilPropertyFromGUI to access post values
  Modules/Category/classes/class.ilObjCategoryGUI.php
  Modules/Course/classes/class.ilObjCourseGUI.php
  Modules/Glossary/classes/class.ilObjGlossaryGUI.php
  Modules/Group/classes/class.ilObjGroupGUI.php
  Modules/LearningModule/classes/class.ilObjContentObjectGUI.php
  Modules/Wiki/classes/class.ilObjWikiGUI.php
  Services/WebServices/ECS/classes/class.ilECSObjectSettings.php
Labels: bugfix

#6415 Fix 31639: redirect loop when session expireds
  Services/Authentication/classes/class.ilSession.php
  Services/Init/classes/class.ilInitialisation.php
  Services/Init/classes/class.ilStartUpGUI.php
Labels: bugfix

#6507 Use: Validate "welcome mail" `Mustache` template
  Services/User/classes/class.ilObjUserFolderGUI.php
  Services/User/templates/default/tpl.usrf_new_account_mail.html
Labels: bugfix, php

#6495 Init: Change password assistance info message when submitting form
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#6513 [FIX] Tile Image Upload in Legacy Forms
  Services/Object/classes/CommonSettings/class.ilObjectCommonSettingFormAdapter.php
  Services/Object/classes/CommonSettings/class.ilObjectCommonSettings.php
  Services/Object/classes/ilObjectDIC.php
Labels: bugfix, improvement
