Repository ILIAS-eLearning/ILIAS, pull requests merged in 2024-03, with the labels that each got.

#7117 Bugfix/Improvement: 0040683 Added info text. Changed modal behaviour.
  Modules/Forum/classes/GUI/class.ilForumThreadFormGUI.php
  Modules/Forum/classes/class.ilObjForumGUI.php
Labels: bugfix, improvement, php

#7119 Fix/9/dcl migration issues
  Modules/DataCollection/classes/Setup/class.ilDataCollectionStorageMigration.php
  Modules/DataCollection/classes/class.ilDataCollectionStakeholder.php
Labels: bugfix

#7106 9/UI/viewcontrols nav arrows shifted for section 40648
  templates/default/070-components/UI-framework/ViewControl/_ui-component_viewcontrol.scss
  templates/default/delos.css
Labels: bugfix

#7123 Registration: Fix preselection of radio button in role access configu…
  Services/Registration/classes/class.ilRegistrationSettingsGUI.php
Labels: bugfix, php

#6637 38618: Cron job 'ECS Task Scheduler': Remove debug output (trunk)
  components/ILIAS/WebServices/ECS/classes/class.ilECSConnector.php
Labels: bugfix

#6638 38618: Cron job 'ECS Task Scheduler': Remove debug output (release_8)
  Services/WebServices/ECS/classes/class.ilECSConnector.php
Labels: bugfix

#6639 38618: Cron job 'ECS Task Scheduler': Remove debug output (release_7)
  Services/WebServices/ECS/classes/class.ilECSConnector.php
Labels: bugfix

#7059 T&A: fix for mantis-Issue #35942
  Modules/Test/classes/class.ilTestGradingMessageBuilder.php
Labels: bugfix

#7060 T&A: fixes mantis-Issue #35942
  Modules/Test/classes/class.ilTestGradingMessageBuilder.php
Labels: bugfix

#7099 T&A 0040614: Starting test with "Use Previous Answers" activated leads to fatal type error
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
  Modules/TestQuestionPool/classes/class.assQuestion.php
Labels: bugfix

#6398 Docs: Introducing Authorities
  components/ILIAS/UI/docs/COMMUNITY.md
  docs/development/contributing.md
  docs/development/maintenance.md
Labels: technical board

#7076 T&A: Missing "s" in Label #39867
  lang/ilias_en.lang
Labels: bugfix

#7107 User/MemberGallery: Fix missing user actions
  Services/User/classes/Actions/class.ilUserActionGUI.php
Labels: bugfix, php

#7113 LDAP: Fix type for object lookup when reading group mapping
  Services/LDAP/classes/class.ilLDAPRoleGroupMappingSettings.php
Labels: bugfix, php

#7114 LDAP: Fix deleting user if LDAP group mapping exists for role
  Services/LDAP/classes/class.ilLDAPRoleGroupMapping.php
Labels: bugfix, php

#7098 T&A 0040488 save and return' returns to question list instead of question page for questions from pool test
  Modules/TestQuestionPool/classes/class.assQuestionGUI.php
Labels: bugfix

#7066 CSVWriter: Remove usage of `utf8_decode`
  Services/CSV/classes/class.ilCSVWriter.php
Labels: bugfix, php

#7065 CSVUtil: Remove usage of `utf8_decode`
  Services/CSV/classes/class.ilCSVUtil.php
Labels: bugfix, php

#6970 Init: Modify global screen for forced startup steps
  Services/Init/classes/StartupSequence/StartUpSequenceDispatcher.php
  Services/Init/classes/StartupSequence/StartUpSequenceLayoutProvider.php
Labels: bugfix, php

#6835 LDAP: Fix return value of `\ilAuthProviderLDAP::changeKeyCase`
  Services/LDAP/classes/class.ilAuthProviderLDAP.php
Labels: bugfix, php

#7110 9 mantis ilias 40569
  Modules/Course/classes/Objectives/class.ilCourseObjectiveQuestion.php
Labels: bugfix, php

#7077 Setup: adjust text for numbers of found migrations. (#40438)
  src/Setup/CLI/MigrateCommand.php
Labels: bugfix

#7094 PRG: 40621, link to local roles' user assignment
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoMembershipsGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeDIC.php
Labels: bugfix

#7128 PRG: 40536, missing format in lang-string
  lang/ilias_en.lang
Labels: bugfix

#7126 PRG: 40674, relevance as single action / do not change relevance of successful progress
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/model/Assignments/ilPRGAssignmentActions.php
Labels: bugfix

#7127 PRG/PrivacySettings: 40553, PRG does not have separate 'export_member_data' permission
  Services/PrivacySecurity/classes/class.ilPrivacySettings.php
Labels: bugfix

#7102 9/UI/legacy-toolbar refactoring, removing hamburger collapse 40080
  Services/UIComponent/Toolbar/classes/class.ilToolbarGUI.php
  Services/UIComponent/Toolbar/templates/default/tpl.toolbar.html
  Services/UIComponent/Toolbar/templates/default/tpl.toolbar_itemgroup.html
  Services/UIComponent/Toolbar/templates/default/tpl.toolbar_items.html
  Services/UIComponent/Toolbar/templates/default/tpl.toolbar_separator.html
  Services/UIComponent/Toolbar/templates/default/tpl.toolbar_sticky_items.html
  src/UI/templates/default/Input/tpl.viewcontrol_container.html
  src/UI/templates/default/Item/tpl.item_standard.html
  src/UI/templates/default/Listing/tpl.propertylisting.html
  src/UI/templates/default/Panel/tpl.listing_standard.html
  src/UI/templates/default/Panel/tpl.secondary.html
  src/UI/templates/default/Panel/tpl.standard.html
  src/UI/templates/default/Table/tpl.presentationrow.html
  src/UI/templates/default/Table/tpl.presentationtable.html
  templates/default/050-layout/_layout_element-bar.scss
  templates/default/070-components/UI-framework/ViewControl/_ui-component_viewcontrol.scss
  templates/default/070-components/legacy/Services/UIComponent/_component_toolbar.scss
  templates/default/delos.css
  tests/UI/Component/Item/ItemTest.php
  tests/UI/Component/Listing/Property/PropertyListingTest.php
  tests/UI/Component/Panel/PanelSecondaryLegacyTest.php
  tests/UI/Component/Panel/PanelSecondaryListingTest.php
  tests/UI/Component/Panel/PanelTest.php
  tests/UI/Component/Table/PresentationTest.php
Labels: bugfix, php

#7144 [Docu] DevTutorial: Created Directory and Placeholder mds
  docs/development/devguide/tutorial/01-community/01-interaction.md
  docs/development/devguide/tutorial/01-community/02-resources.md
  docs/development/devguide/tutorial/01-community/03-development-process.md
  docs/development/devguide/tutorial/01-community/04-type-of-docs.md
  docs/development/devguide/tutorial/02-tools/01-environment.md
  docs/development/devguide/tutorial/02-tools/02-dependencies.md
  docs/development/devguide/tutorial/02-tools/03-setup.md
  docs/development/devguide/tutorial/02-tools/04-toolstack.md
  docs/development/devguide/tutorial/03-development/01-directories.md
  docs/development/devguide/tutorial/03-development/02-versioning.md
  docs/development/devguide/tutorial/03-development/03-endpoints.md
  docs/development/devguide/tutorial/04-coding/01-components.md
  docs/development/devguide/tutorial/04-coding/02-control.md
  docs/development/devguide/tutorial/04-coding/03-repository.md
  docs/development/devguide/tutorial/04-coding/04-ui-framework.md
  docs/development/devguide/tutorial/04-coding/05-ui-inputs.md
  docs/development/devguide/tutorial/04-coding/06-globalscreen.md
  docs/development/devguide/tutorial/04-coding/07-persistence.md
  docs/development/devguide/tutorial/05-contributing/01-bugfixes.md
  docs/development/devguide/tutorial/05-contributing/02-plugin.md
  docs/development/devguide/tutorial/05-contributing/03-ui-component.md
  docs/development/devguide/tutorial/05-contributing/04-core-component.md
  docs/development/devguide/tutorial/05-contributing/README.md
  docs/development/devguide/tutorial/06-extending/01-xml-handling.md
  docs/development/devguide/tutorial/06-extending/02-webservices.md
  docs/development/devguide/tutorial/README.md
Labels: documentation

#6509 Update language.md fixed typos
  docs/development/language.md
Labels: improvement, documentation

#6914 [Docu] DevTutorial: Text Proposal UI Component
  components/ILIAS/UI/README.md
  docs/development/devguide/tutorial/05-contributing/03-ui-component.md
Labels: kitchen sink, documentation

#7148 Container: fetch timing information before sorting (40141)
  Services/Container/Content/class.ItemSetManager.php
Labels: bugfix, php

#7150 Test: Feature IP-Ranges
  components/ILIAS/Test/classes/AccessFileUploadAnswer.php
  components/ILIAS/Test/classes/MainSettings/class.ilObjTestSettingsMainGUI.php
  components/ILIAS/Test/classes/MainSettings/ilObjTestMainSettings.php
  components/ILIAS/Test/classes/MainSettings/ilObjTestMainSettingsDatabaseRepository.php
  components/ILIAS/Test/classes/MainSettings/ilObjTestSettingsAccess.php
  components/ILIAS/Test/classes/Setup/class.ilTest10DBUpdateSteps.php
  components/ILIAS/Test/classes/Setup/class.ilTestSetupAgent.php
  components/ILIAS/Test/classes/TestScreen/class.ilTestScreenGUI.php
  components/ILIAS/Test/classes/class.ilObjTest.php
  components/ILIAS/Test/classes/class.ilObjTestAccess.php
  components/ILIAS/Test/classes/class.ilObjTestGUI.php
  components/ILIAS/Test/classes/class.ilObjTestListGUI.php
  components/ILIAS/Test/classes/class.ilTestAccess.php
  components/ILIAS/Test/classes/class.ilTestCorrectionsGUI.php
  components/ILIAS/Test/classes/class.ilTestEvaluationGUI.php
  components/ILIAS/Test/classes/class.ilTestPlayerAbstractGUI.php
  components/ILIAS/Test/src/Access/ParticipantAccess.php
  components/ILIAS/Test/tests/MainSettings/ilObjTestMainSettingsTest.php
  components/ILIAS/Test/tests/Setup/ilTestSetupAgentTest.php
  components/ILIAS/Test/tests/TestScreen/ilTestScreenGUITest.php
  components/ILIAS/Test/tests/ilTestAccessTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6702 UI/DataTable: 39206, generate translated ordering options by columntype
  Services/Init/classes/Dependencies/InitUIFramework.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Component/Table/Column/Column.php
  src/UI/Implementation/Component/Table/Column/Boolean.php
  src/UI/Implementation/Component/Table/Column/Column.php
  src/UI/Implementation/Component/Table/Column/Date.php
  src/UI/Implementation/Component/Table/Column/EMail.php
  src/UI/Implementation/Component/Table/Column/Factory.php
  src/UI/Implementation/Component/Table/Column/Link.php
  src/UI/Implementation/Component/Table/Column/LinkListing.php
  src/UI/Implementation/Component/Table/Column/Number.php
  src/UI/Implementation/Component/Table/Column/Status.php
  src/UI/Implementation/Component/Table/Column/Text.php
  src/UI/Implementation/Component/Table/Column/TimeSpan.php
  src/UI/Implementation/Component/Table/Data.php
  src/UI/examples/Table/Data/base.php
  tests/UI/Component/Table/Column/ColumnFactoryTest.php
  tests/UI/Component/Table/Column/ColumnTest.php
  tests/UI/Component/Table/DataRendererTest.php
  tests/UI/Component/Table/TableTestBase.php
Labels: bugfix, kitchen sink

#7153 chatserver bugfix: superflous colon in config.json example causes wrong parsing
  Modules/Chatroom/README.md
Labels: bugfix, documentation

#7142 PRG: 40519, no deadline if latest assignment is not in progress
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMailTemplateContext.php
Labels: bugfix

#7156 Fix MantisBug 40759: TypeError strlen() expects parameter 1 to be string, null given
  Services/Language/classes/class.ilLanguageExtTableGUI.php
Labels: bugfix, php

#7158 Saml: Enable Unitests
  Services/Saml/phpunit.xml
  Services/Saml/test/ilSamlIdpXmlMetadataParserTest.php
  Services/Saml/test/ilServicesSamlSuite.php
Labels: bugfix, php

#7139 LDAP: Fix role selection
  Services/LDAP/classes/class.ilLDAPSettingsGUI.php
Labels: bugfix, php

#7001 0040263: Whoops\Exception\ErrorException thrown with message "UilObje…
  Services/Repository/Trash/class.ilRepUtil.php
Labels: bugfix, php

#7161 Saml: Enable Unitests (8)
  Services/Saml/phpunit.xml
  Services/Saml/test/ilServicesSamlSuite.php
Labels: bugfix, php

#7169 adds missing dataset record xml tag
  Services/DataSet/classes/class.ilDataSet.php
Labels: improvement, php

#7157 CSS: Fix Add New Item Scrollbars
  templates/default/070-components/legacy/Services/_component_object.scss
  templates/default/delos.css
Labels: bugfix

#7173 LegalDocuments: Redirect on unavailable page
  Services/LegalDocuments/classes/Conductor.php
  Services/LegalDocuments/test/ConductorTest.php
Labels: bugfix, php

#7174 LegalDocuments: Redirect on unavailable page (trunk)
  components/ILIAS/LegalDocuments/classes/Conductor.php
  components/ILIAS/LegalDocuments/tests/ConductorTest.php
Labels: bugfix, php

#7176 0040826: Unable to open "News Settings" in forum of an older thread
  Modules/Forum/classes/Notification/class.ilForumNotification.php
Labels: bugfix, php

#7179 Chatroom: Prevent double HTML escaping when sending messages
  Modules/Chatroom/js/chat.js
Labels: bugfix, php

#7180 Chatroom: Prevent double HTML escaping when sending messages (trunk)
  components/ILIAS/Chatroom/js/chat.js
Labels: bugfix, php

#7178 0040826: Unable to open "News Settings" in forum of an older thread
  components/ILIAS/Forum/classes/Notification/class.ilForumNotification.php
Labels: bugfix, php

#7177 0040826: Unable to open "News Settings" in forum of an older thread
  Modules/Forum/classes/Notification/class.ilForumNotification.php
Labels: bugfix, php

#7152 Ildcl unique f02
  components/ILIAS/DataCollection/classes/Fields/Base/class.ilDclBaseFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/Base/class.ilDclBaseRecordFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/Number/class.ilDclNumberFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/Text/class.ilDclTextFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/class.ilDclFieldEditGUI.php
  components/ILIAS/DataCollection/classes/Fields/class.ilDclFieldFactory.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6508 Update headlines.md fixed typo issues
  docs/development/headlines.md
Labels: improvement, documentation

#7132 [FIX] UI: Improve documentation about plugin manipulations
  docs/development/code-examples/ui-exchange/00_base_classes/ExamplePlugin.php
  docs/development/code-examples/ui-exchange/00_base_classes/ExampleRenderer.php
  docs/development/code-examples/ui-exchange/custom-components/ExamplePlugin.php
  docs/development/code-examples/ui-exchange/custom-components/HelloWorld.php
  docs/development/code-examples/ui-exchange/custom-components/HelloWorldRenderer.php
  docs/development/code-examples/ui-exchange/rendering-manipulations/ExamplePlugin.php
  docs/development/code-examples/ui-exchange/rendering-manipulations/ExampleRenderer.php
  docs/development/ui-plugin-manipulations.md
Labels: kitchen sink, improvement, documentation

#7165 TestQuestionPool: Fix query in lucene definition file
  Modules/TestQuestionPool/LuceneObjectDefinition.xml
Labels: bugfix, improvement

#7134 SETUP: adjust code for skipping a major update. (#40142)
  setup/classes/class.ilNoMajorVersionSkippedConditionObjective.php
Labels: bugfix

#7200 PRG: 40853, fix iteration over assignments to acknowledge multiple user/courses
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
Labels: bugfix

#7125 PRG: 40568, get PRGIds from post (update cert)
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeMembersGUI.php
Labels: bugfix, php

#7202 Fix listing of subtypes within the dashboard
  Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
Labels: bugfix, php

#7138 Set "current version" after update
  Services/Component/classes/class.ilPluginDBUpdate.php
  Services/Database/classes/class.ilDBUpdate.php
Labels: bugfix, php

#7207 PRG: 40862, fix typo in function call
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix, php

#7204 Fix license, remove docs and add use in dashboard
  Services/Dashboard/Access/class.DashboardAccess.php
  Services/Dashboard/Achievements/classes/class.ilAchievements.php
  Services/Dashboard/Achievements/classes/class.ilAchievementsGUI.php
  Services/Dashboard/Administration/classes/class.ilObjDashboardSettings.php
  Services/Dashboard/Administration/classes/class.ilObjDashboardSettingsAccess.php
  Services/Dashboard/Administration/classes/class.ilObjDashboardSettingsGUI.php
  Services/Dashboard/Administration/js/SortationUserInputHandler.js
  Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
  Services/Dashboard/Block/js/ReplaceModalContent.js
  Services/Dashboard/GlobalScreen/classes/DashboardLayoutProvider.php
  Services/Dashboard/ItemsBlock/classes/class.ilDashObjectsTableGUI.php
  Services/Dashboard/ItemsBlock/classes/class.ilDashObjectsTableRenderer.php
  Services/Dashboard/ItemsBlock/classes/class.ilDashboardSidePanelSettingsRepository.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemBlockMembershipsDTO.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockGroup.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockMembershipsObjectDatabaseRepository.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockMembershipsProvider.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockSelectedItemsProvider.php
  Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockViewSettings.php
  Services/Dashboard/ItemsBlock/interfaces/interface.ilPDSelectedItemsBlockMembershipsObjectRepository.php
  Services/Dashboard/ItemsBlock/interfaces/interface.ilPDSelectedItemsBlockProvider.php
  Services/Dashboard/classes/Setup/ilDashboardUpdateAgent.php
  Services/Dashboard/classes/class.ilDashboardContentBlockGUI.php
  Services/Dashboard/classes/class.ilDashboardGUI.php
  Services/Dashboard/classes/class.ilPersonalDesktopSettingsRepository.php
  Services/Dashboard/interfaces/interface.ilDesktopItemHandling.php
  Services/Dashboard/test/DashboardViewSettingsTest.php
  Services/Dashboard/test/ilServicesDashboardSuite.php
Labels: improvement, php, javascript, documentation

#7184 9 sess xsd adjustment
  xml/SchemaValidation/ilias_sess_7.xsd
  xml/SchemaValidation/ilias_sess_9.xsd
Labels: bugfix

#7209 Session: fix importing/exporting registration settings (29750)
  Modules/Session/classes/class.ilSessionDataSet.php
  Modules/Session/classes/class.ilSessionExporter.php
Labels: bugfix, php

#7212 PRG: 40839, fix null-values in columns for optional user fields
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#7135 ILIAS 8/App: Restrict PHP version to 7.4/8.0
  .github/workflows/checks.yml
  .github/workflows/legacy-ui.yml
  composer.json
  composer.lock
Labels: bugfix, technical board, php

#7172 UI: remove icon's alt txt input if icon label is the same as the node…
  src/UI/Implementation/Component/Symbol/Icon/Icon.php
  src/UI/Implementation/Component/Tree/Node/Renderer.php
  tests/UI/Component/Symbol/Icon/IconTest.php
  tests/UI/Component/Tree/Node/SimpleNodeTest.php
Labels: bugfix

#7228 Language: Fix wrong path to template
  components/ILIAS/Language/classes/class.ilLanguageTableGUI.php
Labels: bugfix, php

#7226 9 mantis ilias 34068
  Services/Calendar/classes/class.ilCalendarPresentationGUI.php
Labels: bugfix, php

#7225 7 mantis ilias 26662
  Services/Calendar/classes/class.ilCalendarPresentationGUI.php
Labels: bugfix, php

#7088 8 mantis ilias 37850
  Services/AccessControl/classes/class.ilClaimingPermissionHelper.php
  Services/AdvancedMetaData/classes/class.ilAdvancedMDPermissionHelper.php
  Services/User/classes/class.ilUDFPermissionHelper.php
Labels: bugfix, php

#7039 Survey: Fix a small bug that leads to a non-empty array
  Modules/Survey/classes/class.ilObjSurvey.php
Labels: improvement

#7213 Mantis #40873 - Fix representation of unfinalized kprim questions in ILIAS learning module
  Modules/TestQuestionPool/classes/class.assKprimChoice.php
Labels: bugfix

#7229 [FIX] #40890 Component: streamline plugin environment.
  Services/Component/classes/Setup/class.ilComponentActivatePluginsObjective.php
  Services/Component/classes/Setup/class.ilComponentInstallPluginObjective.php
  Services/Component/classes/Setup/class.ilComponentUpdatePluginObjective.php
Labels: bugfix, php

#7215 UI: Change text for the default option of a required Selectbox
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Input/Field/Renderer.php
  tests/UI/Component/Input/Field/SelectTest.php
Labels: kitchen sink, improvement, php

#7217 UI: Add label to datatable bulk actions. Add datatable requried flag
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/Implementation/Component/Table/Renderer.php
Labels: kitchen sink, improvement, php

#7231 PRG: 40753, list/link succesfull_by objects
  Modules/StudyProgramme/classes/class.ilStudyProgrammeIndividualPlanTableGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeUserTable.php
  Modules/StudyProgramme/classes/ilStudyProgrammeUserTableRow.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#7129 9 mantis ilias 40106, iass schema adjustments
  xml/SchemaValidation/ilias_iass_9_0.xsd
Labels: bugfix, php

#7234 LegalDocuments: Use correct timestamp for accepted version
  Services/LegalDocuments/classes/Repository/DatabaseHistoryRepository.php
Labels: bugfix, php

#7235 LegalDocuments: Use correct timestamp for accepted version (trunk)
  components/ILIAS/LegalDocuments/classes/Repository/DatabaseHistoryRepository.php
Labels: bugfix, php

#7206 Block: fix path to component-specific block classes (40822)
  components/ILIAS/Block/classes/class.ilColumnGUI.php
Labels: bugfix, php

#7223 0040595: Undefined array key "BlockAfterPassed"
  Modules/Test/classes/class.ilObjTest.php
Labels: bugfix, php

#7233 [FIX] 0040897: Whoops\Exception\ErrorException thrown with message "U…
  Services/AdvancedMetaData/classes/Types/class.ilAdvancedMDFieldDefinitionText.php
Labels: bugfix

#7108 AdvMD: redesign form for editing selects for better stability
  Modules/Wiki/classes/class.ilPCAMDPageList.php
  Services/ADT/classes/Types/Enum/class.ilADTEnumSearchBridgeSingle.php
  Services/AdvancedMetaData/classes/Types/class.ilAdvancedMDFieldDefinitionSelect.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement, php

#7220 Update Dependencies after Release v7.29
  composer.lock
Labels: technical board, dependencies

#7221 Update Dependencies after Release v8.10
  composer.lock
Labels: technical board, dependencies

#7257 PRG: 40877, set back_url for user profile from automations
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoCategoriesGUI.php
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoMembershipsGUI.php
Labels: bugfix

#7256 Language/Setup: Add missing check for empty values before executing q…
  Services/Language/classes/Setup/class.ilSetupLanguage.php
Labels: bugfix, php

#7140 LSO: 39159, parent type for LSOPages (Intro/Extro), Migration and WAC
  Modules/LearningSequence/classes/PageEditor/LSOPageType.php
  Modules/LearningSequence/classes/PageEditor/ilLSOExtroPage.php
  Modules/LearningSequence/classes/PageEditor/ilLSOExtroPageConfig.php
  Modules/LearningSequence/classes/PageEditor/ilLSOIntroPage.php
  Modules/LearningSequence/classes/PageEditor/ilLSOIntroPageConfig.php
  Modules/LearningSequence/classes/Setup/class.LSOMigratePageIdsExtro.php
  Modules/LearningSequence/classes/Setup/class.LSOMigratePageIdsIntro.php
  Modules/LearningSequence/classes/Setup/class.ilLearningSequenceMigrationAgent.php
  Modules/LearningSequence/classes/class.ilLSLocalDI.php
  Modules/LearningSequence/classes/class.ilLearningSequenceExporter.php
  Modules/LearningSequence/classes/class.ilLearningSequenceImporter.php
  Modules/LearningSequence/classes/class.ilObjLearningSequence.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  Modules/LearningSequence/module.xml
Labels: bugfix

#7227 [FEATURE] UI: improve documentation about rendering tests.
  components/ILIAS/UI/README.md
Labels: kitchen sink, documentation

#7243 UI Core: 40906 use ampersand and question mark in preg_replace
  Services/UICore/classes/class.ilCtrl.php
Labels: bugfix, php

#7238 fixed 38856: Hilfe-Tooltip - Settings in persönlichen Settings
  Services/User/classes/Settings/class.ilPersonalSettingsGUI.php
Labels: bugfix

#7251 Ildcl unique f03
  components/ILIAS/DataCollection/classes/Content/class.ilDclRecordEditGUI.php
  components/ILIAS/DataCollection/classes/Fields/Boolean/class.ilDclBooleanFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/Datetime/class.ilDclDatetimeFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/Number/class.ilDclNumberFieldModel.php
  components/ILIAS/DataCollection/classes/Fields/class.ilDclFieldEditGUI.php
Labels: bugfix, php

#7258 SCORM/LearningProgress: Fix accessed undef. key
  Modules/ScormAicc/classes/SCORM/class.ilObjSCORMTracking.php
Labels: bugfix, php

#7044 Use spec-aligned date format when parsing LTI score timestamp
  Modules/LTIConsumer/classes/class.ilLTIConsumerGradeServiceScores.php
Labels: improvement

#7198 Possible fix for 39455: Failed test: # Input: Container → Filter → Standard validieren
  src/UI/Implementation/Component/Input/Container/Filter/Renderer.php
  src/UI/templates/default/Input/tpl.standard_filter.html
  tests/UI/Component/Input/Container/Filter/StandardFilterTest.php
Labels: bugfix

#7263 PRG: 40918, directly mark accredited progress as irrelevant
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
  Modules/StudyProgramme/classes/model/Assignments/ilPRGAssignmentActions.php
Labels: bugfix

#7241 UI: add padding to legacy UI's form buttons positioned in the footer.…
  templates/default/070-components/legacy/Services/_component_form.scss
  templates/default/delos.css
Labels: bugfix

#7149 Upgrade jumbojett/openid-connect-php to 1.0.0
  composer.json
  composer.lock
Labels: dependencies, php
