Repository ILIAS-eLearning/ILIAS, pull requests merged in 2024-01, with the labels that each got.

#6847 UI/PresentationTable: 39476, use CSS instead of deprecated align-attribute
  src/UI/examples/Table/Presentation/base1.php
Labels: bugfix

#6858 Bugfix: Missing parameter for getOriginalId() in multiple choice
  Modules/TestQuestionPool/classes/class.assMultipleChoice.php
Labels: bugfix

#6859 Bugfix: Missing parameter for getOriginalId() in multiple choice
  components/ILIAS/TestQuestionPool/classes/class.assMultipleChoice.php
Labels: bugfix

#6845 OrgU: 39683, uninitialized property
  Modules/OrgUnit/classes/Positions/UserAssignment/class.ilOrgUnitRecursiveUserAssignmentTableGUI.php
Labels: bugfix

#6727 PRG: 39307, Success of Course does not complete PRGNode (7 only)
  Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
Labels: bugfix

#6841 PRG: 39633, catch exception for inactive cert
  Modules/StudyProgramme/classes/class.ilObjStudyProgrammeGUI.php
  Modules/StudyProgramme/classes/class.ilStudyProgrammeAppEventListener.php
Labels: bugfix

#6838 Orgu: 39369, add uninitialized property
  Modules/OrgUnit/classes/LocalUser/class.ilLocalUserGUI.php
Labels: bugfix

#6837 Orgu: 39383, fix confirmationGUI for deletion of position
  Modules/OrgUnit/classes/Positions/class.ilOrgUnitPositionGUI.php
Labels: bugfix

#6812 PRG: 39365, irrelevant nulls points and completion
  Modules/StudyProgramme/classes/model/Assignments/class.ilPRGProgress.php
Labels: bugfix

#6786 PRG: 39377, there _really_ should not be a fixed id on tables ;(
  Modules/StudyProgramme/classes/class.ilStudyProgrammeMembersTableGUI.php
Labels: bugfix

#6729 Exceptions: Fix `Plain Text` error handler
  Services/Exceptions/classes/class.ilDelegatingHandler.php
  Services/Exceptions/classes/class.ilPlainTextHandler.php
  Services/Exceptions/classes/class.ilTestingHandler.php
Labels: bugfix, php

#6720 LSO: 39219, Launchbutton in EditorPage as primary
  Modules/LearningSequence/classes/Player/class.ilLSLaunchlinksBuilder.php
  Services/COPage/xsl/page.xsl
Labels: bugfix

#6848 TA: 39656, calculate points as floats
  Modules/TestQuestionPool/classes/class.assClozeTest.php
  Modules/TestQuestionPool/classes/class.assFileUpload.php
  Modules/TestQuestionPool/classes/class.assFormulaQuestion.php
  Modules/TestQuestionPool/classes/class.assImagemapQuestion.php
  Modules/TestQuestionPool/classes/class.assKprimChoice.php
  Modules/TestQuestionPool/classes/class.assLongMenu.php
  Modules/TestQuestionPool/classes/class.assMultipleChoice.php
  Modules/TestQuestionPool/classes/class.assNumeric.php
  Modules/TestQuestionPool/classes/class.assOrderingHorizontal.php
  Modules/TestQuestionPool/classes/class.assOrderingQuestion.php
  Modules/TestQuestionPool/classes/class.assQuestion.php
  Modules/TestQuestionPool/classes/class.assSingleChoice.php
  Modules/TestQuestionPool/classes/class.assTextQuestion.php
  Modules/TestQuestionPool/classes/class.assTextSubset.php
Labels: bugfix

#6864 Authentication: fix type error (39736)
  Services/Authentication/classes/class.ilSessionStatistics.php
Labels: bugfix, php

#6868 LNG: Exchange of dashboard for participants
  lang/ilias_en.lang
Labels: improvement

#6869 tst: Exchange of dashboard for participants
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement

#6686 OrgU: use IRSS for type icons
  Modules/OrgUnit/classes/Types/class.ilOrgUnitType.php
  Modules/OrgUnit/classes/Types/class.ilOrgUnitTypeCustomIconsFormGUI.php
  Modules/OrgUnit/classes/Types/class.ilOrgUnitTypeFormGUI.php
  Modules/OrgUnit/classes/Types/class.ilOrgUnitTypeGUI.php
  Modules/OrgUnit/classes/Types/class.ilOrgUnitTypeTableGUI.php
  Modules/OrgUnit/classes/Types/class.ilOrgUnitTypeUploadHandlerGUI.php
  Modules/OrgUnit/classes/Types/ilOrgUnitTypeStakeholder.php
  Modules/OrgUnit/classes/class.ilObjOrgUnit.php
  Modules/OrgUnit/classes/class.ilOrgUnitLocalDIC.php
Labels: improvement

#6641 Add support for IPv6 in ILIAS\Data\URI (ILIAS 8)
  src/Data/URI.php
  tests/Data/URITest.php
Labels: improvement, php

#6846 UI/Metabar, more button with aria-expanded (#37151, #38249)
  src/UI/Implementation/Component/MainControls/Renderer.php
  src/UI/Implementation/Component/MainControls/Slate/Renderer.php
  src/UI/templates/js/MainControls/dist/maincontrols.min.js
  src/UI/templates/js/MainControls/metabar.js
  src/UI/templates/js/MainControls/rollup.config.js
  src/UI/templates/js/MainControls/slate.js
  src/UI/templates/js/MainControls/src/maincontrols.js
  src/UI/templates/js/MainControls/src/metabar.class.js
  src/UI/templates/js/MainControls/src/metabar.factory.js
  src/UI/templates/js/MainControls/src/slate.class.js
Labels: bugfix, kitchen sink

#6861 UI: 38290, Paginations with one page only
  src/UI/Implementation/Component/Input/ViewControl/Renderer.php
  src/UI/Implementation/Component/ViewControl/Renderer.php
  src/UI/examples/Input/ViewControl/Pagination/with_one_page.php
  src/UI/examples/ViewControl/Pagination/no_pages.php
  src/UI/templates/default/Input/tpl.viewcontrol_pagination.html
  tests/UI/Component/ViewControl/PaginationTest.php
Labels: bugfix, kitchen sink

#6295 UI/Input/Rating: a five-star rating input
  components/ILIAS/Data/src/FiveStarRatingScale.php
  components/ILIAS/UI/src/Component/Input/Field/Factory.php
  components/ILIAS/UI/src/Component/Input/Field/Rating.php
  components/ILIAS/UI/src/Implementation/Component/Input/Field/Factory.php
  components/ILIAS/UI/src/Implementation/Component/Input/Field/Rating.php
  components/ILIAS/UI/src/Implementation/Component/Input/Field/Renderer.php
  components/ILIAS/UI/src/examples/Input/Field/Rating/base.php
  components/ILIAS/UI/src/templates/default/Input/tpl.rating.html
  components/ILIAS/UI/tests/Component/Input/Field/RatingInputTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  public/templates/default/delos.css
  public/templates/default/delos.css.map
  templates/default/070-components/UI-framework/Input/_ui-component_input.scss
  templates/default/070-components/UI-framework/Input/_ui-component_rating.scss
  templates/default/delos.css.map
Labels: kitchen sink, improvement

#6872 Refinery: Rename test classname
  components/ILIAS/Refinery/tests/Custom/Constraint/CustomTest.php
Labels: bugfix, php

#6193 Docu: Added Services/Notification How-To
  Services/Notification/notify-users.md
Labels: documentation

#6139 Docu: Added Context How-To
  Services/Context/handle-context-related-possibilities.md
Labels: documentation

#6097 Docu: Added Event Handling How-To
  Services/EventHandling/listen-to-and-raise-events.md
Labels: documentation

#6683 TA: 39101, add 'finalized_evaluation' to the Test Results
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
Labels: bugfix

#6695 T&A Bugfix #0039149: Failed test: Add from Qpl Sortations
  Modules/Test/classes/tables/class.ilTestQuestionBrowserTableGUI.php
Labels: bugfix

#6875 Docu: Added Root Directory for DevGuide
  docs/development/devguide/README.md
  docs/development/devguide/template-tutorial-article.md
Labels: documentation

#6874 Calendar: only show consultation hours of current object in repo context (26706)
  Services/Calendar/classes/class.ilCalendarSchedule.php
  Services/Calendar/classes/class.ilCalendarScheduleFilterConsultationHourInRepository.php
Labels: bugfix, php

#6856 TA: 39709, hints - we do not need a special case for KioskContent anymore
  Modules/TestQuestionPool/classes/class.ilAssQuestionHintRequestGUI.php
  Modules/TestQuestionPool/templates/default/tpl.il_tst_question_hints_kiosk_page.html
Labels: bugfix

#6851 TA: 39695, stricter handling of image for multiple/single choice
  Modules/TestQuestionPool/classes/class.assAnswerBinaryStateImage.php
  Modules/TestQuestionPool/classes/class.assAnswerMultipleResponseImage.php
  Modules/TestQuestionPool/classes/class.assMultipleChoice.php
  Modules/TestQuestionPool/classes/class.assMultipleChoiceGUI.php
  Modules/TestQuestionPool/classes/class.assSingleChoice.php
  Modules/TestQuestionPool/classes/class.assSingleChoiceGUI.php
  Modules/TestQuestionPool/classes/class.ilAnswerWizardInputGUI.php
  Modules/TestQuestionPool/classes/class.ilMatchingWizardInputGUI.php
  Modules/TestQuestionPool/classes/class.ilMultipleChoiceWizardInputGUI.php
  Modules/TestQuestionPool/classes/class.ilSingleChoiceWizardInputGUI.php
  Modules/TestQuestionPool/classes/feedback/class.ilAssMultipleChoiceFeedback.php
  Modules/TestQuestionPool/classes/feedback/class.ilAssSingleChoiceFeedback.php
Labels: bugfix

#6840 TA/Utils: 39276, mb_strpos does not accept null as offset
  Services/Utilities/classes/class.ilStr.php
Labels: bugfix

#6836 TA: 39189, enable dragging in post-correction
  Modules/TestQuestionPool/classes/forms/class.ilMultipleNestedOrderingElementsInputGUI.php
Labels: bugfix

#6822 TA: 39410, remove 'finalized_by' if finalization is not set
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
Labels: bugfix

#6797 TA: 39277 remove filter for active/inactive users
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilTestScoringGUI.php
  Modules/Test/classes/tables/class.ilTestManScoringParticipantsTableGUI.php
Labels: bugfix

#6878 T&A Bugfix #0039816: SubsetQuestion correct_answers integer required
  Modules/TestQuestionPool/classes/class.assTextSubsetGUI.php
Labels: bugfix

#6882 TA: 39853, 39840, 39841 - check on null/bool instead of strlen for images
  Modules/TestQuestionPool/classes/class.assMultipleChoice.php
  Modules/TestQuestionPool/classes/class.assSingleChoice.php
  Modules/TestQuestionPool/classes/export/qti12/class.assMultipleChoiceExport.php
  Modules/TestQuestionPool/classes/export/qti12/class.assSingleChoiceExport.php
  Modules/TestQuestionPool/classes/import/qti12/class.assMultipleChoiceImport.php
Labels: bugfix

#6787 Move Deletion Confirmation to Modal
  Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentGUI.php
  Modules/LearningSequence/classes/class.ilObjLearningSequenceGUI.php
  Services/Object/classes/class.ilObject2GUI.php
  Services/Object/classes/class.ilObjectGUI.php
  templates/default/tpl.page_content.html
Labels: bugfix

#6849 T&A Bugfix #0039652: learning objective driven test undefine error
  Modules/Test/classes/class.ilTestQuestionRelatedObjectivesList.php
Labels: bugfix

#6892 TA: 39744, exception for next-button after feedback
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
Labels: bugfix

#6888 TA: 39864, fixed isComplete-check
  Modules/TestQuestionPool/classes/class.assSingleChoice.php
Labels: bugfix

#6886 TA: 39863 error when switching to multiline
  Modules/TestQuestionPool/classes/class.assMultipleChoiceGUI.php
Labels: bugfix

#6880 T&A Bugfix #0039844: Deleting QuestionHints
  Modules/TestQuestionPool/classes/class.ilAssQuestionHintGUI.php
  Modules/TestQuestionPool/classes/class.ilAssQuestionHintsTableGUI.php
Labels: bugfix

#6827 T&A Bugfix #0039405: Failed Tests: Buttonlabel missing for Hints
  Modules/Test/classes/class.ilTestQuestionNavigationGUI.php
Labels: bugfix

#6828 T&A Bugfix #0039506: Failed test: T74255
  Modules/Test/classes/MainSettings/ilObjTestSettingsQuestionBehaviour.php
  Modules/Test/classes/class.ilObjTestSettingsScoringResultsGUI.php
Labels: bugfix

#6826 Test Casting Php8 Bugs
  Modules/Test/classes/class.ilObjTest.php
  Modules/Test/classes/class.ilObjTestGUI.php
Labels: improvement

#6682 TA: 39096, call to undefined method
  Modules/Test/classes/class.ilTestParticipantAccessFilter.php
Labels: bugfix

#6768 TA/Questionpool: add alert icon to incomplete questions
  Modules/TestQuestionPool/classes/QuestionTable.php
Labels: bugfix

#6730 TA: 39312, JS in modals did not prevent defaults and was looking for button-ids
  Modules/Test/js/ilTestPlayerQuestionEditControl.js
Labels: bugfix

#6705 (RemovingLUI) T&A: replace Toolbar with dropdown in QPL Printview
  components/ILIAS/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php
  components/ILIAS/TestQuestionPool/classes/tables/class.ilQuestionPoolPrintViewTableGUI.php
Labels: improvement

#6672 T&A Bugfix #0037248: Wrong cmdNode by using the action menu
  Modules/Test/classes/class.ilObjTestGUI.php
Labels: bugfix

#6788 TA: 37915, get autosave-answers by pass and display in manual scoring
  Modules/Test/classes/Results/class.ilTestResultsFactory.php
  Modules/Test/classes/class.ilTestPassesSelector.php
  Modules/Test/classes/class.ilTestPlayerAbstractGUI.php
  Modules/Test/classes/class.ilTestScoringByQuestionsGUI.php
  Modules/Test/classes/class.ilTestScoringGUI.php
  Modules/TestQuestionPool/classes/class.assTextQuestion.php
  Modules/TestQuestionPool/classes/class.assTextQuestionGUI.php
Labels: bugfix

#6814 SCORM: Fix mail placeholder interpolation
  Modules/ScormAicc/classes/class.ilScormMailTemplateLPContext.php
Labels: bugfix, php

#6667 Release 9: Chatroom, Forum, ContentPage xml import validation
  Modules/Chatroom/classes/class.ilChatroomExporter.php
  Modules/ContentPage/classes/class.ilContentPageExporter.php
  Modules/Forum/classes/class.ilForumExporter.php
  Modules/Forum/classes/class.ilForumXMLParser.php
  xml/SchemaValidation/ilias_chtr_5_3.xsd
  xml/SchemaValidation/ilias_chtr_9.xsd
  xml/SchemaValidation/ilias_copa_9.xsd
  xml/SchemaValidation/ilias_frm_5_1.xsd
  xml/SchemaValidation/ilias_frm_8.xsd
  xml/SchemaValidation/ilias_frm_9.xsd
  xml/ilias_chtr_5_3.xsd
  xml/ilias_chtr_9.xsd
  xml/ilias_frm_4_1.xsd
  xml/ilias_frm_4_5.xsd
  xml/ilias_frm_5_1.xsd
  xml/ilias_frm_9.xsd
Labels: improvement, php

#6895 TA: 39096, fix usage of closure/filter
  Modules/Test/classes/class.ilTestParticipantAccessFilter.php
Labels: bugfix

#6674 InfoScreen: use LOM API (38859, 38868)
  Services/InfoScreen/classes/class.ilInfoScreenGUI.php
Labels: bugfix, php

#6803 Notes: Fix `null` recipients parsing
  Services/Notes/Notifications/class.NotificationsManager.php
Labels: bugfix, php

#6843 9/UI/COPage js needs content in p and surrounding section dropdown
  Services/COPage/classes/class.ilPageObjectGUI.php
Labels: bugfix

#6899 LegalDocuments: Fix filter, pagination, self registration, change messages
  Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
  Services/LegalDocuments/classes/Administration.php
  Services/LegalDocuments/classes/ConsumerToolbox/Blocks.php
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/Agreement.php
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ModifyFooter.php
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/SelfRegistration.php
  Services/LegalDocuments/classes/ConsumerToolbox/UI.php
  Services/LegalDocuments/classes/ConsumerToolbox/User.php
  Services/LegalDocuments/classes/Legacy/ResettingDurationInputGUI.php
  Services/LegalDocuments/classes/Legacy/Table.php
  Services/LegalDocuments/classes/Provide/ProvideDocument.php
  Services/LegalDocuments/classes/Provide/ProvideHistory.php
  Services/LegalDocuments/classes/Repository/DatabaseHistoryRepository.php
  Services/LegalDocuments/classes/Repository/HistoryRepository.php
  Services/LegalDocuments/classes/Setup/UpdateSteps.php
  Services/LegalDocuments/classes/Table/DocumentTable.php
  Services/LegalDocuments/classes/Table/EditableDocumentTable.php
  Services/LegalDocuments/classes/Table/HistoryTable.php
  Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
  Services/LegalDocuments/test/AdministrationTest.php
  Services/LegalDocuments/test/ConsumerToolbox/BlocksTest.php
  Services/LegalDocuments/test/ConsumerToolbox/ConsumerSlots/AgreementTest.php
  Services/LegalDocuments/test/ConsumerToolbox/ConsumerSlots/ModifyFooterTest.php
  Services/LegalDocuments/test/ConsumerToolbox/UserTest.php
  Services/LegalDocuments/test/Provide/ProvideDocumentTest.php
  Services/LegalDocuments/test/Provide/ProvideHistoryTest.php
  Services/LegalDocuments/test/Table/DocumentTableTest.php
  Services/LegalDocuments/test/Table/EditableDocumentTableTest.php
  Services/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php

#6900 LegalDocuments: Fix filter, pagination, self registration, change messages (trunk)
  components/ILIAS/DataProtection/classes/class.ilObjDataProtectionGUI.php
  components/ILIAS/LegalDocuments/classes/Administration.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/Blocks.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/Agreement.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ModifyFooter.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/SelfRegistration.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/UI.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/User.php
  components/ILIAS/LegalDocuments/classes/Legacy/ResettingDurationInputGUI.php
  components/ILIAS/LegalDocuments/classes/Legacy/Table.php
  components/ILIAS/LegalDocuments/classes/Provide/ProvideDocument.php
  components/ILIAS/LegalDocuments/classes/Provide/ProvideHistory.php
  components/ILIAS/LegalDocuments/classes/Repository/DatabaseHistoryRepository.php
  components/ILIAS/LegalDocuments/classes/Repository/HistoryRepository.php
  components/ILIAS/LegalDocuments/classes/Setup/UpdateSteps.php
  components/ILIAS/LegalDocuments/classes/Table/DocumentTable.php
  components/ILIAS/LegalDocuments/classes/Table/EditableDocumentTable.php
  components/ILIAS/LegalDocuments/classes/Table/HistoryTable.php
  components/ILIAS/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
  components/ILIAS/LegalDocuments/tests/AdministrationTest.php
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/BlocksTest.php
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/ConsumerSlots/AgreementTest.php
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/ConsumerSlots/ModifyFooterTest.php
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/UserTest.php
  components/ILIAS/LegalDocuments/tests/Provide/ProvideDocumentTest.php
  components/ILIAS/LegalDocuments/tests/Provide/ProvideHistoryTest.php
  components/ILIAS/LegalDocuments/tests/Table/DocumentTableTest.php
  components/ILIAS/LegalDocuments/tests/Table/EditableDocumentTableTest.php
  components/ILIAS/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php

#6908 Services/Init: Store correct goto url for redirection
  Services/Init/classes/StartupSequence/StartUpSequenceDispatcher.php
Labels: bugfix, php

#6824 ForumModeratorsTable: Switch to new table implementation
  components/ILIAS/Forum/classes/Moderation/class.ForumModeratorsTable.php
  components/ILIAS/Forum/classes/class.ilForumModeratorsGUI.php
  components/ILIAS/Forum/classes/class.ilForumModeratorsTableGUI.php
  components/ILIAS/Forum/templates/default/tpl.forum_moderators_table_row.html
Labels: improvement, php

#6919 LegalDocuments: Add titles for admin forms
  Services/LegalDocuments/classes/Administration.php
  Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
Labels: bugfix, php

#6920 LegalDocuments: Add titles for admin forms
  components/ILIAS/LegalDocuments/classes/Administration.php
  components/ILIAS/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
Labels: bugfix, php

#6883 Forum UI/DataTable: ilForumStatisticsTableGUI
  components/ILIAS/Forum/classes/Tables/ForumStatisticsTable.php
  components/ILIAS/Forum/classes/class.ilForumStatisticsTableGUI.php
  components/ILIAS/Forum/classes/class.ilObjForumGUI.php
  components/ILIAS/Forum/templates/default/tpl.statistics_table_row.html
Labels: improvement, php

#6921 Test: Fix use statement with non-compound name 'ilDBInterface'
  Modules/TestQuestionPool/Setup/class.ilFixMissingQuestionDuplicationMigration.php
Labels: bugfix, php

#6731 Mantis 39324
  Modules/LTIConsumer/LuceneObjectDefinition.xml
Labels: bugfix

#6915 Exercise: Fix mailing in assignment reminder
  Modules/Exercise/Assignment/class.ilExAssignmentReminder.php
Labels: bugfix, php

#6937 Nodejs: Remove Versions <= 19 from docs.
  docs/configuration/install.md
Labels: documentation

#6938 Nodejs: Remove Versions <= 19 from docs (trunk).
  docs/configuration/install.md
Labels: documentation

#6935 Dashboard Bugfix #0039977: Mail DashboardContent Block empty
  Services/Dashboard/classes/class.ilDashboardContentBlockGUI.php
  Services/Mail/templates/default/tpl.pd_mail.html
Labels: bugfix, php

#6942 LegalDocuments: Replace generic on screen messages
  Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
Labels: bugfix, php

#6943 LegalDocuments: Replace generic on screen messages (trunk)
  components/ILIAS/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
Labels: bugfix, php

#6944 Tracking/LearningProgress: Fix accessing undefined array key
  Services/Tracking/classes/class.ilTrQuery.php
Labels: bugfix, php

#6916 Update Dependencies after Release v8.8
  composer.lock
Labels: technical board, dependencies

#6890 PRG: 39836, fix LP check for user not being assigned
  Services/Tracking/classes/status/class.ilLPStatusStudyProgramme.php
Labels: bugfix

#6529 UI, DataTable: #38429, typecheck for Icons in Columns
  Modules/TestQuestionPool/classes/QuestionTable.php
  src/UI/Component/Table/Column/Factory.php
  src/UI/Implementation/Component/Table/Column/Boolean.php
  src/UI/Implementation/Component/Table/Column/Factory.php
  src/UI/Implementation/Component/Table/Column/StatusIcon.php
  src/UI/examples/Table/Column/Boolean/base.php
  src/UI/examples/Table/Column/StatusIcon/base.php
  src/UI/examples/Table/Data/base.php
  src/UI/examples/Table/Data/repo_implementation.php
  tests/UI/Component/Table/Column/ColumnTest.php
Labels: kitchen sink, improvement

#6879 BannedUsersTable: Switch to new table implementation
  components/ILIAS/Chatroom/classes/class.BannedUsersTable.php
  components/ILIAS/Chatroom/classes/class.ilBannedUsersTableGUI.php
  components/ILIAS/Chatroom/classes/gui/class.ilChatroomBanGUI.php
  components/ILIAS/Chatroom/templates/default/tpl.banned_user_table_row.html
Labels: improvement, php

#6960 Mail: Transform title of custom folder for `UI Tree/Node`
  Services/Mail/classes/class.ilMailExplorer.php
Labels: bugfix, php

#6867 mantis ilias 22331
  Services/Container/classes/class.ilContainerSessionsContentGUI.php
Labels: bugfix

#6905 9 didactic template import validation
  Services/DidacticTemplate/classes/Setting/class.ilDidacticTemplateSettingsGUI.php
  Services/DidacticTemplate/classes/class.ilDidacticTemplateImport.php
  xml/SchemaValidation/ilias_otpl_9.xsd
Labels: improvement, php

#6955 9 mantis ilias 29589
  Modules/Course/classes/class.ilObjCourseGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix

#6965 LegalDocuments: Change file upload error message. Change Dpro lang vars (trunk)
  components/ILIAS/LegalDocuments/classes/Administration.php
  components/ILIAS/LegalDocuments/classes/FileUpload/UploadHandler.php
  components/ILIAS/LegalDocuments/classes/Repository/DatabaseDocumentRepository.php
  components/ILIAS/LegalDocuments/classes/Repository/DocumentRepository.php
  components/ILIAS/LegalDocuments/classes/Repository/ReadOnlyDocumentRepository.php
  components/ILIAS/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
  components/ILIAS/LegalDocuments/tests/FileUpload/UploadHandlerTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php

#6964 LegalDocuments: Change file upload error message. Change Dpro lang vars
  Services/LegalDocuments/classes/Administration.php
  Services/LegalDocuments/classes/FileUpload/UploadHandler.php
  Services/LegalDocuments/classes/Repository/DatabaseDocumentRepository.php
  Services/LegalDocuments/classes/Repository/DocumentRepository.php
  Services/LegalDocuments/classes/Repository/ReadOnlyDocumentRepository.php
  Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
  Services/LegalDocuments/test/FileUpload/UploadHandlerTest.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php

#6966 T&A Bugfix #0039994: Long Menu Question AnswerType Save Error
  Modules/TestQuestionPool/classes/class.assLongMenu.php
  Modules/TestQuestionPool/classes/class.assLongMenuGUI.php
  Modules/TestQuestionPool/classes/class.assQuestionGUI.php
  Modules/TestQuestionPool/test/assLongMenuTest.php
Labels: bugfix

#6918 T&A Bugfix #0039867: Change Language for Statistics Export Types
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, improvement

#6969 CSV: Remove `auto_detect_line_endings` usage in CSV reader
  Services/CSV/classes/class.ilCSVReader.php
Labels: bugfix, php

#6815 Fix type error in LegacyGotoHandler
  src/StaticURL/Handler/LegacyGotoHandler.php
Labels: bugfix

#6972 LegalDocuments: Use same links as the other login page links
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ModifyFooter.php
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ShowOnLoginPage.php
  Services/LegalDocuments/classes/ConsumerToolbox/Slot.php
  Services/LegalDocuments/templates/default/login_link.html
  Services/LegalDocuments/test/ConsumerToolbox/ConsumerSlots/ModifyFooterTest.php
  Services/LegalDocuments/test/ConsumerToolbox/ConsumerSlots/ShowOnLoginPageTest.php
  lang/ilias_de.lang
Labels: bugfix, php

#6973 LegalDocuments: Use same links as the other login page links (trunk)
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ModifyFooter.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/ShowOnLoginPage.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/Slot.php
  components/ILIAS/LegalDocuments/templates/default/login_link.html
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/ConsumerSlots/ModifyFooterTest.php
  components/ILIAS/LegalDocuments/tests/ConsumerToolbox/ConsumerSlots/ShowOnLoginPageTest.php
  lang/ilias_de.lang
Labels: bugfix, php

#6884 Add JS bind on standard page
  src/UI/Implementation/Component/Layout/Page/Renderer.php
  src/UI/templates/default/Layout/tpl.standardpage.html
Labels: bugfix, kitchen sink, php, javascript

#6974 LegacyForms: Add `aria-describedby` for (not all) legacy form elements (`il*InputGUI`)
  Services/Form/classes/class.ilCheckboxInputGUI.php
  Services/Form/classes/class.ilNumberInputGUI.php
  Services/Form/classes/class.ilPropertyFormGUI.php
  Services/Form/classes/class.ilRadioGroupInputGUI.php
  Services/Form/classes/class.ilTextAreaInputGUI.php
  Services/Form/classes/class.ilTextInputGUI.php
  Services/Form/templates/default/tpl.prop_checkbox.html
  Services/Form/templates/default/tpl.prop_number.html
  Services/Form/templates/default/tpl.prop_radio.html
  Services/Form/templates/default/tpl.prop_textarea.html
  Services/Form/templates/default/tpl.prop_textinput.html
  Services/Form/templates/default/tpl.property_form.html
Labels: bugfix, php

#6978 UIComponent/Tabs: Transform URL before template rendering
  Services/UIComponent/Tabs/classes/class.ilTabsGUI.php
Labels: bugfix, php

#6985 User: Fix request parameter handling for missing role selection
  Services/User/classes/Cron/class.ilCronDeleteInactiveUserAccounts.php
Labels: bugfix, php

#6977 T&A Bugfix #0040228: Qpl buildTitle error when Test not existent
  Modules/Test/classes/tables/class.ilTestQuestionsTableGUI.php
Labels: bugfix

#6968 Test: Handle exception cases when trying to export PDF archive
  Modules/Test/classes/class.ilTestEvaluationGUI.php
  Modules/Test/classes/class.ilTestTabsManager.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: improvement, php

#6988 User: Fix request parameter handling for missing role selection
  Services/User/classes/Cron/class.ilCronDeleteInactivatedUserAccounts.php
Labels: bugfix, php

#6987 User: Fix overwriting user attributes in XML import
  Services/User/classes/class.ilUserImportParser.php
Labels: bugfix, php

#6957 SCORM: Use templates/html in initialisation context
  Services/Context/classes/class.ilContextScorm.php
Labels: bugfix, php

#6470 FIX: Undefined variable $initGlobalobjData
  Modules/Scorm2004/classes/class.ilSCORM13PlayerGUI.php
Labels: bugfix

#6982 #40301 Forum Bugfix: Missing user_noti_id for cloning notification settings
  Modules/Forum/classes/Notification/class.ilForumNotification.php
  Modules/Forum/test/ilForumNotificationTest.php
Labels: bugfix

#6983 #40301 Forum Bugfix: Missing user_noti_id for cloning notification settings
  Modules/Forum/classes/Notification/class.ilForumNotification.php
  Modules/Forum/test/ilForumNotificationTest.php
Labels: bugfix, php

#6984 #40301 Forum Bugfix: Missing user_noti_id for cloning notification settings
  components/ILIAS/Forum/classes/Notification/class.ilForumNotification.php
  components/ILIAS/Forum/tests/ilForumNotificationTest.php
Labels: bugfix

#6993 LegalDocuments: Fix OSM overwrite. Lang var. string callable mix up
  Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
  Services/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/Agreement.php
  Services/LegalDocuments/classes/Legacy/Table.php
  Services/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php

#6994 LegalDocuments: Fix on screen message overwrite (trunk)
  components/ILIAS/DataProtection/classes/class.ilObjDataProtectionGUI.php
  components/ILIAS/LegalDocuments/classes/ConsumerToolbox/ConsumerSlots/Agreement.php
  components/ILIAS/LegalDocuments/classes/Legacy/Table.php
  components/ILIAS/TermsOfService/classes/class.ilObjTermsOfServiceGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: bugfix, php
